# Spherical orbifolds: the point groups as tilings of the sphere.
#
# Part of the Math Art patterns engine (`math_art/patterns/`).  Python + numpy
# only -- no `bpy` -- so the engine imports and self-tests headlessly;
# the registered operators stay in their flat generator modules.
#
# The spherical half of the Conway-Thurston signature language, whose
# Euclidean half is in `groups.py`: signatures of cost less than 2 are
# spherical, and there are exactly fourteen families.

import math
from math import cos, sin, pi, sqrt, radians
import numpy as np


PHI = (1 + sqrt(5)) / 2


def _rot(axis, ang):
    """3x3 rotation about axis by ang (Rodrigues)."""
    x, y, z = axis
    l = sqrt(x * x + y * y + z * z)
    x, y, z = x / l, y / l, z / l
    c, s = cos(ang), sin(ang)
    C = 1 - c
    return ((c + x * x * C, x * y * C - z * s, x * z * C + y * s),
            (y * x * C + z * s, c + y * y * C, y * z * C - x * s),
            (z * x * C - y * s, z * y * C + x * s, c + z * z * C))


def _mul(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3))
                       for j in range(3)) for i in range(3))


def _key(A):
    return tuple(round(A[i][j], 9) for i in range(3)
                 for j in range(3))


def _det(A):
    return (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1])
            - A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0])
            + A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0]))


_SIGMA_H = ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, -1.0))


_SIGMA_V = ((1.0, 0.0, 0.0), (0.0, -1.0, 0.0), (0.0, 0.0, 1.0))


_SWAP_XY = ((0.0, 1.0, 0.0), (1.0, 0.0, 0.0), (0.0, 0.0, 1.0))


_MINUS_I = ((-1.0, 0.0, 0.0), (0.0, -1.0, 0.0), (0.0, 0.0, -1.0))


# the seven infinite families:
# (generator builders taking n, expected order as a function of n)
_FAMILIES = ('NN', 'STAR_NN', 'N_STAR', 'NX', '22N', '2STAR_N',
             'STAR_22N')


def _s2n(n):
    """S2n rotoreflection about Z: rotate pi/n, reflect in z=0."""
    return _mul(_rot((0, 0, 1), pi / n), _SIGMA_H)


def _generators(signature, n):
    cz = _rot((0, 0, 1), 2 * pi / n)
    c2x = _rot((1, 0, 0), pi)
    if signature == 'NN':                       # Cn
        return (cz,)
    if signature == 'STAR_NN':                  # Cnv
        return (cz, _SIGMA_V)
    if signature == 'N_STAR':                   # Cnh
        return (cz, _SIGMA_H)
    if signature == 'NX':                       # S2n
        return (_s2n(n),)
    if signature == '22N':                      # Dn
        return (cz, c2x)
    if signature == '2STAR_N':                  # Dnd
        return (cz, c2x, _s2n(n))
    if signature == 'STAR_22N':                 # Dnh
        return (cz, c2x, _SIGMA_H)
    t = (_rot((1, 1, 1), 2 * pi / 3), _rot((0, 0, 1), pi))
    o = (_rot((0, 0, 1), pi / 2), _rot((1, 1, 1), 2 * pi / 3))
    i = (_rot((0, 1, PHI), 2 * pi / 5), _rot((1, 1, 1), 2 * pi / 3))
    if signature == '332':                      # T
        return t
    if signature == 'STAR_332':                 # Td
        return t + (_SWAP_XY,)
    if signature == '3STAR_2':                  # Th
        return t + (_MINUS_I,)
    if signature == '432':                      # O
        return o
    if signature == 'STAR_432':                 # Oh
        return o + (_MINUS_I,)
    if signature == '532':                      # I
        return i
    if signature == 'STAR_532':                 # Ih
        return i + (_MINUS_I,)
    raise ValueError(signature)


def expected_order(signature, n=1):
    """Theoretical group order for each orbifold signature."""
    fam = {'NN': n, 'STAR_NN': 2 * n, 'N_STAR': 2 * n, 'NX': 2 * n,
           '22N': 2 * n, '2STAR_N': 4 * n, 'STAR_22N': 4 * n}
    odd = {'332': 12, 'STAR_332': 24, '3STAR_2': 24, '432': 24,
           'STAR_432': 48, '532': 60, 'STAR_532': 120}
    return fam[signature] if signature in fam else odd[signature]


def build_group(signature, n=1):
    """All matrices of the group, generated by closure under
    multiplication with rounding-dedupe."""
    gens = _generators(signature, n)
    I = ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0))
    seen = {_key(I): I}
    frontier = [I]
    while frontier:
        nxt = []
        for A in frontier:
            for G in gens:
                B = _mul(G, A)
                k = _key(B)
                if k not in seen:
                    seen[k] = B
                    nxt.append(B)
        frontier = nxt
        if len(seen) > 1000:            # runaway float drift guard
            break
    return list(seen.values())


def comma_outline(size=1.0, steps=22, cap_steps=14):
    """Closed 2D polygon of a comma / teardrop: a circular head
    blended into a curved, tapering tail (an arc of a circle for
    the head cap plus offset curves of a circular-spiral tail
    centerline).  Deliberately chiral: the tail curls clockwise."""
    r0 = 0.30 * size                    # head radius
    rho = 0.55 * size                   # tail centerline radius
    sweep = radians(150.0)              # tail curl angle
    cy = -rho                           # centerline circle centre

    def cn(t):
        """Centerline point and outward normal at t in [0, 1]."""
        psi = pi / 2 - sweep * t
        return ((rho * cos(psi), cy + rho * sin(psi)),
                (cos(psi), sin(psi)))

    def w(t):
        return r0 * (1.0 - t) ** 1.4    # tapering half-width

    pts = []
    for i in range(steps):              # upper edge, head -> tip
        t = i / steps
        (cx, cyy), (nx, ny) = cn(t)
        ww = w(t)
        pts.append((cx + ww * nx, cyy + ww * ny))
    (cx, cyy), _ = cn(1.0)
    pts.append((cx, cyy))               # tail tip
    for i in range(steps - 1, -1, -1):  # lower edge, tip -> head
        t = i / steps
        (cx, cyy), (nx, ny) = cn(t)
        ww = w(t)
        pts.append((cx - ww * nx, cyy - ww * ny))
    for k in range(1, cap_steps):       # head cap, the long way round
        a = -pi / 2 - pi * k / cap_steps
        pts.append((r0 * cos(a), r0 * sin(a)))
    return pts


def uv_sphere(radius=1.0, segs=48, rings=24):
    """Plain UV sphere shell (verts, faces)."""
    verts = [(0.0, 0.0, radius)]
    for i in range(1, rings):
        th = pi * i / rings
        st, ct = sin(th), cos(th)
        for j in range(segs):
            ph = 2 * pi * j / segs
            verts.append((radius * st * cos(ph),
                          radius * st * sin(ph), radius * ct))
    verts.append((0.0, 0.0, -radius))
    last = len(verts) - 1
    faces = []
    for j in range(segs):
        faces.append([0, 1 + j, 1 + (j + 1) % segs])
    for i in range(rings - 2):
        a = 1 + i * segs
        b = a + segs
        for j in range(segs):
            j1 = (j + 1) % segs
            faces.append([a + j, a + j1, b + j1, b + j])
    a = 1 + (rings - 2) * segs
    for j in range(segs):
        faces.append([last, a + (j + 1) % segs, a + j])
    return verts, faces


# a generic point: spherical coords theta=63, phi=21 degrees --
# off every mirror plane and rotation axis of all 14 groups
_GENERIC_THETA = radians(63.0)


_GENERIC_PHI = radians(21.0)


def _signed_volume(verts, faces):
    """Signed volume of a closed triangulable mesh; positive when
    the faces wind outward."""
    V = np.asarray(verts, float)
    tot = 0.0
    for f in faces:
        for i in range(1, len(f) - 1):
            tot += np.dot(V[f[0]], np.cross(V[f[i]], V[f[i + 1]]))
    return tot / 6.0


def sphere_shell(R, thickness, segs, rings):
    """(verts, faces) of a hollow spherical shell solid: outer
    sphere wound outward, inner sphere (radius R - thickness) wound
    inward toward the cavity.  thickness <= 0 gives the solid
    ball (outer sphere only)."""
    sv, sf = uv_sphere(R, segs, rings)
    outward = _signed_volume(sv, sf) > 0
    if not outward:
        sf = [list(reversed(f)) for f in sf]
    verts = list(sv)
    faces = [list(f) for f in sf]
    if thickness > 0:
        iv, iff = uv_sphere(R - thickness, segs, rings)
        if outward:
            iff = [list(reversed(f)) for f in iff]
        off = len(verts)
        verts.extend(iv)
        faces.extend([off + i for i in f] for f in iff)
    return verts, faces
