# Substitution tilings: prototiles, inflation rules, and expansion.
#
# Part of the Math Art Pattern Engine (`math_art/patterns/`).  Python and
# numpy only -- no `bpy` -- so the engine imports and self-tests headlessly.
#
# A SUBSTITUTION TILING is generated by one rule: each prototile is
# replaced by a patch of smaller prototiles, and the patch is inflated so
# the children are the size the parent was.  Iterate and the tiling grows.
# Penrose, Ammann-Beenker, the rep-tiles, the hat and the spectre are all
# this, differing only in their prototiles and rules.
#
# THE COMMON FORM IS A PLANAR SIMILARITY, written on complex numbers:
#
#     z  ->  A*z + B*conj(z) + C
#
# with B = 0 for an orientation-PRESERVING map (rotate, scale, translate)
# and A = 0 for an orientation-REVERSING one (a reflection as well).  Both
# halves matter: Penrose P2/P3 need only rotations, but the hat tiles the
# plane only if reflected copies are allowed, so a substitution engine
# that cannot express reflection cannot express the hat.
#
# This form was already in the codebase -- `fractal_reptile_generator`
# writes its maps as exactly (A, B, C) and composes them in closed form.
# The other four engines each use a narrower encoding (integer 2x2
# matrices, a bare similarity, a carried transform, or direct vertex
# construction), and all four are expressible here.
#
# WHAT AN EXPANSION RETURNS is a list of PLACEMENTS -- (prototile id,
# similarity) -- not baked polygons.  That is deliberate: the placement
# form is what a tiling backend owes the rest of the engine (the relief
# and interlace layers can then ask for geometry, adjacency, or the group
# word that produced a tile), and baking polygons too early is what makes
# a backend un-composable.
#
# References:
#   R. Penrose, "The role of aesthetics in pure and applied mathematical
#     research", Bull. Inst. Math. Appl. 10 (1974) -- the P2/P3 tilings.
#   B. Grunbaum and G. C. Shephard, "Tilings and Patterns" (1987),
#     chapter 10 -- substitution systems and inflation.
#   D. Smith, J. S. Myers, C. S. Kaplan and C. Goodman-Strauss, "An
#     aperiodic monotile" (arXiv:2303.10798, 2023) and "A chiral
#     aperiodic monotile" (arXiv:2305.17743, 2023) -- the hat and the
#     spectre, and why reflections must be representable.
#   C. Bandt, "Self-similar sets 5: integer matrices and fractal tilings",
#     Proc. AMS 112 (1991) -- rep-tiles as integer-matrix substitutions.

import cmath
import math

import numpy as np

#: the golden ratio, which the Penrose rules are built from
PHI = (1.0 + 5.0 ** 0.5) / 2.0


class Similarity:
    """A planar similarity `z -> A*z + B*conj(z) + C` on complex numbers.

    `B == 0` is orientation-preserving; `A == 0` is orientation-reversing
    (it includes a reflection).  A map with both non-zero is not a
    similarity and is rejected, because silently accepting one would
    produce a tiling whose tiles are not congruent to their prototiles.
    """

    __slots__ = ('A', 'B', 'C')

    def __init__(self, A=1.0 + 0j, B=0.0 + 0j, C=0.0 + 0j):
        A, B, C = complex(A), complex(B), complex(C)
        if abs(A) > 1e-12 and abs(B) > 1e-12:
            raise ValueError(
                "not a similarity: exactly one of A (direct) and B "
                "(reflected) must be zero")
        self.A, self.B, self.C = A, B, C

    # -- construction ----------------------------------------------------
    @classmethod
    def identity(cls):
        return cls(1.0 + 0j, 0.0 + 0j, 0.0 + 0j)

    @classmethod
    def from_pair(cls, s0, s1, d0, d1, reflect=False):
        """The similarity carrying the segment s0->s1 onto d0->d1.

        Two points determine a planar similarity once the handedness is
        fixed, which is what `reflect` selects.
        """
        s0, s1, d0, d1 = (complex(x) for x in (s0, s1, d0, d1))
        ds = s1 - s0
        if abs(ds) < 1e-15:
            raise ValueError("degenerate source segment")
        if reflect:
            B = (d1 - d0) / np.conj(ds)
            return cls(0.0, B, d0 - B * np.conj(s0))
        A = (d1 - d0) / ds
        return cls(A, 0.0, d0 - A * s0)

    @classmethod
    def from_triangle(cls, src, dst, tol=1e-9):
        """The similarity carrying triangle `src` onto `dst`.

        Tries the direct map first and falls back to the reflected one,
        so a rule table can be DERIVED from a worked example rather than
        transcribed by hand -- which is how the Penrose rules below were
        obtained and is why they cannot be mistyped.
        """
        for reflect in (False, True):
            m = cls.from_pair(src[0], src[1], dst[0], dst[1], reflect)
            if abs(m.apply(src[2]) - complex(dst[2])) < tol:
                return m
        raise ValueError("no similarity carries src onto dst")

    # -- use -------------------------------------------------------------
    def apply(self, z):
        z = np.asarray(z)
        return self.A * z + self.B * np.conj(z) + self.C

    def compose(self, other):
        """`self o other`: apply `other` first, then `self`."""
        a2, b2, c2 = self.A, self.B, self.C
        a1, b1, c1 = other.A, other.B, other.C
        A = a2 * a1 + b2 * np.conj(b1)
        B = a2 * b1 + b2 * np.conj(a1)
        C = a2 * c1 + b2 * np.conj(c1) + c2
        return Similarity(A, B, C)

    @property
    def scale(self):
        return abs(self.A) + abs(self.B)

    @property
    def reflected(self):
        return abs(self.B) > abs(self.A)

    def __repr__(self):
        kind = 'reflected' if self.reflected else 'direct'
        return f"Similarity({kind}, scale={self.scale:.6g})"


class Substitution:
    """Prototiles plus an inflation rule, and the expansion they generate.

    `prototiles` maps an id to a polygon (a sequence of complex vertices).
    `rules` maps an id to a list of `(child_id, Similarity)` placements
    expressed IN THE PARENT'S OWN FRAME, so a rule is independent of where
    the parent sits.

    `inflation` is the linear scale factor of one generation -- phi for
    Penrose.  It is not used to expand (the rules carry their own scale)
    but it is checked against them, which catches a mistyped rule.
    """

    def __init__(self, prototiles, rules, inflation=None, name=''):
        self.prototiles = {k: [complex(z) for z in v]
                           for k, v in prototiles.items()}
        self.rules = rules
        self.inflation = inflation
        self.name = name

    def expand(self, placements, generations=1):
        """Apply the rule `generations` times to a list of placements.

        A placement is `(prototile_id, Similarity)`.  Children compose
        their rule transform with the parent's, which is the whole of the
        expansion: no geometry is built until `tiles` is called.
        """
        out = list(placements)
        for _ in range(int(generations)):
            nxt = []
            for pid, T in out:
                for cid, R in self.rules[pid]:
                    nxt.append((cid, T.compose(R)))
            out = nxt
        return out

    def tiles(self, placements):
        """Realise placements as polygons: `(prototile_id, vertices)`."""
        return [(pid, [T.apply(z) for z in self.prototiles[pid]])
                for pid, T in placements]

    def check_rules(self, tol=1e-9):
        """The children of a rule must exactly tile their parent.

        Checked by AREA: the child areas must sum to the parent's.  That
        is the defining property of a substitution, and it is the right
        invariant even when the prototiles differ in size -- a rule's
        children shrink by different factors relative to their OWN
        prototiles whenever the prototiles are not congruent, so a
        per-child scale check would be wrong here and reject the correct
        Penrose rules.

        Also verifies the inflation: one generation must scale linear
        dimensions by 1/`inflation`, i.e. areas by 1/inflation^2.
        """
        def area(poly):
            z = np.asarray(poly)
            return 0.5 * abs(float(np.imag(
                np.sum(np.conj(z) * np.roll(z, -1)))))

        bad = []
        for pid, kids in self.rules.items():
            if not kids:
                bad.append(f"{pid}: no children")
                continue
            parent = area(self.prototiles[pid])
            total = sum(area([R.apply(z) for z in self.prototiles[cid]])
                        for cid, R in kids)
            if abs(total - parent) > max(tol, 1e-9 * parent):
                bad.append(f"{pid}: children cover {total / parent:.6f} "
                           f"of the parent")
            elif self.inflation:
                want = 1.0 / (self.inflation ** 2)
                got = min(area([R.apply(z) for z in self.prototiles[cid]])
                          / area(self.prototiles[cid]) for cid, R in kids)
                if got > 1.0 - 1e-9:
                    bad.append(f"{pid}: no child is smaller than its "
                               f"prototile")
        return bad


# --------------------------------------------------------------------
# Pilot: Penrose P3 (the thin and thick Robinson triangles)
# --------------------------------------------------------------------
# Half-rhomb triangles, deflated: a thin triangle becomes one thin and
# one thick; a thick becomes two thick and one thin, each smaller by phi.
#
# The rules below are DERIVED, not transcribed.  `_p3_rules` runs one
# deflation on a canonical triangle of each colour and reads off the
# similarity carrying the prototile onto each child.  That is worth doing
# because the alternative -- writing nine complex coefficients by hand --
# has no way to be wrong loudly.

# Vertex convention, matching the classical presentation: a triangle is
# (colour, a, b, c) with `a` the apex between the two equal legs.  Thin
# (0) has sides (1, phi, phi); thick (1) has (1, 1, phi).

#: canonical thin triangle: apex at the origin, unit legs, base 1/phi
P3_THIN = (0.0 + 0j,
           cmath.rect(1.0, math.pi / 10.0),
           cmath.rect(1.0, -math.pi / 10.0))


def _p3_children(color, a, b, c):
    """One deflation of a Robinson triangle, as (colour, a, b, c).

    Thin -> 1 thin + 1 thick; thick -> 2 thick + 1 thin; every child
    smaller by phi.
    """
    if color == 0:
        p = a + (b - a) / PHI
        return [(0, c, p, b), (1, p, c, a)]
    q = b + (a - b) / PHI
    r = b + (c - b) / PHI
    return [(1, r, c, a), (1, q, r, b), (0, r, q, a)]


def _p3_rules():
    """Derive the prototiles and the rule table from the deflation itself.

    Only the thin triangle is given; the thick prototile is READ OFF a
    deflation of it, so the two shapes cannot disagree.  The rules are
    then the similarities carrying each prototile onto each child.
    Deriving rather than transcribing is the point: nine hand-written
    complex coefficients have no way to fail loudly, whereas a wrong
    shape here makes `from_triangle` raise immediately.
    """
    kids = _p3_children(0, *P3_THIN)
    thick = next((ca, cb, cc) for col, ca, cb, cc in kids if col == 1)
    protos = {0: P3_THIN, 1: thick}
    rules = {}
    for color, tri in protos.items():
        rules[color] = [
            (ccol, Similarity.from_triangle(protos[ccol], (ca, cb, cc)))
            for ccol, ca, cb, cc in _p3_children(color, *tri)]
    return protos, rules


def penrose_p3():
    """The Penrose P3 substitution, as a `Substitution`."""
    protos, rules = _p3_rules()
    return Substitution({k: list(v) for k, v in protos.items()}, rules,
                        inflation=PHI, name='Penrose P3')


def _selftest():
    ok = True

    # --- the similarity algebra ---------------------------------------
    z = np.array([0 + 0j, 1 + 0j, 0.3 + 0.7j, -0.5 - 0.2j])
    ident = Similarity.identity()
    good = np.allclose(ident.apply(z), z)
    rot = Similarity(cmath.exp(1j * 0.7), 0, 1 + 2j)
    ref = Similarity(0, cmath.exp(1j * 0.3), -1j)
    # a similarity scales every distance by the same factor
    for m, want in ((rot, abs(rot.A)), (ref, abs(ref.B))):
        w = m.apply(z)
        d0 = np.abs(z[:, None] - z[None, :])
        d1 = np.abs(w[:, None] - w[None, :])
        good = good and np.allclose(d1[d0 > 0] / d0[d0 > 0], want)
    ok &= good
    print(f"substitution: identity, and both map kinds preserve ratios "
          f"{'OK' if good else 'FAIL'}")

    # composition is associative and matches applying in turn
    a, b = rot, ref
    good = (np.allclose(a.compose(b).apply(z), a.apply(b.apply(z)))
            and np.allclose(b.compose(a).apply(z), b.apply(a.apply(z))))
    # reflected o reflected is direct
    good = good and not ref.compose(ref).reflected and rot.compose(ref).reflected
    ok &= good
    print(f"substitution: composition matches sequential application, and "
          f"two reflections make a rotation {'OK' if good else 'FAIL'}")

    # a map with both A and B non-zero is not a similarity and is refused
    try:
        Similarity(1, 1, 0)
        good = False
    except ValueError:
        good = True
    ok &= good
    print(f"substitution: a non-similarity is refused "
          f"{'OK' if good else 'FAIL'}")

    # from_triangle recovers direct AND reflected maps
    tri = (0 + 0j, 1 + 0j, 0.4 + 0.9j)
    for m in (rot, ref):
        dst = [m.apply(t) for t in tri]
        rec = Similarity.from_triangle(tri, dst)
        good = good and np.allclose([rec.apply(t) for t in tri], dst)
    ok &= good
    print(f"substitution: from_triangle recovers direct and reflected maps "
          f"{'OK' if good else 'FAIL'}")

    # --- the Penrose P3 pilot ------------------------------------------
    sub = penrose_p3()
    bad = sub.check_rules(tol=1e-9)
    good = not bad
    ok &= good
    print(f"substitution: P3 children exactly tile their parent "
          f"{'OK' if good else 'FAIL ' + '; '.join(bad)}")

    # tile counts follow the Fibonacci-like recurrence the rules encode:
    # thin -> 1 thin + 1 thick, thick -> 1 thin + 2 thick
    nthin, nthick = 1, 0
    place = [(0, Similarity.identity())]
    bad = []
    for g in range(1, 9):
        nthin, nthick = nthin + nthick, nthin + 2 * nthick
        place = sub.expand(place, 1)
        got = (sum(1 for pid, _ in place if pid == 0),
               sum(1 for pid, _ in place if pid == 1))
        if got != (nthin, nthick):
            bad.append(f"gen{g}:{got}!=({nthin},{nthick})")
    good = not bad
    ok &= good
    print(f"substitution: P3 tile counts match the recurrence to 8 "
          f"generations ({nthin}+{nthick}) "
          f"{'OK' if good else 'FAIL ' + ','.join(bad)}")

    # THE RATIO OF THICK TO THIN TENDS TO PHI.  This is the property that
    # makes the tiling aperiodic -- an irrational ratio cannot arise from
    # a periodic pattern -- so it is the check worth making.
    ratio = nthick / nthin
    good = abs(ratio - PHI) < 1e-3
    ok &= good
    print(f"substitution: thick/thin -> {ratio:.6f} (phi = {PHI:.6f}) "
          f"{'OK' if good else 'FAIL'}")

    # every tile is congruent to its prototile: side lengths match after
    # scaling, which is what "substitution" means and what a wrong
    # transform breaks
    tiles = sub.tiles(sub.expand([(1, Similarity.identity())], 4))
    bad = []
    for pid, poly in tiles[:40]:
        proto = sub.prototiles[pid]
        s = abs(poly[1] - poly[0]) / abs(proto[1] - proto[0])
        for i in range(3):
            j = (i + 1) % 3
            want = abs(proto[j] - proto[i]) * s
            if abs(abs(poly[j] - poly[i]) - want) > 1e-9:
                bad.append(pid)
                break
    good = not bad
    ok &= good
    print(f"substitution: every tile is similar to its prototile "
          f"{'OK' if good else 'FAIL'}")


    # THE PILOT'S GATE: the generic engine must reproduce the bespoke
    # Penrose deflation that aperiodic_generator has always used.  Same
    # seed, same generations, compared as a sorted vertex cloud -- if the
    # rules were derived wrongly this diverges within two generations.
    try:
        from .. import aperiodic_generator as _ap
    except ImportError:
        import aperiodic_generator as _ap
    bad = []
    for gens in range(0, 5):
        old = _ap._p3_triangles(gens)
        seed = [(0, Similarity.from_triangle(sub.prototiles[0], (a, b, c)))
                for _c, a, b, c in _ap._p3_seed()]
        got = sub.tiles(sub.expand(seed, gens))
        if len(got) != len(old):
            bad.append(f"gen{gens}:{len(got)}!={len(old)}")
            continue
        co = np.sort_complex(np.round(np.array(
            [v for _c, *tri in old for v in tri]), 7))
        cn = np.sort_complex(np.round(np.array(
            [v for _pid, poly in got for v in poly]), 7))
        if len(co) != len(cn) or float(np.max(np.abs(co - cn))) > 1e-7:
            bad.append(f"gen{gens}:vertices")
    good = not bad
    ok &= good
    print(f"substitution: the engine reproduces aperiodic's own P3 "
          f"deflation to 4 generations "
          f"{'OK' if good else 'FAIL ' + ','.join(bad)}")

    print("RESULT:", "OK" if ok else "FAIL")
    if not ok:
        raise AssertionError("substitution self-test failed")
