"""Evolver cells, generated FROM the surface database.

GENERATED by `python tools/bake_fe_cells.py --module` -- do
not hand-edit.  The defining data lives in the records under
`data/surfaces`; this module exists only so the shipped
extension carries the numbers without needing the database
or the original datafiles.
"""

import numpy as np

FE_CELLS = {
    'CLP_EXACT': {
        'title': 'CLP (exact)',
        'slug': 'clp-exact',
        'source': 'CLP.fe',
        'word': 'af',
        'copies': 4,
        'loops': (
            np.array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0]).reshape(-1, 3),
        ),
        'letters': {
            'a': np.array([-1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'f': np.array([-1, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'H_EXACT': {
        'title': 'H (exact)',
        'slug': 'h-exact',
        'source': 'hcell.fe',
        'word': 'ad',
        'copies': 4,
        'loops': (
            np.array([-1.73205080757, 0, 0, 1.73205080757, 0, 0, 0, 3, 0]).reshape(-1, 3),
            np.array([-1.73205080757, 0, 1, 1.73205080757, 0, 1, 0, 3, 1]).reshape(-1, 3),
        ),
        'letters': {
            'a': np.array([1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'd': np.array([1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 2, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'IWP_SURFACE': {
        'title': 'Iwp surface',
        'slug': 'iwp-surface',
        'source': 'IWP.fe',
        'word': 'bdb',
        'copies': 6,
        'loops': (
            np.array([1, 0.5, 1, 0.5, 0.5, 1, 0, 0, 0.5, 0.5, 0, 0.5]).reshape(-1, 3),
        ),
        'letters': {
            'b': np.array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'd': np.array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'NEOVIUS_SURFACE': {
        'title': 'Neovius surface',
        'slug': 'neovius-surface',
        'source': 'neovius.fe',
        'word': 'bcdbcdbcd',
        'copies': 48,
        'loops': (
            np.array([0.5, 0, 1, 1, 0.2, 1, 0.5, 0.5, 0.5, 0, 0, 0.8]).reshape(-1, 3),
        ),
        'letters': {
            'b': np.array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'c': np.array([1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'd': np.array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'SCHOEN_I8': {
        'title': 'I8_RING (exact)',
        'slug': 'schoen-i8',
        'source': 'I-8.fe',
        'word': 'bac',
        'copies': 8,
        'loops': (
            np.array([0, 0, 0, 1, 0, 0, 0.5, 0.5, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, -0.5, -0.5, 0, -1, 0, 0]).reshape(-1, 3),
            np.array([0, 0, 0.5, 1, 0, 0.5, 0.5, 0.5, 0.5, 0, 1, 0.5, 0, 0, 0.5, 0, -1, 0.5, -0.5, -0.5, 0.5, -1, 0, 0.5]).reshape(-1, 3),
        ),
        'letters': {
            'a': np.array([1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'b': np.array([0, 1, 0, 1, -1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'c': np.array([0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0.5, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'SCHOEN_I9': {
        'title': 'I9_RING (exact)',
        'slug': 'schoen-i9',
        'source': 'I-9.fe',
        'word': 'abc',
        'copies': 8,
        'loops': (
            np.array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, -1, 1, 0, 0, 0, 0, -1, 0, 0, -1, -1, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0]).reshape(-1, 3),
            np.array([0, 0, 0.5, 1, 0, 0.5, 1, 1, 0.5, 0, 0, 0.5, 0, 1, 0.5, -1, 1, 0.5, 0, 0, 0.5, -1, 0, 0.5, -1, -1, 0.5, 0, 0, 0.5, 0, -1, 0.5, 1, -1, 0.5]).reshape(-1, 3),
        ),
        'letters': {
            'a': np.array([1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'b': np.array([1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'c': np.array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0.5, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'SCHOEN_RII': {
        'title': 'RII (exact)',
        'slug': 'schoen-rii',
        'source': 'RII.fe',
        'word': 'fdfedfe',
        'copies': 32,
        'loops': (
            np.array([0, 0, 0, 1, 0, 0, 0, 1, 0]).reshape(-1, 3),
            np.array([0, 0, 0.2, 1, 0, 0.2, 0, 1, 0.2]).reshape(-1, 3),
        ),
        'letters': {
            'd': np.array([1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0.4, 0, 0, 0, 1]).reshape(4, 4),
            'e': np.array([-1, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1, 0.4, 0, 0, 0, 1]).reshape(4, 4),
            'f': np.array([0, -1, 0, 1, -1, 0, 0, 1, 0, 0, -1, 0.4, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'SCHOEN_RIII': {
        'title': 'R3_RING (exact)',
        'slug': 'schoen-riii',
        'source': 'RIII.fe',
        'word': 'fdfedfe',
        'copies': 24,
        'loops': (
            np.array([0, 0, 0, 1.73205080757, 0, 0, 0, 3, 0]).reshape(-1, 3),
            np.array([0, 0, 0.5, 1.73205080757, 0, 0.5, 0, 3, 0.5]).reshape(-1, 3),
        ),
        'letters': {
            'd': np.array([1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 1, 0, 0, 0, 1]).reshape(4, 4),
            'e': np.array([-1, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1, 1, 0, 0, 0, 1]).reshape(4, 4),
            'f': np.array([-0.5, -0.866025403784, 0, 2.59807621135, -0.866025403784, 0.5, 0, 1.5, 0, 0, -1, 1, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'SCHWARZ_D': {
        'title': 'Schwarz D Surface',
        'slug': 'schwarz-d',
        'source': 'dcell.fe',
        'word': 'abcabcg',
        'copies': 48,
        'loops': (
            np.array([1, 0, 1, 0.5, 0.5, 0.5, 0, 0, 1]).reshape(-1, 3),
        ),
        'letters': {
            'a': np.array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'b': np.array([0, -1, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'c': np.array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]).reshape(4, 4),
            'g': np.array([1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 2, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
    'SCHWARZ_P': {
        'title': 'Schwarz P Surface',
        'slug': 'schwarz-p',
        'source': 'pcell.fe',
        'word': 'dcbdcbdcb',
        'copies': 48,
        'loops': (
            np.array([0.5, 0.5, 1, 0.5, 0, 1, 0.5, 0, 0.5, 0.5, 0.5, 0.5]).reshape(-1, 3),
        ),
        'letters': {
            'b': np.array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'c': np.array([1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]).reshape(4, 4),
            'd': np.array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]).reshape(4, 4),
        },
    },
}
