
# The rewriting engine: modules, a maximal-munch tokeniser, productions,
# and derivation.
#
# THE POINT OF THIS MODULE.  The generator this replaces rewrote with
#
#     "".join(rules.get(c, c) for c in s)
#
# -- a per-CHARACTER substitution.  That makes multi-character module
# names (`Fl`, `internode`, `seg`, `Apex`) not merely unsupported but
# *unrepresentable*, which in turn makes every model in chapters 3-5 of
# "The Algorithmic Beauty of Plants" inexpressible.  The tokeniser below
# is the piece that unblocks them, and parameters follow from it.
#
# There is also a theorem behind the change, not just an aesthetic
# complaint.  Frijters and Lindenmayer observed, and Prusinkiewicz and
# Kari formalised, that arbitrarily large MESOTONIC and ACROTONIC
# structures cannot be generated by non-parametric deterministic
# 0L-systems with subapical branching: because new branches appear only
# near the apices, the lowest branches are created first and have the
# longest to grow, so a BASITONIC (base-heavy) form is forced.  Real
# plants are frequently heaviest in the middle or at the top.  So the old
# engine could not produce a realistically shaped tree at all, and no
# choice of preset or angle could fix it -- parameters are the documented
# escape.  `_selftest` checks exactly that case.
#
# WHAT A GRAMMAR LOOKS LIKE.  The text syntax transcribes the book's
# listings closely:
#
#     #define R 0.9              -- a constant, usable in any expression
#     #param  R 0.9 0.5 1.0 0.01 Contraction ratio
#                                -- the same, but declared FREE: a host UI
#                                   can render it, within the range and to
#                                   the increment the author chose
#     #param  arity 2 (Binary=2|Ternary=3) Branches per node
#                                -- a free parameter restricted to a fixed
#                                   set of choices, rendered as a menu
#     #ignore + - /              -- skipped when matching context
#     #mode parallel             -- or `sequential` (see below)
#     module Apex(age), Seg(len) -- declare multi-character module names
#     axiom: Apex(0)
#     p1: Apex(a) : a < 5 -> Seg(1)[+Apex(a+1)]Apex(a+1)
#     p2: A(x) < B(y) > C(z) : x+z > 10 -> E((x+y)/2)F((y+z)/2)
#     p3: A -> B : 0.4           -- stochastic weight after the successor
#
# PARALLEL vs SEQUENTIAL.  L-system productions describe development in
# TIME and are applied to every module at once; Chomsky-style
# decomposition rules describe structure in SPACE and may be applied one
# at a time, terminating when no rule matches rather than after a fixed
# step count.  Both are supported because the curve work and the organ
# placement work in this project are structural, not developmental.
#
# References:
# - Aristid Lindenmayer, "Mathematical models for cellular interaction in
#   development", J. Theoretical Biology 18, 1968.
# - Przemyslaw Prusinkiewicz and Aristid Lindenmayer, "The Algorithmic
#   Beauty of Plants", Springer, 1990 -- sections 1.2 (the triple
#   <V, omega, P>), 1.7 (stochastic), 1.8 (context-sensitive, #ignore)
#   and 1.10 (parametric modules, conditions, #define).
# - Przemyslaw Prusinkiewicz, Jim Hanan, Mark Hammel and Radomir Mech,
#   "L-systems: from the Theory to Visual Models of Plants", SIGGRAPH
#   2003 course notes, chapter 2-1, section 4 -- the three matching
#   conditions (letter, arity, condition) implemented in `_match`.
# - Frederic Boudon, Christophe Pradal, Thomas Cokelaer, Przemyslaw
#   Prusinkiewicz and Christophe Godin, "L-Py: an L-system simulation
#   framework ... based on a dynamic language", Frontiers in Plant
#   Science 3:76, 2012 -- declaration-driven tokenisation, matching on
#   name AND arity, and the StartEach/EndEach hooks.
# - Przemyslaw Prusinkiewicz, Lars Mundermann, Radoslaw Karwowski and
#   Brendan Lane, "The use of positional information in the modeling of
#   plants", SIGGRAPH 2001 -- the L-system versus Chomsky-grammar
#   distinction that `mode` implements.
# - Przemyslaw Prusinkiewicz and Lila Kari, "Subapical bracketed
#   L-systems" -- the mesotonic/acrotonic impossibility result.

import random
import re
from collections import namedtuple

from .expr import ExprError, compile_expr

# A module is a letter plus zero or more real parameters: `F(1.0, 0.5)`.
Module = namedtuple("Module", "sym params")

# A word is a list of Modules.  Brackets are ordinary modules with the
# symbols '[' and ']' so that context matching can skip over them.
BRANCH_OPEN, BRANCH_CLOSE = "[", "]"

DEFAULT_BUDGET = 2_000_000


class GrammarError(ValueError):
    """A grammar could not be parsed.  Carries a human-readable reason;
    the operator surfaces it with self.report({'ERROR'}) instead of
    raising into Blender's UI."""


def m(sym, *params):
    """Terse Module constructor for hand-written data tables."""
    return Module(sym, tuple(float(p) for p in params))


def word_str(word):
    """Render a word the way the books print it, so derivations can be
    compared against published sequences character by character."""
    out = []
    for mod in word:
        if mod.params:
            args = ",".join(_fmt(p) for p in mod.params)
            out.append(f"{mod.sym}({args})")
        else:
            out.append(mod.sym)
    return "".join(out)


def _fmt(v):
    if v == int(v):
        return str(int(v))
    return f"{round(v, 6):g}"


# ---------------------------------------------------------------------
# Tokenising
# ---------------------------------------------------------------------

def tokenize(src, names=()):
    """Split `src` into Modules by MAXIMAL MUNCH over declared names.

    Declared multi-character names are tried longest-first; anything else
    is a single character.  So with `Apex` declared, `Apex` is one module
    -- but `FF` is still two, and `Fseg` is `F` then `seg` (given `seg`
    declared).  Without this rule `Apex` would tokenise as A, p, e, x,
    which is precisely the defect being fixed.

    Parameters are parsed as raw expression SOURCE here; the caller
    decides whether they are literals (in an axiom) or expressions (in a
    successor).
    """
    ordered = sorted({n for n in names if n}, key=len, reverse=True)
    out = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c.isspace():
            i += 1
            continue
        sym = None
        for cand in ordered:
            if src.startswith(cand, i):
                # A declared name must not be a prefix of a longer
                # identifier: with `seg` declared, `segment` is not `seg`
                # followed by `ment` unless `ment` is declared too.
                j = i + len(cand)
                if not (cand[-1].isalnum() and j < n and
                        (src[j].isalnum() or src[j] == "_")
                        and not any(src.startswith(o, j) for o in ordered)):
                    sym = cand
                    break
        if sym is None:
            sym = c
        i += len(sym)
        args = []
        if i < n and src[i] == "(":
            depth, j = 0, i
            while j < n:
                if src[j] == "(":
                    depth += 1
                elif src[j] == ")":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            if depth != 0:
                raise GrammarError(f"unbalanced '(' after {sym!r} in {src!r}")
            args = _split_args(src[i + 1:j])
            i = j + 1
        out.append((sym, args))
    return out


def _split_args(s):
    """Split `a, b(c,d), e` on top-level commas only."""
    out, depth, cur = [], 0, []
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    tail = "".join(cur).strip()
    if tail or out:
        out.append(tail)
    return [a for a in out if a != ""] or ([] if not out else out)


# ---------------------------------------------------------------------
# Productions
# ---------------------------------------------------------------------

class Production:
    """One rewriting rule.

    `left`/`right` are context word patterns (symbols only -- context is
    matched on identity, not on parameter values), `strict` is the module
    being replaced together with its FORMAL parameter names, `cond` is an
    optional compiled condition, `succ` is the successor as
    (symbol, [compiled argument expressions]) pairs, and `prob` is the
    stochastic weight.
    """

    __slots__ = ("label", "left", "strict_sym", "formals", "right",
                 "cond", "succ", "prob", "src")

    def __init__(self, label, left, strict_sym, formals, right,
                 cond, succ, prob, src=""):
        self.label = label
        self.left = left
        self.strict_sym = strict_sym
        self.formals = formals
        self.right = right
        self.cond = cond
        self.succ = succ
        self.prob = prob
        self.src = src

    @property
    def contextual(self):
        return bool(self.left or self.right)

    def __repr__(self):
        return f"Production({self.src!r})"


class Param:
    """A knob a grammar declares with `#param`, for a UI to render.

    Carries everything the caller needs to build a control without
    knowing anything about the grammar: the range, the increment the
    author considers meaningful, and a human label.  `value` is what
    this parse actually used, after any override and clamping.
    """

    __slots__ = ("name", "default", "lo", "hi", "step", "label", "value",
                 "choices")

    def __init__(self, name, default, lo, hi, step, label, value,
                 choices=None):
        self.name = name
        self.default = default
        self.lo = lo
        self.hi = hi
        self.step = step
        self.label = label
        self.value = value
        #: ((text, value), ...) when the author declared a fixed set,
        #: else None.  A UI should render these as a menu, not a slider.
        self.choices = tuple(choices) if choices else None

    @property
    def is_choice(self):
        return self.choices is not None

    def snap(self, v):
        """Coerce a value to what the author actually allows: the nearest
        declared choice, or the range rounded to the declared step."""
        v = float(v)
        if self.choices:
            return min((c[1] for c in self.choices), key=lambda c: abs(c - v))
        if self.step:
            base = self.lo if self.lo is not None else 0.0
            v = base + round((v - base) / self.step) * self.step
        if self.lo is not None:
            v = min(max(v, self.lo), self.hi)
        return v

    def text_for(self, v):
        """The label of the choice matching `v`, for a UI or a report."""
        if not self.choices:
            return f"{v:g}"
        for text, val in self.choices:
            if abs(val - float(v)) < 1e-12:
                return text
        return f"{v:g}"

    def __repr__(self):
        if self.choices:
            return (f"Param({self.name}={self.value:g}, "
                    f"choices={[c[0] for c in self.choices]})")
        return (f"Param({self.name}={self.value:g}, "
                f"range=({self.lo}, {self.hi}), step={self.step})")


def _isnum(tok):
    try:
        float(tok)
        return True
    except ValueError:
        return False


class Grammar:
    """A parsed L-system: alphabet, axiom, productions, constants, ignore
    set -- plus the derivation itself."""

    def __init__(self, axiom, productions, constants=None, ignore=(),
                 names=(), mode="parallel", source="", draw=(), angle=None,
                 step=None, iters=None, max_iters=None, closed=False,
                 title=""):
        self.axiom = list(axiom)
        self.productions = list(productions)
        self.constants = dict(constants or {})
        #: `Param` records from `#param`, in declaration order.
        self.params = ()
        #: True if the grammar asked for the developmental series
        #: (`#develop`) -- see `turtle.stack_series`.
        self.develop = False
        self.ignore = set(ignore)
        self.names = tuple(names)
        self.mode = mode
        self.source = source
        # Presentation defaults a preset may carry with it, so the
        # operator does not need a parallel table of magic numbers.
        # `draw` is the set of letters the turtle advances on: the
        # Sierpinski arrowhead and the Gosper curve draw with A and B,
        # not F, so this cannot be a global constant.
        self.draw = frozenset(draw)
        self.angle = angle
        self.step = step
        self.iters = iters
        self.max_iters = max_iters
        self.closed = closed
        self.title = title
        # Context-sensitive productions take priority over context-free
        # ones; within each group the FIRST match wins.  Both rules are
        # stated in the 2003 course notes and in L-Py.
        self._ordered = ([p for p in self.productions if p.contextual] +
                         [p for p in self.productions if not p.contextual])
        self._by_sym = {}
        for p in self._ordered:
            self._by_sym.setdefault(p.strict_sym, []).append(p)

    # -- parsing ------------------------------------------------------

    @classmethod
    def parse(cls, text, params=None):
        """Parse the text syntax.  Raises GrammarError with a reason.

        `params` overrides the defaults of any `#param` the grammar
        declares -- {name: value}.  Overriding at PARSE time rather than
        at derivation time is deliberate: axiom arguments are folded to
        literals while parsing, so a parameter used in the axiom would
        otherwise be frozen at its declared default.
        """
        overrides = {str(k): float(v) for k, v in (params or {}).items()}
        declared = []
        constants, ignore, names, mode = {}, set(), [], "parallel"
        draw, angle, step = set(), None, None
        iters, max_iters, closed, title = None, None, False, ""
        develop = False
        axiom_src, rule_srcs = None, []

        # Block comments may SPAN LINES, so they are stripped from the
        # whole source before it is split -- doing it per line silently
        # swallowed every line of a multi-line /* ... */ block.
        text_nc = _COMMENT_RE.sub(" ", text)
        for raw in text_nc.splitlines():
            # Comments must not collide with the turtle alphabet.  `--`
            # is "turn right twice" and `//` is "roll right twice", both
            # of which occur in real grammars -- the Koch snowflake's
            # axiom is literally `F--F--F`.  Treating either as an inline
            # comment silently truncates the axiom to `F` and still draws
            # a plausible-looking curve, which is the worst kind of bug.
            # So: `/* ... */` inline (the form the published listings
            # actually use), and `--` or `//` only at the START of a line.
            line = raw.strip()
            if line.startswith("--") or line.startswith("//"):
                continue
            if not line or line.startswith("#!"):
                continue
            low = line.lower()
            if low.startswith("#define"):
                parts = line.split(None, 2)
                if len(parts) < 3:
                    raise GrammarError(f"bad #define: {line!r}")
                try:
                    constants[parts[1]] = float(
                        compile_expr(parts[2], (), constants).ev({}))
                except (ExprError, AttributeError) as exc:
                    raise GrammarError(f"bad #define {parts[1]!r}: {exc}")
                continue
            if low.startswith("#develop"):
                # This grammar describes a FILAMENT, whose single
                # generation is a bare rod; ask the host to draw the
                # developmental series instead.
                develop = True
                continue
            if low.startswith("#param"):
                # #param NAME DEFAULT [MIN MAX] [Label with spaces]
                #
                # A constant the CALLER may override -- the hook the
                # operator uses to turn a grammar's own knobs into
                # sliders.  It behaves exactly like `#define` when no
                # override is supplied, so a grammar stays valid, and
                # self-describing, outside Blender.
                toks = line.split()
                if len(toks) < 3:
                    raise GrammarError(f"bad #param: {line!r}")
                pname = toks[1]
                try:
                    pdef = float(compile_expr(toks[2], (), constants).ev({}))
                except (ExprError, AttributeError) as exc:
                    raise GrammarError(f"bad #param {pname!r}: {exc}")
                choices = None
                grp = _CHOICE_RE.search(line)
                if grp:
                    choices = []
                    for opt in grp.group(1).split("|"):
                        opt = opt.strip()
                        if not opt:
                            continue
                        if "=" in opt:
                            ctext, cval = opt.rsplit("=", 1)
                        else:
                            ctext, cval = opt, opt
                        try:
                            choices.append((ctext.strip(), float(cval)))
                        except ValueError:
                            raise GrammarError(
                                f"bad #param {pname!r}: choice {opt!r} has "
                                f"no numeric value (use `Text=value`)")
                    if not choices:
                        raise GrammarError(
                            f"bad #param {pname!r}: empty choice list")
                    rec = Param(pname, pdef, None, None, 0.0,
                                (line[grp.end():].strip() or pname),
                                pdef, choices)
                    rec.value = rec.snap(overrides.get(pname, pdef))
                    constants[pname] = rec.value
                    declared.append(rec)
                    continue

                rest, lo, hi, pstep = toks[3:], None, None, 0.0
                if len(rest) >= 2 and _isnum(rest[0]) and _isnum(rest[1]):
                    lo, hi = float(rest[0]), float(rest[1])
                    rest = rest[2:]
                    if hi < lo:
                        raise GrammarError(
                            f"bad #param {pname!r}: max {hi} below min {lo}")
                    if rest and _isnum(rest[0]):
                        pstep = abs(float(rest[0]))
                        rest = rest[1:]
                rec = Param(pname, pdef, lo, hi, pstep,
                            " ".join(rest) or pname, pdef)
                rec.value = rec.snap(overrides.get(pname, pdef))
                constants[pname] = rec.value
                declared.append(rec)
                continue
            if low.startswith("#ignore") or low.startswith("#consider"):
                syms = line.split(None, 1)[1] if len(line.split()) > 1 else ""
                # `#consider` is the complement of `#ignore`; store the
                # listed symbols and a flag saying which sense applies.
                if low.startswith("#ignore"):
                    ignore.update(s for s in syms.split() if s)
                else:
                    ignore.add(("__consider__",))
                    ignore.update(("__c__" + s) for s in syms.split() if s)
                continue
            if low.startswith("#draw"):
                draw.update(s for s in line.split(None, 1)[1].split() if s)
                continue
            if low.startswith("#angle"):
                angle = float(line.split(None, 1)[1])
                continue
            if low.startswith("#step"):
                step = float(line.split(None, 1)[1])
                continue
            if low.startswith("#iters"):
                bits = line.split(None, 1)[1].replace(",", " ").split()
                iters = int(float(bits[0]))
                if len(bits) > 1:
                    max_iters = int(float(bits[1]))
                continue
            if low.startswith("#closed"):
                closed = True
                continue
            if low.startswith("#title"):
                title = line.split(None, 1)[1].strip()
                continue
            if low.startswith("#mode"):
                mode = line.split(None, 1)[1].strip().lower()
                if mode not in ("parallel", "sequential"):
                    raise GrammarError(f"unknown #mode {mode!r}")
                continue
            if low.startswith("module"):
                decl = line.split(None, 1)[1]
                for item in _split_args(decl) or [decl]:
                    nm = item.split("(")[0].strip()
                    if nm:
                        names.append(nm)
                continue
            if low.startswith("axiom"):
                axiom_src = line.split(":", 1)[1].strip()
                continue
            if "->" in line or "→" in line:
                rule_srcs.append(line)
                continue
            raise GrammarError(f"unrecognised line: {line!r}")

        if axiom_src is None:
            raise GrammarError("grammar has no `axiom:` line")

        names = tuple(dict.fromkeys(names))
        axiom = [Module(sym, tuple(_lit(a, constants) for a in args))
                 for sym, args in tokenize(axiom_src, names)]
        prods = [_parse_rule(s, names, constants) for s in rule_srcs]
        g = cls(axiom, prods, constants, ignore, names, mode, text,
                draw, angle, step, iters, max_iters, closed, title)
        g.params = tuple(declared)
        g.develop = develop
        return g

    # -- derivation ---------------------------------------------------

    def derive(self, n, seed=None, budget=DEFAULT_BUDGET,
               start=None, start_each=None, end_each=None):
        """Rewrite for `n` steps (parallel) or until quiescent
        (sequential), returning the resulting Word.

        `budget` caps the word length; exceeding it raises GrammarError
        rather than hanging Blender's UI.  `start_each(step, word)` and
        `end_each(step, word)` are the per-step hooks from L-Py; they are
        what make a live module-count read-out or a post-processing pass
        possible without touching this module.
        """
        rng = random.Random(seed if seed is not None else 0)
        word = list(self.axiom if start is None else start)
        sequential = self.mode == "sequential"
        for step in range(int(n)):
            if start_each is not None:
                start_each(step, word)
            nxt = (self._step_sequential(word, rng) if sequential
                   else self._step_parallel(word, rng))
            if len(nxt) > budget:
                raise GrammarError(
                    f"derivation exceeded the {budget:,}-module budget at "
                    f"step {step + 1} (reached {len(nxt):,}); reduce the "
                    f"iteration count")
            changed = nxt != word
            word = nxt
            if end_each is not None:
                end_each(step, word)
            if sequential and not changed:
                break            # quiescent: only terminals remain
        return word

    def _step_parallel(self, word, rng):
        out = []
        for i, mod in enumerate(word):
            p, binding = self._select(word, i, mod, rng)
            if p is None:
                out.append(mod)
            else:
                out.extend(_expand(p, binding))
        return out

    def _step_sequential(self, word, rng):
        """Chomsky-style: rewrite the FIRST matching module only."""
        for i, mod in enumerate(word):
            p, binding = self._select(word, i, mod, rng)
            if p is not None:
                return word[:i] + _expand(p, binding) + word[i + 1:]
        return list(word)

    def _select(self, word, i, mod, rng):
        """Return (production, binding) for the module at `i`, or
        (None, None) when the identity production applies."""
        cands = self._by_sym.get(mod.sym)
        if not cands:
            return None, None
        matches = []
        for p in cands:
            binding = self._match(word, i, mod, p)
            if binding is not None:
                matches.append((p, binding))
                # Deterministic rules resolve to the first match; only
                # gather the rest when weights are actually in play.
                if p.prob >= 1.0 and not any(
                        q.prob < 1.0 for q in cands):
                    break
        if not matches:
            return None, None
        if len(matches) == 1:
            return matches[0]
        total = sum(p.prob for p, _ in matches)
        if total <= 0.0:
            return matches[0]
        r = rng.random() * total
        acc = 0.0
        for p, binding in matches:
            acc += p.prob
            if r <= acc:
                return p, binding
        return matches[-1]

    def _match(self, word, i, mod, p):
        """The three matching conditions from the 2003 course notes:
        the letter agrees, the ARITY agrees, and the condition holds.
        Returns the parameter binding, or None."""
        if len(mod.params) != len(p.formals):
            return None
        binding = dict(self.constants)
        binding.update(zip(p.formals, mod.params))
        if p.left and not self._ctx_left(word, i, p.left):
            return None
        if p.right and not self._ctx_right(word, i, p.right):
            return None
        if p.cond is not None:
            try:
                if p.cond.ev(binding) == 0.0:
                    return None
            except ExprError:
                return None
        return binding

    def _skip(self, sym):
        """True when `sym` is invisible to context matching."""
        if ("__consider__",) in self.ignore:
            return ("__c__" + sym) not in self.ignore
        return sym in self.ignore

    def _ctx_left(self, word, i, pat):
        """Left context: walk back, skipping ignored symbols and whole
        completed branches -- the bracketed string does not preserve
        segment adjacency, so `]`...`[` pairs must be jumped."""
        want = list(pat)[::-1]
        j = i - 1
        depth = 0
        while j >= 0 and want:
            sym = word[j].sym
            if sym == BRANCH_CLOSE:
                depth += 1
            elif sym == BRANCH_OPEN:
                if depth == 0:
                    j -= 1          # leaving our own branch: keep looking
                    continue
                depth -= 1
            elif depth == 0 and not self._skip(sym):
                if sym != want[0]:
                    return False
                want.pop(0)
            j -= 1
        return not want

    def _ctx_right(self, word, i, pat):
        """Right context: a subtree, so a pattern may descend into a
        branch.  Bracket symbols in the pattern are matched literally."""
        want = list(pat)
        j = i + 1
        while j < len(word) and want:
            sym = word[j].sym
            if want[0] in (BRANCH_OPEN, BRANCH_CLOSE):
                if sym == want[0]:
                    want.pop(0)
                elif not self._skip(sym):
                    return False
                j += 1
                continue
            if sym == BRANCH_OPEN:
                # Try inside the branch; if the pattern does not continue
                # there, skip the whole branch and try after it.
                j += 1
                continue
            if sym == BRANCH_CLOSE:
                j += 1
                continue
            if self._skip(sym):
                j += 1
                continue
            if sym != want[0]:
                return False
            want.pop(0)
            j += 1
        return not want

    # -- introspection ------------------------------------------------

    def alphabet(self):
        syms = {mod.sym for mod in self.axiom}
        for p in self.productions:
            syms.add(p.strict_sym)
            syms.update(s for s, _ in p.succ)
        return sorted(syms)

    def is_dol(self):
        """True for a deterministic, context-free, NON-PARAMETRIC system
        -- the only class whose size is predictable in closed form (see
        growth.py) and the only one eligible for the numpy fast path."""
        if any(mod.params for mod in self.axiom):
            return False
        for p in self.productions:
            if p.contextual or p.formals or p.cond is not None:
                return False
            if p.prob < 1.0:
                return False
            if any(args for _, args in p.succ):
                return False
        seen = set()
        for p in self.productions:
            if p.strict_sym in seen:
                return False        # two rules for one symbol: not D0L
            seen.add(p.strict_sym)
        return True

    def __repr__(self):
        return (f"<Grammar {len(self.productions)} productions, "
                f"axiom {word_str(self.axiom)!r}, mode={self.mode}>")


# ---------------------------------------------------------------------
# Rule parsing helpers
# ---------------------------------------------------------------------

_LABEL_RE = re.compile(r"^[A-Za-z_]\w*$")
_COMMENT_RE = re.compile(r"/\*.*?\*/", re.S)
#: the `(a|b=2|c)` group of a `#param` choice declaration
_CHOICE_RE = re.compile(r"\(([^)]*)\)")


def _lit(src, constants):
    e = compile_expr(src, (), constants)
    if e is None:
        return 0.0
    return e.ev({})


def _looks_like_label(s, names):
    """A leading `p1:` is a rule label, not a predecessor.

    The ambiguity is real -- `A : x>1 -> B` has a predecessor before the
    colon, while `p1: A -> B` has a label.  Rule: a label is a bare
    identifier that is NOT a declared module name and either contains a
    digit or is longer than one character.  That accepts `p1`, `rule2`
    and `grow`, and rejects the single-letter module names the books use.
    """
    s = s.strip()
    if not _LABEL_RE.match(s) or s in names:
        return False
    return len(s) > 1 or any(ch.isdigit() for ch in s)


def _parse_rule(src, names, constants):
    arrow = "->" if "->" in src else "→"
    lhs, rhs = src.split(arrow, 1)

    # successor : probability
    prob = 1.0
    if ":" in rhs:
        head, tail = rhs.rsplit(":", 1)
        try:
            prob = float(compile_expr(tail, (), constants).ev({}))
            rhs = head
        except (ExprError, AttributeError, TypeError):
            pass                        # the ':' belonged to the successor

    parts = lhs.split(":")
    label, cond_src = None, None
    if len(parts) >= 3:
        label, pred_src, cond_src = parts[0], parts[1], ":".join(parts[2:])
    elif len(parts) == 2:
        if _looks_like_label(parts[0], names):
            label, pred_src = parts[0], parts[1]
        else:
            pred_src, cond_src = parts[0], parts[1]
    else:
        pred_src = parts[0]

    left, strict, right = _split_context(pred_src)
    stoks = tokenize(strict, names)
    if len(stoks) != 1:
        raise GrammarError(
            f"a production needs exactly one strict predecessor, got "
            f"{len(stoks)} in {src!r}")
    sym, formals = stoks[0]
    for f in formals:
        if not _LABEL_RE.match(f.strip()):
            raise GrammarError(
                f"formal parameter {f!r} is not a name in {src!r}")
    formals = tuple(f.strip() for f in formals)

    cond = compile_expr(cond_src, formals, constants) if cond_src else None
    succ = []
    for s, args in tokenize(rhs, names):
        succ.append((s, [compile_expr(a, formals, constants) for a in args]))

    return Production(label,
                      [s for s, _ in tokenize(left, names)] if left else [],
                      sym, formals,
                      [s for s, _ in tokenize(right, names)] if right else [],
                      cond, succ, prob, src.strip())


def _split_context(pred):
    """`a < B > c` -> ('a', 'B', 'c').  The '<' and '>' that separate
    context are unambiguous here because a predecessor never contains a
    relational operator (those live in the condition)."""
    left, rest = ("", pred)
    if "<" in pred:
        left, rest = pred.split("<", 1)
    right = ""
    if ">" in rest:
        rest, right = rest.split(">", 1)
    return left.strip(), rest.strip(), right.strip()


def _expand(p, binding):
    out = []
    for sym, args in p.succ:
        if args:
            vals = []
            for a in args:
                try:
                    vals.append(a.ev(binding) if a is not None else 0.0)
                except ExprError:
                    vals.append(0.0)
            out.append(Module(sym, tuple(vals)))
        else:
            out.append(Module(sym, ()))
    return out


def parse(text, params=None):
    """Convenience wrapper: `core.parse(text)` -> Grammar.

    `params` overrides any `#param` the grammar declares.
    """
    return Grammar.parse(text, params)


# ---------------------------------------------------------------------

def _selftest():
    # --- tokeniser: the defect this module exists to fix -------------
    assert [s for s, _ in tokenize("FF")] == ["F", "F"]
    assert [s for s, _ in tokenize("Fseg", ("seg",))] == ["F", "seg"]
    assert [s for s, _ in tokenize("Apex", ("Apex",))] == ["Apex"]
    assert [s for s, _ in tokenize("Apex")] == list("Apex"), \
        "undeclared names must still split per character"
    toks = tokenize("A(1,2)B", ())
    assert toks[0][0] == "A" and toks[0][1] == ["1", "2"]

    # --- the published conformance derivation ------------------------
    # ABOP equation (1.7) / Figure 1.34, also printed as equation (2) in
    # the SIGGRAPH 2003 course notes.
    #
    # The two sources disagree about the final word: ABOP prints
    # `C B(1) A(8,7)`, the course notes `C B(1) B(4) A(1.33,0)`.  ABOP is
    # right.  At step 3 the word is `C B(2) A(4,3)`, so A has y = 3;
    # p1's guard is `y <= 3`, which HOLDS, giving A(x*2, x+y) = A(8,7).
    # Reaching the course notes' word would need p2 (`y > 3`) to fire at
    # y = 3.  Deriving from the rules is the arbiter, and it agrees with
    # ABOP at every step.
    g = Grammar.parse("""
        axiom: B(2)A(4,4)
        p1: A(x,y) : y <= 3 -> A(x*2, x+y)
        p2: A(x,y) : y >  3 -> B(x)A(x/y, 0)
        p3: B(x)   : x <  1 -> C
        p4: B(x)   : x >= 1 -> B(x-1)
    """)
    expected = ["B(2)A(4,4)",
                "B(1)B(4)A(1,0)",
                "B(0)B(3)A(2,1)",
                "CB(2)A(4,3)",
                "CB(1)A(8,7)"]
    for k, want in enumerate(expected):
        got = word_str(g.derive(k))
        assert got == want, f"step {k}: got {got!r}, want {want!r}"

    # --- arity is part of matching -----------------------------------
    g2 = Grammar.parse("""
        axiom: A(1)A(1,1)
        p1: A(x)   -> B
        p2: A(x,y) -> C
    """)
    assert word_str(g2.derive(1)) == "BC"

    # --- context sensitivity, priority and #ignore -------------------
    g3 = Grammar.parse("""
        #ignore + -
        axiom: B+A+A+A
        p1: B < A -> B
        p2: A -> A
    """)
    # the signal advances one internode per step, THROUGH the ignored +
    assert word_str(g3.derive(1)) == "B+B+A+A", word_str(g3.derive(1))
    assert word_str(g3.derive(3)) == "B+B+B+B"

    # a context-sensitive rule outranks a context-free one for the same
    # symbol even when it is listed second
    g4 = Grammar.parse("""
        axiom: XA
        p1: A -> Z
        p2: X < A -> Y
    """)
    assert word_str(g4.derive(1)) == "XY"

    # --- the mesotonic test: what the old engine provably could not do
    # Prusinkiewicz & Kari: subapical branching in a NON-parametric D0L
    # forces a basitonic form.  With a parameter carrying each branch's
    # growth potential, the middle branches end up longest.
    gm = Grammar.parse("""
        axiom: F A(0)
        p1: A(v)          -> [-F B(v)][+F B(v)] F A(v+1)
        p2: B(v) : v > 0  -> F B(v-1)
    """)
    w = gm.derive(8)
    lens, depth, cur = [], 0, 0
    for mod in w:
        if mod.sym == "[":
            depth, cur = depth + 1, 0
        elif mod.sym == "]":
            depth -= 1
            if depth == 0:
                lens.append(cur)
        elif depth and mod.sym == "F":
            cur += 1
    pairs = [max(lens[i], lens[i + 1]) for i in range(0, len(lens) - 1, 2)]
    assert len(pairs) >= 5, f"expected several branch pairs, got {pairs}"
    peak = pairs.index(max(pairs))
    assert 0 < peak < len(pairs) - 1, \
        f"branch lengths {pairs} peak at index {peak}: not mesotonic"

    # --- stochastic rules are reproducible per seed ------------------
    gs = Grammar.parse("""
        axiom: A
        p1: A -> AA : 0.5
        p2: A -> B  : 0.5
    """)
    a = word_str(gs.derive(6, seed=7))
    b = word_str(gs.derive(6, seed=7))
    c = word_str(gs.derive(6, seed=8))
    assert a == b, "same seed must give the same word"
    assert a != c, "different seeds should differ here"

    # --- sequential (Chomsky) mode stops when quiescent ---------------
    gq = Grammar.parse("""
        #mode sequential
        axiom: AA
        p1: A -> b
    """)
    assert word_str(gq.derive(1)) == "bA", "sequential rewrites one module"
    assert word_str(gq.derive(50)) == "bb", "and then goes quiescent"

    # --- the budget refuses rather than hanging ----------------------
    gb = Grammar.parse("axiom: A\np1: A -> AA")
    try:
        gb.derive(40, budget=10_000)
    except GrammarError as exc:
        assert "budget" in str(exc)
    else:
        raise AssertionError("runaway derivation must raise")

    # --- comments must not eat turtle symbols ------------------------
    # Regression: `--` is "turn right twice" and `//` is "roll right
    # twice".  Treating them as inline comments truncated the Koch axiom
    # to `F` and its successor to `F+F`, and the curve still LOOKED
    # plausible -- so this is asserted rather than eyeballed.
    gk = Grammar.parse("""
        axiom: F--F--F
        p1: F -> F+F--F+F   /* the Koch generator */
    """)
    assert word_str(gk.axiom) == "F--F--F", word_str(gk.axiom)
    assert "".join(s for s, _ in gk.productions[0].succ) == "F+F--F+F"
    gr = Grammar.parse("""
        axiom: F//F
        p1: F -> F
    """)
    assert word_str(gr.axiom) == "F//F"
    # whole-line comments still work, in both spellings
    g_c = Grammar.parse("""
        -- a comment
        // another
        axiom: F
        p1: F -> FF
    """)
    assert word_str(g_c.axiom) == "F"

    # --- classification ----------------------------------------------
    assert Grammar.parse("axiom: F\np1: F -> F+F").is_dol()
    assert not g.is_dol(), "parametric system is not D0L"
    assert not gs.is_dol(), "stochastic system is not D0L"

    # --- malformed grammars report, not crash ------------------------
    for bad in ("p1: A -> B",                       # no axiom
                "axiom: A\np1: AB -> C",            # two strict predecessors
                "axiom: A\nwhat is this"):
        try:
            Grammar.parse(bad)
        except GrammarError:
            pass
        else:
            raise AssertionError(f"{bad!r} should not parse")

    print("core: OK -- maximal-munch tokeniser, published derivation, "
          "arity+context+priority matching, mesotonic parametric case, "
          "seeded stochastic, sequential mode, budget")
