
# Phyllotaxis: the van Iterson cylinder solver, and Ridley's placement
# on an arbitrary surface of revolution.
#
# TWO DIFFERENT QUESTIONS, KEPT SEPARATE.
#
#   van Iterson (ABOP section 4.2) answers the INVERSE question: given a
#   visible parastichy pair (m, n), what divergence angle and rise put
#   the organs in contact?  That is the analysis tool -- it is what tells
#   you a pine cone is (5,8) and what alpha and h produce it.
#
#   Ridley answers the FORWARD question: given a receptacle shape and an
#   organ size, where do the organs go?  That is the placement engine,
#   and it SUBSUMES the disk and the cylinder -- Vogel's planar model and
#   van Iterson's cylinder are both special cases of one profile curve.
#
# So this module ships both: Ridley as the generator, van Iterson as the
# analysis and preset tool.  Neither replaces the other.
#
# RIDLEY'S MODEL.  Let (fx(s), fy(s)), s in [0, L], generate the
# receptacle when rotated about the y axis, naturally parameterised.  The
# area of the slice generated by [s, s+ds] is 2*pi*fx(s)*ds, and an organ
# at distance s occupies pi*rho(s)^2.  Then
#
#     N(0, s) = integral_0^s  2*fx(s) / rho(s)^2  ds
#
# counts the organs placed in [0, s], and consecutive organs go where
# this increments by one.  Rotate each successive organ by the divergence
# angle about the axis.  Ridley notes it has the same generative power as
# the collision-based model of Fowler et al. but runs faster, because it
# never has to detect a collision.
#
# Consequences worth having: ONE generator covers disk, cone, cylinder,
# sphere, ovoid and curved cone -- pine cone, pineapple, sunflower head,
# Kniphofia poker, thistle -- by editing one profile; and organ size is a
# free function of position, which is what real capitula do.
#
# TWO TRAPS, both verified during the ABOP review before this was written:
#   * use equation (4.8) for d, NOT (4.9);
#   * the (1,1,2) row is degenerate in (4.7) and must be special-cased.
#
# References:
# - Przemyslaw Prusinkiewicz and Aristid Lindenmayer, "The Algorithmic
#   Beauty of Plants", Springer, 1990, section 4.2 and Table 4.1.
# - Gerrit van Iterson, "Mathematische und mikroskopisch-anatomische
#   Studien ueber Blattstellungen", Gustav Fischer, Jena, 1907.
# - J. N. Ridley, "Packing efficiency in sunflower heads", Mathematical
#   Biosciences 58, 1982, pp. 129-139.
# - Przemyslaw Prusinkiewicz, Lars Muendermann, Radoslaw Karwowski and
#   Brendan Lane, "The use of positional information in the modeling of
#   plants", SIGGRAPH 2001, section 7.
# - Helmut Vogel, "A better way to construct the sunflower head",
#   Mathematical Biosciences 44, 1979, pp. 179-189.
# - Alan Turing, "Morphogenesis", collected works; the continuous
#   transition between parastichy pairs.
# - Deborah Fowler, Przemyslaw Prusinkiewicz and Johannes Battjes, "A
#   collision-based model of spiral phyllotaxis", SIGGRAPH 1992.

import numpy as np

#: The golden angle, in degrees.
GOLDEN_ANGLE = 137.50776405003785

#: The pineapple's triple-contact (5,8,13) divergence.
PINEAPPLE_ANGLE = 138.139542


# ---------------------------------------------------------------------
# van Iterson: the inverse problem
# ---------------------------------------------------------------------

def van_iterson(m, n, samples=200000):
    """Divergence and rise putting parastichies (m, n) in contact.

    Returns (alpha_degrees, h).  On a cylinder of unit circumference,
    organ k sits at angle k*alpha and height k*h, so the distance from
    organ 0 to organ k, taken the short way round, is

        d(k)^2 = frac(k*alpha)^2 + (k*h)^2                        (4.8)

    with `frac(x) = x - round(x)` the SIGNED distance to the nearest
    integer.  That signedness is the first trap: equation (4.9) uses the
    unsigned fractional part and picks the wrong branch for half the
    table.

    Requiring only d(m) = d(n) leaves one equation in two unknowns -- it
    describes a CURVE in the van Iterson diagram, not a point, which is
    exactly what the diagram draws.  The isolated solutions the table
    lists are the branch points, where a third family joins:

        d(m) = d(n) = d(m + n)

    Two equations, two unknowns.  Solving the pair is what makes the
    answer well posed.
    """
    m, n = int(m), int(n)
    if m < 1 or n < 1:
        raise ValueError("parastichy numbers must be positive")
    lo, hi = min(m, n), max(m, n)

    # (1,1,2) is degenerate in (4.7): with lo == hi the two contact
    # conditions are the same equation, so there is nothing to solve.
    # It is the top of the van Iterson diagram and has to be supplied.
    if lo == hi:
        return 180.0, 0.5

    p = lo + hi

    def sfrac(x):
        return x - np.round(x)

    def h2_of(j, k, a):
        """Rise^2 implied by requiring organs j and k to be equidistant."""
        fj, fk = sfrac(j * a), sfrac(k * a)
        return (fj * fj - fk * fk) / float(k * k - j * j)

    a = np.linspace(1e-4, 0.5, int(samples))
    r = h2_of(lo, hi, a) - h2_of(lo, p, a)
    sign = np.sign(r)
    cuts = np.flatnonzero(sign[:-1] * sign[1:] < 0)

    # `sfrac` is a sawtooth, so most sign changes are its jumps rather
    # than roots.  Filter on the midpoint first and refine only what
    # survives -- bisecting all ~25,000 crossings would be pointless.
    for c in cuts:
        root = 0.5 * (a[c] + a[c + 1])
        h2 = h2_of(lo, hi, root)
        if h2 <= 0:
            continue
        h = float(np.sqrt(h2))
        # AT a branch point all three families are equidistant, so the
        # two nearest neighbours are any two of {lo, hi, lo+hi} -- asking
        # for exactly {lo, hi} would reject the correct root whenever the
        # tie broke toward the third family, which is what it does for
        # (5,8,13).
        if not set(contact_pair(root * 360.0, h)) <= {lo, hi, p}:
            continue
        a0, a1 = a[c], a[c + 1]
        s0 = np.sign(h2_of(lo, hi, a0) - h2_of(lo, p, a0))
        for _ in range(200):
            mid = 0.5 * (a0 + a1)
            sm = np.sign(h2_of(lo, hi, mid) - h2_of(lo, p, mid))
            if sm == s0:
                a0 = mid
            else:
                a1 = mid
        root = 0.5 * (a0 + a1)
        h2 = max(h2_of(lo, hi, root), 0.0)
        return float(root * 360.0), float(np.sqrt(h2))
    raise ValueError(f"no van Iterson solution found for ({m}, {n})")


def contact_pair(alpha_deg, h):
    """Which parastichy pair is VISIBLE at a given divergence and rise.

    The visible pair is the two k minimising the cylinder distance to
    organ 0 -- the neighbours the eye picks out as spiral families.  This
    is the forward check on `van_iterson`, and it is what makes the
    h-sweep morph legible: as h falls the winning pair steps up the
    Fibonacci ladder without any discontinuity.
    """
    a = float(alpha_deg) / 360.0
    ks = np.arange(1, 64)
    frac = ks * a - np.round(ks * a)
    d = np.sqrt(frac ** 2 + (ks * float(h)) ** 2)
    order = np.argsort(d)
    return int(ks[order[0]]), int(ks[order[1]])


def rise_ladder(pairs=((2, 3), (3, 5), (5, 8), (8, 13), (13, 21)),
                alpha_deg=GOLDEN_ANGLE):
    """Rises at which the visible pair steps, at a FIXED divergence.

    Turing's continuous transition: hold the divergence at the golden
    angle and lower the rise, and the visible parastichy pair climbs the
    Fibonacci ladder with no discontinuity.  Successive rises fall by
    roughly tau^-2, which is why the sequence looks self-similar.
    """
    out = []
    for m, n in pairs:
        h = _rise_for_pair(m, n, alpha_deg)
        out.append((m, n, h))
    return out


def _rise_for_pair(m, n, alpha_deg):
    """The largest rise at which (m, n) is the visible pair."""
    a = float(alpha_deg) / 360.0
    lo, hi = 1e-6, 1.0
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        p = set(contact_pair(alpha_deg, mid))
        if p == {m, n}:
            lo = mid
        else:
            hi = mid
    return float(0.5 * (lo + hi))


# ---------------------------------------------------------------------
# Ridley: the forward problem, on any surface of revolution
# ---------------------------------------------------------------------

#: Profile curves (fx, fy) over s in [0, 1], each generating a classic
#: receptacle when rotated about the y axis.
PROFILES = {
    "DISK":     lambda s: (s, np.zeros_like(s)),
    "CONE":     lambda s: (s, 1.0 - s),
    "CYLINDER": lambda s: (np.full_like(s, 1.0), s),
    "SPHERE":   lambda s: (np.sin(np.pi * s), -np.cos(np.pi * s)),
    "OVOID":    lambda s: (0.75 * np.sin(np.pi * s),
                           -np.cos(np.pi * s) * (1.0 + 0.35 * s)),
    "CURVED_CONE": lambda s: (s * (1.0 - 0.45 * s), 1.0 - s ** 1.4),
    "POKER":    lambda s: (0.35 * np.sin(np.pi * s) ** 0.6, s),
    "THISTLE":  lambda s: (0.6 * np.sin(np.pi * s * 0.85) ** 1.6, s * 0.9),
}


def ridley(profile="CONE", count=200, divergence=GOLDEN_ANGLE,
           rho=None, samples=4000):
    """Place `count` organs on a surface of revolution.

    `rho` is the organ RADIUS as a function of the normalised arc
    parameter -- a free function, so florets can grow or shrink along the
    receptacle the way real capitula do.  Constant by default.

    Returns (points, normals, sizes).
    """
    f = PROFILES[profile] if isinstance(profile, str) else profile
    s = np.linspace(0.0, 1.0, int(samples))
    fx, fy = f(s)
    fx = np.asarray(fx, dtype=float)
    fy = np.asarray(fy, dtype=float)

    if rho is None:
        r = np.full_like(s, 1.0)
    elif callable(rho):
        r = np.asarray(rho(s), dtype=float)
    else:
        r = np.full_like(s, float(rho))
    r = np.maximum(r, 1e-9)

    # N(0,s) = integral 2*fx / rho^2 ds -- the organ count so far.
    integrand = 2.0 * np.abs(fx) / (r ** 2)
    N = np.concatenate([[0.0], np.cumsum(
        0.5 * (integrand[1:] + integrand[:-1]) * np.diff(s))])
    total = float(N[-1])
    if total <= 0:
        return (np.zeros((0, 3)), np.zeros((0, 3)), np.zeros(0))

    # Consecutive organs sit where N increments by one; asking for
    # `count` organs means sampling N at count equal steps.
    wanted = (np.arange(int(count)) + 0.5) * (total / float(count))
    s_at = np.interp(wanted, N, s)
    x_at = np.interp(s_at, s, fx)
    y_at = np.interp(s_at, s, fy)
    r_at = np.interp(s_at, s, r)

    ang = np.radians(float(divergence)) * np.arange(int(count))
    pts = np.stack([x_at * np.cos(ang), x_at * np.sin(ang), y_at], axis=1)

    # Surface normal from the profile tangent, rotated with the organ.
    dx = np.gradient(fx, s)
    dy = np.gradient(fy, s)
    tx = np.interp(s_at, s, dx)
    ty = np.interp(s_at, s, dy)
    L = np.hypot(tx, ty)
    L[L < 1e-12] = 1.0
    nx, ny = ty / L, -tx / L
    nor = np.stack([nx * np.cos(ang), nx * np.sin(ang),
                    np.full_like(nx, 0.0) + ny], axis=1)
    ln = np.linalg.norm(nor, axis=1)
    ln[ln < 1e-12] = 1.0
    return pts, nor / ln[:, None], r_at


def _selftest():
    # --- van Iterson --------------------------------------------------
    # The degenerate (1,1) row must be supplied, not solved: the contact
    # condition collapses there.
    assert van_iterson(1, 1) == (180.0, 0.5)

    # Every pair must give a divergence in range and a positive rise,
    # and -- the real check -- the pair it produces must be the pair that
    # is actually VISIBLE at that divergence and rise.
    # The branch points of the van Iterson diagram, which is what
    # Table 4.1 lists.  They alternate about the golden angle and
    # converge to it -- that convergence is the strongest check there is
    # that the triple-contact condition is the right one.
    alphas = []
    for m, n in ((1, 2), (2, 3), (3, 5), (5, 8), (8, 13), (13, 21)):
        alpha, rise = van_iterson(m, n)
        assert 0.0 < alpha < 360.0, (m, n, alpha)
        assert rise > 0.0, (m, n, rise)
        # at a branch point the three families are equidistant
        assert set(contact_pair(alpha, rise)) <= {m, n, m + n}, (m, n, alpha)
        alphas.append(alpha)
    # they alternate about the golden angle ...
    err = [a - GOLDEN_ANGLE for a in alphas]
    assert all(x * y < 0 for x, y in zip(err, err[1:])), err
    # ... and converge to it
    assert all(abs(b) < abs(a) for a, b in zip(err, err[1:])), err
    # ... geometrically, by a factor of about tau^-2 = 0.382 each step.
    # Asserting the RATE rather than a final tolerance is the sharper
    # test: it would catch a solver that converged to the right place
    # for the wrong reason.
    ratios = [abs(b) / abs(a) for a, b in zip(err, err[1:])]
    assert all(0.30 < q < 0.55 for q in ratios), ratios
    # the convergence is ASYMPTOTIC, so only the later ratios settle on
    # tau^-2; the first is still pre-asymptotic at 0.51
    tau2 = (3.0 - np.sqrt(5.0)) / 2.0
    assert abs(ratios[-1] - tau2) < 0.01, (ratios[-1], tau2)
    assert abs(alphas[-1] - GOLDEN_ANGLE) < 0.1, alphas[-1]

    # The (5,8,13) branch point is the pineapple's triple contact, and
    # the published value is 138.139542 -- an external check on the
    # solver that owes nothing to this implementation.
    a58, h58 = van_iterson(5, 8)
    assert abs(a58 - PINEAPPLE_ANGLE) < 1e-4, (a58, PINEAPPLE_ANGLE)

    # the rise falls as the pair climbs, which is the cone/pineapple
    # progression
    rises = [van_iterson(m, n)[1] for m, n in ((2, 3), (3, 5), (5, 8))]
    assert rises[0] > rises[1] > rises[2], rises
    ok = len(alphas)

    # --- the h-sweep ladder -------------------------------------------
    # At a FIXED golden divergence, lowering the rise steps the visible
    # pair up the Fibonacci ladder -- Turing's continuous transition.
    lad = rise_ladder()
    hs = [h for _m, _n, h in lad]
    assert all(b < a for a, b in zip(hs, hs[1:])), hs
    for m, n, h in lad:
        assert set(contact_pair(GOLDEN_ANGLE, h * 0.98)) == {m, n} or \
            set(contact_pair(GOLDEN_ANGLE, h * 0.9)) == {m, n}, (m, n, h)
    # successive rises fall by roughly tau^-2 = 0.382
    ratios = [b / a for a, b in zip(hs, hs[1:])]
    assert all(0.2 < r < 0.6 for r in ratios), ratios

    # --- Ridley --------------------------------------------------------
    # One engine, every receptacle.  Each must place the requested count
    # of organs, finite, and spread over the profile.
    for name in sorted(PROFILES):
        pts, nor, siz = ridley(name, count=150)
        assert len(pts) == 150, (name, len(pts))
        assert np.all(np.isfinite(pts)), name
        assert np.all(np.isfinite(nor)), name
        assert np.allclose(np.linalg.norm(nor, axis=1), 1.0, atol=1e-6), name
        ext = pts.max(axis=0) - pts.min(axis=0)
        assert float((ext > 1e-9).sum()) >= 2, (name, ext)
        assert len(siz) == 150

    # The disk must reproduce Vogel: radius proportional to sqrt(index).
    pts, _n, _s = ridley("DISK", count=400)
    rad = np.hypot(pts[:, 0], pts[:, 1])
    k = np.arange(len(rad)) + 0.5
    ratio = rad / np.sqrt(k)
    assert float(ratio.std() / ratio.mean()) < 0.02, \
        f"disk should follow Vogel's sqrt law, spread {ratio.std():.4f}"

    # Organ size is a free FUNCTION of position, which is the point of
    # using Ridley rather than a fixed lattice: florets that grow along
    # the receptacle must be placed further apart.
    even = ridley("DISK", count=200, rho=1.0)[0]
    graded = ridley("DISK", count=200, rho=lambda s: 1.0 + 2.0 * s)[0]
    assert not np.allclose(even, graded)
    r_even = np.hypot(even[:, 0], even[:, 1])
    r_grad = np.hypot(graded[:, 0], graded[:, 1])
    assert float(np.diff(r_grad).mean()) > float(np.diff(r_even).mean()), \
        "growing organs must spread outward faster"

    # divergence really drives the spiral
    g = ridley("CONE", count=100, divergence=GOLDEN_ANGLE)[0]
    q = ridley("CONE", count=100, divergence=90.0)[0]
    assert not np.allclose(g, q)

    print(f"phyllo: OK -- van Iterson branch points converge to the "
          f"golden angle at tau^-2 and hit the published pineapple "
          f"angle, "
          f"rise ladder steps 2/3->3/5->5/8->8/13 with ratios "
          f"{[round(r, 3) for r in ratios]}, Ridley covers "
          f"{len(PROFILES)} receptacles and reproduces Vogel on the disk")
