"""
zonotope.py -- zonotopes, zonish polyhedra and their rhombohedral
dissections (pure Python; numpy optional, bpy never).

A zonotope is the Minkowski sum of line segments,

    Z(v_1 ... v_n) = [0, v_1] + [0, v_2] + ... + [0, v_n],

whose 3-dimensional case is the zonohedron.  Every face is centrally
symmetric, and for a star in general position every face is a rhombus.

--------------------------------------------------------------------------
Faces without a convex hull
--------------------------------------------------------------------------
The naive route -- hull of all 2^n subset sums -- is what
`zonohedra_generator` did, and it caps out around thirteen vectors.  It is
also unnecessary: the faces of a zonotope can be written down directly.

For each pair (i, j) the plane normal is n = v_i x v_j.  Split the rest of
the star by the sign of n . v_l.  The two faces with normals +n and -n sit
at

    base(+) = sum of v_l over { l : n . v_l > 0 },
    base(-) = sum of v_l over { l : n . v_l < 0 },

and each face is the 2-dimensional zonotope (a zonogon) generated by every
star vector lying IN that plane -- which is just {v_i, v_j} unless the star
has three or more coplanar vectors, in which case the rhombus opens out
into a 2m-gon.  That is O(n^3) work for the whole solid and exact, so the
552-face 24-zone models and the 30-zone icosahedral stars are ordinary.

--------------------------------------------------------------------------
Dissection into parallelepipeds
--------------------------------------------------------------------------
Z_m = Z_(m-1) + [0, v_m] splits into the tiles of Z_(m-1) plus one prism
per face of Z_(m-1) whose outward normal has positive dot with v_m.  Each
such prism is the face swept along v_m -- a parallelepiped when the face is
a rhombus.  Recursing gives

    T(n) = T(n-1) + C(n-1, 2) = C(n, 3)

cells, which is Kowalewski's dissection: the rhombic dodecahedron into
C(4,3) = 4 blocks, the rhombic triacontahedron into C(6,3) = 20 (ten acute
and ten flat golden rhombohedra), the rhombic enneacontahedron into
C(10,3) = 120.

--------------------------------------------------------------------------
Zonish polyhedra
--------------------------------------------------------------------------
Hart's generalisation: a convex SEED plus a star, P + Z, which keeps the
seed's odd-sided faces instead of forcing central symmetry everywhere.
Since both bodies are convex the sum is the hull of the pairwise vertex
sums, and a zonotope has only n^2 - n + 2 vertices, so the point set stays
small enough to hull directly.

--------------------------------------------------------------------------
Translation surfaces
--------------------------------------------------------------------------
A Minkowski sum of segments is always convex, which puts most of the
parallelogram-faced surfaces out of reach.  Sweeping one polyline along
another instead gives the grid A_i + B_j, whose every quad still has
opposite edges parallel but which is free to be open, non-convex or
toroidal -- rhombic tori, ribbons, and the spiral surfaces Antiprism's
`zono -T` builds from a pair of ordered chains.

--------------------------------------------------------------------------
Zone lengths
--------------------------------------------------------------------------
Each zone carries its own length.  Stretching one widens its band of
faces, shrinking it to zero deletes the zone, and mixing lengths turns the
rhombi into general parallelograms -- the difference between an
Archimedean and a non-Archimedean truncated octahedron.

References:
- Zonohedra: E. S. Fedorov (1885).  H. S. M. Coxeter, "Regular Polytopes",
  3rd ed., Dover, 1973, ch. 2.
- Antiprism (Adrian Rossiter), the `zono` program and
  `base/zonohedron.cc`: the star-extraction methods, the zonohedrified
  seed, and the two-chain translation surface reimplemented here.
- Russell Towle, "Rhombic Spirallohedra" (2003), and the bitten-zonogon
  idea quoted in Michel Petitjean, "Spirallohedra and Space Filling. A
  Tribute to Russell Towle", Symmetry: Culture and Science 19(1) (2008),
  pp. 5-8.
- Jean E. Taylor, "Zonohedra and Generalized Zonohedra", American
  Mathematical Monthly 99(2) (1992), pp. 108-111 -- Fedorov's original
  definition asks only that opposite edges of a face be PARALLEL, which
  is wider than the centrally symmetric faces a Minkowski sum produces,
  so this engine builds a proper subclass of the zonohedra.
- Zonohedrification and zonish polyhedra: George W. Hart, "Zonohedrification",
  Mathematica Journal 7(3) (1999), 201-224; and the Virtual Polyhedra pages
  on zonohedrification and zonish polyhedra.
- Dissection of the rhombic triacontahedron into twenty golden rhombohedra:
  Gerhard Kowalewski, "Der Keplersche Koerper und andere Bauspiele",
  Koehlers, Leipzig (1938).
- The cell count C(n,3) and the sweep recursion: the standard tiling of a
  zonotope; see G. M. Ziegler, "Lectures on Polytopes", Springer (1995),
  ch. 7 (zonotopes and their tilings).
"""

import math
from itertools import combinations

EPS = 1e-9

PHI = (1 + 5 ** 0.5) / 2


# --------------------------------------------------------------------------
# small vector helpers (list-of-3 floats throughout)
# --------------------------------------------------------------------------

def _add(a, b):
    return [a[0] + b[0], a[1] + b[1], a[2] + b[2]]


def _sub(a, b):
    return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]


def _mul(a, s):
    return [a[0] * s, a[1] * s, a[2] * s]


def _dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _cross(a, b):
    return [a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0]]


def _norm(a):
    return math.sqrt(_dot(a, a))


def _unit(a):
    l = _norm(a)
    return [x / l for x in a] if l > EPS else [0.0, 0.0, 0.0]


def _det(a, b, c):
    return _dot(a, _cross(b, c))


# --------------------------------------------------------------------------
# stars
# --------------------------------------------------------------------------

def dedupe_star(vectors, tol=1e-7):
    """Collapse parallel and antiparallel vectors to one representative.

    A zone is a DIRECTION, so v and -v generate the same zone; a seed's
    vertex set is centrally symmetric more often than not (the cube's
    eight vertices give four zones, the icosahedron's twelve give six).
    Each survivor is oriented into a canonical half-space so the result is
    deterministic.
    """
    out = []
    for v in vectors:
        v = [float(c) for c in v]
        if _norm(v) < tol:
            continue
        u = _unit(v)
        # canonical orientation: first significantly nonzero coordinate
        # positive, so v and -v land on the same representative
        for c in u:
            if abs(c) > tol:
                if c < 0:
                    u = _mul(u, -1.0)
                    v = _mul(v, -1.0)
                break
        if not any(_norm(_cross(u, _unit(w))) < tol for w in out):
            out.append(v)
    return out


def vertex_star(V, tol=1e-7):
    """Hart's zonohedrification star: the seed's vertex directions.

    Vertices are used as DIRECTIONS (unit length), so the zonohedrification
    of a solid and of any scaled copy agree.
    """
    return dedupe_star([_unit(v) for v in V], tol)


def normal_star(V, F, tol=1e-7):
    """The seed's face normals as a star -- the other star Hart uses, and
    the one that reproduces a solid's dual-ish zonohedron."""
    ns = []
    for f in F:
        if len(f) < 3:
            continue
        a, b, c = V[f[0]], V[f[1]], V[f[2]]
        n = _cross(_sub(b, a), _sub(c, a))
        if _norm(n) > tol:
            ns.append(_unit(n))
    return dedupe_star(ns, tol)


def edge_star(V, F, tol=1e-7):
    """The seed's edge directions as a star."""
    es = []
    seen = set()
    for f in F:
        for k in range(len(f)):
            a, b = f[k], f[(k + 1) % len(f)]
            key = (min(a, b), max(a, b))
            if key in seen:
                continue
            seen.add(key)
            d = _sub(V[b], V[a])
            if _norm(d) > tol:
                es.append(_unit(d))
    return dedupe_star(es, tol)


def star_from(V, F, source='VERTS', centre=None, unit=True, tol=1e-7):
    """One entry point for every way Antiprism's `zono` reads a star.

    `source` matches its `-m` flag -- VERTS (`v`, centre to vertices),
    PAIRS (`a`, all vertex-to-vertex), EDGES (`i`/`e`, the face sides) --
    with FACES added for the seed's normals, which Hart uses too.
    `centre` is `-c` and only bites on VERTS, where it decides what the
    vectors are measured from; `unit` is `-u`.

    Leaving `unit` off keeps the seed's own lengths, and that changes the
    solid, not just its scale: the icosahedron's edge star gives the
    Archimedean truncated octahedron at unit length and a non-Archimedean
    one at true length.
    """
    if source == 'PAIRS':
        st = all_pairs_star(V, tol)
    elif source == 'EDGES':
        st = edge_star(V, F, tol)
    elif source == 'FACES':
        st = normal_star(V, F, tol)
    else:
        c = centre or [0.0, 0.0, 0.0]
        st = dedupe_star([_sub(v, c) for v in V], tol)
    if unit:
        st = [_unit(v) for v in st if _norm(v) > tol]
    return st


def all_pairs_star(V, tol=1e-7):
    """Every vertex-to-vertex direction as a star -- Antiprism's `-m a`.

    The widest star a seed can give: C(m, 2) segments before deduplication,
    of which a symmetric solid collapses most.  The cube's 8 vertices give
    28 pairs and only 7 zones; the icosahedron's 12 give 66 pairs and 15.
    """
    es = []
    for i in range(len(V)):
        for j in range(i + 1, len(V)):
            d = _sub(V[j], V[i])
            if _norm(d) > tol:
                es.append(d)
    return dedupe_star(es, tol)


def polar_star(n, pitch=45.0):
    """Equal-azimuth star at a common pitch -- the polar zonohedra.

    NOTE the convention: `pitch` is measured from the AXIS, so the ribs
    lean out by `pitch` from vertical.  Every published formula for polar
    zonohedra measures instead from the horizontal; `polyhedra/polar.py`
    holds that convention and the conversion between them.
    """
    p = math.radians(pitch)
    return [[math.sin(p) * math.cos(2 * math.pi * k / n),
             -math.sin(p) * math.sin(2 * math.pi * k / n),
             math.cos(p)] for k in range(n)]


# --------------------------------------------------------------------------
# zone lengths
# --------------------------------------------------------------------------

def weighted_star(star, profile='UNIFORM', spread=0.5, seed=0):
    """Rescale each zone independently.

    A zone's length is a free parameter of the zonohedron -- stretching one
    stretches its band of faces, and shrinking it to zero deletes the zone
    altogether, dropping the face count from n(n-1) to (n-1)(n-2).  Unequal
    lengths break the rhombi into general parallelograms, which is exactly
    the difference between Antiprism's `zono -m i ico` and `zono -m i -u
    ico` (a non-Archimedean and an Archimedean truncated octahedron).
    """
    n = len(star)
    if n == 0 or profile == 'UNIFORM':
        return [list(v) for v in star]
    if profile == 'RAMP':
        w = [1.0 - spread + 2.0 * spread * (k / max(1, n - 1))
             for k in range(n)]
    elif profile == 'SINE':
        w = [1.0 + spread * math.sin(2 * math.pi * k / n) for k in range(n)]
    elif profile == 'RANDOM':
        import random
        rng = random.Random(seed)
        w = [1.0 + spread * (2.0 * rng.random() - 1.0) for _ in range(n)]
    else:
        raise ValueError("unknown zone profile: %s" % profile)
    return [_mul(v, max(0.0, x)) for v, x in zip(star, w)]


# --------------------------------------------------------------------------
# zonogon: the 2-dimensional zonotope, used for every face
# --------------------------------------------------------------------------

def _plane_basis(nrm):
    """Two orthonormal vectors spanning the plane with normal `nrm`."""
    a = [1.0, 0.0, 0.0]
    if abs(_dot(a, nrm)) > 0.9:
        a = [0.0, 1.0, 0.0]
    e1 = _unit(_sub(a, _mul(nrm, _dot(a, nrm))))
    e2 = _cross(nrm, e1)
    return e1, e2


def zonogon(base, vecs, nrm):
    """Boundary of `base` + sum of [0, w] for w in `vecs`, in the plane
    with normal `nrm`.  Returns the 2m vertices, wound counter-clockwise
    about `nrm`.

    Each generator is first flipped into the half-plane of angles [0, pi),
    which moves the start corner: [0, w] = w + [0, -w].  Sorting the
    flipped generators by angle and walking them forward then backward
    traces the convex boundary -- the standard zonogon sweep.
    """
    e1, e2 = _plane_basis(nrm)
    start = list(base)
    ws = []
    for w in vecs:
        a = math.atan2(_dot(w, e2), _dot(w, e1))
        if a < -EPS or a >= math.pi - EPS:
            # outside [0, pi): flip it and shift the start corner
            start = _add(start, w)
            w = _mul(w, -1.0)
            a = math.atan2(_dot(w, e2), _dot(w, e1))
        ws.append((a, w))
    ws.sort(key=lambda t: t[0])
    pts = [list(start)]
    p = list(start)
    for _a, w in ws:                     # up one side
        p = _add(p, w)
        pts.append(list(p))
    for _a, w in ws:                     # and back down the other
        p = _sub(p, w)
        pts.append(list(p))
    pts.pop()                            # last step returns to `start`
    # wind counter-clockwise about nrm
    area = [0.0, 0.0, 0.0]
    for k in range(len(pts)):
        area = _add(area, _cross(pts[k], pts[(k + 1) % len(pts)]))
    if _dot(area, nrm) < 0:
        pts.reverse()
    return pts


def rhombic_rosette(n):
    """The rhombic rose of order n: (verts, rhombi, ring index per rhombus).

    Start with n unit vectors A_k at angles 2.pi.k/n and lay n rhombi round
    the origin, each spanned by a consecutive pair -- their acute angle is
    2.pi/n, so n of them close up exactly.  That leaves notches on the
    outside, and filling them takes a ring of n rhombi of angle 2.(2.pi/n);
    filling the next notches takes angle 3.(2.pi/n), and so on until the
    boundary comes out convex.

    Every rhombus is spanned by a pair A_k, A_{k+j}, and the ones with the
    same gap j form ring j.  A rhombus sits on the sum of the vectors
    strictly between its two spanning ones, which is what slots it into the
    notch left by the previous ring:

        ring j, place k:  base = A_{k+1} + ... + A_{k+j-1}
                          corners  base, base+A_k, base+A_k+A_{k+j},
                                   base+A_{k+j}

    The rings run j = 1 .. (n-1)//2, one short of the point where A_k and
    A_{k+j} would be antiparallel and the rhombus would collapse.  So there
    are (n-1)/2 rings for odd n and (n-2)/2 for even n, giving n(n-1)/2 and
    n(n-2)/2 rhombi -- filling a regular 2n-gon and a regular n-gon
    respectively.  At n = 5 the two ring shapes are the 36-degree and
    72-degree rhombs of the Penrose tilings.
    """
    A = [(math.cos(2 * math.pi * k / n), math.sin(2 * math.pi * k / n))
         for k in range(n)]
    verts, index = [], {}

    def vid(p):
        key = (round(p[0], 9), round(p[1], 9))
        i = index.get(key)
        if i is None:
            i = len(verts)
            index[key] = i
            verts.append((p[0], p[1]))
        return i

    rhombi, rings = [], []
    for j in range(1, (n - 1) // 2 + 1):
        for k in range(n):
            bx = sum(A[(k + t) % n][0] for t in range(1, j))
            by = sum(A[(k + t) % n][1] for t in range(1, j))
            u, w = A[k % n], A[(k + j) % n]
            quad = [(bx, by), (bx + u[0], by + u[1]),
                    (bx + u[0] + w[0], by + u[1] + w[1]),
                    (bx + w[0], by + w[1])]
            rhombi.append([vid(p) for p in quad])
            rings.append(j)
    return verts, rhombi, rings


def bitten_rosette(n, bites=0, width=1, depth=1):
    """A rhombic rose with wedges taken out of its rim.

    Towle described "bitten zonogons": a regular 2n-gon tiled with rhombi
    from which two or three regions are stripped away at the periphery,
    leaving a non-convex rhomb-tiled polygon that still tiles the plane --
    the two-dimensional shadow of his 3- and 4-armed spirallohedra.

    What is implemented here is the general peripheral bite: `bites`
    equally spaced wedges, each `width` rhombi wide at the rim and `depth`
    rings deep, tapering inward by one place per ring so the bite is a
    wedge rather than a slot.  It is NOT a claim to reproduce Towle's
    particular space-filling 2-bite and 3-bite forms, whose exact regions
    he did not publish in a source available here.

    Returns (verts, rhombi, rings) with the bitten rhombi removed.
    """
    verts, rhombi, rings = rhombic_rosette(n)
    if bites <= 0 or depth <= 0 or width <= 0:
        return verts, rhombi, rings
    outer = max(rings)
    drop = set()
    for b in range(int(bites)):
        centre = (b * n) // int(bites)
        for d in range(int(depth)):
            j = outer - d
            if j < 1:
                break
            half = max(0, (int(width) - d + 1) // 2)
            for t in range(-half, half + 1):
                drop.add((j, (centre + t) % n))
    keep = [(f, j) for f, j in zip(rhombi, rings)]
    out_f, out_r = [], []
    for k, (f, j) in enumerate(keep):
        if (j, k % n) in drop:
            continue
        out_f.append(f)
        out_r.append(j)
    return verts, out_f, out_r


# --------------------------------------------------------------------------
# translation surfaces: two chains instead of a star
# --------------------------------------------------------------------------

def translation_surface(chain_a, chain_b, loop_a=None, loop_b=None,
                        tol=1e-7):
    """The surface swept by translating one polyline along another.

    Antiprism's `zono -T`.  With prefix sums A_i and B_j the surface is the
    grid of points A_i + B_j, and the quad on (i, j) has edges A_{i+1}-A_i
    and B_{j+1}-B_j -- so every face is a parallelogram, exactly as on a
    zonohedron, but nothing forces the result to be convex or even closed.
    That is the point: this is how the family reaches rhombic tori, open
    ribbons, and the non-convex parallelogram surfaces a Minkowski sum can
    never produce.

    A chain whose vectors sum to zero closes into a loop; `loop_a` and
    `loop_b` force that either way, and default to detecting it.  Both
    looped gives a torus, neither an open patch, one of each a tube.

    Returns (V, F).
    """
    def _prep(chain, forced):
        vs = [[float(c) for c in v] for v in chain]
        if not vs:
            raise ValueError("a translation surface needs two chains")
        s = [0.0, 0.0, 0.0]
        for v in vs:
            s = _add(s, v)
        closed = _norm(s) < tol if forced is None else bool(forced)
        pre = [[0.0, 0.0, 0.0]]
        for v in vs:
            pre.append(_add(pre[-1], v))
        if closed:
            pre.pop()                       # last point is the first again
        return pre, closed

    PA, la = _prep(chain_a, loop_a)
    PB, lb = _prep(chain_b, loop_b)
    R, C = len(PA), len(PB)
    if R < 2 or C < 2:
        raise ValueError("each chain needs at least two distinct points")

    V = [_add(PA[i], PB[j]) for i in range(R) for j in range(C)]
    F = []
    for i in range(R if la else R - 1):
        i2 = (i + 1) % R
        for j in range(C if lb else C - 1):
            j2 = (j + 1) % C
            F.append([i * C + j, i * C + j2, i2 * C + j2, i2 * C + j])
    return V, F


def closed_polygon_chain(n, step=1, radius=1.0, tilt=0.0, phase=0.0):
    """Edge vectors of a regular (star) polygon, as a closed chain.

    `step` makes it a star polygon {n/step}; `tilt` lifts the polygon's
    plane so a pair of chains can cross at an angle.  The vectors sum to
    zero, so `translation_surface` closes the direction into a loop.
    """
    t = math.radians(tilt)
    pts = []
    for k in range(n):
        a = 2 * math.pi * (k * step) / n + math.radians(phase)
        x, y = radius * math.cos(a), radius * math.sin(a)
        pts.append([x, y * math.cos(t), y * math.sin(t)])
    return [_sub(pts[(k + 1) % n], pts[k]) for k in range(n)]


def helix_chain(n, radius=1.0, rise=0.2, turns=1.0, phase=0.0):
    """Edge vectors of a discrete helix, as an OPEN chain.

    Paired with a closed polygon this sweeps a spiral tube; paired with
    another helix it gives the two-chain surfaces Antiprism builds by
    feeding `zono -T` a pair of translated polygons.
    """
    pts = []
    for k in range(n + 1):
        a = 2 * math.pi * turns * k / n + math.radians(phase)
        pts.append([radius * math.cos(a), radius * math.sin(a),
                    rise * k])
    return [_sub(pts[k + 1], pts[k]) for k in range(n)]


# --------------------------------------------------------------------------
# the zonotope itself
# --------------------------------------------------------------------------

def zonotope_faces(star, tol=1e-7):
    """Every 2-face of the zonotope, as (polygon, outward normal).

    Polygons are in space, not indexed -- `zonotope()` welds them.
    """
    n = len(star)
    if n < 3:
        raise ValueError("a solid zonotope needs at least 3 star vectors")
    out = []
    for i, j in combinations(range(n), 2):
        nrm = _cross(star[i], star[j])
        if _norm(nrm) < tol:
            continue                     # parallel pair: no face
        nrm = _unit(nrm)
        coplanar = [l for l in range(n) if abs(_dot(nrm, star[l])) <= tol]
        if (i, j) != (coplanar[0], coplanar[1]):
            continue                     # this bundle is already done
        vecs = [star[l] for l in coplanar]
        for sgn in (1.0, -1.0):
            m = _mul(nrm, sgn)
            base = [0.0, 0.0, 0.0]
            for l in range(n):
                d = _dot(m, star[l])
                if d > tol:
                    base = _add(base, star[l])
            out.append((zonogon(base, vecs, m), m))
    return out


def _weld(polys, tol=1e-6):
    """Turn a list of space polygons into (V, F) with shared vertices."""
    V = []
    key = {}
    q = 1.0 / tol

    def index(p):
        k = (round(p[0] * q), round(p[1] * q), round(p[2] * q))
        if k not in key:
            key[k] = len(V)
            V.append([p[0], p[1], p[2]])
        return key[k]

    F = []
    for poly in polys:
        f = [index(p) for p in poly]
        # drop any repeated index a rounding collision might introduce
        g = [f[k] for k in range(len(f)) if f[k] != f[(k + 1) % len(f)]]
        if len(g) >= 3:
            F.append(g)
    return V, F


def zonotope_labels(star, tol=1e-7):
    """The zone pair spanning each face, in the order `zonotope` emits.

    Every face of a zonohedron lies in the plane of exactly two zones
    (more when zones are coplanar, in which case the bundle's first two
    name it), so this is the natural thing to colour a zonohedron by: it
    shows the zone structure the solid is made of.
    """
    out = []
    n = len(star)
    for i, j in combinations(range(n), 2):
        nrm = _cross(star[i], star[j])
        if _norm(nrm) < tol:
            continue
        nrm = _unit(nrm)
        coplanar = [l for l in range(n) if abs(_dot(nrm, star[l])) <= tol]
        if (i, j) != (coplanar[0], coplanar[1]):
            continue
        out.append((i, j))                 # the +n face
        out.append((i, j))                 # and its antipode
    return out


def zonotope(star, center=True, tol=1e-7):
    """The zonohedron of `star`, as (V, F)."""
    faces = zonotope_faces(star, tol)
    V, F = _weld([p for p, _n in faces])
    if center:
        c = [0.0, 0.0, 0.0]
        for v in star:
            c = _add(c, v)
        c = _mul(c, 0.5)
        V = [_sub(v, c) for v in V]
    return V, F


def zonotope_volume(star, tol=1e-7):
    """Volume by the divergence theorem over the faces -- independent of
    the sum-of-determinants identity the dissection relies on, so the two
    together are a real check."""
    total = 0.0
    for poly, nrm in zonotope_faces(star, tol):
        # fan the polygon from its first vertex
        a = poly[0]
        for k in range(1, len(poly) - 1):
            b, c = poly[k], poly[k + 1]
            tri = _cross(_sub(b, a), _sub(c, a))
            ar = _norm(tri) / 2.0
            if ar < 1e-15:
                continue
            cen = _mul(_add(_add(a, b), c), 1.0 / 3.0)
            total += _dot(cen, nrm) * ar
    return total / 3.0


def zonotope_vertices(star, tol=1e-7):
    """Just the vertex set (used for Minkowski sums)."""
    V, _F = zonotope(star, center=False, tol=tol)
    return V


# --------------------------------------------------------------------------
# dissection into parallelepipeds
# --------------------------------------------------------------------------

def _prism(poly, v):
    """Sweep a polygon along v: returns (V, F) of the resulting prism.
    A rhombus swept along a third direction is a rhombohedron."""
    m = len(poly)
    V = [list(p) for p in poly] + [_add(p, v) for p in poly]
    F = [list(range(m)), [m + k for k in reversed(range(m))]]
    for k in range(m):
        k2 = (k + 1) % m
        F.append([k, k2, m + k2, m + k])
    return V, F


def zonotope_cells(star, tol=1e-7):
    """Dissect the zonotope into C(n,3) parallelepipeds.

    Z_m = Z_(m-1) + [0, v_m] adds one prism per face of Z_(m-1) facing
    along v_m.  Returns a list of (V, F, triple) with `triple` the index
    triple that generated the block -- the label Kowalewski's colouring
    needs.
    """
    n = len(star)
    if n < 3:
        raise ValueError("a dissection needs at least 3 star vectors")
    cells = []
    # Z_2 is the flat zonogon of the first two vectors; sweeping it by the
    # third gives the single starting block.
    nrm = _unit(_cross(star[0], star[1]))
    poly = zonogon([0.0, 0.0, 0.0], [star[0], star[1]], nrm)
    if _dot(nrm, star[2]) < 0:
        poly = zonogon([0.0, 0.0, 0.0], [star[0], star[1]], _mul(nrm, -1.0))
    Vc, Fc = _prism(poly, star[2])
    cells.append((Vc, Fc, (0, 1, 2)))
    for m in range(3, n):
        v = star[m]
        for poly, fn in zonotope_faces(star[:m], tol):
            if _dot(fn, v) <= tol:
                continue
            Vc, Fc = _prism(poly, v)
            cells.append((Vc, Fc, _triple_of(poly, star, m, tol)))
    return cells


def _triple_of(poly, star, m, tol):
    """Which two zones span this face?  Recovered from the polygon's own
    edge directions, so a swept zonogon reports its real generators."""
    idx = []
    for k in range(len(poly)):
        d = _sub(poly[(k + 1) % len(poly)], poly[k])
        if _norm(d) < tol:
            continue
        for l in range(m):
            if _norm(_cross(d, star[l])) < tol * max(1.0, _norm(d)):
                if l not in idx:
                    idx.append(l)
                break
    return tuple(sorted(idx)) + (m,)


def cells_centered(star, tol=1e-7):
    """The dissection, shifted so the assembled solid is centred like
    `zonotope()` -- otherwise the blocks and the shell disagree."""
    c = [0.0, 0.0, 0.0]
    for v in star:
        c = _add(c, v)
    c = _mul(c, 0.5)
    out = []
    for V, F, t in zonotope_cells(star, tol):
        out.append(([_sub(v, c) for v in V], F, t))
    return out


# Kowalewski's colouring of the rhombic triacontahedron: each of the twenty
# blocks takes three colours from a set of five, and all ten 3-subsets of
# {0..4} appear once as an acute ("pointy") block and once as a flat one.
KOWALEWSKI_TRIPLES = list(combinations(range(5), 3))


def acute_or_flat(V, F):
    """Classify a rhombohedron as the acute ("pointy") or the flat block.

    The three edges meeting at a corner tell them apart -- acute if the
    three pairwise angles can be made acute together, flat if not -- but
    the SIGN of any one edge vector is arbitrary here, because the star
    was canonically oriented by `dedupe_star` and a zone has no preferred
    direction.  Flipping one generator flips exactly two of the three
    pairwise cosines, so their PRODUCT is invariant under every such flip
    while still separating the two shapes: +cos^3 for the acute block,
    -cos^3 for the flat one (cos = 1/sqrt(5) for the golden rhombohedra).
    """
    if len(V) != 8:
        return 'PRISM'                   # a swept 2m-gon, not a block
    e = [_sub(V[1], V[0]), _sub(V[3], V[0]), _sub(V[4], V[0])]
    if any(_norm(x) < 1e-12 for x in e):
        return 'PRISM'
    u = [_unit(x) for x in e]
    prod = (_dot(u[0], u[1]) * _dot(u[0], u[2]) * _dot(u[1], u[2]))
    return 'ACUTE' if prod > 0 else 'FLAT'


# --------------------------------------------------------------------------
# zonish polyhedra: seed + zones
# --------------------------------------------------------------------------

def minkowski_points(seedV, star, tol=1e-7):
    """Point set whose hull is (seed + zonotope).

    Both bodies are convex, so the sum's vertices are among the pairwise
    sums; a zonotope has only n^2 - n + 2 vertices, which keeps this small
    enough to hull directly instead of enumerating 2^n subset sums.
    """
    zv = zonotope_vertices(star, tol)
    return [_add(p, z) for p in seedV for z in zv]


def scaled_star(star, length):
    """Zone length as a fraction of the seed's size -- the dial that takes
    a zonish polyhedron from its seed to its zonohedron."""
    return [_mul(_unit(v), length) for v in star]


# --------------------------------------------------------------------------
# self-test
# --------------------------------------------------------------------------

def _selftest():
    def close(a, b, t=1e-6):
        return abs(a - b) <= t * max(1.0, abs(a), abs(b))

    # --- classic stars reproduce the classic zonohedra -----------------
    cube = [[1.0, 0, 0], [0, 1.0, 0], [0, 0, 1.0]]
    V, F = zonotope(cube)
    assert (len(V), len(F)) == (8, 6), (len(V), len(F))

    rd_star = dedupe_star([[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1]])
    assert len(rd_star) == 4
    V, F = zonotope(rd_star)
    assert (len(V), len(F)) == (14, 12), (len(V), len(F))

    ico = []
    for a in (-1, 1):
        for b in (-PHI, PHI):
            ico += [[0, a, b], [a, b, 0], [b, 0, a]]
    tri_star = vertex_star(ico)
    assert len(tri_star) == 6, len(tri_star)
    V, F = zonotope(tri_star)
    assert (len(V), len(F)) == (32, 30), (len(V), len(F))

    # Hart: the tetrahedron and the cube both zonohedrify to the rhombic
    # dodecahedron; the icosahedron gives the rhombic triacontahedron.
    tet = [[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1]]
    assert len(vertex_star(tet)) == 4
    cub = [[x, y, z] for x in (-1, 1) for y in (-1, 1) for z in (-1, 1)]
    assert len(vertex_star(cub)) == 4
    V, F = zonotope(vertex_star(cub))
    assert (len(V), len(F)) == (14, 12), (len(V), len(F))

    # --- a general star: n^2-n+2 vertices, n(n-1) faces ----------------
    for n in (5, 7, 9):
        st = polar_star(n, 50.0)
        V, F = zonotope(st)
        assert len(F) == n * (n - 1), (n, len(F))
        assert len(V) == n * n - n + 2, (n, len(V))

    # --- Euler ---------------------------------------------------------
    for st in (rd_star, tri_star, polar_star(8, 55.0)):
        V, F = zonotope(st)
        E = set()
        for f in F:
            for k in range(len(f)):
                a, b = f[k], f[(k + 1) % len(f)]
                E.add((min(a, b), max(a, b)))
        assert len(V) - len(E) + len(F) == 2, (len(V), len(E), len(F))

    # labels line up with the faces, one zone pair each
    for st in (rd_star, tri_star, polar_star(8, 55.0)):
        V, F = zonotope(st)
        lab = zonotope_labels(st)
        assert len(lab) == len(F), (len(lab), len(F))
        assert all(0 <= a < len(st) and 0 <= b < len(st) for a, b in lab)
        # each pair appears exactly twice -- a face and its antipode
        from collections import Counter
        assert set(Counter(lab).values()) == {2}, Counter(lab).most_common(3)

    # --- coplanar bundles open the rhombi into 2m-gons -----------------
    # three coplanar vectors plus one off-plane: the plane's face is a
    # hexagon, not a rhombus.
    flat = [[1.0, 0, 0], [0, 1.0, 0], [1.0, 1.0, 0], [0.3, -0.2, 1.0]]
    V, F = zonotope(flat)
    assert any(len(f) == 6 for f in F), sorted(len(f) for f in F)

    # --- dissection ----------------------------------------------------
    for st in (rd_star, tri_star, polar_star(7, 50.0)):
        n = len(st)
        cells = zonotope_cells(st)
        want = n * (n - 1) * (n - 2) // 6
        assert len(cells) == want, (n, len(cells), want)
        # every block's volume is |det| of its triple, and the total must
        # match the volume computed from the faces
        tot = 0.0
        for Vc, _Fc, t in cells:
            e = (_sub(Vc[1], Vc[0]), _sub(Vc[3], Vc[0]),
                 _sub(Vc[len(Vc) // 2], Vc[0]))
            tot += abs(_det(*e))
        assert close(tot, zonotope_volume(st)), (tot, zonotope_volume(st))

    # the RT dissects into ten acute and ten flat golden rhombohedra
    kinds = [acute_or_flat(Vc, Fc) for Vc, Fc, _t in zonotope_cells(tri_star)]
    assert len(kinds) == 20, len(kinds)
    assert kinds.count('ACUTE') == 10, kinds.count('ACUTE')
    assert kinds.count('FLAT') == 10, kinds.count('FLAT')
    assert len(KOWALEWSKI_TRIPLES) == 10

    # the rhombic enneacontahedron: ten dodecahedral axes, 120 blocks
    enne = dedupe_star(
        [[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1]]
        + [[0, a / PHI, PHI] for a in (1, -1)]
        + [[a / PHI, PHI, 0] for a in (1, -1)]
        + [[PHI, 0, a / PHI] for a in (1, -1)])
    assert len(enne) == 10, len(enne)
    V, F = zonotope(enne)
    assert len(F) == 90, len(F)
    assert len(zonotope_cells(enne)) == 120, len(zonotope_cells(enne))

    # --- zonish --------------------------------------------------------
    # seed + zones: the point set is small (a zonotope has n^2-n+2
    # vertices) and the sum must contain both summands' extents.
    pts = minkowski_points(cub, scaled_star(tri_star, 0.5))
    assert len(pts) == 8 * (6 * 6 - 6 + 2), len(pts)
    reach = max(_norm(p) for p in pts)
    assert reach > max(_norm(p) for p in cub), reach

    # --- star extraction -------------------------------------------------
    # `-m a`: every vertex-to-vertex direction.  The cube's 28 pairs
    # collapse to 13 zones -- 3 edge directions, 6 face diagonals and 4
    # body diagonals -- which is the widest star a cube can give.
    assert len(all_pairs_star(cub)) == 13, len(all_pairs_star(cub))
    assert len(star_from(cub, None, 'PAIRS')) == 13
    assert len(star_from(cub, None, 'VERTS')) == 4
    # keeping true lengths is not just a rescale: it changes the solid.
    # The cube's 12 edges give 3 zones either way, but the icosahedron's
    # vertex star at true length is no longer a star of unit segments.
    ico_true = star_from(ico, None, 'VERTS', unit=False)
    assert len({round(_norm(v), 6) for v in ico_true}) == 1   # ico is
    #                                       vertex-transitive, so still one
    mixed = [[1.0, 0, 0], [0, 2.0, 0], [0, 0, 3.0]]
    Vm, Fm = zonotope(mixed)
    assert close(zonotope_volume(mixed), 6.0), zonotope_volume(mixed)

    # --- zone lengths ----------------------------------------------------
    st = polar_star(6, 50.0)
    assert len(zonotope(weighted_star(st, 'UNIFORM'))[1]) == 30
    # a zone shrunk away takes its whole band of faces with it
    killed = weighted_star(st, 'UNIFORM')
    killed[0] = [0.0, 0.0, 0.0]
    live = [v for v in killed if _norm(v) > 1e-12]
    assert len(zonotope(live)[1]) == 5 * 4, len(zonotope(live)[1])
    # unequal lengths keep the faces centrally symmetric but stop them
    # being rhombi
    w = weighted_star(st, 'RAMP', 0.6)
    Vw, Fw = zonotope(w)
    lens = set()
    for f in Fw:
        for k in range(len(f)):
            lens.add(round(_norm(_sub(Vw[f[(k + 1) % len(f)]], Vw[f[k]])), 6))
    assert len(lens) > 1, lens
    for f in Fw:                                  # still parallelograms
        assert len(f) == 4
        e1 = _sub(Vw[f[1]], Vw[f[0]])
        e2 = _sub(Vw[f[2]], Vw[f[3]])
        assert _norm(_sub(e1, e2)) < 1e-9

    # --- translation surfaces --------------------------------------------
    # closed x closed is a torus: chi = 0, and every face a parallelogram
    a = closed_polygon_chain(10, 1, 1.0)
    b = closed_polygon_chain(6, 1, 0.35, tilt=90.0)
    V, F = translation_surface(a, b)
    assert len(F) == 10 * 6, len(F)
    E = set()
    for f in F:
        for k in range(4):
            E.add((min(f[k], f[(k + 1) % 4]), max(f[k], f[(k + 1) % 4])))
    assert len(V) - len(E) + len(F) == 0, (len(V), len(E), len(F))
    for f in F:
        e1 = _sub(V[f[1]], V[f[0]])
        e2 = _sub(V[f[2]], V[f[3]])
        assert _norm(_sub(e1, e2)) < 1e-9
    # open x open is a disc: chi = 1
    h = helix_chain(8, 1.0, 0.25, 1.0)
    o = [[0.0, 0.0, 0.3]] * 4
    V, F = translation_surface(h, o)
    assert len(F) == 8 * 4, len(F)
    E = set()
    for f in F:
        for k in range(4):
            E.add((min(f[k], f[(k + 1) % 4]), max(f[k], f[(k + 1) % 4])))
    assert len(V) - len(E) + len(F) == 1, (len(V), len(E), len(F))
    # one of each is a tube: chi = 0 with a boundary
    V, F = translation_surface(a, h)
    assert len(F) == 10 * 8, len(F)
    # forcing the flags overrides detection
    V, F = translation_surface(a, b, loop_a=False)
    assert len(F) == 10 * 6, len(F)          # 11 rows now, 10 face bands

    # --- rhombic rosette -----------------------------------------------
    # The counts are the published ones, but the decisive check is AREA:
    # if the rhombi covered the polygon with a gap or an overlap the total
    # would not match, and no count would notice.
    for n in range(3, 17):
        V, R, rings = rhombic_rosette(n)
        want = n * (n - 1) // 2 if n % 2 else n * (n - 2) // 2
        assert len(R) == want, (n, len(R), want)
        assert len(set(rings)) == (n - 1) // 2, (n, set(rings))
        edges = {round(math.dist(V[f[i]], V[f[(i + 1) % 4]]), 9)
                 for f in R for i in range(4)}
        assert edges == {1.0}, (n, edges)          # every rhombus is unit
        area = 0.0
        for f in R:
            p = [V[i] for i in f]
            area += abs(sum(p[i][0] * p[(i + 1) % 4][1]
                            - p[(i + 1) % 4][0] * p[i][1]
                            for i in range(4))) / 2.0
        sides = 2 * n if n % 2 else n               # 2n-gon / n-gon
        rad = max(math.hypot(*v) for v in V)
        poly = 0.5 * sides * rad * rad * math.sin(2 * math.pi / sides)
        assert abs(area - poly) < 1e-9, (n, area, poly)
    # n = 5 is the famous one: the two Penrose rhombs, 36 and 72 degrees
    V, R, rings = rhombic_rosette(5)
    acute = set()
    for f in R:
        o, a, b = V[f[0]], V[f[1]], V[f[3]]
        u = (a[0] - o[0], a[1] - o[1])
        w = (b[0] - o[0], b[1] - o[1])
        ang = math.degrees(math.acos(max(-1.0, min(1.0,
                                                   u[0] * w[0] + u[1] * w[1]))))
        acute.add(round(min(ang, 180.0 - ang), 6))
    assert acute == {36.0, 72.0}, acute
    print("rosette: orders 3..16 tile their polygon exactly (area match), "
          "unit edges throughout; order 5 gives the 36/72 Penrose rhombs")

    print("RESULT: OK")
