# Wythoff's kaleidoscope construction in four dimensions.
#
# The six regular convex 4-polytopes are the famous ones, but each sits
# inside a whole FAMILY.  Take the four mirrors of a rank-4 reflection
# group, put a point somewhere in the fundamental region, and reflect it
# around: the orbit is the vertex set of a uniform polytope, and which
# polytope you get depends only on which mirrors the point is held OFF.
# That choice is recorded by "ringing" nodes of the Coxeter diagram, and
# running over all 15 non-empty ring sets in each of the four rank-4
# groups produces the truncated, rectified, cantellated, runcinated and
# omnitruncated polychora -- the 4-dimensional analogues of the thirteen
# Archimedean solids.
#
# The groups are the linear diagrams [p, q, r]:
#
#     A4 = [3,3,3]   order    120   the 5-cell's group
#     B4 = [4,3,3]   order    384   tesseract / 16-cell
#     F4 = [3,4,3]   order   1152   the 24-cell's own group, self-dual
#     H4 = [5,3,3]   order  14400   120-cell / 600-cell
#
# Only vertices and edges are built.  That is not a shortcut but a match
# to what the generator draws -- edge frameworks, projected to 3-space --
# and it is what keeps the construction tractable: extracting the cells
# of an omnitruncated 120-cell is a large computation, while its 14400
# vertices and 28800 edges fall straight out of the orbit.
#
# The mirrors come from the Gram matrix.  Two mirrors meeting at an angle
# pi/m have normals with n_i . n_j = -cos(pi/m), so the whole
# configuration is fixed by the diagram marks; a Cholesky factor of that
# Gram matrix realises it as four actual vectors.  The generating point is
# then the solution of P . n_i = ring_i, since a ringed mirror is one the
# point stands off from and an unringed one is a mirror it lies on.
#
# References:
# - W. A. Wythoff, "A relation between the polytopes of the C600-family",
#   Koninklijke Akademie van Wetenschappen te Amsterdam, Proceedings of
#   the Section of Sciences 20 (1918), 966-970.
# - H. S. M. Coxeter, "Wythoff's construction for uniform polytopes",
#   Proc. London Math. Soc. (2) 38 (1935), 327-339.
# - H. S. M. Coxeter, "Regular Polytopes", 3rd ed., Dover (1973);
#   chapter 11 for the generalized kaleidoscope and section 11.7 for the
#   element counts N_0 = g / g' used as the check here.
# - Alicia Boole Stott, "Geometrical deduction of semiregular from
#   regular polytopes and space fillings" (1910) -- the expansion and
#   contraction operations the ringings correspond to.

import math
import itertools

try:
    import numpy as np
except ImportError:                     # the engine needs a linear solve
    np = None


# (label, marks) for the four rank-4 finite Coxeter groups
FAMILIES = {
    'A4': ("[3,3,3] -- 5-cell", (3, 3, 3)),
    'B4': ("[4,3,3] -- tesseract / 16-cell", (4, 3, 3)),
    'F4': ("[3,4,3] -- 24-cell", (3, 4, 3)),
    'H4': ("[5,3,3] -- 120-cell / 600-cell", (5, 3, 3)),
}

GROUP_ORDER = {'A4': 120, 'B4': 384, 'F4': 1152, 'H4': 14400}


def _chain_order(marks):
    """Order of the Coxeter group of a linear chain with these marks.

    A chain of k marks has k + 1 nodes.  Only the chains that occur as
    sub-diagrams of the four rank-4 groups are needed, and they are all
    short, so the classification is spelt out rather than derived.
    """
    marks = tuple(marks)
    if not marks:
        return 2                        # a single node: order 2
    if len(marks) == 1:
        return 2 * marks[0]             # I2(m) -- the dihedral group
    if len(marks) == 2:
        a, b = marks
        if (a, b) == (3, 3):
            return 24                   # A3
        if 4 in (a, b) and 3 in (a, b):
            return 48                   # B3
        if 5 in (a, b) and 3 in (a, b):
            return 120                  # H3
    raise ValueError("unhandled sub-diagram %r" % (marks,))


def parabolic_order(marks, nodes):
    """Order of the subgroup generated by the mirrors in `nodes`.

    Dropping nodes from a linear diagram leaves a disjoint union of
    shorter chains, and the subgroup is the direct product of their
    groups -- so the order is the product of the chain orders.
    """
    nodes = sorted(nodes)
    if not nodes:
        return 1
    total = 1
    run = [nodes[0]]
    for v in nodes[1:]:
        if v == run[-1] + 1:
            run.append(v)
        else:
            total *= _chain_order([marks[i] for i in run[:-1]])
            run = [v]
    total *= _chain_order([marks[i] for i in run[:-1]])
    return total


def mirrors(marks):
    """Four unit normals realising the Coxeter diagram [p, q, r].

    Mirrors meeting at pi/m have normals at n_i . n_j = -cos(pi/m); the
    diagram is linear, so non-adjacent mirrors are perpendicular and
    their entry is 0.  A Cholesky factor of that Gram matrix turns the
    inner products into actual vectors.
    """
    if np is None:
        raise RuntimeError("the 4D kaleidoscope needs NumPy")
    p, q, r = marks
    m = [[1, p, 2, 2], [p, 1, q, 2], [2, q, 1, r], [2, 2, r, 1]]
    G = np.array([[1.0 if i == j else -math.cos(math.pi / m[i][j])
                   for j in range(4)] for i in range(4)])
    return np.linalg.cholesky(G)        # rows are the normals


def wythoff_point(N, rings):
    """The generating point: off the ringed mirrors, on the others."""
    P = np.linalg.solve(N, np.array([1.0 if b else 0.0 for b in rings]))
    return P / np.linalg.norm(P)


def orbit(N, P, cap=200000):
    """Reflect the point through the mirrors until nothing new appears."""
    def key(v):
        return tuple(int(round(x * 1e7)) for x in v)
    refl = [np.eye(4) - 2.0 * np.outer(n, n) for n in N]
    seen = {key(P): P}
    frontier = [P]
    while frontier:
        nxt = []
        for v in frontier:
            for R in refl:
                w = R @ v
                k = key(w)
                if k not in seen:
                    seen[k] = w
                    nxt.append(w)
                    if len(seen) > cap:
                        raise RuntimeError("orbit too large")
        frontier = nxt
    return [tuple(float(x) for x in v) for v in seen.values()]


def edges(V):
    """Edges are the vertex pairs at the minimum distance.

    Vertex-transitivity means the minimum over the whole polytope is
    already attained at vertex 0, so one linear scan fixes the edge
    length.  The pairs are then found through a spatial hash rather than
    by comparing all pairs -- an omnitruncated 120-cell has 14400
    vertices, and 10^8 comparisons is not the way to find its edges.
    """
    n = len(V)
    A = np.asarray(V, dtype=float)
    d0 = A - A[0]
    d2 = np.einsum('ij,ij->i', d0, d0)
    d2 = d2[d2 > 1e-12]
    d2min = float(d2.min())
    cell = math.sqrt(d2min) * 1.0000001
    buckets = {}
    for i, v in enumerate(A):
        buckets.setdefault(tuple(int(math.floor(x / cell)) for x in v),
                           []).append(i)
    out = set()
    tol = d2min * 1e-6
    for c, members in buckets.items():
        near = []
        for off in itertools.product((-1, 0, 1), repeat=4):
            near.extend(buckets.get(tuple(c[k] + off[k] for k in range(4)),
                                    ()))
        for i in members:
            for j in near:
                if j <= i:
                    continue
                d = A[i] - A[j]
                if abs(float(d @ d) - d2min) < tol:
                    out.add((i, j))
    return sorted(out)


def build(family, rings):
    """(vertices, edges) of the uniform polychoron for this ringing."""
    marks = FAMILIES[family][1]
    N = mirrors(marks)
    V = orbit(N, wythoff_point(N, rings))
    return V, edges(V)


def expected_vertices(family, rings):
    """Coxeter's count N_0 = g / g', Regular Polytopes section 11.7.

    The stabilizer of the generating point is the parabolic subgroup on
    the UNRINGED nodes -- those are exactly the mirrors the point lies
    on, so they fix it -- and the orbit is the group modulo that
    stabilizer.  This is an independent prediction of the orbit size,
    derived from the diagram rather than from the geometry.
    """
    marks = FAMILIES[family][1]
    unringed = [i for i in range(4) if not rings[i]]
    return GROUP_ORDER[family] // parabolic_order(marks, unringed)


def ring_label(rings):
    return ''.join('1' if b else '0' for b in rings)


# The regular polytopes as ringings, for cross-checking the engine
# against the hand-written coordinates already in `regular.py`.
REGULAR_AS_RINGS = {
    'CELL5': ('A4', (1, 0, 0, 0)),
    # In [4,3,3] the node at the 4-branch end is the one whose ringing
    # gives the tesseract's 16 vertices; ringing the far end gives the
    # 16-cell's 8.  (384/24 and 384/48 respectively.)
    'CELL8': ('B4', (1, 0, 0, 0)),
    'CELL16': ('B4', (0, 0, 0, 1)),
    'CELL24': ('F4', (1, 0, 0, 0)),
    'CELL600': ('H4', (0, 0, 0, 1)),
    'CELL120': ('H4', (1, 0, 0, 0)),
}


# --------------------------------------------------------------------------
# The prismatic families: hyperprisms and hyperpyramids
# --------------------------------------------------------------------------
#
# These are the 4-dimensional polytopes that are NOT in the kaleidoscope's
# reach, and they are built directly from a 3-dimensional seed.
#
# A HYPERPRISM is a polyhedron translated along the fourth axis, its two
# copies joined vertex to vertex; its lateral cells are the ordinary
# prisms on the seed's faces.  The only regular one is the hypercube --
# which is the cube's hyperprism, and is a hyperprism in four different
# ways, one per pair of opposite cells.
#
# A HYPERPYRAMID takes a polyhedron and a single apex off the hyperplane,
# joining every vertex of the base to it; its lateral cells are the
# ordinary pyramids on the seed's faces.  The only regular one is the
# 5-cell, the tetrahedron's hyperpyramid.  Two octahedral hyperpyramids
# glued base to base give the 16-cell.

SEED_KINDS = ('TETRA', 'CUBE', 'OCTA', 'DODECA', 'ICOSA')


def _seed(kind):
    try:
        from ..polyhedra.seeds import seed_poly
    except ImportError:                 # flat import outside the package
        from polyhedra.seeds import seed_poly
    return seed_poly(kind, unit=True)


def hyperprism(seed='CUBE', height=1.0):
    """(vertices, edges) of the hyperprism on a Platonic seed."""
    V3, F3 = _seed(seed)
    n = len(V3)
    V = ([tuple(list(v) + [-0.5 * height]) for v in V3]
         + [tuple(list(v) + [0.5 * height]) for v in V3])
    E = set()
    for f in F3:
        for i in range(len(f)):
            a, b = f[i], f[(i + 1) % len(f)]
            E.add((min(a, b), max(a, b)))              # base copy
            E.add((min(a, b) + n, max(a, b) + n))      # top copy
    for i in range(n):
        E.add((i, i + n))                              # the lateral edges
    return V, sorted(E)


def hyperpyramid(seed='TETRA', height=1.0):
    """(vertices, edges) of the hyperpyramid on a Platonic seed."""
    V3, F3 = _seed(seed)
    n = len(V3)
    V = [tuple(list(v) + [0.0]) for v in V3] + [(0.0, 0.0, 0.0, height)]
    E = set()
    for f in F3:
        for i in range(len(f)):
            a, b = f[i], f[(i + 1) % len(f)]
            E.add((min(a, b), max(a, b)))
    for i in range(n):
        E.add((i, n))                                  # base to the apex
    return V, sorted(E)


def _selftest():
    if np is None:
        print("wythoff: skipped, no NumPy")
        return

    # Every ringing in every family: the orbit size must equal Coxeter's
    # g / g'.  That is 60 independent predictions from the diagrams,
    # checked against the geometry the mirrors actually produce.
    checked = 0
    for fam in ('A4', 'B4', 'F4', 'H4'):
        for bits in itertools.product((0, 1), repeat=4):
            if not any(bits):
                continue
            want = expected_vertices(fam, bits)
            if want > 3000:              # keep the self-test quick
                continue
            marks = FAMILIES[fam][1]
            N = mirrors(marks)
            V = orbit(N, wythoff_point(N, bits))
            assert len(V) == want, (fam, ring_label(bits), len(V), want)
            checked += 1
    print("wythoff: %d ringings match Coxeter's N_0 = g / g'" % checked)

    # The decisive gate: the kaleidoscope must reproduce the six regular
    # polytopes that are already in the module as hand-written
    # coordinates.  Vertex and edge counts, and -- since the two
    # constructions have no reason to agree on orientation or scale --
    # the normalised distance spectrum, which is orientation-free.
    from . import regular as _reg
    for kind, (fam, bits) in REGULAR_AS_RINGS.items():
        nv, ne = _reg.COUNTS[kind]
        V, E = build(fam, bits)
        assert len(V) == nv, (kind, len(V), nv)
        assert len(E) == ne, (kind, len(E), ne)
        W = _reg.polytope_vertices(kind)

        def spectrum(P):
            P = np.asarray(P, dtype=float)
            P = P / np.linalg.norm(P, axis=1).max()
            d = np.sqrt(np.maximum(0.0, np.einsum(
                'ij,ij->i', P[0] - P, P[0] - P)))
            return np.round(np.sort(d), 6)
        assert np.allclose(spectrum(V), spectrum(W), atol=1e-6), kind
    print("wythoff: all six regular polytopes reproduced from their "
          "diagrams, counts and distance spectra matching the "
          "hand-written coordinates")

    # A spot check on the big ones against their published counts.
    for fam, bits, nv, name in (
            ('H4', (0, 1, 0, 0), 1200, "rectified 120-cell"),
            ('H4', (0, 0, 1, 0), 720, "rectified 600-cell"),
            ('H4', (1, 1, 0, 0), 2400, "truncated 120-cell"),
            ('F4', (1, 1, 1, 1), 1152, "omnitruncated 24-cell")):
        V, E = build(fam, bits)
        assert len(V) == nv == expected_vertices(fam, bits), \
            (name, len(V), nv)
    print("wythoff: rectified 120-cell (1200), rectified 600-cell (720), "
          "truncated 120-cell (2400) and omnitruncated 24-cell (1152) "
          "all match their published vertex counts")

    # Prismatic families.  Counts follow from the seed: a hyperprism has
    # 2V vertices and 2E + V edges, a hyperpyramid V + 1 and E + V.  The
    # two cases worth naming are the ones that come out regular -- the
    # cube's hyperprism IS the tesseract, and the tetrahedron's
    # hyperpyramid IS the 5-cell -- so those are checked against the
    # hand-written coordinates rather than just against arithmetic.
    from . import regular as _reg
    for seed in SEED_KINDS:
        V3, F3 = _seed(seed)
        e3 = len({(min(f[i], f[(i + 1) % len(f)]),
                   max(f[i], f[(i + 1) % len(f)]))
                  for f in F3 for i in range(len(f))})
        V, E = hyperprism(seed)
        assert len(V) == 2 * len(V3) and len(E) == 2 * e3 + len(V3), \
            (seed, len(V), len(E))
        V, E = hyperpyramid(seed)
        assert len(V) == len(V3) + 1 and len(E) == e3 + len(V3), \
            (seed, len(V), len(E))
    nv, ne = _reg.COUNTS['CELL8']
    V, E = hyperprism('CUBE')
    assert (len(V), len(E)) == (nv, ne), (len(V), len(E), nv, ne)
    nv, ne = _reg.COUNTS['CELL5']
    V, E = hyperpyramid('TETRA')
    assert (len(V), len(E)) == (nv, ne), (len(V), len(E), nv, ne)
    print("wythoff: hyperprisms and hyperpyramids on all five Platonic "
          "seeds; the cube's prism reproduces the tesseract (16, 32) and "
          "the tetrahedron's pyramid the 5-cell (5, 10)")
