
# L-system Generator for Blender -- a thin front-end over `lsystem/`.
#
# Lindenmayer systems: a short axiom is rewritten by parallel
# string-substitution rules for a number of generations, then read as
# turtle commands -- draw forward, turn, pitch, roll, push/pop for
# branching -- and emitted as bevelled curves, filled blades, or a
# skeleton mesh.
#
# WHAT CHANGED, AND WHY IT MATTERS.  This module used to BE the engine,
# and it rewrote with `"".join(rules.get(c, c) for c in s)` -- a
# per-character substitution.  That made it a D0L-system: deterministic,
# context-free, non-parametric, single-character alphabet, one global
# angle, one global step, 11 of the 20 Appendix-C turtle symbols, and a
# single bevelled curve of uniform width and no colour.
#
# The limitation was not a shortage of presets.  Multi-character module
# names (`Fl`, `internode`, `seg`, `plant`) were UNREPRESENTABLE, so
# every model in chapters 3-5 of "The Algorithmic Beauty of Plants" was
# out of reach.  And there is a theorem: Prusinkiewicz and Kari showed
# that arbitrarily large mesotonic and acrotonic structures cannot be
# generated by non-parametric deterministic 0L-systems with subapical
# branching -- so the old engine could not make a realistically shaped
# tree at all, whatever angles you chose.
#
# The engine now lives in the `lsystem` subpackage (parametric,
# stochastic, context-sensitive, full turtle, growth prediction), the
# same way the Seifert surface engine lives in `seifert`.  This file
# keeps only the operator, its properties and the preset enum -- and
# keeps its `bl_idname` and the original seven preset keys, so saved
# operator presets and muscle memory both survive.
#
# References:
# - Aristid Lindenmayer, "Mathematical models for cellular interactions
#   in development", J. Theoretical Biology 18, 1968.
# - Przemyslaw Prusinkiewicz and Aristid Lindenmayer, "The Algorithmic
#   Beauty of Plants", Springer, 1990 (turtle interpretation, most of
#   these production rules, and Appendix C's symbol table).
# - Przemyslaw Prusinkiewicz, Jim Hanan, Mark Hammel and Radomir Mech,
#   "L-systems: from the Theory to Visual Models of Plants", SIGGRAPH
#   2003 course notes, chapter 2-1.
# - Grzegorz Rozenberg and Arto Salomaa, "The Mathematical Theory of
#   L Systems", Academic Press, 1980 (growth functions).
# - Gosper curve / flowsnake: Martin Gardner, "Mathematical Games",
#   Scientific American 235(6), 1976 (after William Gosper).
#
# Space-filling curve note: `space_curve_generator.py` covers Hilbert,
# Moore and Gilbert with exact index algorithms and remains the better
# route to those.  It does NOT cover Peano, which is why PEANO ships
# here as a substitution curve.

bl_info = {
    "name": "L-system Fractals",
    "author": "Math Art project",
    "version": (2, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Math Art > Fractals > L-system",
    "description": "Parametric, stochastic and context-sensitive "
                   "L-systems: curves, plants and trees",
    "category": "Add Curve",
}

try:
    from . import lsystem as ls
except ImportError:                       # headless / direct execution
    import lsystem as ls


def _preset_items():
    """Enum rows grouped as Curves / Plants / Trees."""
    items = []
    for group, keys in ls.GROUPS:
        for k in sorted(keys):
            items.append((k, f"{ls.title(k)}", f"{group}: {ls.title(k)}"))
    return items


# ==========================================================================
# Blender layer
# ==========================================================================

try:
    import bpy
    from bpy.props import (BoolProperty, EnumProperty, FloatProperty,
                           FloatVectorProperty, IntProperty, StringProperty)
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    from .lsystem import emit as ls_emit

    _PRESET_ITEMS = _preset_items()

    # ---- grammar-declared parameters ------------------------------
    #
    # A Blender operator's properties are class-level annotations fixed
    # at REGISTRATION, so a property cannot be created per grammar.  The
    # way round it is a fixed pool of generic slots whose LABEL, range
    # and step are supplied at draw time from whatever the grammar
    # declared with `#param`.  Eight numeric slots and four menus cover
    # every shipped grammar with room to spare; a grammar declaring more
    # gets the first of each kind and is told so in the panel.
    _NUM_SLOTS, _ENUM_SLOTS = 8, 4

    #: Blender requires the caller to keep a reference to the strings an
    #: EnumProperty items-callback returns; a dangling list is a known
    #: crash.  This cache is that reference.
    _ENUM_CACHE = {}

    def _all_choice_ids():
        """Every choice identifier any shipped grammar can produce.

        An items-callback is evaluated the moment a value is ASSIGNED,
        and when a script sets several operator properties at once there
        is no guarantee `kind` has been applied yet -- so the callback
        may be asked to validate a choice belonging to a grammar that is
        not selected yet, and would reject it.  Offering the union of
        every shipped grammar's choices as a fallback makes assignment
        order-independent; the menu still shows only the selected
        grammar's own options.
        """
        seen = {}
        for src in ls.PRESETS.values():
            for line in src.splitlines():
                s = line.strip()
                if not s.lower().startswith("#param") or "(" not in s:
                    continue
                grp = s[s.index("(") + 1:]
                if ")" not in grp:
                    continue
                for opt in grp[:grp.index(")")].split("|"):
                    val = opt.rsplit("=", 1)[-1].strip()
                    try:
                        seen["%.10g" % float(val)] = True
                    except ValueError:
                        pass
        for i in range(16):
            seen["%d" % i] = True
        return [(k, k, "") for k in sorted(seen, key=float)]

    _FALLBACK_ENUM = _all_choice_ids()

    def _params_of(op):
        """The `#param` records of whatever grammar is selected, or ()."""
        try:
            return op._grammar(apply_params=False).params
        except Exception:
            return ()

    def _numeric_params(op):
        return [q for q in _params_of(op) if not q.is_choice]

    def _choice_params(op):
        return [q for q in _params_of(op) if q.is_choice]

    def _enum_items_for(slot):
        def items(op, context):
            recs = _choice_params(op)
            got = ([("%.10g" % v, text, "%s: %s" % (recs[slot].label, text))
                    for text, v in recs[slot].choices]
                   if slot < len(recs) else _FALLBACK_ENUM)
            _ENUM_CACHE[slot] = got          # keep the strings alive
            return got
        return items

    def _snap_on_edit(slot):
        """Enforce the grammar's own min/max/step as the user drags.

        Blender bakes a property's range and step at registration, so a
        generic slot cannot advertise the declared ones.  Snapping the
        value on edit enforces them anyway, and -- unlike clamping later
        in `execute` -- what the panel shows is what actually gets used.
        """
        def update(op, context):
            recs = _numeric_params(op)
            if slot >= len(recs):
                return
            attr = "pnum%d" % slot
            cur = getattr(op, attr)
            snapped = recs[slot].snap(cur)
            if abs(snapped - cur) > 1e-12:
                setattr(op, attr, snapped)   # re-fires once, then settles
        return update

    def _seed_params(op):
        """Load a newly chosen grammar's declared defaults into the slots."""
        for i, q in enumerate(_numeric_params(op)[:_NUM_SLOTS]):
            setattr(op, "pnum%d" % i, q.default)
        for i, q in enumerate(_choice_params(op)[:_ENUM_SLOTS]):
            setattr(op, "penum%d" % i, "%.10g" % q.default)

    class CURVE_OT_lsystem_add(bpy.types.Operator):
        """Add an L-system: fractal curves, plants and published tree
        models, as bevelled curves or filled blades"""
        bl_idname = "curve.lsystem_add"
        bl_label = "L-system"
        bl_options = {'REGISTER', 'UNDO', 'PRESET'}

        source: EnumProperty(
            name="Source",
            items=[('PRESET', "Preset", "One of the shipped grammars"),
                   ('TEXT', "Text Block", "A grammar written in a Blender "
                            "text block -- the power user's escape hatch")],
            default='PRESET')
        kind: EnumProperty(
            name="System", items=_PRESET_ITEMS, default='KOCH',
            update=lambda self, ctx: _seed_params(self))
        use_params: BoolProperty(
            name="Grammar Parameters", default=True,
            description="Expose the free parameters the grammar declares "
                        "with #param")

        # The generic slots.  Their name here is never shown: the label,
        # the range shown beside it and a menu's entries all come from
        # the grammar at draw time.
        pnum0: FloatProperty(name="P0", update=_snap_on_edit(0))
        pnum1: FloatProperty(name="P1", update=_snap_on_edit(1))
        pnum2: FloatProperty(name="P2", update=_snap_on_edit(2))
        pnum3: FloatProperty(name="P3", update=_snap_on_edit(3))
        pnum4: FloatProperty(name="P4", update=_snap_on_edit(4))
        pnum5: FloatProperty(name="P5", update=_snap_on_edit(5))
        pnum6: FloatProperty(name="P6", update=_snap_on_edit(6))
        pnum7: FloatProperty(name="P7", update=_snap_on_edit(7))
        penum0: EnumProperty(name="C0", items=_enum_items_for(0))
        penum1: EnumProperty(name="C1", items=_enum_items_for(1))
        penum2: EnumProperty(name="C2", items=_enum_items_for(2))
        penum3: EnumProperty(name="C3", items=_enum_items_for(3))
        # An Operator cannot hold a PointerProperty to an ID datablock
        # ("this type doesn't support data-block properties"), so the
        # text block is referenced by NAME and resolved at execute time.
        text_block: StringProperty(
            name="Grammar", default="",
            description="Name of a text block holding an L-system grammar")

        iters: IntProperty(
            name="Iterations", default=-1, min=-1, max=24,
            description="Rewrite depth (-1 = the preset's own default). "
                        "Clamped when the predicted size would be "
                        "unreasonable")
        seed: IntProperty(
            name="Seed", default=0, min=0, max=10000,
            description="Random seed for stochastic productions")
        budget: IntProperty(
            name="Module Budget", default=300000, min=1000, max=5000000,
            description="Refuse to derive a word longer than this")

        output: EnumProperty(
            name="Output",
            items=[('CURVE', "Bevelled Curve", "Poly splines with a round "
                             "bevel; per-point radius carries the taper"),
                   ('MESH', "Skeleton Mesh", "Edges with width, colour and "
                            "Strahler attributes")],
            default='CURVE')
        radius: FloatProperty(
            name="Tube Radius", default=0.01, min=0.0, max=0.5,
            description="Bevel radius at the widest point (0 = bare curve)")
        resolution: IntProperty(
            name="Bevel Resolution", default=2, min=0, max=12)
        fillet: FloatProperty(
            name="Round Corners", default=0.25, min=0.0, max=0.5,
            description="Round each corner by this fraction of the "
                        "shorter adjacent segment. Blender places a "
                        "bevel profile in the plane BISECTING two "
                        "segments rather than mitring it, so a sharp "
                        "corner pinches the tube to cos(angle/2) of its "
                        "width -- half, at a 120-degree Koch turn. "
                        "Rounding spreads the turn and keeps the "
                        "cross-section even; 0 keeps corners exact")
        taper: BoolProperty(
            name="Taper", default=True,
            description="Let the '!' symbol drive per-point radius")
        tip_radius: FloatProperty(
            name="Tip Radius", default=0.15, min=0.0, max=1.0,
            description="Smallest radius as a fraction of the trunk. "
                        "Da Vinci's width law over a deep tree spans a "
                        "300:1 range, so the outer branches would "
                        "otherwise render below one pixel. Raising this "
                        "keeps the taper's order while making them "
                        "visible; 0 gives the untouched law")
        blades: BoolProperty(
            name="Filled Blades", default=True,
            description="Emit '{ . }' polygon captures as filled mesh "
                        "leaves and petals")

        angle: FloatProperty(
            name="Angle Override", default=-1.0, min=-1.0, max=180.0,
            description="Default turn angle in degrees (-1 = the "
                        "grammar's own)")
        scale: FloatProperty(name="Scale", default=1.0, min=0.01, max=100.0)
        development: EnumProperty(
            name="Development",
            items=[('AUTO', "Auto", "Draw the developmental series only "
                            "for grammars that ask for it with #develop"),
                   ('ON', "Series", "Draw every generation as a row -- "
                          "the classic depiction of a developing "
                          "filament, and the only way a one-dimensional "
                          "system reads as anything but a rod"),
                   ('OFF', "Final Only", "Draw the last generation only")],
            default='AUTO')

        show_grammar: BoolProperty(
            name="Show Grammar", default=False,
            description="Display the selected preset's grammar -- its "
                        "axiom, productions and directives -- in the "
                        "redo panel")

        use_tropism: BoolProperty(
            name="Tropism", default=False,
            description="Bend each segment toward a fixed direction, by "
                        "alpha = e |H x T| -- gravity or light")
        tropism: FloatVectorProperty(
            name="Direction", default=(0.0, 0.0, -1.0), size=3, subtype='XYZ')
        elasticity: FloatProperty(
            name="Elasticity", default=0.22, min=0.0, max=1.0,
            description="Susceptibility to bending; published values run "
                        "0.14 to 0.40")

        def _overrides(self, declared):
            """Slot values -> {param name: value}, in declared order."""
            if not self.use_params:
                return {}
            out, ni, ci = {}, 0, 0
            for q in declared:
                if q.is_choice:
                    if ci < _ENUM_SLOTS:
                        out[q.name] = float(getattr(self, "penum%d" % ci))
                    ci += 1
                else:
                    if ni < _NUM_SLOTS:
                        out[q.name] = getattr(self, "pnum%d" % ni)
                    ni += 1
            return out

        def _source_text(self):
            if self.source == 'TEXT':
                blk = bpy.data.texts.get(self.text_block)
                return None if blk is None else blk.as_string()
            return ls.PRESETS.get(self.kind)

        def _grammar(self, apply_params=True):
            """Parse the selected grammar, applying any parameter slots.

            Overrides are applied by RE-PARSING with them rather than by
            patching the parsed result: axiom arguments are folded to
            literals during parsing, so a parameter used in the axiom
            would otherwise be stuck at its declared default.
            """
            src = self._source_text()
            if src is not None and apply_params:
                declared = ls.parse(src).params
                if declared:
                    return ls.parse(src, self._overrides(declared))
            return self._grammar_raw()

        def _grammar_raw(self):
            if self.source == 'TEXT':
                blk = bpy.data.texts.get(self.text_block)
                if blk is None:
                    raise ls.GrammarError(
                        f"no text block named {self.text_block!r}"
                        if self.text_block else "no text block selected")
                return ls.parse(blk.as_string())
            return ls.preset(self.kind)

        def invoke(self, context, event):
            # Seed the slots from the grammar's own defaults before the
            # first run, so the redo panel opens on what the author
            # intended rather than on zeros.
            _seed_params(self)
            return self.execute(context)

        def execute(self, context):
            try:
                g = self._grammar()
            except ls.GrammarError as exc:
                self.report({'ERROR'}, f"Grammar: {exc}")
                return {'CANCELLED'}

            n = g.iters if self.iters < 0 else self.iters
            if n is None:
                n = 4
            if g.max_iters is not None:
                n = min(n, g.max_iters)

            # Predict before deriving: for a D0L grammar the size is
            # available in closed form, so a runaway preset is clamped
            # instead of freezing the session.
            note = ""
            safe = ls.safe_iterations(g, self.budget)
            if safe is not None and n > safe:
                note = (f"; clamped {n} -> {safe} "
                        f"({ls.classify(g)} growth)")
                n = safe

            def _draw_word(w):
                return ls.interpret(
                    w,
                    angle=(g.angle if self.angle < 0.0 else self.angle)
                    or ls.DEFAULT_ANGLE,
                    step=g.step if g.step is not None else ls.DEFAULT_STEP,
                    draw=g.draw or None,
                    tropism=tuple(self.tropism) if self.use_tropism else None,
                    elasticity=self.elasticity if self.use_tropism else 0.0)

            series = (self.development == 'ON'
                      or (self.development == 'AUTO' and g.develop))
            try:
                if series:
                    # A FILAMENT is one-dimensional, so one generation of
                    # it can only ever be a bare rod.  Draw the whole
                    # development instead -- generation 0, 1, 2 ... as
                    # rows -- which is how these systems are always shown
                    # and what makes the division pattern legible.
                    outs = []
                    for k in range(n + 1):
                        w = g.derive(k, seed=self.seed, budget=self.budget)
                        outs.append(_draw_word(w))
                    word = w
                    out = ls.stack_series(outs)
                else:
                    word = g.derive(n, seed=self.seed, budget=self.budget)
                    out = _draw_word(word)
            except ls.GrammarError as exc:
                self.report({'ERROR'}, str(exc))
                return {'CANCELLED'}
            out.bbox_fit(2.0, self.scale)

            if not out.strands and not out.polygons:
                self.report({'ERROR'}, "L-system produced no geometry")
                return {'CANCELLED'}

            label = g.title or ls.title(self.kind)
            objs = []
            if self.output == 'CURVE':
                objs.append(ls_emit.emit_curve(
                    out, f"L-system {label}", self.radius, self.resolution,
                    closed=g.closed, taper=self.taper,
                    tip=self.tip_radius, fillet=self.fillet))
            else:
                objs.append(ls_emit.emit_mesh(out, f"L-system {label}"))
            if self.blades and out.polygons:
                objs.append(ls_emit.emit_polygons(
                    out, f"L-system {label} Blades"))

            ls_emit.link(context, objs)
            for o in objs:
                o.location = context.scene.cursor.location

            self.report({'INFO'},
                        f"{label}: n={n}, {len(word):,} modules, "
                        f"{out.stats()}{note}")
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            lay.prop(self, "source")
            if self.source == 'TEXT':
                lay.prop_search(self, "text_block", bpy.data, "texts")
            else:
                lay.prop(self, "kind")
                lay.prop(self, "show_grammar")
                if self.show_grammar:
                    self._draw_grammar(lay)
            self._draw_params(lay)
            for k in ("iters", "seed", "scale", "angle", "development"):
                lay.prop(self, k)
            lay.separator()
            lay.prop(self, "output")
            if self.output == 'CURVE':
                for k in ("radius", "resolution", "fillet", "taper"):
                    lay.prop(self, k)
                if self.taper:
                    lay.prop(self, "tip_radius")
            lay.prop(self, "blades")
            lay.separator()
            lay.prop(self, "use_tropism")
            if self.use_tropism:
                lay.prop(self, "tropism")
                lay.prop(self, "elasticity")
            lay.separator()
            lay.prop(self, "budget")

        def _draw_params(self, lay):
            """Render whatever knobs the grammar declared.

            The slot is generic; its label, the range shown beside it and
            a menu's entries all come straight from the `#param` line, so
            a grammar the add-on has never seen still gets properly named
            controls.
            """
            declared = _params_of(self)
            if not declared:
                return
            lay.separator()
            lay.prop(self, "use_params")
            if not self.use_params:
                return
            box = lay.box()
            ni = ci = over = 0
            for q in declared:
                if q.is_choice:
                    if ci < _ENUM_SLOTS:
                        box.prop(self, "penum%d" % ci, text=q.label)
                    else:
                        over += 1
                    ci += 1
                else:
                    if ni < _NUM_SLOTS:
                        rng = ("" if q.lo is None
                               else "  [%g, %g]" % (q.lo, q.hi))
                        box.prop(self, "pnum%d" % ni, text=q.label + rng)
                    else:
                        over += 1
                    ni += 1
            if over:
                box.label(text="%d more parameter(s) not shown" % over,
                          icon='INFO')

        def _draw_grammar(self, lay):
            """Show the preset's own source in the redo panel.

            The grammar IS the interesting content of a preset -- an
            axiom and two or three productions -- so hiding it behind a
            dropdown label wastes the best part.  Seeing it also makes
            the Text Block route discoverable: copy what is shown, edit
            it, feed it back in.
            """
            src = ls.PRESETS.get(self.kind, "")
            box = lay.box()
            box.use_property_split = False
            col = box.column(align=True)
            col.scale_y = 0.72
            shown = 0
            for raw in src.splitlines():
                line = raw.strip()
                if not line:
                    continue
                if line.startswith("/*") or line.startswith("*"):
                    continue          # provenance notes, not grammar
                if line.startswith("#title"):
                    continue          # already the dropdown label
                col.label(text=line)
                shown += 1
                if shown >= 22:       # keep the panel a sane height
                    col.label(text="...")
                    break
            try:
                g = ls.preset(self.kind)
                n = g.iters if self.iters < 0 else self.iters
                info = ls.describe(g, n if n is not None else 4)
                box.label(text=info, icon='INFO')
            except Exception:
                pass

    def _menu_func(self, context):
        self.layout.operator("curve.lsystem_add", icon='GRAPH')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(CURVE_OT_lsystem_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_curve_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_curve_add.remove(_menu_func)
        bpy.utils.unregister_class(CURVE_OT_lsystem_add)


def _selftest():
    """The operator layer is Blender-only, so this checks the contract
    between it and the engine: every enum row must resolve to a grammar
    that derives and draws."""
    items = _preset_items()
    assert len(items) == len(ls.PRESETS), (len(items), len(ls.PRESETS))
    keys = {k for k, _n, _d in items}
    for legacy in ("KOCH", "LEVY", "DRAGON", "ARROWHEAD", "GOSPER",
                   "PLANT", "BUSH3D"):
        assert legacy in keys, f"legacy preset {legacy} missing from the enum"
    # the default the operator opens on must work
    out = ls.build("KOCH")
    assert out.strands, "default preset drew nothing"
    # and clamping must actually bite on an exponential grammar
    g = ls.preset("KOCH")
    safe = ls.safe_iterations(g, 5000)
    assert safe is not None and ls.counts(g, safe) <= 5000 < ls.counts(
        g, safe + 1)
    print(f"l_system_generator: OK -- {len(items)} enum rows resolve, "
          f"legacy 7 present, clamping bites")
