# Space-filling with saddle polyhedra.
#
# Pearce's saddle polyhedra are INTERSTITIAL DOMAINS: each one is the
# space left between the branches of a periodic net, so copies of it
# pack to fill space with no gaps.  Table 8.2 enumerates 42 such
# systems.  This module builds the packing for a single cell type, over
# an arbitrary block of unit cells.
#
# HOW THE COPIES ARE FOUND.  Not by hand-written lattice vectors -- by
# ORBIT.  A cell of the net maps to another cell of the same net under
# any isometry that carries the net to itself, so the packing is
# generated by applying the 24 cubic rotations (and, for an achiral
# cell, the improper ones too) at every net site, keeping the images
# whose vertices all land on net sites.  That reproduces the cell's
# whole orbit without needing to know the space group by name.
#
# HOW IT IS CHECKED -- and this is the part that matters.  An orbit can
# contain OVERLAPPING copies: nothing in "every vertex is a net site"
# forbids two images occupying the same region.  So the packing is
# verified by VOLUME ACCOUNTING.  The signed volume of each closed cell
# is computed by the divergence theorem, and the total is compared with
# the volume of the block being filled.  If copies overlapped, or if
# the cell simply does not tile alone, the totals disagree and the
# builder says so instead of quietly emitting a tangle.  A face census
# is reported alongside: in a true packing every interior saddle face
# is shared by exactly two cells, which is also the condition Pearce's
# CW-meets-CCW rule decorates.
#
# NOT EVERY SOLID TILES ALONE.  Pearce's 53 are all components of space
# filling systems, but many of those systems are combinations of two or
# more different cells (Table 8.2).  A solid that needs a partner will
# fail the volume check here, correctly -- that is a fact about the
# solid, not a bug, and the report says which.
#
# References:
# - Peter Pearce, "Structure in Nature is a Strategy for Design", The
#   MIT Press, 1978 (paperback 1990), ch. 8 -- saddle polyhedra as
#   interstitial domains of periodic nets, and Table 8.2's inventory of
#   42 saddle polyhedral space filling systems.

import numpy as np

try:
    from . import pearce_net as pnet
except Exception:                       # legacy single-file / CLI use
    import pearce_net as pnet


def cell_volume(verts, faces):
    """Signed volume of a closed cell, by the divergence theorem.

    Faces are skew, so each is fanned from its own centroid -- the
    same subdivision the surfacer uses, which keeps the volume
    consistent with the mesh that actually gets built."""
    P = np.asarray(verts, float)
    total = 0.0
    for cyc in faces:
        loop = P[list(cyc)]
        c = loop.mean(axis=0)
        n = len(cyc)
        for k in range(n):
            a = loop[k]
            b = loop[(k + 1) % n]
            total += float(np.dot(c, np.cross(a, b))) / 6.0
    return total


def _net_sites(kind, n):
    """The net's point set, as a set of integer eighth-coordinates."""
    if isinstance(kind, str):
        Vi, _idx, _adj = pnet.net_chunk(kind, n)
    else:
        Vi, _idx, _adj = pnet.mixed_net(tuple(kind), n=n)
    return set(Vi)


def cell_orbit(verts, faces, net, nx=1, ny=1, nz=1, chiral_only=None):
    """Every copy of this cell that fits the requested block.

    Returns a list of vertex tuples (one per copy), each a translated
    and rotated image of `verts` whose vertices all lie on net sites.
    Copies are deduplicated by their vertex set, so a symmetry of the
    cell itself does not produce a duplicate."""
    V0 = np.asarray(verts, float)
    # A cell can straddle a unit cell, so the site set must extend a
    # margin beyond the block; copies are then selected by CENTROID,
    # the standard way to tile without double-counting.  Requiring a
    # copy to fit wholly inside the block instead rejects every
    # straddling cell and yields an empty orbit.
    span = int(np.ceil(float((V0.max(axis=0) - V0.min(axis=0)).max()) / 8.0))
    margin = max(1, span)
    n = max(nx, ny, nz) + 2 * margin
    sites = _net_sites(net, n)
    lo = np.array([0.0, 0.0, 0.0])
    hi = np.array([8.0 * nx, 8.0 * ny, 8.0 * nz])
    shift = np.asarray([8 * margin] * 3, int)

    if chiral_only is None:
        chiral_only = pnet.is_chiral([tuple(v) for v in verts])
    mats = list(pnet._octahedral_rotations())
    if not chiral_only:
        mats = mats + [-np.asarray(M) for M in mats]

    seen = {}
    for M in mats:
        W = np.rint((np.asarray(M, float) @ V0.T).T).astype(int)
        for anchor in sorted(sites):
            off = np.asarray(anchor, int) - W[0]
            Q = W + off
            pts = [tuple(int(x) for x in p) for p in Q]
            if any(p not in sites for p in pts):
                continue
            c = Q.mean(axis=0) - shift
            if not np.all((c >= lo - 1e-9) & (c < hi - 1e-9)):
                continue
            key = tuple(sorted(pts))
            if key in seen:
                continue
            seen[key] = pts
    return list(seen.values())


def translation_orbit(verts, faces, net, nx=1, ny=1, nz=1):
    """Copies of the cell related by TRANSLATION only.

    The rotation-free part of the orbit.  Used as a safe fallback for
    solids that do not tile alone: translates of a single cell cannot
    intersect unless the cell exceeds its own lattice period."""
    V0 = np.asarray(verts, int)
    span = int(np.ceil(float((V0.max(axis=0) - V0.min(axis=0)).max()) / 8.0))
    margin = max(1, span)
    n = max(nx, ny, nz) + 2 * margin
    sites = _net_sites(net, n)
    shift = np.asarray([8 * margin] * 3, int)
    hi = np.array([8.0 * nx, 8.0 * ny, 8.0 * nz])

    seen = {}
    for anchor in sorted(sites):
        off = np.asarray(anchor, int) - V0[0]
        Q = V0 + off
        pts = [tuple(int(x) for x in p) for p in Q]
        if any(p not in sites for p in pts):
            continue
        c = Q.mean(axis=0) - shift
        if not np.all((c >= -1e-9) & (c < hi - 1e-9)):
            continue
        key = tuple(sorted(pts))
        if key in seen:
            continue
        seen[key] = pts
    return list(seen.values())


def _cell_triangles(pts, faces):
    """Fan-triangulate a cell's skew faces, for point-in-solid tests."""
    P = np.asarray(pts, float)
    tris = []
    for cyc in faces:
        loop = P[list(cyc)]
        c = loop.mean(axis=0)
        n = len(cyc)
        for k in range(n):
            tris.append((loop[k], loop[(k + 1) % n], c))
    return tris


def point_in_cell(p, tris, eps=1e-9):
    """Is a point inside a closed cell?  Ray casting along +x.

    The cell's faces are skew, so they are fanned from their own
    centroids first -- the same subdivision the volume uses, which
    keeps the two tests consistent with each other."""
    p = np.asarray(p, float)
    hits = 0
    d = np.array([1.0, 0.0, 0.0])
    for a, b, c in tris:
        n = np.cross(b - a, c - a)
        den = float(n @ d)
        if abs(den) < eps:
            continue
        t = float(n @ (a - p)) / den
        if t <= eps:
            continue
        x = p + t * d
        v0, v1, v2 = b - a, c - a, x - a
        d00 = float(v0 @ v0)
        d01 = float(v0 @ v1)
        d11 = float(v1 @ v1)
        d20 = float(v2 @ v0)
        d21 = float(v2 @ v1)
        den2 = d00 * d11 - d01 * d01
        if abs(den2) < 1e-18:
            continue
        u = (d11 * d20 - d01 * d21) / den2
        w = (d00 * d21 - d01 * d20) / den2
        if u > eps and w > eps and u + w < 1.0 - eps:
            hits += 1
    return hits % 2 == 1


def _face_keys(pts, faces):
    return [tuple(sorted(tuple(pts[i]) for i in cyc)) for cyc in faces]


def _trim_overlap(copies, faces, cap):
    """Largest subset using no face more than twice, up to `cap` cells.

    Deterministic: the orderings are drawn from a fixed seed sequence,
    so the same block always yields the same packing.  Subsets that
    reach the cap and share the most faces win, because a packing whose
    cells meet face to face is the one Pearce describes."""
    keys = [_face_keys(p, faces) for p in copies]
    best = None
    best_key = None
    for t in range(400):
        order = list(range(len(copies)))
        _shuffle(order, t)
        used = {}
        sel = []
        for i in order:
            if len(sel) >= cap:
                break
            if any(used.get(k, 0) >= 2 for k in keys[i]):
                continue
            for k in keys[i]:
                used[k] = used.get(k, 0) + 1
            sel.append(i)
        shared = sum(1 for v in used.values() if v == 2)
        key = (len(sel), shared)
        if best is None or key > best_key:
            best, best_key = sel, key
        if len(sel) == cap and shared:
            break
    return [copies[i] for i in sorted(best)] if best else []


def _shuffle(seq, seed):
    """A small deterministic shuffle (no dependence on `random`)."""
    x = seed * 2654435761 + 1
    for i in range(len(seq) - 1, 0, -1):
        x = (x * 1103515245 + 12345) & 0x7FFFFFFF
        j = x % (i + 1)
        seq[i], seq[j] = seq[j], seq[i]


def disjoint_packing(copies, faces):
    """Grow a packing from one cell by MATCHING FACES.

    The full cubic orbit is not a packing: it contains placements that
    are individually valid -- every vertex on a net site -- yet occupy
    the same region in different orientations.  Selecting a consistent
    subset by overlap-testing centroids does not work for these solids:
    a saddle cell is strongly non-convex and its neighbours interlock,
    so a neighbour's centroid genuinely lies inside it, and rejecting
    on that basis throws away cells that do tile (it halved the
    decatrihedron's correct 8-cell packing).

    What is reliable is Pearce's own condition: cells of a space
    filling meet FACE TO FACE, each interior saddle face shared by
    exactly two cells.  So the packing is grown from a seed, adding
    only cells that match an already-exposed face exactly, vertex for
    vertex -- which is the same rule the triamond space-filler used,
    generalised off that one net."""
    if not copies:
        return []
    keys = [_face_keys(pts, faces) for pts in copies]
    by_face = {}
    for i, ks in enumerate(keys):
        for k in ks:
            by_face.setdefault(k, []).append(i)

    best = []
    for seed in range(len(copies)):
        taken = {seed}
        used = {}
        for k in keys[seed]:
            used[k] = 1
        frontier = [seed]
        while frontier:
            i = frontier.pop()
            for k in keys[i]:
                for j in by_face.get(k, ()):
                    if j in taken:
                        continue
                    # a candidate may only close open faces, never
                    # re-use one already shared by two cells
                    if any(used.get(kk, 0) >= 2 for kk in keys[j]):
                        continue
                    taken.add(j)
                    for kk in keys[j]:
                        used[kk] = used.get(kk, 0) + 1
                    frontier.append(j)
        if len(taken) > len(best):
            best = sorted(taken)
        if len(best) == len(copies):
            break
    return [copies[i] for i in best]


def face_census(copies, faces):
    """How many cells each saddle face belongs to.

    Returns (shared, boundary): faces used by two cells, and faces used
    by one.  In a true packing there is nothing else."""
    count = {}
    for pts in copies:
        for cyc in faces:
            key = tuple(sorted(tuple(pts[i]) for i in cyc))
            count[key] = count.get(key, 0) + 1
    shared = sum(1 for v in count.values() if v == 2)
    boundary = sum(1 for v in count.values() if v == 1)
    over = sum(1 for v in count.values() if v > 2)
    return shared, boundary, over


def pack(verts, faces, net, nx=1, ny=1, nz=1, tol=0.06):
    """Build the packing and CHECK it fills the block.

    Returns (copies, report).  `report['fills']` is True only if the
    cells' total volume accounts for the block's volume, which is what
    catches overlapping orbit images and cells that need a partner."""
    orbit = cell_orbit(verts, faces, net, nx, ny, nz)
    vol = abs(cell_volume(verts, faces))
    block = float(8 * nx) * float(8 * ny) * float(8 * nz)

    def score(cs):
        r = (vol * len(cs) / block) if block > 0 else 0.0
        sh, bd, ov = face_census(cs, faces)
        return r, sh, bd, ov

    # Choose between the whole orbit and a face-to-face connected
    # subset of it.
    #
    # A RATIO ABOVE 1 IS PROOF OF OVERLAP: the cells cannot occupy more
    # volume than the block they sit in unless they intersect each
    # other.  So it disqualifies a candidate outright -- it is not
    # merely a worse fit.  An earlier revision ranked candidates by
    # |ratio - 1| alone and therefore preferred a 1.333 orbit over a
    # 0.167 subset, emitting visibly intersecting cells for the
    # wurtzite trihedron.  Under-filling is honest and looks like what
    # it is; over-filling is a tangle.
    # THE ORBIT IS THE PACKING.  It is what the net's own symmetry
    # produces, and it is what these solids are built from; the volume
    # ratio is reported but does NOT filter it.
    #
    # An earlier revision used the ratio as a hard gate, on the
    # reasoning that cells cannot fill more than the block they sit in
    # without intersecting.  That reasoning is only valid when the cell
    # is commensurate with the CUBIC block being measured against, and
    # the wurtzite trihedron is not: its bounding box is 1728 cubic
    # eighths, one and a half cubic cells, because its natural net is
    # hexagonal.  Measuring it against 512 gave 1.333 and the gate threw
    # away a packing that was in fact fine.  (The volume itself is
    # sound -- the divergence-theorem figure agrees with a Monte-Carlo
    # measurement to within 1% for every solid -- it is the denominator
    # that does not apply.)
    #
    # So: keep the orbit, report the numbers, and only fall back to a
    # face-connected subset when the orbit is empty.
    copies = orbit
    if orbit and score(orbit)[3] > 0:
        # A face belonging to THREE cells is proof of overlap that does
        # not depend on any volume denominator, so it is safe to act on
        # even for a cell whose net is not cubic.  It fires for exactly
        # one solid, the fcc orthorhombic tetrahedron, whose orbit
        # double-covers the block (24 cells at twice the volume).
        #
        # Trim to a subset that uses no face more than twice, capped at
        # the number of cells the block can actually hold.  The cap is
        # what makes it a packing rather than merely a legal face
        # census: without it the search happily returns 13 cells, which
        # is 8% more volume than the block has.
        cap = int(round(block / vol)) if vol > 1e-9 else len(orbit)
        copies = _trim_overlap(orbit, faces, cap)
    if not copies:
        copies = disjoint_packing(orbit, faces) or \
            translation_orbit(verts, faces, net, nx, ny, nz)
    orbit_ratio = score(orbit)[0] if orbit else 0.0
    ratio, shared, boundary, over = score(copies) if copies else (0.0, 0, 0, 0)
    total = vol * len(copies)
    ratio, shared, boundary, over = score(copies) if copies else (0.0, 0, 0, 0)
    total = vol * len(copies)
    report = dict(copies=len(copies), orbit=len(orbit),
                  orbit_ratio=orbit_ratio,
                  overlapping_orbit=orbit_ratio > 1.0 + tol,
                  self_intersecting=over > 0,
                  trimmed=len(copies) < len(orbit),
                  cell_volume=vol, block_volume=block,
                  filled=total, ratio=ratio,
                  fills=abs(ratio - 1.0) <= tol,
                  shared_faces=shared, boundary_faces=boundary,
                  overused_faces=over)
    return copies, report


def _selftest():
    ok = True

    def chk(name, cond, extra=""):
        nonlocal ok
        ok = ok and bool(cond)
        print("  %-58s %s %s" % (name, "OK" if cond else "BAD", extra))

    try:
        from . import pearce_data as pdata
    except Exception:
        import pearce_data as pdata

    print("pearce_tiling: packing saddle polyhedra")

    # volume of a known cell, against a direct decomposition
    cell = pnet.find_cell('BCC', 4, 4, n=2)
    chk("bcc tetrahedron found", cell is not None)
    if cell:
        V, F = cell
        vol = abs(cell_volume(V, F))
        chk("  volume is positive and finite",
            vol > 0 and np.isfinite(vol), "%.3f" % vol)
        # the same cell, translated, must have the same volume
        V2 = tuple(tuple(c + d for c, d in zip(p, (8, 0, 0))) for p in V)
        chk("  volume is translation invariant",
            abs(abs(cell_volume(V2, F)) - vol) < 1e-9)

    for s in pdata.SOLIDS:
        tag = "#%d %s" % (s['number'], s['name'])
        V, F = s['verts'], s['faces']
        vol = abs(cell_volume(V, F))
        chk("%s: closed cell has volume" % tag, vol > 1e-9, "%.2f" % vol)
        try:
            copies, rep = pack(V, F, s['net'], 1, 1, 1)
        except Exception as exc:
            chk("%s: packs" % tag, False, str(exc))
            continue
        chk("%s: orbit is non-empty" % tag, rep['copies'] >= 1,
            "%d copies, ratio %.3f" % (rep['copies'], rep['ratio']))
        # Overlap is REPORTED, not forbidden.  The orbit is what the
        # net's symmetry gives and it is what gets built; for a couple
        # of solids it self-intersects, and the honest move is to say
        # so rather than substitute something that is not the packing.
        chk("%s: overlap is reported truthfully" % tag,
            rep['self_intersecting'] == (rep['overused_faces'] > 0),
            "overused=%d reported=%s"
            % (rep['overused_faces'], rep['self_intersecting']))
        # The ratio is REPORTED, not gated: it only means "fraction of
        # a cubic block" and a cell whose net is not cubic can exceed
        # 1 without intersecting anything.  What is gated is that the
        # orbit is non-empty and no face is used more than twice.
        # The orbit IS the packing unless it provably double-covered:
        # a trim only happens when some face belonged to three cells,
        # and what it produces must itself be clean.
        if rep['trimmed']:
            chk("%s: trimmed only a double cover" % tag,
                rep['overused_faces'] == 0 and rep['ratio'] <= 1.0 + 1e-6,
                "%d of %d, ratio %.3f"
                % (rep['copies'], rep['orbit'], rep['ratio']))
        else:
            chk("%s: orbit is the packing" % tag,
                rep['copies'] == rep['orbit'] or rep['orbit'] == 0,
                "%d of %d" % (rep['copies'], rep['orbit']))
        print("      %-30s tiles=%s  copies=%d ratio=%.3f "
              "shared=%d boundary=%d"
              % ("", rep['fills'], rep['copies'], rep['ratio'],
                 rep['shared_faces'], rep['boundary_faces']))

    print("RESULT:", "OK" if ok else "BAD")
    if not ok:
        raise AssertionError("pearce_tiling self-test failed")
