# Spidron mathematics -- shared kernel for the spidron generators.
#
# Pure Python + numpy, no `bpy`.  Three generators sit on top of this
# module: `spidron_rosette_generator` (planar tilings),
# `spidron_nest_generator` (the folded relief) and
# `spidron_ball_generator` (spidronised polyhedra).
#
# THE FIGURE.  A spidron is a plane figure built entirely from an
# alternating, ever-shrinking sequence of equilateral and 120-degree
# isosceles triangles that spirals to a point of convergence.  Six of
# them -- as semi-spidrons, or "arms" -- fill a regular hexagon (a
# "spidron nest"), and since the hexagon tiles the plane so does the
# spidron system.  Daniel Erdely devised it in 1979 as homework for
# Erno Rubik's design class.
#
# THE RING CONSTRUCTION.  The implementation here uses the similarity
# formulation rather than the turtle-graphics recursion of the
# Gangopadhyay papers, because it is exact and self-checking.  Take a
# regular m-gon of circumradius R and connect alternate vertices; the
# inner m-gon that appears has
#
#       R'/R = cos(ag)/cos(ag/2),   rotated by ag/2,   ag = 2*pi/m
#
# and the annulus between the two m-gons triangulates into 2m triangles:
# for each k, (P_k, P_k+1, Q_k) and (Q_k, P_k+1, Q_k+1).  At m = 6 those
# are exactly the 120-degree isosceles and the equilateral triangle of
# the classical definition, and the ratio is cos60/cos30 = 1/sqrt(3) --
# the constant Nylander hard-codes and Hujter derives as the scale of
# his kite similarity.  Iterating the similarity gives the whole nest.
#
# THE FOLD.  The nest folds into three dimensions WITHOUT DISTORTING ANY
# TRIANGLE -- a one-parameter rigid motion, and the reason the figure is
# interesting.  Ring k carries a state triple (d, alpha, beta): edge
# length, azimuth, and the inclination of its outer edges to the base
# plane.  Szilassi's recursion advances it:
#
#       d_k+1 = d_k / sqrt(3),  alpha_k+1 = alpha_k + a(beta_k),
#       beta_k+1 = b(beta_k)
#
# where b is the "Spidron Formula".  Three independent derivations of b
# exist (Szilassi 2004, Erdely-Kiss 1998-2018, Hujter 2018) and this
# module implements all of them, cross-validating them against each
# other in `_selftest` -- three independent derivations agreeing is the
# strongest correctness evidence available for this construction.
#
# DOMAIN.  The radicand -1 + 4c - 3c^2 factors as -(3c - 1)(c - 1), so
# the formulas are real exactly for cos(beta) in [1/3, 1], i.e. up to
# arccos(1/3) ~ 70.5288 deg.  The PHYSICAL bound is tighter: at 60 deg
# both triangles of a base figure stand perpendicular to the base plane,
# and beyond it the surface passes through itself.  Generators clamp at
# 60 by default.
#
# References:
# - Daniel Erdely, "Some Surprising New Properties of the Spidrons",
#   Bridges 2005 Conference Proceedings, pp. 179-186 -- the inventor's
#   own account of the figure and its folding.
# - Lajos Szilassi, "The right for doubting - and the necessity of
#   doubt: Thoughts concerning the analysis of Erdely's Spidron
#   System", Proceedings of the "Sprout-Selecting" Conference (ed.
#   Csaba Sarvari), Pecs, Hungary, 2004, pp. 78-96 -- the first
#   rigorous analysis; the closed forms a(f) and b(f) and the ring-by-
#   ring build recursion implemented here, the 60-degree physical
#   bound, and the proof that the fold decays to the plane.
# - Gergo Kiss, "A Way to Derive the Spidron Formulas", G4G13 Exchange
#   Book vol. 1, Gathering 4 Gardner, 2018, pp. 185-192 -- the fold
#   angle phi = arccos(2 - 1/cos alpha), the arcsin form of the Spidron
#   Formula, and the ring twist gamma.
# - Mihaly Hujter, "A csillaghatszog spidronszeru felgyurodese mogotti
#   matematika", Haladvany Kiadvany, 16 June 2018 -- an independent
#   proof via a planar auxiliary lemma, and the arccos form.
# - Walt van Ballegooijen, Paul Gailiunas & Daniel Erdely,
#   "Spidronised Space-fillers", Bridges 2009 Conference Proceedings,
#   pp. 271-278 -- spidronisation generalised to an arbitrary (possibly
#   skew) polygon, and the rule that chirality must alternate across a
#   shared face in any aggregation.
# - Rinki Imada, Thomas C. Hull, Jason S. Ku & Tomohiro Tachi,
#   "Nonlinear Kinematics of Recursive Origami Inspired by the
#   Spidron", Origami8 (Lecture Notes in Mechanical Engineering,
#   Springer); arXiv:2403.09278 -- the two-parameter square-boundary
#   generalisation and its pro-/anti-rotation folding modes.
# - T. Gangopadhyay, "On an Alternate Construction Method for
#   Generating Spidrons and New Tiling Patterns Generated by them",
#   International Journal of Computer Applications 160(3), 2017,
#   pp. 25-29 -- the m-part arm family and the ladder/creeper variants.

from math import (cos, sin, tan, atan2, acos, asin, sqrt, pi, radians,
                  degrees, hypot)

import numpy as np

SQRT3 = sqrt(3.0)

# Analytic domain of the Spidron Formula: cos(beta) >= 1/3.
BETA_MAX = acos(1.0 / 3.0)                 # ~ 70.5288 deg
# Physical bound (Szilassi): beyond this the folded surface self-crosses.
BETA_PHYSICAL = pi / 3.0                   # 60 deg
# The fold map's own ceiling: b(beta) <= arcsin(1/sqrt(3)).
BETA_IMAGE_MAX = asin(1.0 / SQRT3)         # ~ 35.2644 deg


def _clamp(x, lo=-1.0, hi=1.0):
    return lo if x < lo else (hi if x > hi else x)


# --------------------------------------------------------------------
# 1.  Planar construction -- rings, arms and rosettes
# --------------------------------------------------------------------

ARM_KINDS = ('SPIDRON', 'LADDER', 'CREEPER')


def arm_ratio(m):
    """Per-ring similarity ratio of an m-part arm: cos(ag)/cos(ag/2).

    Positive only for ag < 90 deg, i.e. m >= 5; m = 6 gives 1/sqrt(3).
    """
    ag = 2.0 * pi / m
    return cos(ag) / cos(0.5 * ag)


def arm_turn(m):
    """Per-ring rotation of the similarity: ag/2."""
    return pi / m


def ring_polygon(m, R, phi):
    """The m vertices of a regular m-gon, circumradius R, phase phi."""
    return [(R * cos(phi + 2.0 * pi * k / m),
             R * sin(phi + 2.0 * pi * k / m)) for k in range(m)]


def ring_triangles(P, Q):
    """Triangulate the annulus between two m-gons P (outer) and Q
    (inner, already scaled and rotated).  Returns a list of
    (triangle, kind) with kind 0 = the wide isosceles triangle sitting
    on an outer edge, kind 1 = the narrow one closing onto the inner
    ring.  At m = 6 those are the 120-degree isosceles and the
    equilateral triangle of the classical spidron."""
    m = len(P)
    out = []
    for k in range(m):
        k1 = (k + 1) % m
        out.append(((P[k], P[k1], Q[k]), 0))
        out.append(((Q[k], P[k1], Q[k1]), 1))
    return out


def planar_rings(m, rings, R=1.0, phi=0.0):
    """The nested-m-gon sequence: [(P_i, Q_i)] for i in range(rings),
    where Q_i is P_(i+1)."""
    r, dphi = arm_ratio(m), arm_turn(m)
    out, Rk, pk = [], float(R), float(phi)
    for _ in range(rings):
        P = ring_polygon(m, Rk, pk)
        Rk2, pk2 = Rk * r, pk + dphi
        Q = ring_polygon(m, Rk2, pk2)
        out.append((P, Q))
        Rk, pk = Rk2, pk2
    return out


def arm_polys(m, rings, arm='SPIDRON', index=0, R=1.0, phi=0.0,
              chirality=1):
    """Triangles of ONE arm of an m-part spidron figure.

    `arm` selects the member of the Gangopadhyay family.  All three are
    the same ring recursion; they differ only in how fast the arm's
    index advances from ring to ring, which is what the papers state as
    a difference of scale exponent and inter-iteration turn:

      SPIDRON -- the index is fixed, so the arm is one limb spiralling
                 straight in.  Scale per index step: cos(ag)/cos(ag/2).
      CREEPER -- the index advances by one every ring, so the limb
                 winds round the figure as it shrinks.
      LADDER  -- the index advances by one every SECOND ring, so an
                 index step spans two rings and four triangles, and the
                 scale per index step is (cos(ag)/cos(ag/2))^2 -- the
                 squared step the ladder papers give.

    Returns [(triangle, kind)].
    """
    if chirality < 0:
        phi = -phi
    out = []
    for i, (P, Q) in enumerate(planar_rings(m, rings, R, phi)):
        if arm == 'CREEPER':
            k = (index + i) % m
        elif arm == 'LADDER':
            k = (index + i // 2) % m
        else:
            k = index % m
        k1 = (k + 1) % m
        out.append(((P[k], P[k1], Q[k]), 0))
        out.append(((Q[k], P[k1], Q[k1]), 1))
    if chirality < 0:
        out = [(tuple((x, -y) for (x, y) in t), kd) for t, kd in out]
    return out


def rosette_ngon(m, n, R=1.0):
    """The regular n-gon a rosette's arms are carried round.

    Its SIDE equals the base edge of an m-part arm of circumradius R
    (2R sin(pi/m)), so the arm drops onto each edge at its natural
    size -- this is what makes Corners and Arm Parts independent: the
    arm keeps its own m-part geometry whatever polygon it is wound
    round.  Returns the n vertices, counterclockwise."""
    L = 2.0 * R * sin(pi / m)
    Rn = L / (2.0 * sin(pi / n))
    return ring_polygon(n, Rn, pi / n - pi / 2.0)


def rosette_polys(m, n, rings, arm='SPIDRON', winding='OUT', R=1.0):
    """A rosette: `n` copies of an m-part arm carried round a regular
    n-gon, one arm per edge, spiralling on the OUTSIDE of the polygon
    -- the "polygonal designs inscribing a regular n-gon" of the
    Gangopadhyay papers.  The centre stays an empty n-gon and the arms
    make a wreath of n spirals round it.

    `winding` picks the sense: OUT is the paper's clockwise design,
    IN the anticlockwise one -- the same arms mirrored edge for edge
    (each IN arm is the OUT arm reflected across its edge's
    perpendicular bisector) -- and BOTH superimposes the two, the
    richest figure and the one the tiling papers build from.

    Returns (polys, kinds, ring_ix, arm_ix): triangle vertex lists,
    the 0/1 triangle shape, the ring each triangle belongs to, and
    which arm it is part of -- OUT arms are numbered 0..n-1 anticlock-
    wise round the polygon, IN arms n..2n-1, so colour-by-arm works in
    every winding."""
    base = arm_polys(m, rings, arm, 0, R, 0.0)
    # canonical frame: base edge A->B mapped to (0,0)->(L,0), with the
    # arm's body (which spirals toward the m-gon centre) at y > 0.
    ag = 2.0 * pi / m
    A = (R, 0.0)
    B = (R * cos(ag), R * sin(ag))
    L = hypot(B[0] - A[0], B[1] - A[1])
    e1 = ((B[0] - A[0]) / L, (B[1] - A[1]) / L)
    e2 = (-e1[1], e1[0])
    sgn = 1.0 if (-A[0] * e2[0] - A[1] * e2[1]) >= 0.0 else -1.0

    def canon(p):
        qx, qy = p[0] - A[0], p[1] - A[1]
        return (qx * e1[0] + qy * e1[1],
                sgn * (qx * e2[0] + qy * e2[1]))

    cbase = [([canon(v) for v in tri], kind) for tri, kind in base]

    V = rosette_ngon(m, n, R)
    polys, kinds, ring_ix, arm_ix = [], [], [], []
    for j in range(n):
        Vj, Vj1 = V[j], V[(j + 1) % n]
        ex = ((Vj1[0] - Vj[0]) / L, (Vj1[1] - Vj[1]) / L)
        nout = (ex[1], -ex[0])          # outward normal of a CCW n-gon

        def place(p, mirror):
            x, y = p
            if mirror:
                x = L - x
            return (Vj[0] + x * ex[0] + y * nout[0],
                    Vj[1] + x * ex[1] + y * nout[1])

        for mirror, aid in ((True, j), (False, n + j)):
            if mirror and winding not in ('OUT', 'BOTH'):
                continue
            if not mirror and winding not in ('IN', 'BOTH'):
                continue
            for i, (tri, kind) in enumerate(cbase):
                polys.append([place(v, mirror) for v in tri])
                kinds.append(kind)
                ring_ix.append(i // 2)
                arm_ix.append(aid)
    return polys, kinds, ring_ix, arm_ix


def full_figure_polys(m, rings, R=1.0, phi=0.0):
    """All 2m triangles of every ring -- the complete m-gon subdivision
    (Gangopadhyay's `polyspidron`).  Returns (polys, types) with the
    type carrying the ring index so colour-by-ring works."""
    polys, types = [], []
    for i, (P, Q) in enumerate(planar_rings(m, rings, R, phi)):
        for tri, kind in ring_triangles(P, Q):
            polys.append(list(tri))
            types.append(2 * i + kind)
    return polys, types


# --------------------------------------------------------------------
# 2.  The Spidron Formula and its companions
# --------------------------------------------------------------------
#
# beta is the inclination of a ring's OUTER hexagon edges to the base
# plane; the four functions below all return the same inclination for
# the ring's INNER edges.  They come from three independent derivations
# and are kept separately so `_selftest` can cross-validate them.

def fold_inner(beta):
    """Szilassi's arctan form.  Preferred internally: its denominator
    2 - 4c + 3c^2 has discriminant 16 - 24 < 0 so it never vanishes,
    which the arcsin form's radicand cannot promise near the domain
    edge."""
    c = cos(beta)
    num = -1.0 + 4.0 * c - 3.0 * c * c
    den = 2.0 - 4.0 * c + 3.0 * c * c
    return atan2(sqrt(max(num, 0.0)), sqrt(den))


def fold_inner_kiss(beta):
    """Erdely-Kiss: the arcsin form usually called *the* Spidron
    Formula."""
    c = cos(beta)
    return asin(_clamp(sqrt(max(-1.0 + 4.0 * c - 3.0 * c * c, 0.0))))


def fold_inner_hujter(beta):
    """Hujter's arccos form."""
    c = cos(beta)
    return acos(_clamp(sqrt(max(3.0 * c * c - 4.0 * c + 2.0, 0.0))))


def fold_angle(beta):
    """Kiss's fold angle phi: the rotation of a ring's isosceles
    triangles about their own bases, phi = arccos(2 - 1/cos beta)."""
    return acos(_clamp(2.0 - 1.0 / cos(beta)))


def fold_inner_cheap(beta):
    """sin(beta') = cos(beta) * sin(phi) -- the cheapest equivalent."""
    return asin(_clamp(cos(beta) * sin(fold_angle(beta))))


def ring_twist(beta):
    """Kiss's gamma: how far a ring turns about the nest axis relative
    to the ring outside it, measured in his aligned frame."""
    phi = fold_angle(beta)
    return atan2(sin(beta) * sin(phi), -3.0 * cos(beta) + cos(phi))


def fold_turn(beta):
    """Szilassi's a(beta): the azimuth advance from a ring to the next,
    in the nest frame.  Runs from 30 deg (flat) to 60 deg at the
    60-degree physical bound."""
    c = cos(beta)
    num = (SQRT3 * (1.0 - 2.0 * c + 3.0 * c * c)
           - sin(beta) * sqrt(max(-1.0 + 4.0 * c - 3.0 * c * c, 0.0)))
    den = 4.0 * c * sqrt(2.0 - 4.0 * c + 3.0 * c * c)
    return acos(_clamp(num / den))


def nest_states(fold, rings, d0=1.0):
    """The (d, alpha, beta) triple for each ring, outermost first."""
    out, d, a, b = [], float(d0), 0.0, float(fold)
    for _ in range(rings):
        out.append((d, a, b))
        d, a, b = d / SQRT3, a + fold_turn(b), fold_inner(b)
    return out


# --------------------------------------------------------------------
# 3.  The folded hexagonal nest
# --------------------------------------------------------------------

def skew_hexagon(d, alpha, beta):
    """The six vertices of a ring's outer hexagon.

    Midpoints of the edges stay in the base plane; the vertices
    alternate +/- (d/2) sin(beta) about it, and the whole hexagon
    projects to a regular planar hexagon of side d cos(beta).  Every
    edge has length exactly d whatever beta is -- that invariance is
    the fold's defining property.
    """
    V = []
    for j in range(6):
        th = alpha + pi / 6.0 + j * pi / 3.0
        V.append((d * cos(beta) * cos(th),
                  d * cos(beta) * sin(th),
                  ((-1) ** j) * 0.5 * d * sin(beta)))
    return V


def nest_mesh(fold, rings, cap=True, d0=1.0, chirality=1):
    """Build the folded nest.  Returns (verts, faces, mats) with mat 0
    for the wide isosceles triangles, 1 for the equilateral ones and 2
    for the centre cap."""
    states = nest_states(fold, rings, d0)
    hexes = [skew_hexagon(d, chirality * a, b) for (d, a, b) in states]
    # the ring inside the last one closes the sequence
    d, a, b = states[-1]
    hexes.append(skew_hexagon(d / SQRT3, chirality * (a + fold_turn(b)),
                              fold_inner(b)))

    verts, faces, mats = [], [], []
    base = []
    for H in hexes:
        base.append(len(verts))
        verts.extend(H)
    for i in range(len(hexes) - 1):
        o, q = base[i], base[i + 1]
        for k in range(6):
            k1 = (k + 1) % 6
            faces.append((o + k, o + k1, q + k))
            mats.append(0)
            faces.append((q + k, o + k1, q + k1))
            mats.append(1)
    if cap:
        H = hexes[-1]
        c = (sum(v[0] for v in H) / 6.0, sum(v[1] for v in H) / 6.0,
             sum(v[2] for v in H) / 6.0)
        ci = len(verts)
        verts.append(c)
        o = base[-1]
        for k in range(6):
            faces.append((o + k, o + (k + 1) % 6, ci))
            mats.append(2)
    return verts, faces, mats


# --------------------------------------------------------------------
# 4.  Spidronisation of an arbitrary (possibly skew) polygon
# --------------------------------------------------------------------

def _best_fit_normal(P):
    """Newell's method -- robust for skew polygons."""
    n = np.zeros(3)
    m = len(P)
    for i in range(m):
        a, b = P[i], P[(i + 1) % m]
        n[0] += (a[1] - b[1]) * (a[2] + b[2])
        n[1] += (a[2] - b[2]) * (a[0] + b[0])
        n[2] += (a[0] - b[0]) * (a[1] + b[1])
    L = np.linalg.norm(n)
    return n / L if L > 1e-15 else np.array([0.0, 0.0, 1.0])


def _rot_about(axis, ang):
    axis = np.asarray(axis, float)
    axis = axis / np.linalg.norm(axis)
    c, s = cos(ang), sin(ang)
    x, y, z = axis
    return np.array([
        [c + x * x * (1 - c), x * y * (1 - c) - z * s, x * z * (1 - c) + y * s],
        [y * x * (1 - c) + z * s, c + y * y * (1 - c), y * z * (1 - c) - x * s],
        [z * x * (1 - c) - y * s, z * y * (1 - c) + x * s, c + z * z * (1 - c)],
    ])


def spidronise(poly, scale, twist, rings, chirality=1, centre=None,
               normal=None, cap=False):
    """Spidronise a polygon (van Ballegooijen-Gailiunas-Erdely 2009).

    Repeatedly scale the polygon toward `centre` by `scale` and rotate
    it by `chirality * twist` about the axis through the centre along
    the polygon's normal, triangulating the annulus between each
    consecutive pair.  Every vertex's images lie on a logarithmic
    spiral.  Works for skew polygons, which is what makes the
    spidronised polyhedra possible.

    Returns (verts, faces, mats); mats alternate 0/1 per annulus
    triangle pair, with 2 for the optional centre cap.
    """
    P = np.asarray(poly, float)
    m = len(P)
    C = np.asarray(centre, float) if centre is not None else P.mean(axis=0)
    N = np.asarray(normal, float) if normal is not None else _best_fit_normal(P)
    Rm = _rot_about(N, chirality * twist)

    loops = [P]
    cur = P
    for _ in range(rings):
        cur = (Rm @ (cur - C).T).T * scale + C
        loops.append(cur)

    verts, faces, mats = [], [], []
    base = []
    for L in loops:
        base.append(len(verts))
        verts.extend([tuple(float(c) for c in v) for v in L])
    for i in range(len(loops) - 1):
        o, q = base[i], base[i + 1]
        for k in range(m):
            k1 = (k + 1) % m
            faces.append((o + k, o + k1, q + k))
            mats.append(0)
            faces.append((q + k, o + k1, q + k1))
            mats.append(1)
    if cap:
        ci = len(verts)
        verts.append(tuple(float(c) for c in loops[-1].mean(axis=0)))
        o = base[-1]
        for k in range(m):
            faces.append((o + k, o + (k + 1) % m, ci))
            mats.append(2)
    return verts, faces, mats


def skew_lift(poly, dz, normal=None):
    """Alternate a polygon's vertices +/- dz along its normal, turning a
    planar 2k-gon into a regular skew 2k-gon.  This is what makes a
    spidronised face stand out of the solid (Nylander's spidroball
    look); with an odd vertex count the polygon is first refined with
    edge midpoints so the alternation closes."""
    P = [list(map(float, v)) for v in poly]
    if len(P) % 2:
        Q = []
        for i in range(len(P)):
            a, b = P[i], P[(i + 1) % len(P)]
            Q.append(a)
            Q.append([0.5 * (a[k] + b[k]) for k in range(3)])
        P = Q
    A = np.asarray(P, float)
    N = np.asarray(normal, float) if normal is not None else _best_fit_normal(A)
    for i in range(len(A)):
        A[i] = A[i] + ((-1) ** i) * dz * N
    return [tuple(float(c) for c in v) for v in A]


# --------------------------------------------------------------------
# 5.  The generalized square pattern (Imada-Hull-Ku-Tachi)
# --------------------------------------------------------------------

def square_theta_max(s):
    """Largest twist that keeps the square crease pattern free of
    self-intersection (paper Eq. 1)."""
    if s <= sqrt(2.0) / 2.0:
        return pi / 4.0
    return acos(_clamp((1.0 + sqrt(max(2.0 * s * s - 1.0, 0.0))) / (2.0 * s)))


def square_crease_lengths(s, theta):
    """(r1, r2) for a unit outer edge (paper Eq. 2 at t = 0)."""
    r1 = sqrt(max(0.5 * s * s - s * cos(theta) + 0.5, 0.0))
    r2 = sqrt(max(0.5 * s * s - s * sin(theta) + 0.5, 0.0))
    return r1, r2


def _square_outer(rho):
    """The four outer-boundary vertices of a ring at isotropic dihedral
    `rho` (paper Eq. 3 with rho1 = -rho2 = rho), unit edge."""
    t = tan(0.5 * rho)
    # Eq. 3 with rho1 = -rho2 = rho collapses to d = 1/sqrt(2 + t^2);
    # at rho = 0 that is 1/sqrt(2), the flat unit square.
    d = 1.0 / sqrt(2.0 + t * t)
    h = sqrt(max(1.0 - 2.0 * d * d, 0.0))
    sg = 1.0 if rho >= 0 else -1.0
    return np.array([
        [d, 0.0, -sg * 0.5 * h],
        [0.0, d, +sg * 0.5 * h],
        [-d, 0.0, -sg * 0.5 * h],
        [0.0, -d, +sg * 0.5 * h],
    ])


def _circle_about_edge(p0, p1, r1, r2, ref):
    """Parameterise the points at distance r1 from p0 and r2 from p1 as
    a circle; returns (centre, u, v, radius) so the point at angle t is
    centre + radius*(cos t * u + sin t * v).

    `ref` fixes the frame: u points from the circle's centre away from
    `ref` (the ring's own centre), perpendicular to the edge.  Deriving
    the frame from the ring rather than from an arbitrary world axis is
    what makes "the same t on all four edges" mean the same geometric
    configuration -- i.e. what makes the isotropic ansatz valid.
    """
    d = p1 - p0
    L = np.linalg.norm(d)
    e = d / L
    x = (L * L + r1 * r1 - r2 * r2) / (2.0 * L)
    rad2 = r1 * r1 - x * x
    if rad2 <= 0.0:
        return None
    cen = p0 + x * e
    out = cen - np.asarray(ref, float)
    out = out - float(out @ e) * e
    n = np.linalg.norm(out)
    if n < 1e-12:
        tmp = np.array([0.0, 0.0, 1.0])
        if abs(float(e @ tmp)) > 0.9:
            tmp = np.array([1.0, 0.0, 0.0])
        out = np.cross(e, tmp)
        n = np.linalg.norm(out)
    u = out / n
    v = np.cross(e, u)
    return cen, u, v, sqrt(rad2)


def square_solve_ring(rho, s, theta, mode='PRO'):
    """Solve one ring of the generalized square spidron.

    Rather than transcribing the paper's quartic, the inner vertices are
    found from first principles: q_i must sit at r1 from p_i and r2 from
    p_(i+1), which puts it on a circle about that edge; the remaining
    freedom is one angle, fixed by requiring the inner edge |q1 - q0| to
    equal s.  The two real roots of that scalar equation are the paper's
    pro- and anti-rotation modes.  Returns (Q, rho_in) or None.
    """
    P = _square_outer(rho)
    r1, r2 = square_crease_lengths(s, theta)
    # THE FLAT STATE IS A TANGENT ROOT.  At rho = 0 the ring is planar
    # and the metric residual touches zero without changing sign, so the
    # sign-change scan below cannot see it -- the solve would return
    # nothing, or succeed only when float noise in the caller's
    # parameters happened to perturb the tangency into a crossing.  The
    # flat state is known in closed form, so return it directly.
    if abs(rho) < 1e-7:
        c, sn = cos(theta), sin(theta)
        Rz = np.array([[c, -sn, 0.0], [sn, c, 0.0], [0.0, 0.0, 1.0]])
        for sg in (1.0, -1.0):
            Rs = Rz if sg > 0 else Rz.T
            Q = (Rs @ P.T).T * s
            if abs(float(np.linalg.norm(Q[0] - P[0])) - r1) < 1e-9:
                return Q, 0.0
        return (Rz @ P.T).T * s, 0.0
    ctr = P.mean(axis=0)
    circles = []
    for i in range(4):
        c = _circle_about_edge(P[i], P[(i + 1) % 4], r1, r2, ctr)
        if c is None:
            return None
        circles.append(c)

    def q_at(i, t):
        # ISOTROPIC ANSATZ.  The paper's isotropic folded state is
        # phi^1 = -phi^2, so the parameter alternates in sign from edge
        # to edge -- the pattern's 4-fold symmetry is a quarter turn
        # composed with the boundary's z-alternation, not a pure
        # rotation.  With the sign alternating, all four inner edges
        # come out equal identically; with a single shared t they do
        # not, and no configuration satisfies the metric constraint.
        cen, u, v, rad = circles[i]
        tt = t if (i % 2 == 0) else -t
        return cen + rad * (cos(tt) * u + sin(tt) * v)

    def resid(t):
        Q = [q_at(i, t) for i in range(4)]
        return float(np.linalg.norm(Q[1] - Q[0]) - s)

    roots = []
    ts = np.linspace(-pi, pi, 721)
    prev_t, prev_r = ts[0], resid(ts[0])
    for t in ts[1:]:
        r = resid(t)
        if prev_r == 0.0 or (prev_r < 0.0) != (r < 0.0):
            a, b = prev_t, t
            for _ in range(60):
                mid = 0.5 * (a + b)
                rm = resid(mid)
                if (resid(a) < 0.0) != (rm < 0.0):
                    b = mid
                else:
                    a = mid
            roots.append(0.5 * (a + b))
        prev_t, prev_r = t, r
    if not roots:
        return None

    def inner_of(t):
        Q = np.array([q_at(i, t) for i in range(4)])
        cen = Q.mean(axis=0)
        rel = Q - cen
        dd = float(np.linalg.norm(rel[0][:2]))
        edge = float(np.linalg.norm(Q[1] - Q[0]))
        if edge < 1e-12:
            return None
        dn = dd / edge
        tt2 = 1.0 / max(dn * dn, 1e-18) - 2.0
        if tt2 < 0.0:
            tt2 = 0.0
        zsign = 1.0 if rel[1][2] >= rel[0][2] else -1.0
        return Q, 2.0 * atan2(sqrt(tt2), 1.0) * zsign

    cands = []
    for t in roots:
        got = inner_of(t)
        if got is None:
            continue
        Q, rin = got
        # sense of the inner boundary's rotation relative to the outer
        turn = atan2(Q[0][1], Q[0][0]) - atan2(P[0][1], P[0][0])
        while turn > pi:
            turn -= 2 * pi
        while turn < -pi:
            turn += 2 * pi
        cands.append((turn, Q, rin))
    if not cands:
        return None
    cands.sort(key=lambda c: c[0])
    pick = cands[-1] if mode == 'PRO' else cands[0]
    return pick[1], pick[2]


def _similarity(A, B):
    """The scale+rotation+translation carrying point set A onto B
    (Kabsch with uniform scale).  Both are (n, 3) and congruent up to
    similarity; used to place each ring's canonical solution into the
    frame the previous ring left behind."""
    A = np.asarray(A, float)
    B = np.asarray(B, float)
    ca, cb = A.mean(axis=0), B.mean(axis=0)
    X, Y = A - ca, B - cb
    U, S, Vt = np.linalg.svd(X.T @ Y)
    d = np.sign(np.linalg.det(Vt.T @ U.T))
    D = np.diag([1.0, 1.0, d])
    R = Vt.T @ D @ U.T
    var = float((X * X).sum())
    scl = float(S[:2].sum() + d * S[2]) / var if var > 1e-18 else 1.0
    return R, scl, cb, ca


def square_nest(rho0, s, theta, rings, mode='PRO'):
    """Iterate `square_solve_ring` inward, composing each ring's
    canonical solution into world space.  PLEATS alternates the two
    modes ring to ring.  Returns (loops, rhos)."""
    loops = [_square_outer(rho0)]
    rhos = [float(rho0)]
    rho = float(rho0)
    for k in range(rings):
        md = mode
        if mode == 'PLEATS':
            md = 'PRO' if (k % 2 == 0) else 'ANTI'
        got = square_solve_ring(rho, s, theta, md)
        if got is None:
            break
        Q, rho_in = got
        # Q solves the ring whose outer boundary is the CANONICAL
        # _square_outer(rho); map that canonical outer onto the loop we
        # actually have, and carry Q along with it.
        R, scl, cb, ca = _similarity(_square_outer(rho), loops[-1])
        loops.append(((Q - ca) @ R.T) * scl + cb)
        rhos.append(rho_in)
        rho = rho_in
    return loops, rhos


def square_mesh(rho0, s, theta, rings, mode='PRO', cap=True):
    """Mesh of the generalized square spidron."""
    loops, rhos = square_nest(rho0, s, theta, rings, mode)
    verts, faces, mats, base = [], [], [], []
    for L in loops:
        base.append(len(verts))
        verts.extend([tuple(float(c) for c in v) for v in L])
    for i in range(len(loops) - 1):
        o, q = base[i], base[i + 1]
        for k in range(4):
            k1 = (k + 1) % 4
            faces.append((o + k, o + k1, q + k))
            mats.append(0)
            faces.append((q + k, o + k1, q + k1))
            mats.append(1)
    if cap and len(loops) > 1:
        ci = len(verts)
        verts.append(tuple(float(c) for c in np.asarray(loops[-1]).mean(axis=0)))
        o = base[-1]
        for k in range(4):
            faces.append((o + k, o + (k + 1) % 4, ci))
            mats.append(2)
    return verts, faces, mats, rhos


# --------------------------------------------------------------------
# Self-test
# --------------------------------------------------------------------

def _selftest():
    ok = True

    def chk(name, cond, extra=""):
        nonlocal ok
        ok = ok and bool(cond)
        print("  %-52s %s %s" % (name, "OK" if cond else "BAD", extra))

    print("spidron_math: planar construction")
    chk("arm ratio m=6 == 1/sqrt(3)", abs(arm_ratio(6) - 1.0 / SQRT3) < 1e-15,
        "%.12f" % arm_ratio(6))
    chk("arm turn m=6 == 30 deg", abs(degrees(arm_turn(6)) - 30.0) < 1e-12)
    chk("ratio positive only for m >= 5",
        arm_ratio(5) > 0 and arm_ratio(4) <= 1e-15 and arm_ratio(3) < 0)

    # the m=6 ring is the classical isosceles+equilateral pair
    P, Q = planar_rings(6, 1, 1.0, 0.0)[0]
    tris = ring_triangles(P, Q)
    iso = np.array(sorted(hypot(*(np.array(tris[0][0][i]) -
                                  np.array(tris[0][0][(i + 1) % 3])))
                          for i in range(3)))
    equ = np.array(sorted(hypot(*(np.array(tris[1][0][i]) -
                                  np.array(tris[1][0][(i + 1) % 3])))
                          for i in range(3)))
    chk("m=6 ring: 120-deg isosceles (1, 1/r3, 1/r3)",
        np.abs(iso - sorted([1.0, 1 / SQRT3, 1 / SQRT3])).max() < 1e-12)
    chk("m=6 ring: equilateral (1/r3)^3",
        np.abs(equ - 1 / SQRT3).max() < 1e-12)

    # area: the ring triangles exactly tile the annulus between the m-gons
    for m in (5, 6, 8, 12):
        P, Q = planar_rings(m, 1, 1.0, 0.0)[0]

        def area(poly):
            a = 0.0
            for i in range(len(poly)):
                x0, y0 = poly[i]
                x1, y1 = poly[(i + 1) % len(poly)]
                a += x0 * y1 - x1 * y0
            return abs(a) * 0.5
        tri_area = sum(area(t) for t, _ in ring_triangles(P, Q))
        chk("m=%2d ring triangles tile the annulus" % m,
            abs(tri_area - (area(P) - area(Q))) < 1e-12)

    print("spidron_math: the Spidron Formula")
    worst = 0.0
    for beta in np.linspace(0.0, BETA_MAX - 1e-9, 600):
        v = [fold_inner(beta), fold_inner_kiss(beta),
             fold_inner_hujter(beta), fold_inner_cheap(beta)]
        worst = max(worst, max(v) - min(v))
    chk("four independent forms agree", worst < 1e-11, "spread %.2e" % worst)
    chk("a(0+) -> 30 deg", abs(degrees(fold_turn(1e-9)) - 30.0) < 1e-6)
    # Kiss's gamma and Szilassi's a measure the same azimuth advance in
    # frames that differ by a constant; pinning that constant validates
    # gamma, which nothing else exercises.
    off = [degrees(ring_twist(b)) + degrees(fold_turn(b))
           for b in np.linspace(0.05, BETA_PHYSICAL, 200)]
    chk("Kiss gamma = 210 deg - Szilassi a(beta)",
        max(abs(o - 210.0) for o in off) < 1e-9,
        "offset %.9f deg" % off[0])
    chk("a(60) == 60 deg",
        abs(degrees(fold_turn(BETA_PHYSICAL)) - 60.0) < 1e-9)
    chk("b(60) == 30 deg",
        abs(degrees(fold_inner(BETA_PHYSICAL)) - 30.0) < 1e-9)
    chk("b(beta) <= arcsin(1/sqrt3)",
        max(fold_inner(b) for b in np.linspace(0, BETA_MAX, 4000))
        <= BETA_IMAGE_MAX + 1e-12)
    chk("both domain endpoints map to 0",
        fold_inner(0.0) < 1e-12 and fold_inner(BETA_MAX) < 1e-6)
    chk("b(f) < f strictly on (0, 60]",
        all(fold_inner(b) < b
            for b in np.linspace(1e-3, BETA_PHYSICAL, 500)))
    # b(f) = f - f^3/4 + O(f^5); the cubic coefficient is what makes the
    # decay slow (b'(0) = 1), so pin it rather than the naive "small
    # after N steps" test, which is false here -- see the asymptotic
    # check below and Szilassi's Universe-to-quark remark.
    cub = [(f - fold_inner(f)) / f ** 3 for f in (1e-2, 3e-2, 1e-1)]
    chk("b(f) = f - f^3/4 + O(f^5)",
        max(abs(c - 0.25) for c in cub) < 2e-3, "coeff ~ %.6f" % cub[0])
    seq, b = [], BETA_PHYSICAL
    for _ in range(20000):
        b = fold_inner(b)
        seq.append(b)
    chk("iterating decays monotonically",
        all(seq[i + 1] < seq[i] for i in range(len(seq) - 1))
        and seq[-1] > 0.0)
    # x_{k+1} = x_k - x_k^3/4 gives x_k -> sqrt(2/k).
    chk("decay follows beta_k -> sqrt(2)/sqrt(k)",
        abs(seq[19999] * sqrt(20000) - sqrt(2.0)) < 2e-2,
        "beta_k*sqrt(k) = %.4f vs sqrt2 = %.4f"
        % (seq[19999] * sqrt(20000), sqrt(2.0)))

    print("spidron_math: the folded nest")
    for fd in (0.0, 10.0, 30.0, 45.0, 59.0):
        f = radians(fd)
        st = nest_states(f, 6)
        bad_e = bad_i = bad_q = 0.0
        for i in range(len(st) - 1):
            d, a, b = st[i]
            d2, a2, b2 = st[i + 1]
            H, G = skew_hexagon(d, a, b), skew_hexagon(d2, a2, b2)
            H = np.array(H)
            G = np.array(G)
            for k in range(6):
                k1 = (k + 1) % 6
                bad_e = max(bad_e, abs(np.linalg.norm(H[k1] - H[k]) - d))
                t1 = sorted([np.linalg.norm(H[k1] - H[k]),
                             np.linalg.norm(G[k] - H[k]),
                             np.linalg.norm(G[k] - H[k1])])
                t2 = sorted([np.linalg.norm(G[k1] - G[k]),
                             np.linalg.norm(H[k1] - G[k]),
                             np.linalg.norm(H[k1] - G[k1])])
                bad_i = max(bad_i, max(abs(np.array(t1) - sorted(
                    [d, d / SQRT3, d / SQRT3]))))
                bad_q = max(bad_q, max(abs(np.array(t2) - d / SQRT3)))
        chk("f=%4.1f edges keep length d" % fd, bad_e < 1e-12,
            "%.1e" % bad_e)
        chk("f=%4.1f triangles stay congruent" % fd,
            bad_i < 1e-9 and bad_q < 1e-9, "%.1e / %.1e" % (bad_i, bad_q))

    st = nest_states(radians(40.0), 5)
    chk("folded nest is NOT self-similar",
        abs(st[1][2] - st[0][2]) > 1e-3,
        "b0=%.3f b1=%.3f deg" % (degrees(st[0][2]), degrees(st[1][2])))
    st0 = nest_states(0.0, 5)
    chk("flat nest IS self-similar",
        all(abs(s[2]) < 1e-15 for s in st0)
        and abs(st0[1][0] * SQRT3 - st0[0][0]) < 1e-15)
    H = np.array(skew_hexagon(1.0, 0.0, radians(40.0)))
    chk("skew hexagon midpoints lie in the base plane",
        max(abs(0.5 * (H[k][2] + H[(k + 1) % 6][2])) for k in range(6)) < 1e-15)

    V, F, M = nest_mesh(radians(40.0), 6, cap=True)
    edges = {}
    for f in F:
        for i in range(len(f)):
            e = tuple(sorted((f[i], f[(i + 1) % len(f)])))
            edges[e] = edges.get(e, 0) + 1
    inner = sum(1 for c in edges.values() if c == 2)
    chk("capped nest is watertight",
        inner == len(edges) - 6, "%d/%d interior" % (inner, len(edges)))
    Z = np.array(V)
    ext = Z.max(axis=0) - Z.min(axis=0)
    chk("folded nest has real relief (z >= 0.15 x)",
        ext[2] >= 0.15 * ext[0], "z/x = %.3f" % (ext[2] / ext[0]))
    V0, _, _ = nest_mesh(0.0, 6, cap=True)
    Z0 = np.array(V0)
    chk("flat nest is flat", abs(Z0[:, 2]).max() < 1e-15)

    print("spidron_math: spidronise")
    sq = [(1, 0, 0), (0, 1, 0), (-1, 0, 0), (0, -1, 0)]
    V, F, M = spidronise(sq, 0.6, radians(20.0), 5)
    P0 = np.array(V[0])
    rs, ds = [], []
    for i in range(5):
        p = np.array(V[4 * (i + 1)])
        rs.append(np.linalg.norm(p))
        ds.append(atan2(p[1], p[0]))
    ratios = [rs[i + 1] / rs[i] for i in range(len(rs) - 1)]
    chk("images lie on a logarithmic spiral",
        max(abs(r - 0.6) for r in ratios) < 1e-12,
        "ratio %.9f" % ratios[0])
    Va, _, _ = spidronise(sq, 0.6, radians(20.0), 3, chirality=+1)
    Vb, _, _ = spidronise(sq, 0.6, radians(20.0), 3, chirality=-1)
    chk("chirality flips the spiral sense",
        abs(np.array(Va)[4][1] + np.array(Vb)[4][1]) < 1e-12)
    sk = skew_lift(sq, 0.3)
    zs = [v[2] for v in sk]
    chk("skew lift alternates about the plane",
        abs(sum(zs)) < 1e-12 and all(abs(abs(z) - 0.3) < 1e-12 for z in zs))

    print("spidron_math: generalized square pattern")
    chk("theta clamp at s <= sqrt2/2 is pi/4",
        abs(square_theta_max(0.5) - pi / 4.0) < 1e-15)
    chk("theta clamp shrinks above sqrt2/2",
        square_theta_max(0.9) < pi / 4.0,
        "%.4f deg" % degrees(square_theta_max(0.9)))
    worst_m = worst_s = 0.0
    solved = 0
    for (rd, s_, th) in ((40.0, 0.5, 15.0), (60.0, 0.6, 30.0),
                         (30.0, 0.45, 45.0), (25.0, 0.7, 10.0)):
        got = square_solve_ring(radians(rd), s_, radians(th), 'PRO')
        if got is None:
            continue
        solved += 1
        Q, _ = got
        e = [float(np.linalg.norm(Q[(i + 1) % 4] - Q[i])) for i in range(4)]
        worst_m = max(worst_m, max(abs(x - s_) for x in e))
        worst_s = max(worst_s, max(e) - min(e))
    chk("square ring meets the metric constraint (4 cases)",
        solved == 4 and worst_m < 1e-7,
        "|e|-s <= %.1e" % worst_m)
    chk("isotropic ansatz: all four inner edges equal",
        worst_s < 1e-12, "spread %.1e" % worst_s)
    lp, rh = square_nest(radians(50.0), 0.55, radians(20.0), 6, 'PRO')
    chk("square nest chains rings", len(lp) >= 4,
        "%d loops" % len(lp))
    ok_edge = True
    for L in lp[1:]:
        e = [float(np.linalg.norm(L[(i + 1) % 4] - L[i])) for i in range(4)]
        ok_edge = ok_edge and (max(e) - min(e)) < 1e-9
    chk("placed rings stay square", ok_edge)
    lp2, _ = square_nest(radians(50.0), 0.55, radians(20.0), 6, 'ANTI')
    chk("PRO and ANTI are different modes",
        len(lp2) < 2 or abs(float(np.asarray(lp[1])[0][2])
                            - float(np.asarray(lp2[1])[0][2])) > 1e-6)

    print("RESULT:", "OK" if ok else "BAD")
    return ok
