# Triangle Spiral Rosette -- planar spidron figures and tilings.
#
# The two-dimensional half of the spidron family: the nested-polygon
# subdivision itself, single spiralling arms, rosettes assembled from
# several arms, and plane tilings of the result.  The three-dimensional
# halves are `spidron_nest_generator` (the folded relief) and
# `spidron_ball_generator` (spidronised polyhedra); all three share
# `spidron_math`.
#
# WHAT IS DRAWN.  Take a regular m-gon and connect alternate vertices; a
# smaller m-gon appears inside, scaled by cos(ag)/cos(ag/2) and turned
# by ag/2, where ag = 360/m.  The annulus between the two triangulates
# into 2m triangles, and repeating the step fills the m-gon with a
# spiral of ever-smaller triangles.  At m = 6 the two triangles per step
# are exactly the 120-degree isosceles and the equilateral triangle of
# Erdely's original spidron, and the ratio is 1/sqrt(3).
#
# A single limb of that figure is a "semi-spidron", or arm.  Following
# Gangopadhyay, the arm comes in three flavours that differ only in how
# fast the limb's index advances from ring to ring -- fixed (spidron),
# every ring (creeper), every second ring (ladder, whose index step
# therefore spans four triangles and squares the scale ratio).  Arms are
# then placed round a regular n-gon, wound outward, inward, or both
# superimposed, and the result can be tiled across the plane.
#
# Output goes through the shared Pattern Engine, so grout margin, relief
# height, per-tile materials and separate-tile output all come for free.
#
# References:
# - Daniel Erdely, "Some Surprising New Properties of the Spidrons",
#   Bridges 2005 Conference Proceedings, pp. 179-186 -- the figure and
#   its hexagonal nest.
# - T. Gangopadhyay, "On an Alternate Construction Method for
#   Generating Spidrons and New Tiling Patterns Generated by them",
#   International Journal of Computer Applications 160(3), 2017,
#   pp. 25-29 -- m-part arms assembled into a regular polygon, and the
#   tilings drawn from them.
# - T. Gangopadhyay, "On New Polygonal Designs Constructed using
#   Spidrons and New Tiling Patterns Generated by Them", International
#   Journal of Computer Applications 162(1), 2017, pp. 11-15 -- the
#   clockwise, anti-clockwise and superimposed rosettes.
# - T. Gangopadhyay, "On Subdividing Regular Polygons using Structures
#   other than Spidrons and Tiling Patterns Generated by Them",
#   International Journal of Computer Applications 163(2), 2017,
#   pp. 9-12 -- the "ladder" variant.
# - T. Gangopadhyay, "On further Subdivisions of Regular Polygons using
#   Structures other than Spidrons and Tiling Patterns Generated by
#   them", International Journal of Computer Applications 165(1), 2017,
#   pp. 31-34 -- the "creeper" variant.
# - Mihaly Hujter, "A csillaghatszog spidronszeru felgyurodese mogotti
#   matematika", Haladvany Kiadvany, 16 June 2018 -- the kite
#   similarity that fixes the 1/sqrt(3) scale and 30-degree turn.

bl_info = {
    "name": "Triangle Spiral Rosette",
    "author": "Math Art project",
    "version": (1, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Math Art > Patterns",
    "description": "Spidron figures: nested-polygon triangle spirals, "
                   "single arms, rosettes and plane tilings",
    "category": "Add Mesh",
}

from math import cos, sin, pi, sqrt

import numpy as np

try:
    from .patterns import common as pc
    from . import tiling_generator as tg
    from . import spidron_math as sm
except Exception:                       # legacy single-file / CLI use
    from patterns import common as pc
    import tiling_generator as tg
    import spidron_math as sm


LAYOUT_ITEMS = [
    ('FIGURE', "Full Figure",
     "The whole polygon subdivision: every triangle of every ring, "
     "filling the starting polygon"),
    ('ARM', "Single Arm",
     "One spiralling limb on its own, so the arm's shape is visible"),
    ('ROSETTE', "Rosette",
     "Several arms placed round a regular polygon"),
    ('TILING', "Tiling",
     "A lattice of rosettes covering a patch of the plane"),
]

ARM_ITEMS = [
    ('SPIDRON', "Spidron",
     "The classical limb: the arm keeps the same position in every "
     "ring and spirals straight inward"),
    ('CREEPER', "Creeper",
     "The arm advances one position per ring, so it winds round the "
     "figure as it shrinks"),
    ('LADDER', "Ladder",
     "The arm advances one position every second ring, so each step "
     "spans four triangles and squares the scale ratio"),
]

WINDING_ITEMS = [
    ('OUT', "Outward", "Arms wound outward from the centre"),
    ('IN', "Inward", "Arms wound inward, the mirrored placement"),
    ('BOTH', "Both", "Both windings superimposed -- the richest figure, "
                     "and the one the tiling papers use"),
]


def build_polys(layout, m, n, rings, arm, winding, tiles_x, tiles_y):
    """Return (polys, types, ring_index) in the plane for the chosen
    layout.  `types` distinguishes the triangle shapes (and, for the
    rosettes, the winding); `ring_index` is carried separately so
    colouring by ring is possible in every layout rather than only in
    the full figure."""
    if layout == 'FIGURE':
        polys, types = sm.full_figure_polys(m, rings)
        return polys, [t % 2 for t in types], [t // 2 for t in types]
    if layout == 'ARM':
        tris = sm.arm_polys(m, rings, arm, 0)
        return ([list(t) for t, _ in tris], [k for _, k in tris],
                [i // 2 for i in range(len(tris))])
    if layout == 'ROSETTE':
        polys, types = sm.rosette_polys(m, n, rings, arm, winding)
        per = len(polys) // max(1, (n * (2 if winding == 'BOTH' else 1)))
        return polys, types, [(i % per) // 2 for i in range(len(polys))]

    polys, types, rix = build_polys('ROSETTE', m, n, rings, arm,
                                    winding, 1, 1)
    # lattice pitch: the rosette spans the circumcircle of the n-gon of
    # unit-circumradius arms, so a square lattice at 2R packs them
    # touching without overlap.
    step = 2.0
    out_p, out_t, out_r = [], [], []
    for iy in range(tiles_y):
        for ix in range(tiles_x):
            dx = (ix - 0.5 * (tiles_x - 1)) * step
            dy = (iy - 0.5 * (tiles_y - 1)) * step
            for p, t, r in zip(polys, types, rix):
                out_p.append([(x + dx, y + dy) for (x, y) in p])
                out_t.append(t)
                out_r.append(r)
    return out_p, out_t, out_r


try:
    import bpy
    from bpy.props import (IntProperty, FloatProperty, EnumProperty,
                           BoolProperty)
    from bpy_extras.object_utils import AddObjectHelper
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    class MESH_OT_spidron_rosette_add(bpy.types.Operator, AddObjectHelper):
        """Add a spidron figure: a spiral of triangles filling a
        regular polygon, as a single arm, a rosette or a tiling"""
        bl_idname = "mesh.spidron_rosette_add"
        bl_label = "Triangle Spiral Rosette"
        bl_options = {'REGISTER', 'UNDO'}

        layout_kind: EnumProperty(
            name="Layout", items=LAYOUT_ITEMS, default='FIGURE',
            description="What to build: the whole polygon subdivision, "
                        "one arm, a rosette of arms, or a tiling")
        arm: EnumProperty(
            name="Arm", items=ARM_ITEMS, default='SPIDRON',
            description="Which limb of the spidron family to draw")
        arm_parts: IntProperty(
            name="Arm Parts", default=6, min=5, max=24,
            description="Sides of the polygon the arm subdivides; the "
                        "arm angle is 360 divided by this. Five is the "
                        "smallest that gives a shrinking spiral, six is "
                        "the classical hexagonal spidron")
        corners: IntProperty(
            name="Corners", default=6, min=3, max=24,
            description="How many arms are placed round the rosette. "
                        "Independent of Arm Parts")
        rings: IntProperty(
            name="Rings", default=10, min=1, max=24,
            description="How many times the spiral step repeats. Each "
                        "ring is smaller than the last, so beyond about "
                        "sixteen the additions are invisible")
        winding: EnumProperty(
            name="Winding", items=WINDING_ITEMS, default='OUT',
            description="Sense in which the arms are wound round the "
                        "rosette")
        tiles_x: IntProperty(
            name="Columns", default=3, min=1, max=12,
            description="Rosettes across the tiling")
        tiles_y: IntProperty(
            name="Rows", default=3, min=1, max=12,
            description="Rosettes down the tiling")
        color_by: EnumProperty(
            name="Color", default='SHAPE',
            items=[('SHAPE', "Triangle Shape",
                    "One material per triangle shape, so the two "
                    "shapes of each ring read differently"),
                   ('RING', "Ring", "One material per ring, showing "
                                    "the spiral banding"),
                   ('UNIFORM', "Uniform", "A single material")],
            description="How materials are assigned")
        margin: FloatProperty(
            name="Margin", default=0.0, min=0.0, max=0.4,
            description="Inset each triangle by this fraction, leaving "
                        "a grout gap between tiles")
        height: FloatProperty(
            name="Height", default=0.0, min=0.0, max=2.0,
            description="Extrude each triangle to this depth; zero "
                        "leaves a flat pattern")
        separate: BoolProperty(
            name="Separate Tiles", default=False,
            description="Build one object per triangle under a parent "
                        "empty instead of a single merged mesh")

        def execute(self, context):
            m, n = int(self.arm_parts), int(self.corners)
            polys, types, rix = build_polys(
                self.layout_kind, m, n, int(self.rings), self.arm,
                self.winding, int(self.tiles_x), int(self.tiles_y))
            if not polys:
                self.report({'ERROR'}, "no triangles generated")
                return {'CANCELLED'}
            if self.color_by == 'RING':
                npal = len(pc.PALETTE_RGBA)
                types = [r % npal for r in rix]
                cby = 'TYPE'
            elif self.color_by == 'SHAPE':
                types = [t % 2 for t in types]
                cby = 'TYPE'
            else:
                types = [0] * len(polys)
                cby = 'UNIFORM'
            cells = tg.cells_from_polys(
                lambda a, b: (polys, types), 1, 1, cby,
                self.margin, self.height, False)
            obj = pc.emit(context, "Spidron Rosette", cells,
                          self.separate, fit=True, operator=self)
            if obj is None:
                self.report({'ERROR'}, "no geometry generated")
                return {'CANCELLED'}
            obj["math_art_pattern"] = True
            self.report({'INFO'}, "%s  m=%d  %d triangles"
                        % (self.layout_kind.title(), m, len(polys)))
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            lay.prop(self, 'layout_kind')
            lay.prop(self, 'arm_parts')
            if self.layout_kind != 'FIGURE':
                lay.prop(self, 'arm')
            if self.layout_kind in ('ROSETTE', 'TILING'):
                lay.prop(self, 'corners')
                lay.prop(self, 'winding')
            lay.prop(self, 'rings')
            if self.layout_kind == 'TILING':
                lay.prop(self, 'tiles_x')
                lay.prop(self, 'tiles_y')
            for p in ('color_by', 'margin', 'height'):
                lay.prop(self, p)
            lay.prop(self, 'separate')
            lay.prop(self, 'align')

    def _menu_func(self, context):
        self.layout.operator("mesh.spidron_rosette_add",
                             icon='FORCE_VORTEX')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(MESH_OT_spidron_rosette_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.remove(_menu_func)
        bpy.utils.unregister_class(MESH_OT_spidron_rosette_add)


# --------------------------------------------------------------------
# Self-test
# --------------------------------------------------------------------

def _poly_area(p):
    a = 0.0
    for i in range(len(p)):
        x0, y0 = p[i]
        x1, y1 = p[(i + 1) % len(p)]
        a += x0 * y1 - x1 * y0
    return 0.5 * a


def _selftest():
    ok = True

    def chk(name, cond, extra=""):
        nonlocal ok
        ok = ok and bool(cond)
        print("  %-52s %s %s" % (name, "OK" if cond else "BAD", extra))

    print("spidron_rosette: layouts")
    for lay in ('FIGURE', 'ARM', 'ROSETTE', 'TILING'):
        p, t, r = build_polys(lay, 6, 6, 6, 'SPIDRON', 'OUT', 2, 2)
        chk("%-8s builds triangles" % lay,
            len(p) > 0 and all(len(q) == 3 for q in p),
            "%d tris" % len(p))
        chk("%-8s types align with polys" % lay,
            len(p) == len(t) == len(r))
        chk("%-8s ring index spans the rings" % lay,
            max(r) + 1 == 6 or lay == 'ROSETTE', "max ring %d" % max(r))

    # counts are exactly predictable
    p, _, _ = build_polys('FIGURE', 6, 6, 5, 'SPIDRON', 'OUT', 1, 1)
    chk("full figure = 2*m per ring", len(p) == 2 * 6 * 5, "%d" % len(p))
    p, _, _ = build_polys('ARM', 8, 6, 7, 'SPIDRON', 'OUT', 1, 1)
    chk("arm = 2 per ring", len(p) == 2 * 7, "%d" % len(p))
    p, _, _ = build_polys('ROSETTE', 6, 5, 4, 'SPIDRON', 'BOTH', 1, 1)
    chk("BOTH winding doubles the rosette", len(p) == 2 * 5 * 2 * 4,
        "%d" % len(p))
    p, _, _ = build_polys('TILING', 6, 6, 3, 'SPIDRON', 'OUT', 3, 2)
    chk("tiling repeats the rosette", len(p) == 6 * (6 * 2 * 3),
        "%d" % len(p))

    print("spidron_rosette: geometry")
    for m in (5, 6, 8, 12):
        p, _, _ = build_polys('FIGURE', m, 6, 4, 'SPIDRON', 'OUT', 1, 1)
        chk("m=%2d every triangle has positive area" % m,
            all(abs(_poly_area(q)) > 1e-12 for q in p))
    p, _, _ = build_polys('FIGURE', 6, 6, 8, 'SPIDRON', 'OUT', 1, 1)
    tot = sum(abs(_poly_area(q)) for q in p)
    R = 1.0
    outer = 0.5 * 6 * R * R * sin(2 * pi / 6)
    inner_R = R * sm.arm_ratio(6) ** 8
    inner = 0.5 * 6 * inner_R * inner_R * sin(2 * pi / 6)
    chk("figure tiles the polygon minus its core",
        abs(tot - (outer - inner)) < 1e-12, "%.2e" % abs(tot - (outer - inner)))

    for arm in sm.ARM_KINDS:
        p, _, _ = build_polys('ARM', 6, 6, 8, arm, 'OUT', 1, 1)
        chk("%-8s arm builds" % arm, len(p) == 16)
    a1, _, _ = build_polys('ARM', 6, 6, 6, 'SPIDRON', 'OUT', 1, 1)
    a2, _, _ = build_polys('ARM', 6, 6, 6, 'CREEPER', 'OUT', 1, 1)
    chk("arms are genuinely different figures",
        max(abs(np.array(a1[6]) - np.array(a2[6])).max(), 0.0) > 1e-6)

    print("RESULT:", "OK" if ok else "BAD")
    return ok
