# Spidron Rosette -- planar spidron figures and tilings.
#
# The two-dimensional half of the spidron family: the nested-polygon
# subdivision itself, single spiralling arms, rosettes assembled from
# several arms, and plane tilings of the result.  The three-dimensional
# halves are `spidron_nest_generator` (the folded relief) and
# `spidron_ball_generator` (spidronised polyhedra); all three share
# `spidron_math`.
#
# WHAT IS DRAWN.  Take a regular m-gon and connect alternate vertices; a
# smaller m-gon appears inside, scaled by cos(ag)/cos(ag/2) and turned
# by ag/2, where ag = 360/m.  The annulus between the two triangulates
# into 2m triangles, and repeating the step fills the m-gon with a
# spiral of ever-smaller triangles.  At m = 6 the two triangles per step
# are exactly the 120-degree isosceles and the equilateral triangle of
# Erdely's original spidron, and the ratio is 1/sqrt(3).
#
# A single limb of that figure is a "semi-spidron", or arm.  Following
# Gangopadhyay, the arm comes in three flavours that differ only in how
# fast the limb's index advances from ring to ring -- fixed (spidron),
# every ring (creeper), every second ring (ladder, whose index step
# therefore spans four triangles and squares the scale ratio).  The
# full figure is exactly m such arms interleaved, and every triangle
# knows which arm it belongs to, so the arms can be coloured
# individually -- which is how the papers draw every one of these
# figures, and this operator's default colouring.
#
# The ROSETTE carries n arms round a regular n-gon, one per edge with
# the arm's base edge dropped onto the polygon edge, spiralling on the
# outside -- Gangopadhyay's "polygonal designs inscribing a regular
# n-gon".  The polygon's side equals the arm's base edge, so Corners
# and Arm Parts stay independent.  Winding OUT and IN are the papers'
# clockwise and anticlockwise designs (the same arms mirrored edge for
# edge) and BOTH superimposes the two.  The TILING repeats a motif over
# the plane.  The WREATH motif repeats the rosette on a rectangular
# lattice whose pitch is the rosette's own bounding box, so
# neighbouring rosettes pack edge to edge without overlapping (open
# background shows between the wreaths).  The FIGURE motif repeats the
# filled polygon itself; at six arm parts -- where the polygon is the
# hexagon -- it sits on the proper honeycomb lattice (neighbour centres
# one double-apothem apart, along the edge normals), so adjacent
# hexagons share their edges exactly and the spiral arms cover the
# plane with no background at all: the classic spidron plane tiling.
# No other arm count tiles the plane, so those fall back to a spaced
# rectangular grid.
#
# Output goes through the shared Pattern Engine, so grout margin, relief
# height, per-tile materials and separate-tile output all come for free.
#
# References:
# - Daniel Erdely, "Some Surprising New Properties of the Spidrons",
#   Bridges 2005 Conference Proceedings, pp. 179-186 -- the figure and
#   its hexagonal nest.
# - T. Gangopadhyay, "On an Alternate Construction Method for
#   Generating Spidrons and New Tiling Patterns Generated by them",
#   International Journal of Computer Applications 160(3), 2017,
#   pp. 25-29 -- m-part arms assembled into a regular polygon, and the
#   tilings drawn from them.
# - T. Gangopadhyay, "On New Polygonal Designs Constructed using
#   Spidrons and New Tiling Patterns Generated by Them", International
#   Journal of Computer Applications 162(1), 2017, pp. 11-15 -- the
#   clockwise, anti-clockwise and superimposed rosettes.
# - T. Gangopadhyay, "On Subdividing Regular Polygons using Structures
#   other than Spidrons and Tiling Patterns Generated by Them",
#   International Journal of Computer Applications 163(2), 2017,
#   pp. 9-12 -- the "ladder" variant.
# - T. Gangopadhyay, "On further Subdivisions of Regular Polygons using
#   Structures other than Spidrons and Tiling Patterns Generated by
#   them", International Journal of Computer Applications 165(1), 2017,
#   pp. 31-34 -- the "creeper" variant.
# - Mihaly Hujter, "A csillaghatszog spidronszeru felgyurodese mogotti
#   matematika", Haladvany Kiadvany, 16 June 2018 -- the kite
#   similarity that fixes the 1/sqrt(3) scale and 30-degree turn.

bl_info = {
    "name": "Spidron Rosette",
    "author": "Math Art project",
    "version": (1, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Math Art > Patterns",
    "description": "Spidron figures: nested-polygon triangle spirals, "
                   "single arms, rosettes and plane tilings",
    "category": "Add Mesh",
}

from math import cos, sin, pi, sqrt, hypot, radians

import numpy as np

try:
    from .patterns import common as pc
    from . import tiling_generator as tg
    from . import spidron_math as sm
    from . import spidron_nests as sn
except Exception:                       # legacy single-file / CLI use
    from patterns import common as pc
    import tiling_generator as tg
    import spidron_math as sm
    import spidron_nests as sn


LAYOUT_ITEMS = [
    ('NEST', "Named Nest",
     "One of the 34 nests catalogued for spidronised space-fillers. "
     "A nest is a spidronised polygon; only seven of them are flat, "
     "so most are SKEW and cannot be drawn as a planar rosette"),
    ('FIGURE', "Full Figure",
     "The whole polygon subdivision: the starting polygon filled by "
     "its arms, every triangle of every ring"),
    ('ARM', "Single Arm",
     "One spiralling limb on its own, so the arm's shape is visible"),
    ('ROSETTE', "Rosette",
     "A wreath: one arm on each edge of a regular polygon, "
     "spiralling outward round an open centre"),
    ('TILING', "Tiling",
     "Rosettes repeated on a lattice, packed edge to edge to cover "
     "a patch of the plane"),
]

ARM_ITEMS = [
    ('SPIDRON', "Spidron",
     "The classical limb: the arm keeps the same position in every "
     "ring and spirals straight inward"),
    ('CREEPER', "Creeper",
     "The arm advances one position per ring, so it winds round the "
     "figure as it shrinks"),
    ('LADDER', "Ladder",
     "The arm advances one position every second ring, so each step "
     "spans four triangles and squares the scale ratio"),
]

WINDING_ITEMS = [
    ('OUT', "Clockwise",
     "Arms wound clockwise round the polygon -- the papers' first "
     "symmetric design"),
    ('IN', "Anticlockwise",
     "The mirrored winding: each arm reflected on its own edge -- the "
     "papers' second symmetric design"),
    ('BOTH', "Both", "Both windings superimposed -- the richest figure, "
                     "and the one the tiling papers use"),
]


def _ccw(tri):
    """The triangle with positive signed area, so every emitted face
    points up regardless of any mirroring in the assembly."""
    (x0, y0), (x1, y1), (x2, y2) = tri
    a = (x1 - x0) * (y2 - y0) - (x2 - x0) * (y1 - y0)
    return list(tri) if a >= 0.0 else [tri[0], tri[2], tri[1]]


def arm_materials(arm_ix, npal, colors=None):
    """Material index per triangle for colour-by-arm.

    Cycles the palette -- capped to the first `colors` entries when
    given, e.g. 2 for Kaplan's two-tone pinwheel -- over the arms in
    order.  When the arm count is one more than a multiple of the
    cycle, the cycle is shortened by one so the last arm never matches
    the first: neighbouring arms always read as different colours.
    The one case where that guarantee is impossible is a two-colour
    cycle round an ODD number of arms (an odd cycle is not
    2-colourable), so there the shortening is skipped and exactly one
    adjacent pair matches."""
    ids = sorted(set(arm_ix))
    if not ids:
        return []
    per = max(2, min(npal, colors if colors else npal))
    if len(ids) > 1 and (len(ids) - 1) % per == 0 and per > 2:
        per -= 1
    rank = {a: i for i, a in enumerate(ids)}
    return [rank[a] % per for a in arm_ix]


def build_polys(layout, m, n, rings, arm, winding, tiles_x, tiles_y,
                motif='WREATH'):
    """Return (polys, kinds, ring_ix, arm_ix) in the plane for the
    chosen layout: triangle vertex lists (counterclockwise), the 0/1
    triangle shape, the ring each triangle belongs to, and the arm it
    is part of.  Ring and arm are carried for every layout, so
    colour-by-ring and colour-by-arm work everywhere -- the full
    figure is assembled from its m arms rather than ring by ring
    precisely so that arm identity survives.

    `motif` applies to TILING only: WREATH repeats the rosette on a
    bounding-box grid; FIGURE repeats the filled polygon, and at m = 6
    places the hexagons on the honeycomb lattice so neighbours share
    their edges exactly and the plane is covered with no gaps."""
    if layout == 'FIGURE':
        polys, kinds, rix, aix = [], [], [], []
        for j in range(m):
            for i, (t, k) in enumerate(sm.arm_polys(m, rings, arm, j)):
                polys.append(_ccw(t))
                kinds.append(k)
                rix.append(i // 2)
                aix.append(j)
        return polys, kinds, rix, aix
    if layout == 'ARM':
        tris = sm.arm_polys(m, rings, arm, 0)
        return ([_ccw(t) for t, _ in tris], [k for _, k in tris],
                [i // 2 for i in range(len(tris))], [0] * len(tris))
    if layout == 'ROSETTE':
        polys, kinds, rix, aix = sm.rosette_polys(m, n, rings, arm,
                                                  winding)
        return [_ccw(p) for p in polys], kinds, rix, aix

    base_layout = 'FIGURE' if motif == 'FIGURE' else 'ROSETTE'
    polys, kinds, rix, aix = build_polys(base_layout, m, n, rings, arm,
                                         winding, 1, 1)
    offsets = []
    if motif == 'FIGURE' and m == 6:
        # THE CLASSIC SPIDRON TILING.  The filled hexagon (circumradius
        # 1, a vertex at angle 0) tiles the plane on the honeycomb
        # lattice: neighbouring centres one double-apothem apart
        # (2 cos(pi/6) = sqrt 3), along the edge-normal directions 30,
        # 90 and 150 degrees.  The patch walks that lattice in offset
        # columns -- column pitch 3R/2, row pitch sqrt(3) R, odd
        # columns raised half a row -- so a Columns x Rows patch reads
        # as a roughly rectangular block.  On this lattice the
        # hexagons' corner vertices coincide EXACTLY (verified in
        # `_selftest`), so adjacent tiles share whole edges and the
        # spiral arms cover the plane with no background showing.
        pitch = 2.0 * cos(pi / 6.0)
        for iy in range(tiles_y):
            for ix in range(tiles_x):
                offsets.append((1.5 * (ix - 0.5 * (tiles_x - 1)),
                                pitch * (iy - 0.5 * (tiles_y - 1))
                                + 0.5 * pitch * (ix % 2)))
    else:
        # lattice pitch: the motif's own bounding box, so copies pack
        # edge to edge -- touching where the motif reaches its box,
        # never overlapping.  (An m-gon with m != 6 cannot tile the
        # plane, so the FIGURE motif also lands here: an honest spaced
        # grid rather than a fake tiling.)
        xs = [x for p in polys for (x, _) in p]
        ys = [y for p in polys for (_, y) in p]
        sx, sy = max(xs) - min(xs), max(ys) - min(ys)
        for iy in range(tiles_y):
            for ix in range(tiles_x):
                offsets.append(((ix - 0.5 * (tiles_x - 1)) * sx,
                                (iy - 0.5 * (tiles_y - 1)) * sy))
    out_p, out_k, out_r, out_a = [], [], [], []
    for (dx, dy) in offsets:
        for p, k, r, a in zip(polys, kinds, rix, aix):
            out_p.append([(x + dx, y + dy) for (x, y) in p])
            out_k.append(k)
            out_r.append(r)
            out_a.append(a)
    return out_p, out_k, out_r, out_a


try:
    import bpy
    from bpy.props import (IntProperty, FloatProperty, EnumProperty,
                           BoolProperty)
    from bpy_extras.object_utils import AddObjectHelper
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    class MESH_OT_spidron_rosette_add(bpy.types.Operator, AddObjectHelper):
        """Add a spidron figure: a spiral of triangles filling a
        regular polygon, as a single arm, a rosette or a tiling"""
        bl_idname = "mesh.spidron_rosette_add"
        bl_label = "Spidron Rosette"
        bl_options = {'REGISTER', 'UNDO'}

        layout_kind: EnumProperty(
            name="Layout", items=LAYOUT_ITEMS, default='FIGURE',
            description="What to build: the whole polygon subdivision, "
                        "one arm, a rosette of arms, or a tiling")
        nest: EnumProperty(
            name="Nest",
            items=lambda self, ctx: [
                (c, "%s  (%d-gon, %s)" % (c, sn.NESTS[c][0],
                                          sn.NESTS[c][1]),
                 "Angles: %s" % ", ".join(
                     "%g" % a for a in sn.NESTS[c][3]))
                for c in sn.verified_codes()],
            default=13,
            description="Which catalogued nest to build")
        nest_step: FloatProperty(
            name="Nest step", default=0.5774, min=0.05, max=0.95,
            description="Shrink factor between successive annuli. The "
                        "hexagonal nest's own value is 1/sqrt(3)")
        nest_twist: FloatProperty(
            name="Nest twist", default=radians(30.0),
            min=radians(-90.0), max=radians(90.0), subtype='ANGLE',
            description="Rotation between annuli. The hexagonal nest's "
                        "own value is 30 degrees")
        cap_center: BoolProperty(
            name="Cap centre", default=False,
            description="Close the small polygon left at the centre")
        arm: EnumProperty(
            name="Arm", items=ARM_ITEMS, default='SPIDRON',
            description="Which limb of the spidron family to draw. In "
                        "the Full Figure the geometry is the same for "
                        "all three; what changes is how the triangles "
                        "group into arms, which colour-by-arm shows")
        arm_parts: IntProperty(
            name="Arm Parts", default=6, min=5, max=24,
            description="Sides of the polygon the arm subdivides; the "
                        "arm angle is 360 divided by this. Five is the "
                        "smallest that gives a shrinking spiral, six is "
                        "the classical hexagonal spidron")
        corners: IntProperty(
            name="Corners", default=6, min=3, max=24,
            description="How many arms are placed round the rosette. "
                        "Independent of Arm Parts")
        rings: IntProperty(
            name="Rings", default=10, min=1, max=24,
            description="How many times the spiral step repeats. Each "
                        "ring is smaller than the last, so beyond about "
                        "sixteen the additions are invisible")
        winding: EnumProperty(
            name="Winding", items=WINDING_ITEMS, default='OUT',
            description="Sense in which the arms are wound round the "
                        "rosette")
        motif: EnumProperty(
            name="Motif", default='WREATH',
            items=[('WREATH', "Wreath",
                    "Repeat the open-centred rosette on a bounding-box "
                    "grid; background shows between the wreaths"),
                   ('FIGURE', "Figure",
                    "Repeat the filled polygon. With six arm parts the "
                    "hexagons sit on the honeycomb lattice and share "
                    "their edges exactly, covering the plane with no "
                    "gaps -- the classic spidron tiling. No other arm "
                    "count tiles, so those get a spaced grid instead")],
            description="What the tiling repeats")
        tiles_x: IntProperty(
            name="Columns", default=3, min=1, max=12,
            description="Motifs across the tiling")
        tiles_y: IntProperty(
            name="Rows", default=3, min=1, max=12,
            description="Motifs down the tiling")
        color_by: EnumProperty(
            name="Color", default='ARM',
            items=[('ARM', "Arm",
                    "One material per spiralling arm, neighbouring "
                    "arms different -- the colouring the papers use, "
                    "and the one that makes the arms visible"),
                   ('SHAPE', "Triangle Shape",
                    "One material per triangle shape, so the two "
                    "shapes of each ring read differently"),
                   ('RING', "Ring", "One material per ring, showing "
                                    "the spiral banding"),
                   ('UNIFORM', "Uniform", "A single material")],
            description="How materials are assigned")
        colors: IntProperty(
            name="Colors", default=12, min=2, max=12,
            description="How many materials the palette is cut down to "
                        "for the arm colouring. Two gives the classic "
                        "two-tone pinwheel; with an odd number of arms "
                        "two colours cannot alternate all the way "
                        "round, so one pair of neighbouring arms will "
                        "match")
        margin: FloatProperty(
            name="Margin", default=0.0, min=0.0, max=0.4,
            description="Inset each triangle by this fraction, leaving "
                        "a grout gap between tiles")
        height: FloatProperty(
            name="Height", default=0.0, min=0.0, max=2.0,
            description="Extrude each triangle to this depth; zero "
                        "leaves a flat pattern")
        separate: BoolProperty(
            name="Separate Tiles", default=False,
            description="Build one object per triangle under a parent "
                        "empty instead of a single merged mesh")

        def _execute_nest(self, context):
            """One catalogued nest: its boundary, spidronised.

            Most nests are SKEW, so this is not a planar rosette -- the
            boundary comes from `spidron_nests`, which reconstructs it
            from the published angle sequence as a circuit of Universal
            Node branches."""
            code = self.nest
            pts = sn.oriented(code)
            if pts is None:
                self.report({'ERROR'}, "cannot construct nest %s" % code)
                return {'CANCELLED'}
            loop = np.asarray(pts, float)
            verts, faces, mats = sm.spidronise(
                loop, float(self.nest_step), float(self.nest_twist),
                int(self.rings), cap=self.cap_center)
            # spidronise emits (annulus, corner, two triangles) in that
            # order, so ring and arm indices come straight from the
            # triangle index -- the same colourings the Full Figure
            # offers, on the same footing.
            m = len(loop)
            per_ring = 2 * m
            npal = len(pc.PALETTE_RGBA)
            ring_of, arm_of = [], []
            for t in range(len(faces)):
                if mats[t] == 2:                 # centre cap
                    ring_of.append(int(self.rings))
                    arm_of.append(t % m)
                else:
                    ring_of.append(t // per_ring)
                    arm_of.append((t % per_ring) // 2)
            if self.color_by == 'ARM':
                ncol = max(2, min(int(self.colors), npal))
                mats = [arm_of[t] % ncol for t in range(len(faces))]
            elif self.color_by == 'RING':
                mats = [ring_of[t] % npal for t in range(len(faces))]
            elif self.color_by == 'UNIFORM':
                mats = [0] * len(faces)
            # SHAPE keeps spidronise's own 0/1/2 labelling
            obj = pc.build_object(context, "Spidron Nest %s" % code,
                                  [tuple(v) for v in verts],
                                  [tuple(f) for f in faces], list(mats),
                                  span=2.0, fit=True)
            if obj is None:
                self.report({'ERROR'}, "no geometry generated")
                return {'CANCELLED'}
            n, group, sym, angles = sn.NESTS[code]
            self.report({'INFO'},
                        "Nest %s: %d-gon, %s, %s, %d rings%s"
                        % (code, n, group, sym, int(self.rings),
                           "" if group == 'flat' else " (skew)"))
            return {'FINISHED'}

        def execute(self, context):
            if self.layout_kind == 'NEST':
                return self._execute_nest(context)
            m, n = int(self.arm_parts), int(self.corners)
            polys, kinds, rix, aix = build_polys(
                self.layout_kind, m, n, int(self.rings), self.arm,
                self.winding, int(self.tiles_x), int(self.tiles_y),
                self.motif)
            if not polys:
                self.report({'ERROR'}, "no triangles generated")
                return {'CANCELLED'}
            if (self.layout_kind == 'TILING' and self.motif == 'FIGURE'
                    and m != 6):
                self.report({'WARNING'},
                            "only six arm parts tile the plane without "
                            "gaps; built a spaced grid")
            npal = len(pc.PALETTE_RGBA)
            if self.color_by == 'ARM':
                types = arm_materials(aix, npal, int(self.colors))
                cby = 'TYPE'
            elif self.color_by == 'RING':
                types = [r % npal for r in rix]
                cby = 'TYPE'
            elif self.color_by == 'SHAPE':
                types = [k % 2 for k in kinds]
                cby = 'TYPE'
            else:
                types = [0] * len(polys)
                cby = 'UNIFORM'
            cells = tg.cells_from_polys(
                lambda a, b: (polys, types), 1, 1, cby,
                self.margin, self.height, False)
            if (self.winding == 'BOTH' and self.height <= 0.0
                    and self.layout_kind in ('ROSETTE', 'TILING')
                    and not (self.layout_kind == 'TILING'
                             and self.motif == 'FIGURE')):
                # the superimposed design lays the two windings in one
                # plane; a hair of separation keeps the flat faces from
                # z-fighting where they overlap (relief height already
                # separates them when it is nonzero)
                lift = 0.003
                for ci, a in enumerate(aix):
                    if a >= n:
                        cv, cf, cm = cells[ci]
                        cells[ci] = ([(x, y, z + lift)
                                      for (x, y, z) in cv], cf, cm)
            obj = pc.emit(context, "Spidron Rosette", cells,
                          self.separate, fit=True, operator=self)
            if obj is None:
                self.report({'ERROR'}, "no geometry generated")
                return {'CANCELLED'}
            obj["math_art_pattern"] = True
            self.report({'INFO'}, "%s  m=%d  %d arms  %d triangles"
                        % (self.layout_kind.title(), m,
                           len(set(aix)), len(polys)))
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            lay.prop(self, 'layout_kind')
            if self.layout_kind == 'NEST':
                lay.prop(self, 'nest')
                lay.prop(self, 'rings')
                lay.prop(self, 'nest_step')
                lay.prop(self, 'nest_twist')
                lay.prop(self, 'cap_center')
                lay.prop(self, 'color_by')
                if self.color_by == 'ARM':
                    lay.prop(self, 'colors')
                return
            lay.prop(self, 'arm_parts')
            # the arm kind matters in EVERY layout: in the full figure
            # it decides how the triangles group into arms, which is
            # what colour-by-arm shows
            lay.prop(self, 'arm')
            wreathy = (self.layout_kind == 'ROSETTE'
                       or (self.layout_kind == 'TILING'
                           and self.motif == 'WREATH'))
            if self.layout_kind == 'TILING':
                lay.prop(self, 'motif')
            if wreathy:
                lay.prop(self, 'corners')
                lay.prop(self, 'winding')
            lay.prop(self, 'rings')
            if self.layout_kind == 'TILING':
                lay.prop(self, 'tiles_x')
                lay.prop(self, 'tiles_y')
            lay.prop(self, 'color_by')
            if self.color_by == 'ARM':
                lay.prop(self, 'colors')
            for p in ('margin', 'height'):
                lay.prop(self, p)
            lay.prop(self, 'separate')
            lay.prop(self, 'align')

    def _menu_func(self, context):
        self.layout.operator("mesh.spidron_rosette_add",
                             icon='FORCE_VORTEX')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(MESH_OT_spidron_rosette_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.remove(_menu_func)
        bpy.utils.unregister_class(MESH_OT_spidron_rosette_add)


# --------------------------------------------------------------------
# Self-test
# --------------------------------------------------------------------

def _poly_area(p):
    a = 0.0
    for i in range(len(p)):
        x0, y0 = p[i]
        x1, y1 = p[(i + 1) % len(p)]
        a += x0 * y1 - x1 * y0
    return 0.5 * a


def _tri_key(t, nd=9):
    return tuple(sorted((round(x, nd), round(y, nd)) for (x, y) in t))


def _selftest():
    ok = True

    def chk(name, cond, extra=""):
        nonlocal ok
        ok = ok and bool(cond)
        print("  %-52s %s %s" % (name, "OK" if cond else "BAD", extra))

    print("spidron_rosette: layouts")
    for lay in ('FIGURE', 'ARM', 'ROSETTE', 'TILING'):
        p, k, r, a = build_polys(lay, 6, 6, 6, 'SPIDRON', 'OUT', 2, 2)
        chk("%-8s builds triangles" % lay,
            len(p) > 0 and all(len(q) == 3 for q in p),
            "%d tris" % len(p))
        chk("%-8s labels align with polys" % lay,
            len(p) == len(k) == len(r) == len(a))
        chk("%-8s ring index spans the rings" % lay,
            max(r) + 1 == 6, "max ring %d" % max(r))
        chk("%-8s every triangle is counterclockwise" % lay,
            all(_poly_area(q) > 1e-12 for q in p))

    # counts are exactly predictable
    p, _, _, a = build_polys('FIGURE', 6, 6, 5, 'SPIDRON', 'OUT', 1, 1)
    chk("full figure = 2*m per ring", len(p) == 2 * 6 * 5, "%d" % len(p))
    chk("full figure carries m arms of 2 tris per ring",
        sorted(set(a)) == list(range(6))
        and all(a.count(j) == 2 * 5 for j in range(6)))
    p, _, _, a = build_polys('ARM', 8, 6, 7, 'SPIDRON', 'OUT', 1, 1)
    chk("arm = 2 per ring, one arm", len(p) == 2 * 7 and set(a) == {0},
        "%d" % len(p))
    p, _, _, a = build_polys('ROSETTE', 6, 5, 4, 'SPIDRON', 'BOTH', 1, 1)
    chk("BOTH winding doubles the rosette", len(p) == 2 * 5 * 2 * 4,
        "%d" % len(p))
    chk("BOTH carries 2n distinct arms", sorted(set(a)) == list(range(10)))
    p, _, _, a = build_polys('TILING', 6, 6, 3, 'SPIDRON', 'OUT', 3, 2)
    chk("tiling repeats the rosette", len(p) == 6 * (6 * 2 * 3),
        "%d" % len(p))

    print("spidron_rosette: the figure is its arms")
    # the full figure assembled arm by arm must be EXACTLY the nested-
    # polygon subdivision, whichever arm kind does the grouping -- the
    # three kinds are three ways of cutting one figure into m limbs.
    for m in (5, 6, 9):
        ref, _ = sm.full_figure_polys(m, 6)
        want = sorted(_tri_key(t) for t in ref)
        for arm in sm.ARM_KINDS:
            p, _, _, a = build_polys('FIGURE', m, 6, 6, arm, 'OUT', 1, 1)
            got = sorted(_tri_key(t) for t in p)
            chk("m=%d %-8s arms partition the figure" % (m, arm),
                got == want and len(set(a)) == m)

    print("spidron_rosette: geometry")
    for m in (5, 6, 8, 12):
        p, _, _, _ = build_polys('FIGURE', m, 6, 4, 'SPIDRON', 'OUT', 1, 1)
        chk("m=%2d every triangle has positive area" % m,
            all(_poly_area(q) > 1e-12 for q in p))
    p, _, _, _ = build_polys('FIGURE', 6, 6, 8, 'SPIDRON', 'OUT', 1, 1)
    tot = sum(abs(_poly_area(q)) for q in p)
    R = 1.0
    outer = 0.5 * 6 * R * R * sin(2 * pi / 6)
    inner_R = R * sm.arm_ratio(6) ** 8
    inner = 0.5 * 6 * inner_R * inner_R * sin(2 * pi / 6)
    chk("figure tiles the polygon minus its core",
        abs(tot - (outer - inner)) < 1e-12, "%.2e" % abs(tot - (outer - inner)))

    for arm in sm.ARM_KINDS:
        p, _, _, _ = build_polys('ARM', 6, 6, 8, arm, 'OUT', 1, 1)
        chk("%-8s arm builds" % arm, len(p) == 16)
        linked = all(
            len(set(_tri_key(p[i])) & set(_tri_key(p[i + 1]))) >= 1
            for i in range(len(p) - 1))
        chk("%-8s arm is a linked chain" % arm, linked)
    a1, _, _, _ = build_polys('ARM', 6, 6, 6, 'SPIDRON', 'OUT', 1, 1)
    a2, _, _, _ = build_polys('ARM', 6, 6, 6, 'CREEPER', 'OUT', 1, 1)
    chk("arms are genuinely different figures",
        max(abs(np.array(a1[6]) - np.array(a2[6])).max(), 0.0) > 1e-6)

    # the papers' scale laws: an index step of the spidron/creeper is
    # one ring pair scaled by cos(ag)/cos(ag/2); the ladder's unit
    # spans two rings and four triangles and SQUARES that ratio.
    def perim(t):
        return sum(hypot(t[i][0] - t[(i + 1) % 3][0],
                         t[i][1] - t[(i + 1) % 3][1]) for i in range(3))

    for arm, stride, want in (('SPIDRON', 2, sm.arm_ratio(8)),
                              ('CREEPER', 2, sm.arm_ratio(8)),
                              ('LADDER', 4, sm.arm_ratio(8) ** 2)):
        p, _, _, _ = build_polys('ARM', 8, 6, 8, arm, 'OUT', 1, 1)
        r = perim(p[stride]) / perim(p[0])
        chk("%-8s unit scales by ratio%s" % (arm,
            "^2" if stride == 4 else "  "),
            abs(r - want) < 1e-12, "%.9f" % r)

    print("spidron_rosette: the rosette is a wreath")
    for (m, n) in ((6, 6), (6, 8), (8, 5)):
        V = sm.rosette_ngon(m, n)
        p, _, _, a = build_polys('ROSETTE', m, n, 5, 'SPIDRON', 'OUT',
                                 1, 1)
        L = 2.0 * sin(pi / m)
        side = np.linalg.norm(np.array(V[1]) - np.array(V[0]))
        chk("m=%d n=%d polygon side = arm base edge" % (m, n),
            abs(side - L) < 1e-12)
        # each arm sits on its own polygon edge, entirely outside it
        good_base = good_out = True
        for j in range(n):
            tris = [t for t, ai in zip(p, a) if ai == j]
            Vj, Vj1 = np.array(V[j]), np.array(V[(j + 1) % n])
            ex = (Vj1 - Vj) / side
            nout = np.array([ex[1], -ex[0]])
            base = {tuple(np.round(v, 9)) for v in (Vj, Vj1)}
            first = {tuple(np.round(v, 9)) for v in tris[0][:2]}
            good_base = good_base and first == base
            for t in tris:
                for v in t:
                    if float((np.array(v) - Vj) @ nout) < -1e-9:
                        good_out = False
        chk("m=%d n=%d arms sit on the polygon edges" % (m, n), good_base)
        chk("m=%d n=%d arms stay outside the polygon" % (m, n), good_out)
    # IN is OUT mirrored edge for edge
    po, _, _, ao = build_polys('ROSETTE', 6, 6, 5, 'SPIDRON', 'OUT', 1, 1)
    pb, _, _, ab = build_polys('ROSETTE', 6, 6, 5, 'SPIDRON', 'BOTH', 1, 1)
    V = np.array(sm.rosette_ngon(6, 6))
    j = 0
    Vj, Vj1 = V[j], V[(j + 1) % 6]
    mid = 0.5 * (Vj + Vj1)
    ax = (Vj1 - Vj) / np.linalg.norm(Vj1 - Vj)   # reflection axis normal
    out_j = [t for t, ai in zip(pb, ab) if ai == j]
    in_j = [t for t, ai in zip(pb, ab) if ai == 6 + j]
    mirror_ok = len(out_j) == len(in_j) > 0
    for to, ti in zip(out_j, in_j):
        ref = set()
        for vo in to:
            q = np.array(vo) - mid
            q = q - 2.0 * float(q @ ax) * ax
            ref.add(tuple(np.round(q + mid, 9)))
        got = {tuple(np.round(v, 9)) for v in ti}
        mirror_ok = mirror_ok and ref == got
    chk("IN arm = OUT arm reflected on its edge", mirror_ok)
    chk("OUT alone matches the OUT half of BOTH",
        all(_tri_key(a_) == _tri_key(b_) for a_, b_ in
            zip(po, [t for t, ai in zip(pb, ab) if ai < 6])))

    print("spidron_rosette: tiling and colouring")
    p1, _, _, _ = build_polys('ROSETTE', 6, 6, 4, 'SPIDRON', 'OUT', 1, 1)
    xs = [x for q in p1 for (x, _) in q]
    ys = [y for q in p1 for (_, y) in q]
    w, h = max(xs) - min(xs), max(ys) - min(ys)
    pt, _, _, _ = build_polys('TILING', 6, 6, 4, 'SPIDRON', 'OUT', 3, 2)
    xs2 = [x for q in pt for (x, _) in q]
    ys2 = [y for q in pt for (_, y) in q]
    chk("tiling pitch is the rosette's bounding box",
        abs((max(xs2) - min(xs2)) - 3 * w) < 1e-9
        and abs((max(ys2) - min(ys2)) - 2 * h) < 1e-9)
    per = len(p1)
    minx, miny = min(xs2), min(ys2)
    overlap = False
    for ti in range(6):
        iy, ix = divmod(ti, 3)
        for q in pt[ti * per:(ti + 1) * per]:
            for (x, y) in q:
                if not (ix * w - 1e-9 <= x - minx <= (ix + 1) * w + 1e-9
                        and iy * h - 1e-9 <= y - miny
                        <= (iy + 1) * h + 1e-9):
                    overlap = True
    chk("each tile stays in its own lattice cell", not overlap)

    npal = len(pc.PALETTE_RGBA)
    for count in (2, 6, npal, npal + 1, 2 * npal, 2 * npal + 1):
        mats = arm_materials(list(range(count)), npal)
        ring_ok = all(mats[i] != mats[(i + 1) % count]
                      for i in range(count)) or count == 1
        chk("colour-by-arm: %2d arms, neighbours differ" % count,
            ring_ok and max(mats) < npal)
    _, _, _, a = build_polys('FIGURE', 13, 6, 3, 'SPIDRON', 'OUT', 1, 1)
    mats = arm_materials(a, npal)
    chk("13-arm figure: last arm avoids the first's colour",
        mats[0] != mats[-1] and len(set(mats)) <= npal)

    # the Colors cap: two-tone pinwheels, and honest odd-count seams
    for count in (4, 6, 8, 12):
        mats = arm_materials(list(range(count)), npal, 2)
        chk("two colours alternate round %2d arms" % count,
            max(mats) <= 1
            and all(mats[i] != mats[(i + 1) % count]
                    for i in range(count)))
    for count in (5, 7, 13):
        # an odd cycle is not 2-colourable: exactly ONE adjacent pair
        # may match, never more, and the cap must still hold
        mats = arm_materials(list(range(count)), npal, 2)
        seams = sum(mats[i] == mats[(i + 1) % count]
                    for i in range(count))
        chk("two colours round %2d arms leave one seam" % count,
            max(mats) <= 1 and seams == 1)
    for cap in (3, 5, 12):
        mats = arm_materials(list(range(12)), npal, cap)
        chk("colour cap %2d respected, neighbours differ" % cap,
            max(mats) < cap
            and all(mats[i] != mats[(i + 1) % 12] for i in range(12)))

    print("spidron_rosette: the figure motif tiles the plane")
    pf, kf, rf, af = build_polys('TILING', 6, 6, 4, 'SPIDRON', 'OUT',
                                 3, 3, motif='FIGURE')
    chk("figure tiling repeats the filled hexagon",
        len(pf) == 9 * 2 * 6 * 4, "%d tris" % len(pf))
    # neighbouring hexagons must share their corner vertices EXACTLY
    # (round to 1e-9): each tile's six ring-0 outer corners, matched
    # across every edge-adjacent pair of the honeycomb lattice.
    per = len(pf) // 9
    tile_corners = []
    for t in range(9):
        cs = set()
        for q, kk, rr in zip(pf[t * per:(t + 1) * per],
                             kf[t * per:(t + 1) * per],
                             rf[t * per:(t + 1) * per]):
            if rr == 0 and kk == 0:
                cs.add((round(q[0][0], 9), round(q[0][1], 9)))
                cs.add((round(q[1][0], 9), round(q[1][1], 9)))
        tile_corners.append(cs)
    chk("each figure tile has six outer corners",
        all(len(c) == 6 for c in tile_corners))
    # lattice coordinates of the offset-column walk: tile (ix, iy) sits
    # at ix * u + (iy - ix//2) * v with u = (3R/2, sqrt3 R/2) and
    # v = (0, sqrt3 R); edge-adjacency is a unit lattice step
    idx = {(ix, iy - ix // 2): iy * 3 + ix
           for iy in range(3) for ix in range(3)}
    share_ok, npairs = True, 0
    for (i, j), t in idx.items():
        for (di, dj) in ((1, 0), (0, 1), (1, -1)):
            t2 = idx.get((i + di, j + dj))
            if t2 is None:
                continue
            npairs += 1
            if len(tile_corners[t] & tile_corners[t2]) != 2:
                share_ok = False
    chk("neighbouring hexagons share an edge exactly",
        share_ok and npairs == 16, "%d adjacent pairs" % npairs)
    # gapless coverage: sample a disk spanning the central tile and its
    # crossings into all six neighbours; every point must be covered by
    # EXACTLY one triangle.  (The open spiral cores are excluded: any
    # finite ring count leaves a hexagonal core of radius ratio^rings,
    # which is the construction, not a gap.)
    pf6, _k6, _r6, _a6 = build_polys('TILING', 6, 6, 6, 'SPIDRON',
                                     'OUT', 3, 3, motif='FIGURE')
    pitch = 2.0 * cos(pi / 6.0)
    centres = [(1.5 * (ix - 1.0),
                pitch * (iy - 1.0) + 0.5 * pitch * (ix % 2))
               for iy in range(3) for ix in range(3)]
    ccx, ccy = centres[4]                    # the central tile
    core = sm.arm_ratio(6) ** 6
    boxes = []
    for q in pf6:
        xs = [x for (x, _) in q]
        ys = [y for (_, y) in q]
        boxes.append((q, min(xs), max(xs), min(ys), max(ys)))
    tested = bad = 0
    for ixp in range(41):
        for iyp in range(41):
            x = ccx - 1.1 + 2.2 * ixp / 40.0 + 0.0137
            y = ccy - 1.1 + 2.2 * iyp / 40.0 + 0.0071
            if (x - ccx) ** 2 + (y - ccy) ** 2 > 1.1 * 1.1:
                continue
            if any((x - cx) ** 2 + (y - cy) ** 2 < (2.0 * core) ** 2
                   for cx, cy in centres):
                continue
            cnt = 0
            for q, x0, x1, y0, y1 in boxes:
                if x0 <= x <= x1 and y0 <= y <= y1 and tg._pip(q, x, y):
                    cnt += 1
            tested += 1
            if cnt != 1:
                bad += 1
    chk("figure tiling covers the plane, no gaps or overlaps",
        tested > 400 and bad == 0,
        "%d sampled, %d bad" % (tested, bad))
    # any other arm count cannot tile: the fallback still builds, as an
    # honest spaced grid of the m-gon figure
    p5, _, _, _ = build_polys('TILING', 5, 6, 3, 'SPIDRON', 'OUT', 2, 2,
                              motif='FIGURE')
    chk("figure motif falls back for m != 6",
        len(p5) == 4 * 2 * 5 * 3)

    print("RESULT:", "OK" if ok else "BAD")
    return ok
