
# Symmetric Sculpture designer for Blender
#
# After George W. Hart's sculpture design program described in
# "Symmetric sculpture", Journal of Mathematics and the Arts 1(1),
# 2007, pp. 21-28, doi:10.1080/17513470701228040 -- and its
# precursor, "Sculpture from Symmetrically Arranged Planar
# Components", Bridges 2003, pp. 315-322 (the tool behind Twisted
# Rivers, Tumbleweed, Frabjous, Spaghetti Code, ...).
#
# References:
#   G. W. Hart, "Symmetric sculpture", J. Mathematics and the Arts
#     1(1), 2007, 21-28.  doi:10.1080/17513470701228040
#   G. W. Hart, "Sculpture from Symmetrically Arranged Planar
#     Components", Bridges 2003, 315-322.
#   H. S. M. Coxeter, P. Du Val, H. T. Flather, J. F. Petrie, "The
#     Fifty-Nine Icosahedra", U. Toronto Press, 1938 -- the
#     stellation pattern drawn as the editing guides.
#
# A flat motif drawn in ONE representative
# plane is replicated live into a whole family of symmetrically
# arranged planes -- the extended face planes of an icosahedron,
# dodecahedron, rhombic triacontahedron or hexecontahedron (or their
# octahedral / tetrahedral analogues).
#
# The replication is done with a Geometry Nodes modifier: a motif
# placed in a plane perpendicular to a k-fold axis and instanced
# under all N rotations of the chosen point group automatically
# lands in N/k planes with k-fold symmetry inside each plane, which
# is exactly Hart's plane-family construction. Three objects are
# created:
#
#   SymSculpt         points + Geometry Nodes modifier (the result)
#   SymSculpt Motif   flat mesh on the world XY plane -- edit this
#                     (edit mode, or move/rotate the object) and every
#                     copy updates in real time; the node group maps
#                     it onto the representative plane
#   SymSculpt Guides  wireframe stellation pattern: the lines where
#                     the other planes of the family cut this one,
#                     for snapping/drawing against, as in Hart's 2D
#                     editor window
#
# The modifier's "Shell" input radially extrudes the surface away
# from the origin by that fraction of its distance (Hart's ~4%
# radial extrusion, which preserves planarity and yields a watertight
# solid for 3D printing); "Weld" merges coincident vertices where
# copies meet exactly on the plane-intersection lines; "Lift" raises
# the replicated sculpture up +Z so it no longer surrounds the Motif
# and Guides, which stay at the origin where they can be drawn on
# (only the modifier result moves -- the objects themselves stay put,
# so the sculpture keeps its true position for export); "Translucent"
# swaps the copies onto a ghost material so the motif reads through
# them, off by default.

bl_info = {
    "name": "Symmetric Sculpture",
    "author": "Math Art project (after George W. Hart)",
    "version": (1, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Mesh > Symmetric Sculpture",
    "description": "Replicate a flat motif into symmetric plane "
                   "families, live, after Hart's sculpture software",
    "category": "Add Mesh",
}

import math
from math import cos, sin, pi, sqrt

PHI = (1 + sqrt(5)) / 2


# ---------------------------------------------------------------- #
#  rotation groups by closure                                      #
# ---------------------------------------------------------------- #

def _rot(axis, ang):
    """3x3 rotation about axis by ang (Rodrigues)."""
    x, y, z = axis
    l = sqrt(x * x + y * y + z * z)
    x, y, z = x / l, y / l, z / l
    c, s = cos(ang), sin(ang)
    C = 1 - c
    return ((c + x * x * C, x * y * C - z * s, x * z * C + y * s),
            (y * x * C + z * s, c + y * y * C, y * z * C - x * s),
            (z * x * C - y * s, z * y * C + x * s, c + z * z * C))


def _mul(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3))
                       for j in range(3)) for i in range(3))


def _apply(A, v):
    return tuple(sum(A[i][k] * v[k] for k in range(3)) for i in range(3))


def _key(A):
    return tuple(round(A[i][j], 9) for i in range(3) for j in range(3))


_GENS = {
    'TETRA': (_rot((1, 1, 1), 2 * pi / 3), _rot((0, 0, 1), pi)),
    'OCTA': (_rot((0, 0, 1), pi / 2), _rot((1, 1, 1), 2 * pi / 3)),
    'ICOSA': (_rot((0, 1, PHI), 2 * pi / 5), _rot((1, 1, 1), 2 * pi / 3)),
}
_ORDER = {'TETRA': 12, 'OCTA': 24, 'ICOSA': 60}


def group_rotations(kind):
    """All rotations of the chiral tetrahedral / octahedral /
    icosahedral group, generated by closure."""
    gens = _GENS[kind]
    seen = {}
    I = ((1.0, 0, 0), (0, 1.0, 0), (0, 0, 1.0))
    frontier = [I]
    seen[_key(I)] = I
    while frontier:
        nxt = []
        for A in frontier:
            for G in gens:
                B = _mul(G, A)
                k = _key(B)
                if k not in seen:
                    seen[k] = B
                    nxt.append(B)
        frontier = nxt
    rots = list(seen.values())
    assert len(rots) == _ORDER[kind], (kind, len(rots))
    return rots


# plane-family axis per (group, family); the plane sits at distance
# d perpendicular to this axis.
_AXES = {
    ('ICOSA', 'P5'): (0.0, 1.0, PHI),      # 12 planes, 5-fold each
    ('ICOSA', 'P3'): (1.0, 1.0, 1.0),      # 20 planes, 3-fold
    ('ICOSA', 'P2'): (0.0, 0.0, 1.0),      # 30 planes, 2-fold
    # 60 planes, no in-plane symmetry; the axis is a snub
    # dodecahedron vertex direction, so these are the face
    # planes of the pentagonal hexecontahedron (Hart's Whimsy)
    ('ICOSA', 'P1'): (0.089963, -0.816073, -0.570904),
    ('OCTA', 'P4'): (0.0, 0.0, 1.0),       # 6 planes (cube), 4-fold
    ('OCTA', 'P3'): (1.0, 1.0, 1.0),       # 8 planes, 3-fold
    ('OCTA', 'P2'): (1.0, 1.0, 0.0),       # 12 planes, 2-fold
    ('OCTA', 'P1'): (0.21, 0.45, 1.0),     # 24 planes
    ('TETRA', 'P3'): (1.0, 1.0, 1.0),      # 4 planes, 3-fold
    ('TETRA', 'P2'): (0.0, 0.0, 1.0),      # 6 planes, 2-fold
    ('TETRA', 'P1'): (0.21, 0.45, 1.0),    # 12 planes
}


def _normalize(v):
    l = sqrt(sum(c * c for c in v))
    return tuple(c / l for c in v)


def plane_normals(kind, family):
    """Distinct unit normals of the plane family = orbit of the axis
    under the group. Returns (axis, normals)."""
    a = _normalize(_AXES[(kind, family)])
    seen = {}
    for R in group_rotations(kind):
        b = _apply(R, a)
        k = tuple(round(c, 6) for c in b)
        if k not in seen:
            seen[k] = b
    return a, list(seen.values())


def _frame(a):
    """Right-handed orthonormal (u, v, a)."""
    t = (0.0, 0.0, 1.0) if abs(a[2]) < 0.9 else (1.0, 0.0, 0.0)
    u = _normalize((t[1] * a[2] - t[2] * a[1],
                    t[2] * a[0] - t[0] * a[2],
                    t[0] * a[1] - t[1] * a[0]))
    v = (a[1] * u[2] - a[2] * u[1],
         a[2] * u[0] - a[0] * u[2],
         a[0] * u[1] - a[1] * u[0])
    return u, v


def max_line_foot(kind, family, d=1.0):
    """Largest foot radius over the family's guide lines -- the
    smallest guide extent that still emits every line.

    A line is dropped entirely once its foot (the point of the line
    closest to the plane centre) falls outside the guide disc, so an
    extent below this silently loses the outermost lines -- and with
    them the intersections the outer corners of a motif snap to.  For
    the icosahedral 2-fold planes (Frabjous) this is phi^2 + 1/phi^2
    ~ 3.078, while the pointed ends of the parts reach out to the
    3-fold piercings at phi^2 ~ 2.618."""
    a, normals = plane_normals(kind, family)
    u, v = _frame(a)
    best = 0.0
    for b in normals:
        ab = sum(x * y for x, y in zip(a, b))
        if abs(ab) > 1 - 1e-9:
            continue
        Bu = sum(x * y for x, y in zip(b, u))
        Bv = sum(x * y for x, y in zip(b, v))
        n2 = Bu * Bu + Bv * Bv
        c = d * (1 - ab)
        best = max(best, sqrt((c * Bu / n2) ** 2 + (c * Bv / n2) ** 2))
    return best


def stellation_lines(kind, family, d=1.0, extent=3.0):
    """The guide pattern of Hart's 2D editor: line segments (in the
    representative plane's local xy coordinates) where the other
    planes of the family cut it, clipped to a disc of radius
    extent * d."""
    a, normals = plane_normals(kind, family)
    u, v = _frame(a)
    R = extent * d
    segs = []
    for b in normals:
        ab = sum(x * y for x, y in zip(a, b))
        if abs(ab) > 1 - 1e-9:
            continue                      # this plane or its parallel
        Bu = sum(x * y for x, y in zip(b, u))
        Bv = sum(x * y for x, y in zip(b, v))
        c = d * (1 - ab)
        n2 = Bu * Bu + Bv * Bv
        px, py = c * Bu / n2, c * Bv / n2  # foot of the line
        h2 = R * R - (px * px + py * py)
        if h2 <= 0:
            continue                      # line misses the guide disc
        h = sqrt(h2)
        tl = sqrt(n2)
        tx, ty = -Bv / tl, Bu / tl
        segs.append(((px - h * tx, py - h * ty),
                     (px + h * tx, py + h * ty)))
    return segs


def sculpture_radius(verts, d, shell=0.0):
    """Outer radius of the finished sculpture, from the motif alone.

    The node group maps a motif vertex (x, y, z) onto the
    representative plane as x*u + y*v + (z + d)*a, and u, v, a are
    orthonormal -- so that vertex sits sqrt(x^2 + y^2 + (z+d)^2) from
    the origin.  Every copy is a rotation about the origin, so the
    whole sculpture is bounded by the largest such radius, and the
    radial shell scales it by (1 + shell)."""
    r = 0.0
    for x, y, z in verts:
        r = max(r, sqrt(x * x + y * y + (z + d) * (z + d)))
    return r * (1.0 + shell)


def lift_height(verts, d, shell=0.0, margin=0.3):
    """Lift that clears the motif by `margin` of the sculpture's own
    radius.

    The sculpture surrounds the origin, so its lowest point sits one
    radius below the motif plane; raising it by that radius brings it
    down exactly onto the motif, and the margin opens the gap.  Scaled
    to the actual geometry rather than a fixed multiple of the plane
    distance, because a motif reaching far out in its plane (Frabjous
    runs to phi^2) makes a far bigger sculpture than a compact one
    (Tumbleweed) at the very same plane distance."""
    return sculpture_radius(verts, d, shell) * (1.0 + margin)


def _ribbon(path, widths):
    """Flat quad-strip mesh (verts, faces) along a 2D centerline
    with per-point half-widths."""
    verts = []
    faces = []
    n = len(path)
    for i, (x, y) in enumerate(path):
        x0, y0 = path[max(i - 1, 0)]
        x1, y1 = path[min(i + 1, n - 1)]
        tx, ty = x1 - x0, y1 - y0
        l = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / l, tx / l
        w = widths[i]
        verts.append((x - nx * w, y - ny * w, 0.0))
        verts.append((x + nx * w, y + ny * w, 0.0))
    for i in range(n - 1):
        k = 2 * i
        faces.append([k, k + 2, k + 3, k + 1])
    return verts, faces


def demo_motif(d=1.0):
    """Default motif: a flat C-shaped ribbon arc in the local xy
    plane -- with 3-fold in-plane replication this gives the curved
    'rivers' of Hart's Twisted Rivers, Knotted Sea."""
    r_mid = 0.52 * d
    a0, a1 = math.radians(15), math.radians(200)
    steps = 28
    path = []
    widths = []
    for i in range(steps + 1):
        t = i / steps
        ang = a0 + (a1 - a0) * t
        path.append((r_mid * cos(ang), r_mid * sin(ang)))
        widths.append(0.075 * d * (0.25 + 0.75 * sin(pi * t)))
    return _ribbon(path, widths)


def tumbleweed_motif(d=1.0):
    """One swirling pinwheel arm; the 5-fold symmetry of the
    dodecahedral planes turns it into the flower of Hart's
    Tumbleweed (12 planes x 5 arms)."""
    steps = 32
    a0 = math.radians(-25)
    sweep = math.radians(150)
    path = []
    widths = []
    for i in range(steps + 1):
        t = i / steps
        ang = a0 + sweep * t ** 1.15    # curl tightens outward
        r = d * (0.12 + 0.63 * t ** 0.9)
        path.append((r * cos(ang), r * sin(ang)))
        widths.append(d * (0.02 + 0.055 * sin(pi * t) ** 0.7))
    return _ribbon(path, widths)


def _spline(pts, m):
    """Catmull-Rom resample of a 2D control polyline."""
    pts = [pts[0]] + list(pts) + [pts[-1]]
    out = []
    segs = len(pts) - 3
    for i in range(segs):
        p0, p1, p2, p3 = pts[i], pts[i + 1], pts[i + 2], pts[i + 3]
        steps = m if i < segs - 1 else m + 1
        for k in range(steps):
            t = k / m
            t2, t3 = t * t, t * t * t
            out.append(tuple(
                0.5 * ((2 * p1[j]) + (-p0[j] + p2[j]) * t
                       + (2 * p0[j] - 5 * p1[j] + 4 * p2[j]
                          - p3[j]) * t2
                       + (-p0[j] + 3 * p1[j] - 3 * p2[j]
                          + p3[j]) * t3)
                for j in range(2)))
    return out


def _earclip(poly):
    """Triangulate a simple 2D polygon (list of (x, y), CCW)."""
    idx = list(range(len(poly)))
    area2 = sum(poly[i][0] * poly[(i + 1) % len(poly)][1]
                - poly[(i + 1) % len(poly)][0] * poly[i][1]
                for i in range(len(poly)))
    if area2 < 0:
        idx.reverse()
    tris = []
    guard = 0
    while len(idx) > 3 and guard < 10000:
        guard += 1
        n = len(idx)
        for k in range(n):
            a, b, c = idx[k - 1], idx[k], idx[(k + 1) % n]
            ax, ay = poly[a]
            bx, by = poly[b]
            cx, cy = poly[c]
            cross = (bx - ax) * (cy - ay) - (by - ay) * (cx - ax)
            if cross <= 1e-12:
                continue
            ok = True
            for j in idx:
                if j in (a, b, c):
                    continue
                px, py = poly[j]
                d1 = (bx - ax) * (py - ay) - (by - ay) * (px - ax)
                d2 = (cx - bx) * (py - by) - (cy - by) * (px - bx)
                d3 = (ax - cx) * (py - cy) - (ay - cy) * (px - cx)
                if d1 >= -1e-12 and d2 >= -1e-12 and d3 >= -1e-12:
                    ok = False
                    break
            if ok:
                tris.append((a, b, c))
                idx.pop(k)
                break
        else:
            break
    if len(idx) == 3:
        tris.append(tuple(idx))
    return tris


def frabjous_motif(d=1.0):
    """Half of one of the thirty S-shaped parts of Hart's
    Frabjous, drawn in a face plane of the GREAT rhombic
    triacontahedron: the plane at distance d perpendicular to a
    2-fold axis, with the rhombus corners at the piercings of
    the neighbouring 3-fold axes (+-phi^2 d on the local x axis,
    where the pointed ends of three parts meet) and 5-fold axes
    (+-phi d on the local y axis, the vortex openings the parts
    swirl around).  The in-plane 2-fold symmetry adds the other
    half of the S; the teardrop opening near the tip follows
    Hart's template."""
    PHI2 = PHI * PHI
    cl = _spline([(0.0, 0.0), (0.45 * d, 0.20 * d),
                  (0.95 * d, 0.35 * d), (1.45 * d, 0.44 * d),
                  (1.90 * d, 0.44 * d), (2.25 * d, 0.33 * d),
                  (2.50 * d, 0.16 * d), (PHI2 * d, 0.01 * d)],
                 6)
    wl = _spline([(0.0, 0.200 * d), (1.0, 0.190 * d),
                  (2.0, 0.180 * d), (3.0, 0.170 * d),
                  (4.0, 0.155 * d), (5.0, 0.130 * d),
                  (6.0, 0.080 * d), (7.0, 0.012 * d)], 6)
    n = len(cl)
    verts = []
    faces = []
    rows = []
    for i, (x, y) in enumerate(cl):
        x0, y0 = cl[max(i - 1, 0)]
        x1, y1 = cl[min(i + 1, n - 1)]
        tx, ty = x1 - x0, y1 - y0
        ln = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / ln, tx / ln
        w = wl[i][1]
        t = i / (n - 1)
        # teardrop opening near the tip: outer band stays
        # thick, a thin sliver remains on the inner side
        if 0.52 < t < 0.94:
            s = math.sin(math.pi * (t - 0.52) / 0.42)
            hole = 0.5 * (s ** 0.8)
        else:
            hole = 0.0
        f_out = 0.40
        o_edge = (x + nx * w, y + ny * w)
        h1 = (x + nx * w * (1 - 2 * f_out),
              y + ny * w * (1 - 2 * f_out))
        h2 = (x + nx * w * (1 - 2 * f_out - 2 * hole),
              y + ny * w * (1 - 2 * f_out - 2 * hole))
        i_edge = (x - nx * w, y - ny * w)
        base = len(verts)
        for px, py in (o_edge, h1, h2, i_edge):
            verts.append((px, py, 0.0))
        rows.append(base)
    for i in range(n - 1):
        b0, b1 = rows[i], rows[i + 1]
        faces.append([b0, b1, b1 + 1, b0 + 1])
        faces.append([b0 + 2, b1 + 2, b1 + 3, b0 + 3])
    return verts, faces


def whimsy_motif(d=1.0):
    """One of the sixty flat parts of Hart's Whimsy, drawn in a
    face plane of the pentagonal hexecontahedron (the snub
    dodecahedron's dual).  The pieces are openwork: a web of
    constant-width curved ribbons -- straight along the long
    mating edge at the 5-fold hub, following the pentagon rim
    to the 3-fold corner where three modules meet, with
    swooping interior ribs -- leaving the large swirling
    negative spaces of the sculpture.  Corner coordinates are
    the exact face-pentagon corners in units of the plane
    distance."""
    P5 = (-0.06298 * d, -0.43738 * d)   # 5-fold apex
    G1 = (+0.26728 * d, -0.06800 * d)
    G2 = (+0.18165 * d, +0.20753 * d)
    T3 = (-0.10596 * d, +0.24549 * d)   # 3-fold corner
    G3 = (-0.27561 * d, +0.01017 * d)

    def lerp(A, B, t):
        return (A[0] + (B[0] - A[0]) * t,
                A[1] + (B[1] - A[1]) * t)

    strips = [
        # straight mating ribbon on the long edge P5-G1
        ([P5, lerp(P5, G1, 0.5), G1], 0.036),
        # rim ribbon G1 -> G2 -> T3
        ([G1, (G2[0] * 1.04, G2[1] * 1.04), T3], 0.032),
        # rim ribbon T3 -> G3 -> P5
        ([T3, (G3[0] * 1.04, G3[1] * 1.04), P5], 0.032),
        # interior rib: from the mating edge swooping to the
        # 3-fold corner
        ([lerp(P5, G1, 0.45), (0.05 * d, 0.01 * d), T3],
         0.030),
        # interior rib: hub apex arcing out to the rim
        ([P5, (0.09 * d, -0.17 * d),
          lerp(G1, G2, 0.55)], 0.028),
    ]
    verts = []
    faces = []
    for ctrl, hw in strips:
        path = _spline(ctrl, 10)
        w = [hw * d] * len(path)
        sv, sf = _ribbon(path, w)
        base = len(verts)
        verts.extend(sv)
        faces.extend([[base + i for i in f] for f in sf])
    return verts, faces


# preset -> (group, plane family, motif builder)
PRESETS = {
    'TWISTED_RIVERS': ('ICOSA', 'P3', demo_motif),
    'TUMBLEWEED': ('ICOSA', 'P5', tumbleweed_motif),
    'FRABJOUS': ('ICOSA', 'P2', frabjous_motif),
    'WHIMSY': ('ICOSA', 'P1', whimsy_motif),
}


try:
    import bpy
    from mathutils import Matrix
    from bpy.props import (FloatProperty, EnumProperty, BoolProperty,
                           StringProperty)
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    _NG_NAME = "Math Art Symmetric Sculpture"

    def _ghost_material():
        """Shared translucent material for the replicated copies, so
        the editable motif stands out from the full sculpture."""
        name = "SymSculpt Copies"
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        mat = bpy.data.materials.new(name)
        rgba = (0.55, 0.66, 0.78, 0.16)
        mat.diffuse_color = rgba          # solid-view translucency
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgba[:3], 1.0)
            bsdf.inputs["Alpha"].default_value = rgba[3]
            bsdf.inputs["Roughness"].default_value = 0.4
        if hasattr(mat, 'surface_render_method'):    # EEVEE Next
            mat.surface_render_method = 'BLENDED'
        elif hasattr(mat, 'blend_method'):           # legacy EEVEE
            mat.blend_method = 'BLEND'
        return mat

    def _motif_material():
        name = "SymSculpt Motif"
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        mat = bpy.data.materials.new(name)
        rgb = (0.9, 0.45, 0.15)
        mat.diffuse_color = (*rgb, 1.0)
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
            bsdf.inputs["Roughness"].default_value = 0.45
        return mat

    def _node_group():
        """Get or build the replicator node group: instance the motif
        object on the rotation points, optionally ghost the copies
        (Translucent), realize, weld, extrude radially from the origin
        (preserves planarity), and lift the result clear of the
        motif."""
        for ng in bpy.data.node_groups:
            if (ng.name.startswith(_NG_NAME)
                    and ng.type == 'GEOMETRY'
                    and any(it.name == 'Translucent'
                            for it in ng.interface.items_tree)):
                return ng
        ng = bpy.data.node_groups.new(_NG_NAME, 'GeometryNodeTree')
        face = ng.interface.new_socket
        face("Geometry", in_out='INPUT',
             socket_type='NodeSocketGeometry')
        face("Motif", in_out='INPUT', socket_type='NodeSocketObject')
        s = face("Shell", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 0.04, 0.0, 1.0
        s.description = "Radial extrusion as a fraction of the " \
                        "distance from the origin (0 = flat planes)"
        s = face("Weld", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 1e-4, 0.0, 0.1
        s.description = "Merge distance where copies meet exactly"
        s = face("Full Sculpture", in_out='INPUT',
                 socket_type='NodeSocketBool')
        s.default_value = False
        s.description = "Keep the copy that coincides with the " \
                        "editable Motif; off drops that one copy so " \
                        "the Motif object stands alone in its plane. " \
                        "Only has an effect while Lift is 0 -- a " \
                        "lifted sculpture is already clear of the " \
                        "motif, so every copy is kept"
        s = face("Translucent", in_out='INPUT',
                 socket_type='NodeSocketBool')
        s.default_value = False
        s.description = "Draw the replicated copies in the ghost " \
                        "Copy Material instead of the motif's own, " \
                        "so the editable motif reads through them. " \
                        "Off = the sculpture's real material"
        s = face("Lift", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 0.0, 0.0, 100.0
        s.description = "Raise the whole sculpture this far up +Z, " \
                        "leaving the Motif and Guides behind at the " \
                        "origin so they can be seen and edited " \
                        "(0 = in place). Only the modifier result " \
                        "moves, not the objects; while lifted the " \
                        "motif's own copy is kept, since the " \
                        "sculpture is already out of the way"
        s = face("Copy Material", in_out='INPUT',
                 socket_type='NodeSocketMaterial')
        s.default_value = _ghost_material()
        s.description = "Material for the replicated copies while " \
                        "Translucent is on"
        s = face("Plane Rotation", in_out='INPUT',
                 socket_type='NodeSocketVector')
        s.description = "Euler rotation mapping the motif's XY " \
                        "plane onto the representative plane"
        s = face("Plane Offset", in_out='INPUT',
                 socket_type='NodeSocketVector')
        s.description = "Translation of the representative plane " \
                        "(distance x axis)"
        face("Geometry", in_out='OUTPUT',
             socket_type='NodeSocketGeometry')

        n = ng.nodes.new
        gi = n('NodeGroupInput')
        # design view: drop the point whose copy coincides with the
        # editable motif object (is_motif AND NOT Full Sculpture)
        nam = n('GeometryNodeInputNamedAttribute')
        nam.data_type = 'BOOLEAN'
        nam.inputs['Name'].default_value = "is_motif"
        bnot = n('FunctionNodeBooleanMath')
        bnot.operation = 'NOT'
        band = n('FunctionNodeBooleanMath')
        band.operation = 'AND'
        # a lifted sculpture already stands clear of the motif, so the
        # motif's own copy is only dropped while Lift is zero
        cmpl = n('FunctionNodeCompare')
        cmpl.data_type = 'FLOAT'
        cmpl.operation = 'GREATER_THAN'
        cmpl.inputs[1].default_value = 1e-6
        bnotl = n('FunctionNodeBooleanMath')
        bnotl.operation = 'NOT'
        bandl = n('FunctionNodeBooleanMath')
        bandl.operation = 'AND'
        dg = n('GeometryNodeDeleteGeometry')
        dg.domain = 'POINT'
        oi = n('GeometryNodeObjectInfo')
        oi.transform_space = 'RELATIVE'
        oi.inputs['As Instance'].default_value = True
        tg = n('GeometryNodeTransform')
        na = n('GeometryNodeInputNamedAttribute')
        na.data_type = 'FLOAT_VECTOR'
        na.inputs['Name'].default_value = "sym_rot"
        iop = n('GeometryNodeInstanceOnPoints')
        sm = n('GeometryNodeSetMaterial')
        smw = n('GeometryNodeSwitch')     # ghosts vs real materials
        smw.input_type = 'GEOMETRY'
        ri = n('GeometryNodeRealizeInstances')
        md = n('GeometryNodeMergeByDistance')
        pos = n('GeometryNodeInputPosition')
        off = n('ShaderNodeVectorMath')
        off.operation = 'SCALE'
        ex = n('GeometryNodeExtrudeMesh')
        ex.mode = 'FACES'
        ex.inputs['Individual'].default_value = False
        cmp = n('FunctionNodeCompare')
        cmp.data_type = 'FLOAT'
        cmp.operation = 'GREATER_THAN'
        cmp.inputs[1].default_value = 1e-5
        sw = n('GeometryNodeSwitch')
        sw.input_type = 'GEOMETRY'
        # the lift is applied LAST: the radial shell above offsets each
        # point along its own position vector, so translating before it
        # would change every point's distance from the origin and
        # corrupt the extrusion
        lz = n('ShaderNodeCombineXYZ')
        lt = n('GeometryNodeTransform')
        go = n('NodeGroupOutput')

        ln = ng.links.new
        ln(gi.outputs['Full Sculpture'], bnot.inputs[0])
        ln(nam.outputs['Attribute'], band.inputs[0])
        ln(bnot.outputs['Boolean'], band.inputs[1])
        ln(gi.outputs['Lift'], cmpl.inputs[0])
        ln(cmpl.outputs['Result'], bnotl.inputs[0])
        ln(band.outputs['Boolean'], bandl.inputs[0])
        ln(bnotl.outputs['Boolean'], bandl.inputs[1])
        ln(gi.outputs['Geometry'], dg.inputs['Geometry'])
        ln(bandl.outputs['Boolean'], dg.inputs['Selection'])
        ln(dg.outputs['Geometry'], iop.inputs['Points'])
        ln(gi.outputs['Motif'], oi.inputs['Object'])
        ln(oi.outputs['Geometry'], tg.inputs['Geometry'])
        ln(gi.outputs['Plane Rotation'], tg.inputs['Rotation'])
        ln(gi.outputs['Plane Offset'], tg.inputs['Translation'])
        ln(tg.outputs['Geometry'], iop.inputs['Instance'])
        ln(na.outputs['Attribute'], iop.inputs['Rotation'])
        ln(iop.outputs['Instances'], sm.inputs['Geometry'])
        ln(gi.outputs['Copy Material'], sm.inputs['Material'])
        ln(gi.outputs['Translucent'], smw.inputs['Switch'])
        ln(iop.outputs['Instances'], smw.inputs['False'])
        ln(sm.outputs['Geometry'], smw.inputs['True'])
        ln(smw.outputs['Output'], ri.inputs['Geometry'])
        ln(ri.outputs['Geometry'], md.inputs['Geometry'])
        ln(gi.outputs['Weld'], md.inputs['Distance'])
        ln(pos.outputs['Position'], off.inputs[0])
        ln(gi.outputs['Shell'], off.inputs['Scale'])
        ln(md.outputs['Geometry'], ex.inputs['Mesh'])
        ln(off.outputs['Vector'], ex.inputs['Offset'])
        ln(gi.outputs['Shell'], cmp.inputs[0])
        ln(cmp.outputs['Result'], sw.inputs['Switch'])
        ln(md.outputs['Geometry'], sw.inputs['False'])
        ln(ex.outputs['Mesh'], sw.inputs['True'])
        ln(gi.outputs['Lift'], lz.inputs['Z'])
        ln(sw.outputs['Output'], lt.inputs['Geometry'])
        ln(lz.outputs['Vector'], lt.inputs['Translation'])
        ln(lt.outputs['Geometry'], go.inputs['Geometry'])
        for i, node in enumerate((gi, nam, bnot, band, cmpl, bnotl,
                                  bandl, dg, oi, tg, na, iop, sm, smw,
                                  ri, md, pos, off, ex, cmp, sw, lz,
                                  lt, go)):
            node.location = (200 * (i % 6), -240 * (i // 6))
        return ng

    class OBJECT_OT_symmetric_sculpture_add(bpy.types.Operator):
        """Set up a Hart-style symmetric sculpture: a flat motif in
        one plane, replicated live into the whole plane family by a
        Geometry Nodes modifier"""
        bl_idname = "object.symmetric_sculpture_add"
        bl_label = "Symmetric Sculpture"
        bl_options = {'REGISTER', 'UNDO'}

        preset: EnumProperty(
            name="Preset",
            items=[('TWISTED_RIVERS', "Twisted Rivers",
                    "After Twisted Rivers, Knotted Sea (2001): "
                    "C-shaped rivers in the 20 icosahedral planes, "
                    "three per plane"),
                   ('TUMBLEWEED', "Tumbleweed",
                    "After Tumbleweed (2006): swirling five-armed "
                    "pinwheels in the 12 dodecahedral planes"),
                   ('FRABJOUS', "Frabjous",
                    "After Frabjous (2003): 30 S-shaped parts in "
                    "the face planes of the GREAT rhombic "
                    "triacontahedron -- ends meeting in threes at "
                    "the 3-fold corners (phi^2 x the plane "
                    "distance), five-fold vortices at the 5-fold "
                    "corners (phi x)"),
                   ('WHIMSY', "Whimsy",
                    "After Whimsy (2014): 60 flat blades in the "
                    "face planes of the pentagonal "
                    "hexecontahedron (snub dodecahedron dual), "
                    "five to a hub, meeting in threes at the "
                    "3-fold corners"),
                   ('CUSTOM', "Custom",
                    "Choose the group and plane family yourself; "
                    "starts from the demo arc motif")],
            default='TWISTED_RIVERS',
            description="Sculpture setups after Hart's pieces; the "
                        "motif stays editable afterwards")
        group: EnumProperty(
            name="Symmetry Group",
            items=[('ICOSA', "Icosahedral (60)",
                    "60 rotations -- Hart's usual choice"),
                   ('OCTA', "Octahedral (24)", "24 rotations"),
                   ('TETRA', "Tetrahedral (12)", "12 rotations")],
            default='ICOSA')
        family: EnumProperty(
            name="Plane Family",
            items=[('P5', "5-fold planes (dodecahedral)",
                    "12 planes, 5-fold symmetry in each "
                    "(icosahedral group only)"),
                   ('P4', "4-fold planes (cube)",
                    "6 planes, 4-fold each (octahedral group only)"),
                   ('P3', "3-fold planes (icosahedral)",
                    "Planes perpendicular to the 3-fold axes: 20 for "
                    "the icosahedral group (Hart's Twisted Rivers), "
                    "8 octahedral, 4 tetrahedral"),
                   ('P2', "2-fold planes (triacontahedral)",
                    "Planes perpendicular to the 2-fold axes: 30 "
                    "icosahedral (Frabjous), 12 octahedral, 6 "
                    "tetrahedral"),
                   ('P1', "General planes (hexecontahedral)",
                    "A full-orbit family with no in-plane symmetry: "
                    "60 / 24 / 12 planes")],
            default='P3')
        distance: FloatProperty(
            name="Plane Distance", default=1.0, min=0.1, max=10.0,
            description="Distance of the plane family from the origin")
        shell: FloatProperty(
            name="Shell", default=0.04, min=0.0, max=1.0,
            description="Radial extrusion fraction (Hart used ~4%); "
                        "0 keeps the flat planes")
        guide_extent: FloatProperty(
            name="Guide Extent", default=3.2, min=1.0, max=12.0,
            description="Radius of the guide pattern, in units of "
                        "the plane distance. 3.2 covers every line "
                        "of the 5-, 4-, 3- and 2-fold families "
                        "(the outermost sits at 3.078, on the "
                        "icosahedral 2-fold planes) so the outer "
                        "corners a motif snaps to -- e.g. Frabjous's "
                        "tips at phi^2 = 2.618 -- have guide lines "
                        "crossing there. The general P1 families run "
                        "much farther out and need a bigger radius "
                        "to draw in full")
        lift: BoolProperty(
            name="Lift Sculpture Clear of Motif", default=True,
            description="Raise the sculpture up +Z so it stops "
                        "surrounding the Motif and Guides, which stay "
                        "at the origin where they can be seen and "
                        "edited. The height is measured from the "
                        "sculpture this motif actually makes, so it "
                        "clears by the same relative margin whatever "
                        "the size; tune it afterwards with the "
                        "modifier's Lift input")
        translucent: BoolProperty(
            name="Translucent Copies", default=False,
            description="Draw the replicated copies in a ghost "
                        "material so the editable motif reads through "
                        "them; off = the sculpture's real material")
        motif_object: StringProperty(
            name="Motif Object", default="",
            description="Mesh object to replicate instead of the "
                        "preset motif -- draw it flat on the XY "
                        "plane. Leave empty to build the preset's "
                        "own motif")

        def execute(self, context):
            motif_builder = demo_motif
            if self.preset in PRESETS:
                g, f, motif_builder = PRESETS[self.preset]
                self.group, self.family = g, f
            kind, family = self.group, self.family
            if (kind, family) not in _AXES:
                family = 'P3'
                self.report({'WARNING'},
                            "Plane family not available for this "
                            "group -- using 3-fold planes")
            rots = group_rotations(kind)
            a, normals = plane_normals(kind, family)
            u, v = _frame(a)
            d = self.distance

            motif = None
            if self.motif_object:
                ao = bpy.data.objects.get(self.motif_object)
                if ao is not None and ao.type == 'MESH':
                    motif = ao
                else:
                    self.report({'WARNING'},
                                f"'{self.motif_object}' is not a mesh "
                                f"object -- built the preset motif "
                                f"instead")
            if motif is None:
                verts, faces = motif_builder(d)
                me = bpy.data.meshes.new("SymSculpt Motif")
                me.from_pydata(verts, [], faces)
                me.validate()
                me.update()
                motif = bpy.data.objects.new("SymSculpt Motif", me)
                context.collection.objects.link(motif)
            # the motif is authored and edited flat on the world
            # XY plane; the node group maps it onto the
            # representative plane with this rotation + offset
            plane_rot = Matrix((
                (u[0], v[0], a[0]),
                (u[1], v[1], a[1]),
                (u[2], v[2], a[2]))).to_euler()
            plane_off = (d * a[0], d * a[1], d * a[2])
            motif.matrix_world = Matrix.Identity(4)
            if not motif.data.materials:
                motif.data.materials.append(_motif_material())
            # how high the sculpture has to go to clear the motif --
            # measured from the motif that is actually being used, so
            # a big motif gets a proportionally bigger lift
            lift_z = lift_height([tuple(v.co) for v in
                                  motif.data.vertices],
                                 d, self.shell)

            # guide pattern (stellation diagram) in the same plane
            segs = stellation_lines(kind, family, d, self.guide_extent)
            gverts = []
            gedges = []
            for (p0, p1) in segs:
                gverts.append((p0[0], p0[1], 0.0))
                gverts.append((p1[0], p1[1], 0.0))
                gedges.append((len(gverts) - 2, len(gverts) - 1))
            gme = bpy.data.meshes.new("SymSculpt Guides")
            gme.from_pydata(gverts, gedges, [])
            gme.update()
            guides = bpy.data.objects.new("SymSculpt Guides", gme)
            context.collection.objects.link(guides)
            guides.matrix_world = Matrix.Identity(4)
            guides.display_type = 'WIRE'
            guides.hide_render = True

            # the sculpture: one point per rotation, euler attribute
            pts = bpy.data.meshes.new("SymSculpt")
            pts.from_pydata([(0.0, 0.0, 0.0)] * len(rots), [], [])
            attr = pts.attributes.new("sym_rot", 'FLOAT_VECTOR',
                                      'POINT')
            eulers = []
            for R in rots:
                eulers.extend(Matrix(R).to_euler())
            attr.data.foreach_set('vector', eulers)
            attr = pts.attributes.new("copy_index", 'INT', 'POINT')
            attr.data.foreach_set('value', list(range(len(rots))))
            attr = pts.attributes.new("is_motif", 'BOOLEAN', 'POINT')
            attr.data.foreach_set(
                'value',
                [all(abs(R[i][j] - (1.0 if i == j else 0.0)) < 1e-9
                     for i in range(3) for j in range(3))
                 for R in rots])
            obj = bpy.data.objects.new("SymSculpt", pts)
            context.collection.objects.link(obj)

            mod = obj.modifiers.new("Symmetric Sculpture", 'NODES')
            ng = _node_group()
            mod.node_group = ng
            for item in ng.interface.items_tree:
                if item.in_out != 'INPUT':
                    continue
                if item.name == 'Motif':
                    mod[item.identifier] = motif
                elif item.name == 'Shell':
                    mod[item.identifier] = self.shell
                elif item.name == 'Lift':
                    # sized from the sculpture the motif actually
                    # makes, not from d alone; still a live modifier
                    # input afterwards
                    mod[item.identifier] = lift_z if self.lift else 0.0
                elif item.name == 'Translucent':
                    mod[item.identifier] = self.translucent
                elif item.name == 'Plane Rotation':
                    mod[item.identifier] = list(plane_rot)
                elif item.name == 'Plane Offset':
                    mod[item.identifier] = list(plane_off)

            motif.parent = obj
            motif.matrix_parent_inverse = Matrix.Identity(4)
            guides.parent = obj
            guides.matrix_parent_inverse = Matrix.Identity(4)

            for o in context.selected_objects:
                o.select_set(False)
            obj.select_set(True)
            motif.select_set(True)
            context.view_layer.objects.active = obj
            fold = len(rots) // len(normals)
            self.report(
                {'INFO'},
                f"{len(normals)} planes x {fold}-fold: edit the "
                f"Motif object and every copy follows")
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            lay.prop(self, 'preset')
            if self.preset == 'CUSTOM':
                lay.prop(self, 'group')
                lay.prop(self, 'family')
            # what gets replicated, straight after which planes it is
            # replicated into
            lay.prop_search(self, 'motif_object', bpy.data, 'objects')
            for k in ('distance', 'shell', 'guide_extent', 'lift',
                      'translucent'):
                lay.prop(self, k)

    def _menu_func(self, context):
        self.layout.operator_menu_enum(
            "object.symmetric_sculpture_add", "preset",
            text="Symmetric Sculpture", icon='MOD_MIRROR')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(OBJECT_OT_symmetric_sculpture_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.remove(_menu_func)
        bpy.utils.unregister_class(
            OBJECT_OT_symmetric_sculpture_add)


def _selftest():
    # group orders and plane-family counts
    for kind, order in _ORDER.items():
        rots = group_rotations(kind)
        print(f"{kind}: {len(rots)} rotations "
              f"{'OK' if len(rots) == order else 'BAD'}")
        assert len(rots) == order
    expect = {('ICOSA', 'P5'): 12, ('ICOSA', 'P3'): 20,
              ('ICOSA', 'P2'): 30, ('ICOSA', 'P1'): 60,
              ('OCTA', 'P4'): 6, ('OCTA', 'P3'): 8,
              ('OCTA', 'P2'): 12, ('OCTA', 'P1'): 24,
              ('TETRA', 'P3'): 4, ('TETRA', 'P2'): 6,
              ('TETRA', 'P1'): 12}
    for (kind, fam), n in expect.items():
        _, normals = plane_normals(kind, fam)
        ok = len(normals) == n
        print(f"{kind}/{fam}: {len(normals)} planes "
              f"(want {n}) {'OK' if ok else 'BAD'}")
        assert ok
    # icosa 3-fold: 18 guide lines (19 others minus the parallel)
    segs = stellation_lines('ICOSA', 'P3', 1.0, 10.0)
    print(f"ICOSA/P3 guide lines: {len(segs)} "
          f"{'OK' if len(segs) == 18 else 'BAD'}")
    assert len(segs) == 18

    # the shipped Guide Extent must emit EVERY line of the k-fold
    # families -- a line whose foot lies outside the disc is dropped
    # altogether, taking with it the corner intersections that the
    # outer tips of a motif are drawn to.
    default_extent = 3.2
    for kind, fam in (('ICOSA', 'P5'), ('ICOSA', 'P3'), ('ICOSA', 'P2'),
                      ('OCTA', 'P4'), ('OCTA', 'P3'), ('OCTA', 'P2'),
                      ('TETRA', 'P3'), ('TETRA', 'P2')):
        _, normals = plane_normals(kind, fam)
        foot = max_line_foot(kind, fam, 1.0)
        segs = stellation_lines(kind, fam, 1.0, default_extent)
        want = sum(1 for b in normals
                   if abs(sum(x * y for x, y in
                              zip(_normalize(_AXES[(kind, fam)]), b)))
                   <= 1 - 1e-9)
        ok = len(segs) == want and foot < default_extent
        print(f"{kind}/{fam} guides at extent {default_extent}: "
              f"{len(segs)}/{want} lines, max foot {foot:.3f} "
              f"{'OK' if ok else 'BAD'}")
        assert ok, (kind, fam, len(segs), want, foot)

    # Frabjous draws its pointed ends to the 3-fold piercings at
    # phi^2; those must be a real crossing of two guide lines, and
    # inside the default disc
    assert max_line_foot('ICOSA', 'P2', 1.0) > PHI * PHI
    assert PHI * PHI < default_extent
    print(f"ICOSA/P2 reaches the phi^2={PHI * PHI:.4f} corner OK")

    # a motif flat on XY at plane distance d lands at sqrt(r^2+d^2)
    flat = [(0.0, 0.0, 0.0), (3.0, 4.0, 0.0)]
    r = sculpture_radius(flat, 12.0)
    print(f"sculpture_radius (3,4,0) at d=12: {r:.4f} "
          f"{'OK' if abs(r - 13.0) < 1e-9 else 'BAD'}")
    assert abs(r - 13.0) < 1e-9            # 5-12-13
    assert abs(sculpture_radius(flat, 12.0, 0.5) - 19.5) < 1e-9

    # the lift must put the sculpture's lowest point exactly `margin`
    # of a radius above the motif plane, and must grow with the motif
    for verts, d, shell in ((flat, 12.0, 0.0), (flat, 12.0, 0.04),
                            ([(0.0, 0.0, 0.0)], 1.0, 0.0)):
        rad = sculpture_radius(verts, d, shell)
        gap = lift_height(verts, d, shell, 0.3) - rad
        assert abs(gap - 0.3 * rad) < 1e-9, (verts, d, shell)
    small = lift_height([(0.5, 0.0, 0.0)], 1.0)
    big = lift_height([(PHI * PHI, 0.0, 0.0)], 1.0)
    print(f"lift scales with motif: {small:.3f} -> {big:.3f} "
          f"{'OK' if big > small else 'BAD'}")
    assert big > small
    # ... and never buries the motif: the lowest point stays clear
    assert small > sculpture_radius([(0.5, 0.0, 0.0)], 1.0)
