
# Symmetric Sculpture designer for Blender
#
# After George W. Hart's sculpture design program described in
# "Symmetric sculpture", Journal of Mathematics and the Arts 1(1),
# 2007 (the tool behind Twisted Rivers, Tumbleweed, Frabjous,
# Spaghetti Code, ...). A flat motif drawn in ONE representative
# plane is replicated live into a whole family of symmetrically
# arranged planes -- the extended face planes of an icosahedron,
# dodecahedron, rhombic triacontahedron or hexecontahedron (or their
# octahedral / tetrahedral analogues).
#
# The replication is done with a Geometry Nodes modifier: a motif
# placed in a plane perpendicular to a k-fold axis and instanced
# under all N rotations of the chosen point group automatically
# lands in N/k planes with k-fold symmetry inside each plane, which
# is exactly Hart's plane-family construction. Three objects are
# created:
#
#   SymSculpt         points + Geometry Nodes modifier (the result)
#   SymSculpt Motif   flat mesh in the representative plane -- edit
#                     this (edit mode, or move/rotate the object) and
#                     every copy updates in real time
#   SymSculpt Guides  wireframe stellation pattern: the lines where
#                     the other planes of the family cut this one,
#                     for snapping/drawing against, as in Hart's 2D
#                     editor window
#
# The modifier's "Shell" input radially extrudes the surface away
# from the origin by that fraction of its distance (Hart's ~4%
# radial extrusion, which preserves planarity and yields a watertight
# solid for 3D printing); "Weld" merges coincident vertices where
# copies meet exactly on the plane-intersection lines.

bl_info = {
    "name": "Symmetric Sculpture",
    "author": "David Krider (Math Art project, after George W. Hart)",
    "version": (1, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Mesh > Symmetric Sculpture",
    "description": "Replicate a flat motif into symmetric plane "
                   "families, live, after Hart's sculpture software",
    "category": "Add Mesh",
}

import math
from math import cos, sin, pi, sqrt

PHI = (1 + sqrt(5)) / 2


# ---------------------------------------------------------------- #
#  rotation groups by closure                                      #
# ---------------------------------------------------------------- #

def _rot(axis, ang):
    """3x3 rotation about axis by ang (Rodrigues)."""
    x, y, z = axis
    l = sqrt(x * x + y * y + z * z)
    x, y, z = x / l, y / l, z / l
    c, s = cos(ang), sin(ang)
    C = 1 - c
    return ((c + x * x * C, x * y * C - z * s, x * z * C + y * s),
            (y * x * C + z * s, c + y * y * C, y * z * C - x * s),
            (z * x * C - y * s, z * y * C + x * s, c + z * z * C))


def _mul(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3))
                       for j in range(3)) for i in range(3))


def _apply(A, v):
    return tuple(sum(A[i][k] * v[k] for k in range(3)) for i in range(3))


def _key(A):
    return tuple(round(A[i][j], 9) for i in range(3) for j in range(3))


_GENS = {
    'TETRA': (_rot((1, 1, 1), 2 * pi / 3), _rot((0, 0, 1), pi)),
    'OCTA': (_rot((0, 0, 1), pi / 2), _rot((1, 1, 1), 2 * pi / 3)),
    'ICOSA': (_rot((0, 1, PHI), 2 * pi / 5), _rot((1, 1, 1), 2 * pi / 3)),
}
_ORDER = {'TETRA': 12, 'OCTA': 24, 'ICOSA': 60}


def group_rotations(kind):
    """All rotations of the chiral tetrahedral / octahedral /
    icosahedral group, generated by closure."""
    gens = _GENS[kind]
    seen = {}
    I = ((1.0, 0, 0), (0, 1.0, 0), (0, 0, 1.0))
    frontier = [I]
    seen[_key(I)] = I
    while frontier:
        nxt = []
        for A in frontier:
            for G in gens:
                B = _mul(G, A)
                k = _key(B)
                if k not in seen:
                    seen[k] = B
                    nxt.append(B)
        frontier = nxt
    rots = list(seen.values())
    assert len(rots) == _ORDER[kind], (kind, len(rots))
    return rots


# plane-family axis per (group, family); the plane sits at distance
# d perpendicular to this axis.
_AXES = {
    ('ICOSA', 'P5'): (0.0, 1.0, PHI),      # 12 planes, 5-fold each
    ('ICOSA', 'P3'): (1.0, 1.0, 1.0),      # 20 planes, 3-fold
    ('ICOSA', 'P2'): (0.0, 0.0, 1.0),      # 30 planes, 2-fold
    ('ICOSA', 'P1'): (0.21, 0.45, 1.0),    # 60 planes, no symmetry
    ('OCTA', 'P4'): (0.0, 0.0, 1.0),       # 6 planes (cube), 4-fold
    ('OCTA', 'P3'): (1.0, 1.0, 1.0),       # 8 planes, 3-fold
    ('OCTA', 'P2'): (1.0, 1.0, 0.0),       # 12 planes, 2-fold
    ('OCTA', 'P1'): (0.21, 0.45, 1.0),     # 24 planes
    ('TETRA', 'P3'): (1.0, 1.0, 1.0),      # 4 planes, 3-fold
    ('TETRA', 'P2'): (0.0, 0.0, 1.0),      # 6 planes, 2-fold
    ('TETRA', 'P1'): (0.21, 0.45, 1.0),    # 12 planes
}


def _normalize(v):
    l = sqrt(sum(c * c for c in v))
    return tuple(c / l for c in v)


def plane_normals(kind, family):
    """Distinct unit normals of the plane family = orbit of the axis
    under the group. Returns (axis, normals)."""
    a = _normalize(_AXES[(kind, family)])
    seen = {}
    for R in group_rotations(kind):
        b = _apply(R, a)
        k = tuple(round(c, 6) for c in b)
        if k not in seen:
            seen[k] = b
    return a, list(seen.values())


def _frame(a):
    """Right-handed orthonormal (u, v, a)."""
    t = (0.0, 0.0, 1.0) if abs(a[2]) < 0.9 else (1.0, 0.0, 0.0)
    u = _normalize((t[1] * a[2] - t[2] * a[1],
                    t[2] * a[0] - t[0] * a[2],
                    t[0] * a[1] - t[1] * a[0]))
    v = (a[1] * u[2] - a[2] * u[1],
         a[2] * u[0] - a[0] * u[2],
         a[0] * u[1] - a[1] * u[0])
    return u, v


def stellation_lines(kind, family, d=1.0, extent=3.0):
    """The guide pattern of Hart's 2D editor: line segments (in the
    representative plane's local xy coordinates) where the other
    planes of the family cut it, clipped to a disc of radius
    extent * d."""
    a, normals = plane_normals(kind, family)
    u, v = _frame(a)
    R = extent * d
    segs = []
    for b in normals:
        ab = sum(x * y for x, y in zip(a, b))
        if abs(ab) > 1 - 1e-9:
            continue                      # this plane or its parallel
        Bu = sum(x * y for x, y in zip(b, u))
        Bv = sum(x * y for x, y in zip(b, v))
        c = d * (1 - ab)
        n2 = Bu * Bu + Bv * Bv
        px, py = c * Bu / n2, c * Bv / n2  # foot of the line
        h2 = R * R - (px * px + py * py)
        if h2 <= 0:
            continue                      # line misses the guide disc
        h = sqrt(h2)
        tl = sqrt(n2)
        tx, ty = -Bv / tl, Bu / tl
        segs.append(((px - h * tx, py - h * ty),
                     (px + h * tx, py + h * ty)))
    return segs


def _ribbon(path, widths):
    """Flat quad-strip mesh (verts, faces) along a 2D centerline
    with per-point half-widths."""
    verts = []
    faces = []
    n = len(path)
    for i, (x, y) in enumerate(path):
        x0, y0 = path[max(i - 1, 0)]
        x1, y1 = path[min(i + 1, n - 1)]
        tx, ty = x1 - x0, y1 - y0
        l = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / l, tx / l
        w = widths[i]
        verts.append((x - nx * w, y - ny * w, 0.0))
        verts.append((x + nx * w, y + ny * w, 0.0))
    for i in range(n - 1):
        k = 2 * i
        faces.append([k, k + 2, k + 3, k + 1])
    return verts, faces


def demo_motif(d=1.0):
    """Default motif: a flat C-shaped ribbon arc in the local xy
    plane -- with 3-fold in-plane replication this gives the curved
    'rivers' of Hart's Twisted Rivers, Knotted Sea."""
    r_mid = 0.52 * d
    a0, a1 = math.radians(15), math.radians(200)
    steps = 28
    path = []
    widths = []
    for i in range(steps + 1):
        t = i / steps
        ang = a0 + (a1 - a0) * t
        path.append((r_mid * cos(ang), r_mid * sin(ang)))
        widths.append(0.075 * d * (0.25 + 0.75 * sin(pi * t)))
    return _ribbon(path, widths)


def tumbleweed_motif(d=1.0):
    """One swirling pinwheel arm; the 5-fold symmetry of the
    dodecahedral planes turns it into the flower of Hart's
    Tumbleweed (12 planes x 5 arms)."""
    steps = 32
    a0 = math.radians(-25)
    sweep = math.radians(150)
    path = []
    widths = []
    for i in range(steps + 1):
        t = i / steps
        ang = a0 + sweep * t ** 1.15    # curl tightens outward
        r = d * (0.12 + 0.63 * t ** 0.9)
        path.append((r * cos(ang), r * sin(ang)))
        widths.append(d * (0.02 + 0.055 * sin(pi * t) ** 0.7))
    return _ribbon(path, widths)


def frabjous_motif(d=1.0):
    """Half of an S-shaped part, starting at the plane centre. The
    2-fold in-plane symmetry of the triacontahedral planes adds the
    180-degree copy, welding into the 30 S-curves of Hart's
    Frabjous."""
    p0, p1 = (0.0, 0.0), (0.34 * d, 0.30 * d)
    p2, p3 = (0.56 * d, -0.26 * d), (0.80 * d, 0.22 * d)
    steps = 26
    path = []
    widths = []
    for i in range(steps + 1):
        t = i / steps
        s = 1 - t
        x = (s * s * s * p0[0] + 3 * s * s * t * p1[0]
             + 3 * s * t * t * p2[0] + t * t * t * p3[0])
        y = (s * s * s * p0[1] + 3 * s * s * t * p1[1]
             + 3 * s * t * t * p2[1] + t * t * t * p3[1])
        path.append((x, y))
        # full width at the centre join, tapering to the tip
        widths.append(d * (0.022 + 0.062 * sin(pi / 2 + pi / 2 * t)
                           ** 1.5))
    return _ribbon(path, widths)


# preset -> (group, plane family, motif builder)
PRESETS = {
    'TWISTED_RIVERS': ('ICOSA', 'P3', demo_motif),
    'TUMBLEWEED': ('ICOSA', 'P5', tumbleweed_motif),
    'FRABJOUS': ('ICOSA', 'P2', frabjous_motif),
}


try:
    import bpy
    from mathutils import Matrix
    from bpy.props import (FloatProperty, EnumProperty, BoolProperty)
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    _NG_NAME = "Math Art Symmetric Sculpture"

    def _ghost_material():
        """Shared translucent material for the replicated copies, so
        the editable motif stands out from the full sculpture."""
        name = "SymSculpt Copies"
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        mat = bpy.data.materials.new(name)
        rgba = (0.55, 0.66, 0.78, 0.16)
        mat.diffuse_color = rgba          # solid-view translucency
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgba[:3], 1.0)
            bsdf.inputs["Alpha"].default_value = rgba[3]
            bsdf.inputs["Roughness"].default_value = 0.4
        if hasattr(mat, 'surface_render_method'):    # EEVEE Next
            mat.surface_render_method = 'BLENDED'
        elif hasattr(mat, 'blend_method'):           # legacy EEVEE
            mat.blend_method = 'BLEND'
        return mat

    def _motif_material():
        name = "SymSculpt Motif"
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        mat = bpy.data.materials.new(name)
        rgb = (0.9, 0.45, 0.15)
        mat.diffuse_color = (*rgb, 1.0)
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
            bsdf.inputs["Roughness"].default_value = 0.45
        return mat

    def _node_group():
        """Get or build the replicator node group: instance the motif
        object on the rotation points, ghost the copies (unless Full
        Sculpture), realize, weld, and optionally extrude radially
        from the origin (preserves planarity)."""
        for ng in bpy.data.node_groups:
            if (ng.name.startswith(_NG_NAME)
                    and ng.type == 'GEOMETRY'
                    and any(it.name == 'Copy Material'
                            for it in ng.interface.items_tree)):
                return ng
        ng = bpy.data.node_groups.new(_NG_NAME, 'GeometryNodeTree')
        face = ng.interface.new_socket
        face("Geometry", in_out='INPUT',
             socket_type='NodeSocketGeometry')
        face("Motif", in_out='INPUT', socket_type='NodeSocketObject')
        s = face("Shell", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 0.04, 0.0, 1.0
        s.description = "Radial extrusion as a fraction of the " \
                        "distance from the origin (0 = flat planes)"
        s = face("Weld", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 1e-4, 0.0, 0.1
        s.description = "Merge distance where copies meet exactly"
        s = face("Full Sculpture", in_out='INPUT',
                 socket_type='NodeSocketBool')
        s.default_value = False
        s.description = "Show all copies with the motif's own " \
                        "material (for export/render); off = design " \
                        "view with translucent copies and the " \
                        "motif's own copy hidden"
        s = face("Copy Material", in_out='INPUT',
                 socket_type='NodeSocketMaterial')
        s.default_value = _ghost_material()
        s.description = "Material for the replicated copies in " \
                        "design view"
        face("Geometry", in_out='OUTPUT',
             socket_type='NodeSocketGeometry')

        n = ng.nodes.new
        gi = n('NodeGroupInput')
        # design view: drop the point whose copy coincides with the
        # editable motif object (is_motif AND NOT Full Sculpture)
        nam = n('GeometryNodeInputNamedAttribute')
        nam.data_type = 'BOOLEAN'
        nam.inputs['Name'].default_value = "is_motif"
        bnot = n('FunctionNodeBooleanMath')
        bnot.operation = 'NOT'
        band = n('FunctionNodeBooleanMath')
        band.operation = 'AND'
        dg = n('GeometryNodeDeleteGeometry')
        dg.domain = 'POINT'
        oi = n('GeometryNodeObjectInfo')
        oi.transform_space = 'RELATIVE'
        oi.inputs['As Instance'].default_value = True
        na = n('GeometryNodeInputNamedAttribute')
        na.data_type = 'FLOAT_VECTOR'
        na.inputs['Name'].default_value = "sym_rot"
        iop = n('GeometryNodeInstanceOnPoints')
        sm = n('GeometryNodeSetMaterial')
        smw = n('GeometryNodeSwitch')     # ghosts vs real materials
        smw.input_type = 'GEOMETRY'
        ri = n('GeometryNodeRealizeInstances')
        md = n('GeometryNodeMergeByDistance')
        pos = n('GeometryNodeInputPosition')
        off = n('ShaderNodeVectorMath')
        off.operation = 'SCALE'
        ex = n('GeometryNodeExtrudeMesh')
        ex.mode = 'FACES'
        ex.inputs['Individual'].default_value = False
        cmp = n('FunctionNodeCompare')
        cmp.data_type = 'FLOAT'
        cmp.operation = 'GREATER_THAN'
        cmp.inputs[1].default_value = 1e-5
        sw = n('GeometryNodeSwitch')
        sw.input_type = 'GEOMETRY'
        go = n('NodeGroupOutput')

        ln = ng.links.new
        ln(gi.outputs['Full Sculpture'], bnot.inputs[0])
        ln(nam.outputs['Attribute'], band.inputs[0])
        ln(bnot.outputs['Boolean'], band.inputs[1])
        ln(gi.outputs['Geometry'], dg.inputs['Geometry'])
        ln(band.outputs['Boolean'], dg.inputs['Selection'])
        ln(dg.outputs['Geometry'], iop.inputs['Points'])
        ln(gi.outputs['Motif'], oi.inputs['Object'])
        ln(oi.outputs['Geometry'], iop.inputs['Instance'])
        ln(na.outputs['Attribute'], iop.inputs['Rotation'])
        ln(iop.outputs['Instances'], sm.inputs['Geometry'])
        ln(gi.outputs['Copy Material'], sm.inputs['Material'])
        ln(gi.outputs['Full Sculpture'], smw.inputs['Switch'])
        ln(sm.outputs['Geometry'], smw.inputs['False'])
        ln(iop.outputs['Instances'], smw.inputs['True'])
        ln(smw.outputs['Output'], ri.inputs['Geometry'])
        ln(ri.outputs['Geometry'], md.inputs['Geometry'])
        ln(gi.outputs['Weld'], md.inputs['Distance'])
        ln(pos.outputs['Position'], off.inputs[0])
        ln(gi.outputs['Shell'], off.inputs['Scale'])
        ln(md.outputs['Geometry'], ex.inputs['Mesh'])
        ln(off.outputs['Vector'], ex.inputs['Offset'])
        ln(gi.outputs['Shell'], cmp.inputs[0])
        ln(cmp.outputs['Result'], sw.inputs['Switch'])
        ln(md.outputs['Geometry'], sw.inputs['False'])
        ln(ex.outputs['Mesh'], sw.inputs['True'])
        ln(sw.outputs['Output'], go.inputs['Geometry'])
        for i, node in enumerate((gi, nam, bnot, band, dg, oi,
                                  na, iop, sm, smw, ri, md,
                                  pos, off, ex, cmp, sw, go)):
            node.location = (200 * (i % 6), -240 * (i // 6))
        return ng

    class OBJECT_OT_symmetric_sculpture_add(bpy.types.Operator):
        """Set up a Hart-style symmetric sculpture: a flat motif in
        one plane, replicated live into the whole plane family by a
        Geometry Nodes modifier"""
        bl_idname = "object.symmetric_sculpture_add"
        bl_label = "Symmetric Sculpture"
        bl_options = {'REGISTER', 'UNDO'}

        preset: EnumProperty(
            name="Preset",
            items=[('TWISTED_RIVERS', "Twisted Rivers",
                    "After Twisted Rivers, Knotted Sea (2001): "
                    "C-shaped rivers in the 20 icosahedral planes, "
                    "three per plane"),
                   ('TUMBLEWEED', "Tumbleweed",
                    "After Tumbleweed (2006): swirling five-armed "
                    "pinwheels in the 12 dodecahedral planes"),
                   ('FRABJOUS', "Frabjous",
                    "After Frabjous (2003): 30 S-shaped parts in the "
                    "triacontahedral planes, each S assembled from "
                    "two half-arms by the in-plane 2-fold symmetry"),
                   ('CUSTOM', "Custom",
                    "Choose the group and plane family yourself; "
                    "starts from the demo arc motif")],
            default='TWISTED_RIVERS',
            description="Sculpture setups after Hart's pieces; the "
                        "motif stays editable afterwards")
        group: EnumProperty(
            name="Symmetry Group",
            items=[('ICOSA', "Icosahedral (60)",
                    "60 rotations -- Hart's usual choice"),
                   ('OCTA', "Octahedral (24)", "24 rotations"),
                   ('TETRA', "Tetrahedral (12)", "12 rotations")],
            default='ICOSA')
        family: EnumProperty(
            name="Plane Family",
            items=[('P5', "5-fold planes (dodecahedral)",
                    "12 planes, 5-fold symmetry in each "
                    "(icosahedral group only)"),
                   ('P4', "4-fold planes (cube)",
                    "6 planes, 4-fold each (octahedral group only)"),
                   ('P3', "3-fold planes (icosahedral)",
                    "Planes perpendicular to the 3-fold axes: 20 for "
                    "the icosahedral group (Hart's Twisted Rivers), "
                    "8 octahedral, 4 tetrahedral"),
                   ('P2', "2-fold planes (triacontahedral)",
                    "Planes perpendicular to the 2-fold axes: 30 "
                    "icosahedral (Frabjous), 12 octahedral, 6 "
                    "tetrahedral"),
                   ('P1', "General planes (hexecontahedral)",
                    "A full-orbit family with no in-plane symmetry: "
                    "60 / 24 / 12 planes")],
            default='P3')
        distance: FloatProperty(
            name="Plane Distance", default=1.0, min=0.1, max=10.0,
            description="Distance of the plane family from the origin")
        shell: FloatProperty(
            name="Shell", default=0.04, min=0.0, max=1.0,
            description="Radial extrusion fraction (Hart used ~4%); "
                        "0 keeps the flat planes")
        guide_extent: FloatProperty(
            name="Guide Extent", default=2.2, min=1.0, max=8.0,
            description="Radius of the guide pattern, in units of "
                        "the plane distance")
        use_active: BoolProperty(
            name="Use Active Object as Motif", default=False,
            description="Place the active mesh object into the "
                        "representative plane instead of creating "
                        "the demo arc motif (draw it flat in its "
                        "local XY plane)")

        def execute(self, context):
            motif_builder = demo_motif
            if self.preset in PRESETS:
                g, f, motif_builder = PRESETS[self.preset]
                self.group, self.family = g, f
            kind, family = self.group, self.family
            if (kind, family) not in _AXES:
                family = 'P3'
                self.report({'WARNING'},
                            "Plane family not available for this "
                            "group -- using 3-fold planes")
            rots = group_rotations(kind)
            a, normals = plane_normals(kind, family)
            u, v = _frame(a)
            d = self.distance

            motif = None
            if self.use_active:
                ao = context.active_object
                if ao is not None and ao.type == 'MESH':
                    motif = ao
                else:
                    self.report({'WARNING'},
                                "No active mesh object -- created "
                                "the demo motif instead")
            if motif is None:
                verts, faces = motif_builder(d)
                me = bpy.data.meshes.new("SymSculpt Motif")
                me.from_pydata(verts, [], faces)
                me.validate()
                me.update()
                motif = bpy.data.objects.new("SymSculpt Motif", me)
                context.collection.objects.link(motif)
            plane = Matrix((
                (u[0], v[0], a[0], d * a[0]),
                (u[1], v[1], a[1], d * a[1]),
                (u[2], v[2], a[2], d * a[2]),
                (0.0, 0.0, 0.0, 1.0)))
            motif.matrix_world = plane
            if not motif.data.materials:
                motif.data.materials.append(_motif_material())

            # guide pattern (stellation diagram) in the same plane
            segs = stellation_lines(kind, family, d, self.guide_extent)
            gverts = []
            gedges = []
            for (p0, p1) in segs:
                gverts.append((p0[0], p0[1], 0.0))
                gverts.append((p1[0], p1[1], 0.0))
                gedges.append((len(gverts) - 2, len(gverts) - 1))
            gme = bpy.data.meshes.new("SymSculpt Guides")
            gme.from_pydata(gverts, gedges, [])
            gme.update()
            guides = bpy.data.objects.new("SymSculpt Guides", gme)
            context.collection.objects.link(guides)
            guides.matrix_world = plane
            guides.display_type = 'WIRE'
            guides.hide_render = True

            # the sculpture: one point per rotation, euler attribute
            pts = bpy.data.meshes.new("SymSculpt")
            pts.from_pydata([(0.0, 0.0, 0.0)] * len(rots), [], [])
            attr = pts.attributes.new("sym_rot", 'FLOAT_VECTOR',
                                      'POINT')
            eulers = []
            for R in rots:
                eulers.extend(Matrix(R).to_euler())
            attr.data.foreach_set('vector', eulers)
            attr = pts.attributes.new("copy_index", 'INT', 'POINT')
            attr.data.foreach_set('value', list(range(len(rots))))
            attr = pts.attributes.new("is_motif", 'BOOLEAN', 'POINT')
            attr.data.foreach_set(
                'value',
                [all(abs(R[i][j] - (1.0 if i == j else 0.0)) < 1e-9
                     for i in range(3) for j in range(3))
                 for R in rots])
            obj = bpy.data.objects.new("SymSculpt", pts)
            context.collection.objects.link(obj)

            mod = obj.modifiers.new("Symmetric Sculpture", 'NODES')
            ng = _node_group()
            mod.node_group = ng
            for item in ng.interface.items_tree:
                if item.name == 'Motif' and item.in_out == 'INPUT':
                    mod[item.identifier] = motif
                elif item.name == 'Shell' and item.in_out == 'INPUT':
                    mod[item.identifier] = self.shell

            motif.parent = obj
            motif.matrix_parent_inverse = Matrix.Identity(4)
            guides.parent = obj
            guides.matrix_parent_inverse = Matrix.Identity(4)

            for o in context.selected_objects:
                o.select_set(False)
            obj.select_set(True)
            motif.select_set(True)
            context.view_layer.objects.active = obj
            fold = len(rots) // len(normals)
            self.report(
                {'INFO'},
                f"{len(normals)} planes x {fold}-fold: edit the "
                f"Motif object and every copy follows")
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            lay.prop(self, 'preset')
            for k in ('group', 'family'):
                if self.preset == 'CUSTOM':
                    lay.prop(self, k)
            for k in ('distance', 'shell', 'guide_extent',
                      'use_active'):
                lay.prop(self, k)

    def _menu_func(self, context):
        self.layout.operator_menu_enum(
            "object.symmetric_sculpture_add", "preset",
            text="Symmetric Sculpture", icon='MOD_MIRROR')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(OBJECT_OT_symmetric_sculpture_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.remove(_menu_func)
        bpy.utils.unregister_class(
            OBJECT_OT_symmetric_sculpture_add)


if __name__ == "__main__":
    if _IN_BLENDER:
        register()
    else:
        # group orders and plane-family counts
        for kind, order in _ORDER.items():
            rots = group_rotations(kind)
            print(f"{kind}: {len(rots)} rotations "
                  f"{'OK' if len(rots) == order else 'BAD'}")
        expect = {('ICOSA', 'P5'): 12, ('ICOSA', 'P3'): 20,
                  ('ICOSA', 'P2'): 30, ('ICOSA', 'P1'): 60,
                  ('OCTA', 'P4'): 6, ('OCTA', 'P3'): 8,
                  ('OCTA', 'P2'): 12, ('OCTA', 'P1'): 24,
                  ('TETRA', 'P3'): 4, ('TETRA', 'P2'): 6,
                  ('TETRA', 'P1'): 12}
        for (kind, fam), n in expect.items():
            _, normals = plane_normals(kind, fam)
            ok = len(normals) == n
            print(f"{kind}/{fam}: {len(normals)} planes "
                  f"(want {n}) {'OK' if ok else 'BAD'}")
        # icosa 3-fold: 18 guide lines (19 others minus the parallel)
        segs = stellation_lines('ICOSA', 'P3', 1.0, 10.0)
        print(f"ICOSA/P3 guide lines: {len(segs)} "
              f"{'OK' if len(segs) == 18 else 'BAD'}")
