
# Symmetric Sculpture designer for Blender
#
# After George W. Hart's sculpture design program described in
# "Symmetric sculpture", Journal of Mathematics and the Arts 1(1),
# 2007, pp. 21-28, doi:10.1080/17513470701228040 -- and its
# precursor, "Sculpture from Symmetrically Arranged Planar
# Components", Bridges 2003, pp. 315-322 (the tool behind Twisted
# Rivers, Tumbleweed, Frabjous, Spaghetti Code, ...).
#
# References:
#   G. W. Hart, "Symmetric sculpture", J. Mathematics and the Arts
#     1(1), 2007, 21-28.  doi:10.1080/17513470701228040
#   G. W. Hart, "Sculpture from Symmetrically Arranged Planar
#     Components", Bridges 2003, 315-322.
#   H. S. M. Coxeter, P. Du Val, H. T. Flather, J. F. Petrie, "The
#     Fifty-Nine Icosahedra", U. Toronto Press, 1938 -- the
#     stellation pattern drawn as the editing guides.
#
# A flat motif drawn in ONE representative
# plane is replicated live into a whole family of symmetrically
# arranged planes -- the extended face planes of an icosahedron,
# dodecahedron, rhombic triacontahedron or hexecontahedron (or their
# octahedral / tetrahedral analogues).
#
# The replication is done with a Geometry Nodes modifier: a motif
# placed in a plane perpendicular to a k-fold axis and instanced
# under all N rotations of the chosen point group automatically
# lands in N/k planes with k-fold symmetry inside each plane, which
# is exactly Hart's plane-family construction. Three objects are
# created:
#
#   SymSculpt         points + Geometry Nodes modifier (the result)
#   SymSculpt Motif   flat mesh on the world XY plane -- edit this
#                     (edit mode, or move/rotate the object) and every
#                     copy updates in real time; the node group maps
#                     it onto the representative plane
#   SymSculpt Guides  wireframe stellation pattern: the lines where
#                     the other planes of the family cut this one,
#                     for snapping/drawing against, as in Hart's 2D
#                     editor window
#
# The modifier's "Shell" input radially extrudes the surface away
# from the origin by that fraction of its distance (Hart's ~4%
# radial extrusion, which preserves planarity and yields a watertight
# solid for 3D printing); "Weld" merges coincident vertices where
# copies meet exactly on the plane-intersection lines; "Lift" raises
# the replicated sculpture up +Z so it no longer surrounds the Motif
# and Guides, which stay at the origin where they can be drawn on
# (only the modifier result moves -- the objects themselves stay put,
# so the sculpture keeps its true position for export); "Translucent"
# swaps the copies onto a ghost material so the motif reads through
# them, off by default.

bl_info = {
    "name": "Symmetric Sculpture",
    "author": "Math Art project (after George W. Hart)",
    "version": (1, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Mesh > Symmetric Sculpture",
    "description": "Replicate a flat motif into symmetric plane "
                   "families, live, after Hart's sculpture software",
    "category": "Add Mesh",
}

import math
from math import cos, sin, pi, sqrt

PHI = (1 + sqrt(5)) / 2


# ---------------------------------------------------------------- #
#  rotation groups by closure                                      #
# ---------------------------------------------------------------- #

def _rot(axis, ang):
    """3x3 rotation about axis by ang (Rodrigues)."""
    x, y, z = axis
    l = sqrt(x * x + y * y + z * z)
    x, y, z = x / l, y / l, z / l
    c, s = cos(ang), sin(ang)
    C = 1 - c
    return ((c + x * x * C, x * y * C - z * s, x * z * C + y * s),
            (y * x * C + z * s, c + y * y * C, y * z * C - x * s),
            (z * x * C - y * s, z * y * C + x * s, c + z * z * C))


def _mul(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3))
                       for j in range(3)) for i in range(3))


def _apply(A, v):
    return tuple(sum(A[i][k] * v[k] for k in range(3)) for i in range(3))


def _key(A):
    return tuple(round(A[i][j], 9) for i in range(3) for j in range(3))


_GENS = {
    'TETRA': (_rot((1, 1, 1), 2 * pi / 3), _rot((0, 0, 1), pi)),
    'OCTA': (_rot((0, 0, 1), pi / 2), _rot((1, 1, 1), 2 * pi / 3)),
    'ICOSA': (_rot((0, 1, PHI), 2 * pi / 5), _rot((1, 1, 1), 2 * pi / 3)),
}
_ORDER = {'TETRA': 12, 'OCTA': 24, 'ICOSA': 60}


def group_rotations(kind):
    """All rotations of the chiral tetrahedral / octahedral /
    icosahedral group, generated by closure."""
    gens = _GENS[kind]
    seen = {}
    I = ((1.0, 0, 0), (0, 1.0, 0), (0, 0, 1.0))
    frontier = [I]
    seen[_key(I)] = I
    while frontier:
        nxt = []
        for A in frontier:
            for G in gens:
                B = _mul(G, A)
                k = _key(B)
                if k not in seen:
                    seen[k] = B
                    nxt.append(B)
        frontier = nxt
    rots = list(seen.values())
    assert len(rots) == _ORDER[kind], (kind, len(rots))
    return rots


# plane-family axis per (group, family); the plane sits at distance
# d perpendicular to this axis.
_AXES = {
    ('ICOSA', 'P5'): (0.0, 1.0, PHI),      # 12 planes, 5-fold each
    ('ICOSA', 'P3'): (1.0, 1.0, 1.0),      # 20 planes, 3-fold
    ('ICOSA', 'P2'): (0.0, 0.0, 1.0),      # 30 planes, 2-fold
    # 60 planes, no in-plane symmetry; the axis is a snub
    # dodecahedron vertex direction, so these are the face
    # planes of the pentagonal hexecontahedron (Hart's Whimsy)
    ('ICOSA', 'P1'): (0.089963, -0.816073, -0.570904),
    ('OCTA', 'P4'): (0.0, 0.0, 1.0),       # 6 planes (cube), 4-fold
    ('OCTA', 'P3'): (1.0, 1.0, 1.0),       # 8 planes, 3-fold
    ('OCTA', 'P2'): (1.0, 1.0, 0.0),       # 12 planes, 2-fold
    ('OCTA', 'P1'): (0.21, 0.45, 1.0),     # 24 planes
    ('TETRA', 'P3'): (1.0, 1.0, 1.0),      # 4 planes, 3-fold
    ('TETRA', 'P2'): (0.0, 0.0, 1.0),      # 6 planes, 2-fold
    ('TETRA', 'P1'): (0.21, 0.45, 1.0),    # 12 planes
}


def _normalize(v):
    l = sqrt(sum(c * c for c in v))
    return tuple(c / l for c in v)


def plane_normals(kind, family):
    """Distinct unit normals of the plane family = orbit of the axis
    under the group. Returns (axis, normals)."""
    a = _normalize(_AXES[(kind, family)])
    seen = {}
    for R in group_rotations(kind):
        b = _apply(R, a)
        k = tuple(round(c, 6) for c in b)
        if k not in seen:
            seen[k] = b
    return a, list(seen.values())


def _frame(a):
    """Right-handed orthonormal (u, v, a)."""
    t = (0.0, 0.0, 1.0) if abs(a[2]) < 0.9 else (1.0, 0.0, 0.0)
    u = _normalize((t[1] * a[2] - t[2] * a[1],
                    t[2] * a[0] - t[0] * a[2],
                    t[0] * a[1] - t[1] * a[0]))
    v = (a[1] * u[2] - a[2] * u[1],
         a[2] * u[0] - a[0] * u[2],
         a[0] * u[1] - a[1] * u[0])
    return u, v


# Which solid's extended face planes each (group, family) actually
# is.  A plane perpendicular to a k-fold axis is held by k of the
# group's N rotations, so the orbit is N/k planes carrying k copies
# apiece -- the same "P3" therefore means 20 icosahedral planes under
# the icosahedral group but 8 octahedral ones under the octahedral.
_FAMILY_SOLID = {
    ('ICOSA', 'P5'): (12, "dodecahedral"),
    ('ICOSA', 'P3'): (20, "icosahedral"),
    ('ICOSA', 'P2'): (30, "triacontahedral"),
    ('ICOSA', 'P1'): (60, "hexecontahedral"),
    ('OCTA', 'P4'): (6, "cube"),
    ('OCTA', 'P3'): (8, "octahedral"),
    ('OCTA', 'P2'): (12, "rhombic dodecahedral"),
    ('OCTA', 'P1'): (24, ""),
    ('TETRA', 'P3'): (4, "tetrahedral"),
    ('TETRA', 'P2'): (6, "cube"),
    ('TETRA', 'P1'): (12, ""),
}
_FOLD = {'P5': 5, 'P4': 4, 'P3': 3, 'P2': 2, 'P1': 1}


def family_label(kind, family):
    """Human label for a plane family under one particular group."""
    n, solid = _FAMILY_SOLID[(kind, family)]
    k = _FOLD[family]
    where = f"{n} {solid} planes" if solid else f"{n} planes"
    if k == 1:
        return f"General: {where}"
    return f"{k}-fold: {where}"


def guide_ring_radii(kind, family, d=1.0):
    """Sorted distinct foot radii of the family's guide lines.

    The stellation pattern is built of concentric rings of lines: all
    the lines at one radius are equivalent under the plane's own
    k-fold symmetry.  Counting rings from the middle outwards gives a
    natural way to thin the pattern down."""
    a, normals = plane_normals(kind, family)
    u, v = _frame(a)
    seen = []
    for b in normals:
        ab = sum(x * y for x, y in zip(a, b))
        if abs(ab) > 1 - 1e-9:
            continue
        Bu = sum(x * y for x, y in zip(b, u))
        Bv = sum(x * y for x, y in zip(b, v))
        n2 = Bu * Bu + Bv * Bv
        c = d * (1 - ab)
        r = sqrt((c * Bu / n2) ** 2 + (c * Bv / n2) ** 2)
        if not any(abs(r - s) < 1e-6 for s in seen):
            seen.append(r)
    return sorted(seen)


def family_polyhedron(kind, family, d=1.0):
    """The solid whose extended face planes ARE this plane family:
    the intersection of the half-spaces {x : x.n <= d} over the
    family's normals.  Returns (verts, faces).

    Built face by face rather than by intersecting triples of planes:
    each face starts as a big square lying in its own plane and is
    clipped by every other half-space, which is O(F^2) instead of
    O(F^3) and hands back the face polygons already in order."""
    _, normals = plane_normals(kind, family)
    big = 40.0 * d
    verts = []
    faces = []
    index = {}
    for n in normals:
        u, v = _frame(n)
        poly = [(-big, -big), (big, -big), (big, big), (-big, big)]
        for m in normals:
            if m is n:
                continue
            A = sum(x * y for x, y in zip(u, m))
            B = sum(x * y for x, y in zip(v, m))
            C = d - d * sum(x * y for x, y in zip(n, m))
            if abs(A) < 1e-12 and abs(B) < 1e-12:
                continue                  # parallel: no constraint here
            out = []
            k = len(poly)
            for i in range(k):
                p0, p1 = poly[i], poly[(i + 1) % k]
                f0 = A * p0[0] + B * p0[1] - C
                f1 = A * p1[0] + B * p1[1] - C
                if f0 <= 1e-12:
                    out.append(p0)
                if (f0 > 1e-12) != (f1 > 1e-12):
                    t = f0 / (f0 - f1)
                    out.append((p0[0] + t * (p1[0] - p0[0]),
                                p0[1] + t * (p1[1] - p0[1])))
            poly = out
            if len(poly) < 3:
                break
        if len(poly) < 3:
            continue
        face = []
        for x, y in poly:
            p = tuple(d * n[i] + x * u[i] + y * v[i] for i in range(3))
            key = tuple(round(c, 6) for c in p)
            if key not in index:
                index[key] = len(verts)
                verts.append(p)
            j = index[key]
            if j not in face:
                face.append(j)
        if len(face) >= 3:
            faces.append(face)
    return verts, faces


def crossing_points(kind, family, d=1.0, extent=3.2, rings=0):
    """Where the drawn guide lines cross, as (x, y, lines).

    These are the points a motif's corners want to sit on: a crossing
    of k guide lines is a point where k+1 planes of the family meet,
    so k+1 parts converge there and the joint closes exactly.  `lines`
    is that k, which is what distinguishes a plain corner from a hub
    where a whole rosette meets.

    Derived from the segments stellation_lines actually emits, so
    thinning the pattern with `rings` thins the crossings with it."""
    segs = stellation_lines(kind, family, d, extent, rings)
    lines = []
    for p0, p1 in segs:
        A = p1[1] - p0[1]
        B = p0[0] - p1[0]
        n = sqrt(A * A + B * B)
        if n < 1e-12:
            continue
        lines.append((A / n, B / n, (A * p0[0] + B * p0[1]) / n))
    pts = []
    for i in range(len(lines)):
        a1, b1, c1 = lines[i]
        for j in range(i + 1, len(lines)):
            a2, b2, c2 = lines[j]
            det = a1 * b2 - a2 * b1
            if abs(det) < 1e-9:
                continue                  # parallel
            x = (c1 * b2 - c2 * b1) / det
            y = (a1 * c2 - a2 * c1) / det
            if sqrt(x * x + y * y) > extent * d + 1e-9:
                continue
            if any(abs(x - px) < 1e-6 and abs(y - py) < 1e-6
                   for px, py in pts):
                continue
            pts.append((x, y))
    out = []
    for x, y in pts:
        k = sum(1 for A, B, C in lines
                if abs(A * x + B * y - C) < 1e-6)
        out.append((x, y, k))
    return out


def crossing_orbits(kind, family, crossings, d=1.0):
    """Sort the crossings into orbits under the rotation group.

    Returns (points, groups): `points` is [(3-D point, group)] over
    every point equivalent to some crossing, and `groups[i]` is the
    group of `crossings[i]`.

    The orbit is the honest notion of "same kind of point" -- two
    crossings share a group exactly when a rotation of the sculpture
    carries one onto the other, so they play identical roles in the
    design.  Orbits come out at the group's own sizes: 12, 20, 30 or
    60 for the icosahedral rotations, according to whether the point
    sits on a 5-, 3- or 2-fold axis or on none.

    A crossing is a point of the plane arrangement and so recurs in
    every plane through it; carrying the representative plane's
    crossings around the group is what shows where they all sit
    relative to the defining solid."""
    a, _ = plane_normals(kind, family)
    u, v = _frame(a)
    rots = group_rotations(kind)
    seen = {}
    points = []
    groups = []
    nxt = 0
    for x, y, _k in crossings:
        p = tuple(d * a[i] + x * u[i] + y * v[i] for i in range(3))
        key = tuple(round(c, 5) for c in p)
        if key in seen:
            groups.append(seen[key])       # already in an earlier orbit
            continue
        g = nxt
        nxt += 1
        groups.append(g)
        for R in rots:
            q = _apply(R, p)
            kq = tuple(round(c, 5) for c in q)
            if kq in seen:
                continue
            seen[kq] = g
            points.append((q, g))
    return points, groups


def max_line_foot(kind, family, d=1.0):
    """Largest foot radius over the family's guide lines -- the
    smallest guide extent that still emits every line.

    A line is dropped entirely once its foot (the point of the line
    closest to the plane centre) falls outside the guide disc, so an
    extent below this silently loses the outermost lines -- and with
    them the intersections the outer corners of a motif snap to.  For
    the icosahedral 2-fold planes (Frabjous) this is phi^2 + 1/phi^2
    ~ 3.078, while the pointed ends of the parts reach out to the
    3-fold piercings at phi^2 ~ 2.618."""
    a, normals = plane_normals(kind, family)
    u, v = _frame(a)
    best = 0.0
    for b in normals:
        ab = sum(x * y for x, y in zip(a, b))
        if abs(ab) > 1 - 1e-9:
            continue
        Bu = sum(x * y for x, y in zip(b, u))
        Bv = sum(x * y for x, y in zip(b, v))
        n2 = Bu * Bu + Bv * Bv
        c = d * (1 - ab)
        best = max(best, sqrt((c * Bu / n2) ** 2 + (c * Bv / n2) ** 2))
    return best


def stellation_lines(kind, family, d=1.0, extent=3.0, rings=0):
    """The guide pattern of Hart's 2D editor: line segments (in the
    representative plane's local xy coordinates) where the other
    planes of the family cut it, clipped to a disc of radius
    extent * d.

    rings > 0 keeps only the innermost `rings` concentric rings of
    lines (see guide_ring_radii), thinning a crowded pattern down to
    the lines nearest the centre.  Note the outer rings are the ones
    carrying the far corners a motif may reach for, so cutting rings
    trades reach for legibility."""
    a, normals = plane_normals(kind, family)
    u, v = _frame(a)
    R = extent * d
    keep = None
    if rings > 0:
        keep = guide_ring_radii(kind, family, d)[:rings]
    segs = []
    for b in normals:
        ab = sum(x * y for x, y in zip(a, b))
        if abs(ab) > 1 - 1e-9:
            continue                      # this plane or its parallel
        Bu = sum(x * y for x, y in zip(b, u))
        Bv = sum(x * y for x, y in zip(b, v))
        c = d * (1 - ab)
        n2 = Bu * Bu + Bv * Bv
        px, py = c * Bu / n2, c * Bv / n2  # foot of the line
        if keep is not None and not any(
                abs(sqrt(px * px + py * py) - s) < 1e-6 for s in keep):
            continue                      # outside the kept rings
        h2 = R * R - (px * px + py * py)
        if h2 <= 0:
            continue                      # line misses the guide disc
        h = sqrt(h2)
        tl = sqrt(n2)
        tx, ty = -Bv / tl, Bu / tl
        segs.append(((px - h * tx, py - h * ty),
                     (px + h * tx, py + h * ty)))
    return segs


def sculpture_radius(verts, d, shell=0.0):
    """Outer radius of the finished sculpture, from the motif alone.

    The node group maps a motif vertex (x, y, z) onto the
    representative plane as x*u + y*v + (z + d)*a, and u, v, a are
    orthonormal -- so that vertex sits sqrt(x^2 + y^2 + (z+d)^2) from
    the origin.  Every copy is a rotation about the origin, so the
    whole sculpture is bounded by the largest such radius, and the
    radial shell scales it by (1 + shell)."""
    r = 0.0
    for x, y, z in verts:
        r = max(r, sqrt(x * x + y * y + (z + d) * (z + d)))
    return r * (1.0 + shell)


def lift_height(verts, d, shell=0.0, margin=0.3):
    """Lift that clears the motif by `margin` of the sculpture's own
    radius.

    The sculpture surrounds the origin, so its lowest point sits one
    radius below the motif plane; raising it by that radius brings it
    down exactly onto the motif, and the margin opens the gap.  Scaled
    to the actual geometry rather than a fixed multiple of the plane
    distance, because a motif reaching far out in its plane (Frabjous
    runs to phi^2) makes a far bigger sculpture than a compact one
    (Tumbleweed) at the very same plane distance."""
    return sculpture_radius(verts, d, shell) * (1.0 + margin)


def _ribbon(path, widths):
    """Flat quad-strip mesh (verts, faces) along a 2D centerline
    with per-point half-widths."""
    verts = []
    faces = []
    n = len(path)
    for i, (x, y) in enumerate(path):
        x0, y0 = path[max(i - 1, 0)]
        x1, y1 = path[min(i + 1, n - 1)]
        tx, ty = x1 - x0, y1 - y0
        l = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / l, tx / l
        w = widths[i]
        verts.append((x - nx * w, y - ny * w, 0.0))
        verts.append((x + nx * w, y + ny * w, 0.0))
    for i in range(n - 1):
        k = 2 * i
        faces.append([k, k + 2, k + 3, k + 1])
    return verts, faces


def demo_motif(d=1.0):
    """Default motif: a flat C-shaped ribbon arc in the local xy
    plane -- with 3-fold in-plane replication this gives the curved
    'rivers' of Hart's Twisted Rivers, Knotted Sea."""
    r_mid = 0.52 * d
    a0, a1 = math.radians(15), math.radians(200)
    steps = 28
    path = []
    widths = []
    for i in range(steps + 1):
        t = i / steps
        ang = a0 + (a1 - a0) * t
        path.append((r_mid * cos(ang), r_mid * sin(ang)))
        widths.append(0.075 * d * (0.25 + 0.75 * sin(pi * t)))
    return _ribbon(path, widths)


def tumbleweed_motif(d=1.0):
    """One swirling pinwheel arm; the 5-fold symmetry of the
    dodecahedral planes turns it into the flower of Hart's
    Tumbleweed (12 planes x 5 arms)."""
    steps = 32
    a0 = math.radians(-25)
    sweep = math.radians(150)
    path = []
    widths = []
    for i in range(steps + 1):
        t = i / steps
        ang = a0 + sweep * t ** 1.15    # curl tightens outward
        r = d * (0.12 + 0.63 * t ** 0.9)
        path.append((r * cos(ang), r * sin(ang)))
        widths.append(d * (0.02 + 0.055 * sin(pi * t) ** 0.7))
    return _ribbon(path, widths)


def _spline(pts, m):
    """Catmull-Rom resample of a 2D control polyline."""
    pts = [pts[0]] + list(pts) + [pts[-1]]
    out = []
    segs = len(pts) - 3
    for i in range(segs):
        p0, p1, p2, p3 = pts[i], pts[i + 1], pts[i + 2], pts[i + 3]
        steps = m if i < segs - 1 else m + 1
        for k in range(steps):
            t = k / m
            t2, t3 = t * t, t * t * t
            out.append(tuple(
                0.5 * ((2 * p1[j]) + (-p0[j] + p2[j]) * t
                       + (2 * p0[j] - 5 * p1[j] + 4 * p2[j]
                          - p3[j]) * t2
                       + (-p0[j] + 3 * p1[j] - 3 * p2[j]
                          + p3[j]) * t3)
                for j in range(2)))
    return out


def _earclip(poly):
    """Triangulate a simple 2D polygon (list of (x, y), CCW)."""
    idx = list(range(len(poly)))
    area2 = sum(poly[i][0] * poly[(i + 1) % len(poly)][1]
                - poly[(i + 1) % len(poly)][0] * poly[i][1]
                for i in range(len(poly)))
    if area2 < 0:
        idx.reverse()
    tris = []
    guard = 0
    while len(idx) > 3 and guard < 10000:
        guard += 1
        n = len(idx)
        for k in range(n):
            a, b, c = idx[k - 1], idx[k], idx[(k + 1) % n]
            ax, ay = poly[a]
            bx, by = poly[b]
            cx, cy = poly[c]
            cross = (bx - ax) * (cy - ay) - (by - ay) * (cx - ax)
            if cross <= 1e-12:
                continue
            ok = True
            for j in idx:
                if j in (a, b, c):
                    continue
                px, py = poly[j]
                # Skip by POSITION, not just by index: bridging a hole
                # into the outer loop duplicates two vertices, and a
                # duplicate carries a different index while sitting
                # exactly on the candidate ear's boundary -- counted
                # as "inside", it would veto every ear in turn and
                # stall the triangulation.
                if ((abs(px - ax) < 1e-12 and abs(py - ay) < 1e-12)
                        or (abs(px - bx) < 1e-12 and abs(py - by) < 1e-12)
                        or (abs(px - cx) < 1e-12
                            and abs(py - cy) < 1e-12)):
                    continue
                d1 = (bx - ax) * (py - ay) - (by - ay) * (px - ax)
                d2 = (cx - bx) * (py - by) - (cy - by) * (px - bx)
                d3 = (ax - cx) * (py - cy) - (ay - cy) * (px - cx)
                if d1 >= -1e-12 and d2 >= -1e-12 and d3 >= -1e-12:
                    ok = False
                    break
            if ok:
                tris.append((a, b, c))
                idx.pop(k)
                break
        else:
            break
    if len(idx) == 3:
        tris.append(tuple(idx))
    return tris


def _bridge_holes(outer, holes):
    """Splice each hole into the outer loop along a bridge, giving one
    simple polygon that ear clipping can chew.

    The outer loop must run counter-clockwise and each hole clockwise;
    the hole is entered and left at the pair of vertices closest to
    each other, and both are duplicated so the seam has zero width."""
    poly = list(outer)
    # rightmost holes first: bridging them outward-in keeps later
    # bridges from having to cross an earlier seam
    for hole in sorted(holes, key=lambda h: -max(p[0] for p in h)):
        bi = bj = 0
        best = None
        for i, p in enumerate(poly):
            for j, q in enumerate(hole):
                dd = (p[0] - q[0]) ** 2 + (p[1] - q[1]) ** 2
                if best is None or dd < best:
                    best, bi, bj = dd, i, j
        ring = hole[bj:] + hole[:bj + 1]
        poly = poly[:bi + 1] + ring + poly[bi:]
    return poly


def polygon_with_holes(outer, holes):
    """(verts, faces) for a flat region bounded by `outer` with
    `holes` cut out of it."""
    poly = _bridge_holes(outer, holes)
    verts = [(x, y, 0.0) for x, y in poly]
    return verts, [list(t) for t in _earclip(poly)]


def frabjous_motif(d=1.0):
    """Half of one of the thirty S-shaped parts of Hart's
    Frabjous, drawn in a face plane of the GREAT rhombic
    triacontahedron: the plane at distance d perpendicular to a
    2-fold axis, with the rhombus corners at the piercings of
    the neighbouring 3-fold axes (+-phi^2 d on the local x axis,
    where the pointed ends of three parts meet) and 5-fold axes
    (+-phi d on the local y axis, the vortex openings the parts
    swirl around).  The in-plane 2-fold symmetry adds the other
    half of the S; the teardrop opening near the tip follows
    Hart's template."""
    PHI2 = PHI * PHI
    cl = _spline([(0.0, 0.0), (0.45 * d, 0.20 * d),
                  (0.95 * d, 0.35 * d), (1.45 * d, 0.44 * d),
                  (1.90 * d, 0.44 * d), (2.25 * d, 0.33 * d),
                  (2.50 * d, 0.16 * d), (PHI2 * d, 0.01 * d)],
                 6)
    wl = _spline([(0.0, 0.200 * d), (1.0, 0.190 * d),
                  (2.0, 0.180 * d), (3.0, 0.170 * d),
                  (4.0, 0.155 * d), (5.0, 0.130 * d),
                  (6.0, 0.080 * d), (7.0, 0.012 * d)], 6)
    n = len(cl)
    verts = []
    faces = []
    rows = []
    for i, (x, y) in enumerate(cl):
        x0, y0 = cl[max(i - 1, 0)]
        x1, y1 = cl[min(i + 1, n - 1)]
        tx, ty = x1 - x0, y1 - y0
        ln = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / ln, tx / ln
        w = wl[i][1]
        t = i / (n - 1)
        # teardrop opening near the tip: outer band stays
        # thick, a thin sliver remains on the inner side
        if 0.52 < t < 0.94:
            s = math.sin(math.pi * (t - 0.52) / 0.42)
            hole = 0.5 * (s ** 0.8)
        else:
            hole = 0.0
        f_out = 0.40
        o_edge = (x + nx * w, y + ny * w)
        h1 = (x + nx * w * (1 - 2 * f_out),
              y + ny * w * (1 - 2 * f_out))
        h2 = (x + nx * w * (1 - 2 * f_out - 2 * hole),
              y + ny * w * (1 - 2 * f_out - 2 * hole))
        i_edge = (x - nx * w, y - ny * w)
        base = len(verts)
        for px, py in (o_edge, h1, h2, i_edge):
            verts.append((px, py, 0.0))
        rows.append(base)
    for i in range(n - 1):
        b0, b1 = rows[i], rows[i + 1]
        faces.append([b0, b1, b1 + 1, b0 + 1])
        faces.append([b0 + 2, b1 + 2, b1 + 3, b0 + 3])
    return verts, faces


# Hart's Whimsy blade, traced from the laser-cutting template
# (Asset 1.svg) and fitted into the face plane of the pentagonal
# hexecontahedron.  Coordinates are the plane's local (x, y) in units
# of the plane distance d.
#
# The fit is fixed by the piece itself, not chosen: the blade has two
# sharp tips, and in the assembled sculpture five blades meet at each
# of the twelve 5-fold hubs while three meet at each of the twenty
# 3-fold corners (60 parts x 2 tips = 12x5 + 20x3 = 120).  So the
# tips land on the piercings of the nearest 5-fold and 3-fold axes,
# which fixes scale, rotation and position.  Which tip goes where is
# settled by the tip angles -- 67.45 deg and 111.87 deg, against
# 360/5 = 72 and 360/3 = 120 -- and the sharper tip's two straight
# edges then reproduce the face pentagon's own corner at the hub to
# within a quarter of a degree.  The reflection is settled the same
# way: as traced, the tip edge follows the pentagon edge to within
# 1.2 deg, where the mirror image is 22.4 deg out.
#
# Outline decimated (Douglas-Peucker, 0.05 svg units ~ 0.014% of the
# blade's length), so the curves are visually exact.

_WHIMSY_OUTER = (
    (-0.06298, -0.43738), (-0.14110, -0.28131), (-0.14817, -0.28105),
    (-0.15502, -0.28057), (-0.16229, -0.27976), (-0.16741, -0.27901),
    (-0.17360, -0.27785), (-0.17897, -0.27663), (-0.18530, -0.27489),
    (-0.18973, -0.27346), (-0.19452, -0.27169), (-0.20014, -0.26930),
    (-0.20597, -0.26640), (-0.21057, -0.26378), (-0.21538, -0.26067),
    (-0.21910, -0.25797), (-0.22266, -0.25513), (-0.22676, -0.25146),
    (-0.22992, -0.24832), (-0.23384, -0.24393), (-0.23718, -0.23972),
    (-0.24025, -0.23534), (-0.24355, -0.22997), (-0.24585, -0.22570),
    (-0.24852, -0.21998), (-0.25016, -0.21591), (-0.25196, -0.21084),
    (-0.25363, -0.20518), (-0.25514, -0.19892), (-0.25624, -0.19303),
    (-0.25708, -0.18707), (-0.25771, -0.17998), (-0.25798, -0.17385),
    (-0.25800, -0.16765), (-0.25758, -0.15828), (-0.25677, -0.14987),
    (-0.25582, -0.14302), (-0.25399, -0.13297), (-0.25205, -0.12451),
    (-0.24931, -0.11448), (-0.24631, -0.10504), (-0.24311, -0.09617),
    (-0.23896, -0.08584), (-0.23557, -0.07818), (-0.23123, -0.06909),
    (-0.22606, -0.05913), (-0.22056, -0.04933), (-0.21478, -0.03971),
    (-0.20810, -0.02935), (-0.20176, -0.02011), (-0.19520, -0.01109),
    (-0.18844, -0.00224), (-0.18080, +0.00726), (-0.17224, +0.01735),
    (-0.16421, +0.02637), (-0.15454, +0.03672), (-0.14543, +0.04601),
    (-0.13541, +0.05577), (-0.12446, +0.06596), (-0.11495, +0.07441),
    (-0.10453, +0.08329), (-0.09645, +0.08993), (-0.08337, +0.10020),
    (-0.07347, +0.10762), (-0.06263, +0.11540), (-0.05255, +0.12233),
    (-0.10596, +0.24549), (-0.24018, +0.24179), (-0.26057, +0.20224),
    (-0.26804, +0.18703), (-0.27474, +0.17265), (-0.27967, +0.16152),
    (-0.28626, +0.14572), (-0.29170, +0.13174), (-0.29783, +0.11476),
    (-0.30297, +0.09929), (-0.30812, +0.08244), (-0.31183, +0.06929),
    (-0.31702, +0.04923), (-0.32096, +0.03239), (-0.32420, +0.01735),
    (-0.32745, +0.00084), (-0.33097, -0.01934), (-0.33379, -0.03815),
    (-0.33584, -0.05418), (-0.33773, -0.07206), (-0.33917, -0.08957),
    (-0.34009, -0.10539), (-0.34077, -0.12393), (-0.34099, -0.13817),
    (-0.34090, -0.15827), (-0.34040, -0.17714), (-0.33932, -0.19917),
    (-0.33803, -0.21689), (-0.33632, -0.23444), (-0.33393, -0.25304),
    (-0.33176, -0.26625), (-0.32949, -0.27772), (-0.32641, -0.29078),
    (-0.32431, -0.29840), (-0.32164, -0.30710), (-0.31825, -0.31682),
    (-0.31524, -0.32460), (-0.31199, -0.33228), (-0.30735, -0.34225),
    (-0.30441, -0.34810), (-0.29938, -0.35748), (-0.29498, -0.36517),
    (-0.28880, -0.37537), (-0.28334, -0.38397), (-0.27583, -0.39532),
    (-0.26867, -0.40579), (-0.25856, -0.42014), (-0.23709, -0.44966),
)

_WHIMSY_HOLE_A = (
    (-0.13295, +0.20310), (-0.10413, +0.13670), (-0.11649, +0.12718),
    (-0.12628, +0.11932), (-0.13599, +0.11122), (-0.14560, +0.10289),
    (-0.15512, +0.09432), (-0.16629, +0.08383), (-0.17443, +0.07589),
    (-0.18248, +0.06773), (-0.19045, +0.05937), (-0.19830, +0.05079),
    (-0.20603, +0.04199), (-0.21362, +0.03297), (-0.22105, +0.02371),
    (-0.22830, +0.01421), (-0.23537, +0.00448), (-0.24223, -0.00551),
    (-0.24887, -0.01575), (-0.25494, -0.02568), (-0.26046, -0.03529),
    (-0.26574, -0.04510), (-0.27075, -0.05511), (-0.27546, -0.06530),
    (-0.27984, -0.07567), (-0.28190, -0.08092), (-0.28574, -0.09155),
    (-0.28917, -0.10233), (-0.29218, -0.11326), (-0.29351, -0.11877),
    (-0.29581, -0.12991), (-0.29761, -0.14118), (-0.29860, -0.14966),
    (-0.29927, -0.15812), (-0.29933, -0.13356), (-0.29908, -0.12139),
    (-0.29862, -0.10922), (-0.29795, -0.09699), (-0.29706, -0.08466),
    (-0.29504, -0.06370), (-0.29238, -0.04250), (-0.29031, -0.02860),
    (-0.28855, -0.01797), (-0.28593, -0.00351), (-0.28374, +0.00755),
    (-0.27878, +0.03023), (-0.27309, +0.05301), (-0.26680, +0.07525),
    (-0.26004, +0.09658), (-0.25652, +0.10679), (-0.25244, +0.11790),
    (-0.24905, +0.12668), (-0.24391, +0.13924), (-0.23536, +0.15867),
    (-0.22536, +0.17958), (-0.21452, +0.20087),
)

_WHIMSY_HOLE_B = (
    (-0.29598, -0.20694), (-0.29352, -0.21709), (-0.29037, -0.22713),
    (-0.28719, -0.23537), (-0.28363, -0.24315), (-0.27873, -0.25216),
    (-0.27312, -0.26088), (-0.26680, -0.26922), (-0.26221, -0.27455),
    (-0.25732, -0.27967), (-0.25213, -0.28456), (-0.24665, -0.28921),
    (-0.24089, -0.29359), (-0.23484, -0.29769), (-0.22938, -0.30100),
    (-0.22460, -0.30362), (-0.21970, -0.30608), (-0.21213, -0.30944),
    (-0.20694, -0.31147), (-0.19895, -0.31421), (-0.19349, -0.31582),
    (-0.18512, -0.31793), (-0.17654, -0.31966), (-0.16776, -0.32102),
    (-0.12809, -0.40025), (-0.21708, -0.40654), (-0.23026, -0.38810),
    (-0.24106, -0.37245), (-0.25005, -0.35881), (-0.25723, -0.34724),
    (-0.26359, -0.33620), (-0.26919, -0.32552), (-0.27411, -0.31503),
    (-0.27841, -0.30455), (-0.28225, -0.29360), (-0.28562, -0.28218),
    (-0.28853, -0.27019), (-0.29103, -0.25754), (-0.29333, -0.24291),
    (-0.29509, -0.22863), (-0.29652, -0.21389), (-0.29777, -0.19673),
)


def whimsy_motif(d=1.0):
    """One of the sixty flat blades of Hart's Whimsy (2014), traced
    from the cutting template: a curved band pierced by two teardrop
    openings, running from a 5-fold hub to a 3-fold corner in a face
    plane of the pentagonal hexecontahedron (the snub dodecahedron's
    dual).  See the note above for how the placement is pinned."""
    outer = [(x * d, y * d) for x, y in _WHIMSY_OUTER]
    holes = [[(x * d, y * d) for x, y in _WHIMSY_HOLE_A],
             [(x * d, y * d) for x, y in _WHIMSY_HOLE_B]]
    return polygon_with_holes(outer, holes)


# preset -> (group, plane family, motif builder)
PRESETS = {
    'TWISTED_RIVERS': ('ICOSA', 'P3', demo_motif),
    'TUMBLEWEED': ('ICOSA', 'P5', tumbleweed_motif),
    'FRABJOUS': ('ICOSA', 'P2', frabjous_motif),
    'WHIMSY': ('ICOSA', 'P1', whimsy_motif),
}


try:
    import bpy
    from mathutils import Matrix
    from bpy.props import (FloatProperty, EnumProperty, BoolProperty,
                           StringProperty, IntProperty)
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    _NG_NAME = "Math Art Symmetric Sculpture"

    # Blender only borrows the strings a dynamic enum callback
    # returns, so the list has to stay alive on the Python side or
    # the UI reads freed memory.
    _FAMILY_ITEMS = []

    def _family_items(self, context):
        """Plane families available for the chosen group, named for
        the planes that group actually produces."""
        _FAMILY_ITEMS.clear()
        for fam in ('P5', 'P4', 'P3', 'P2', 'P1'):
            if (self.group, fam) not in _AXES:
                continue
            n, solid = _FAMILY_SOLID[(self.group, fam)]
            k = _FOLD[fam]
            desc = (f"{n} planes, no symmetry within each -- one copy "
                    f"of the motif per plane"
                    if k == 1 else
                    f"{n} planes perpendicular to the {k}-fold axes, "
                    f"{k} copies of the motif in each")
            # 5-tuples: a dynamic enum can only take an integer
            # default, so each family carries its fold as the number
            # and the property defaults to 3 (= P3, the one family
            # every group has)
            _FAMILY_ITEMS.append(
                (fam, family_label(self.group, fam), desc, '', k))
        return _FAMILY_ITEMS

    def _ghost_material():
        """Shared translucent material for the replicated copies, so
        the editable motif stands out from the full sculpture."""
        name = "SymSculpt Copies"
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        mat = bpy.data.materials.new(name)
        rgba = (0.55, 0.66, 0.78, 0.16)
        mat.diffuse_color = rgba          # solid-view translucency
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgba[:3], 1.0)
            bsdf.inputs["Alpha"].default_value = rgba[3]
            bsdf.inputs["Roughness"].default_value = 0.4
        if hasattr(mat, 'surface_render_method'):    # EEVEE Next
            mat.surface_render_method = 'BLENDED'
        elif hasattr(mat, 'blend_method'):           # legacy EEVEE
            mat.blend_method = 'BLEND'
        return mat

    # a viewport aid should not quietly build a hundred thousand
    # spheres; the general plane families can reach that
    _MAX_MARKS = 3000

    def _group_rgb(i):
        """Colour for orbit i.

        Stepping the hue by the golden angle puts consecutive orbits
        on opposite sides of the wheel, so neighbouring groups stay
        told apart however many there are -- a fixed palette would
        run out, since the general planes reach a couple of dozen
        orbits."""
        import colorsys
        h = (i * 0.6180339887498949) % 1.0
        s = 0.85 if i % 2 else 0.62
        v = 0.95 if i % 3 else 0.72
        return colorsys.hsv_to_rgb(h, s, v)

    def _class_material(i, alpha=1.0):
        name = f"SymSculpt Orbit {i}" + ("" if alpha >= 1.0 else " Ghost")
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        rgb = _group_rgb(i)
        mat = bpy.data.materials.new(name)
        mat.diffuse_color = (*rgb, alpha)
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
            bsdf.inputs["Alpha"].default_value = alpha
            bsdf.inputs["Roughness"].default_value = 0.4
        if alpha < 1.0:
            if hasattr(mat, 'surface_render_method'):
                mat.surface_render_method = 'BLENDED'
            elif hasattr(mat, 'blend_method'):
                mat.blend_method = 'BLEND'
        return mat

    def _solid_material():
        name = "SymSculpt Polyhedron"
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        mat = bpy.data.materials.new(name)
        rgba = (0.62, 0.68, 0.78, 0.12)
        mat.diffuse_color = rgba
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgba[:3], 1.0)
            bsdf.inputs["Alpha"].default_value = rgba[3]
            bsdf.inputs["Roughness"].default_value = 0.35
        if hasattr(mat, 'surface_render_method'):
            mat.surface_render_method = 'BLENDED'
        elif hasattr(mat, 'blend_method'):
            mat.blend_method = 'BLEND'
        return mat

    def _ball(c, r, seg=8, ring=6):
        """Low-res UV sphere at c -- a viewport marker, not geometry
        anyone will render closely."""
        verts = [(c[0], c[1], c[2] + r)]
        for j in range(1, ring):
            phi = pi * j / ring
            for i in range(seg):
                th = 2 * pi * i / seg
                verts.append((c[0] + r * sin(phi) * cos(th),
                              c[1] + r * sin(phi) * sin(th),
                              c[2] + r * cos(phi)))
        verts.append((c[0], c[1], c[2] - r))
        faces = []
        last = len(verts) - 1
        for i in range(seg):
            faces.append([0, 1 + i, 1 + (i + 1) % seg])
            faces.append([last, last - seg + (i + 1) % seg,
                          last - seg + i])
        for j in range(ring - 2):
            b0, b1 = 1 + j * seg, 1 + (j + 1) * seg
            for i in range(seg):
                k = (i + 1) % seg
                faces.append([b0 + i, b1 + i, b1 + k, b0 + k])
        return verts, faces

    def _disc(c, r, n=20):
        verts = [(c[0], c[1], c[2])]
        for i in range(n):
            th = 2 * pi * i / n
            verts.append((c[0] + r * cos(th), c[1] + r * sin(th), c[2]))
        return verts, [[0, 1 + i, 1 + (i + 1) % n] for i in range(n)]

    def _build_marker_object(name, chunks, alpha):
        """One object holding every marker, with a material slot per
        vertex class so the classes stay distinguishable."""
        verts = []
        faces = []
        slots = []
        used = {}
        for cls, (cv, cf) in chunks:
            if cls not in used:
                used[cls] = len(slots)
                slots.append(cls)
            base = len(verts)
            verts.extend(cv)
            faces.extend(([base + i for i in f], used[cls]) for f in cf)
        me = bpy.data.meshes.new(name)
        me.from_pydata(verts, [], [f for f, _ in faces])
        me.validate()
        me.update()
        for cls in slots:
            me.materials.append(_class_material(cls, alpha))
        for poly, (_, si) in zip(me.polygons, faces):
            poly.material_index = si
        obj = bpy.data.objects.new(name, me)
        return obj

    def _drive_z_from_lift(obj, sculpt, mod_name, socket):
        """Tie obj's Z to the modifier's Lift input.

        The solid and its vertex balls are the sculpture's own
        geometry, so they have to rise with it -- but the lift lives
        inside the node group and moves only the modifier's result.
        A driver keeps them together while Lift stays adjustable,
        where baking the height in would strand them the moment it
        was touched."""
        fc = obj.driver_add("location", 2)
        drv = fc.driver
        drv.type = 'SCRIPTED'
        var = drv.variables.new()
        var.name = "lift"
        var.type = 'SINGLE_PROP'
        var.targets[0].id = sculpt
        var.targets[0].data_path = (f'modifiers["{mod_name}"]'
                                    f'["{socket}"]')
        drv.expression = "lift"
        return fc

    def _motif_material():
        name = "SymSculpt Motif"
        mat = bpy.data.materials.get(name)
        if mat is not None:
            return mat
        mat = bpy.data.materials.new(name)
        rgb = (0.9, 0.45, 0.15)
        mat.diffuse_color = (*rgb, 1.0)
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf is not None:
            bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
            bsdf.inputs["Roughness"].default_value = 0.45
        return mat

    def _node_group():
        """Get or build the replicator node group: instance the motif
        object on the rotation points, optionally ghost the copies
        (Translucent), realize, weld, extrude radially from the origin
        (preserves planarity), and lift the result clear of the
        motif."""
        for ng in bpy.data.node_groups:
            if (ng.name.startswith(_NG_NAME)
                    and ng.type == 'GEOMETRY'
                    and any(it.name == 'Translucent'
                            for it in ng.interface.items_tree)):
                return ng
        ng = bpy.data.node_groups.new(_NG_NAME, 'GeometryNodeTree')
        face = ng.interface.new_socket
        face("Geometry", in_out='INPUT',
             socket_type='NodeSocketGeometry')
        face("Motif", in_out='INPUT', socket_type='NodeSocketObject')
        s = face("Shell", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 0.04, 0.0, 1.0
        s.description = "Radial extrusion as a fraction of the " \
                        "distance from the origin (0 = flat planes)"
        s = face("Weld", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 1e-4, 0.0, 0.1
        s.description = "Merge distance where copies meet exactly"
        s = face("Full Sculpture", in_out='INPUT',
                 socket_type='NodeSocketBool')
        s.default_value = False
        s.description = "Keep the copy that coincides with the " \
                        "editable Motif; off drops that one copy so " \
                        "the Motif object stands alone in its plane. " \
                        "Only has an effect while Lift is 0 -- a " \
                        "lifted sculpture is already clear of the " \
                        "motif, so every copy is kept"
        s = face("Translucent", in_out='INPUT',
                 socket_type='NodeSocketBool')
        s.default_value = False
        s.description = "Draw the replicated copies in the ghost " \
                        "Copy Material instead of the motif's own, " \
                        "so the editable motif reads through them. " \
                        "Off = the sculpture's real material"
        s = face("Lift", in_out='INPUT', socket_type='NodeSocketFloat')
        s.default_value, s.min_value, s.max_value = 0.0, 0.0, 100.0
        s.description = "Raise the whole sculpture this far up +Z, " \
                        "leaving the Motif and Guides behind at the " \
                        "origin so they can be seen and edited " \
                        "(0 = in place). Only the modifier result " \
                        "moves, not the objects; while lifted the " \
                        "motif's own copy is kept, since the " \
                        "sculpture is already out of the way"
        s = face("Copy Material", in_out='INPUT',
                 socket_type='NodeSocketMaterial')
        s.default_value = _ghost_material()
        s.description = "Material for the replicated copies while " \
                        "Translucent is on"
        s = face("Plane Rotation", in_out='INPUT',
                 socket_type='NodeSocketVector')
        s.description = "Euler rotation mapping the motif's XY " \
                        "plane onto the representative plane"
        s = face("Plane Offset", in_out='INPUT',
                 socket_type='NodeSocketVector')
        s.description = "Translation of the representative plane " \
                        "(distance x axis)"
        face("Geometry", in_out='OUTPUT',
             socket_type='NodeSocketGeometry')

        n = ng.nodes.new
        gi = n('NodeGroupInput')
        # design view: drop the point whose copy coincides with the
        # editable motif object (is_motif AND NOT Full Sculpture)
        nam = n('GeometryNodeInputNamedAttribute')
        nam.data_type = 'BOOLEAN'
        nam.inputs['Name'].default_value = "is_motif"
        bnot = n('FunctionNodeBooleanMath')
        bnot.operation = 'NOT'
        band = n('FunctionNodeBooleanMath')
        band.operation = 'AND'
        # a lifted sculpture already stands clear of the motif, so the
        # motif's own copy is only dropped while Lift is zero
        cmpl = n('FunctionNodeCompare')
        cmpl.data_type = 'FLOAT'
        cmpl.operation = 'GREATER_THAN'
        cmpl.inputs[1].default_value = 1e-6
        bnotl = n('FunctionNodeBooleanMath')
        bnotl.operation = 'NOT'
        bandl = n('FunctionNodeBooleanMath')
        bandl.operation = 'AND'
        dg = n('GeometryNodeDeleteGeometry')
        dg.domain = 'POINT'
        oi = n('GeometryNodeObjectInfo')
        oi.transform_space = 'RELATIVE'
        oi.inputs['As Instance'].default_value = True
        tg = n('GeometryNodeTransform')
        na = n('GeometryNodeInputNamedAttribute')
        na.data_type = 'FLOAT_VECTOR'
        na.inputs['Name'].default_value = "sym_rot"
        iop = n('GeometryNodeInstanceOnPoints')
        sm = n('GeometryNodeSetMaterial')
        smw = n('GeometryNodeSwitch')     # ghosts vs real materials
        smw.input_type = 'GEOMETRY'
        ri = n('GeometryNodeRealizeInstances')
        md = n('GeometryNodeMergeByDistance')
        pos = n('GeometryNodeInputPosition')
        off = n('ShaderNodeVectorMath')
        off.operation = 'SCALE'
        ex = n('GeometryNodeExtrudeMesh')
        ex.mode = 'FACES'
        ex.inputs['Individual'].default_value = False
        cmp = n('FunctionNodeCompare')
        cmp.data_type = 'FLOAT'
        cmp.operation = 'GREATER_THAN'
        cmp.inputs[1].default_value = 1e-5
        sw = n('GeometryNodeSwitch')
        sw.input_type = 'GEOMETRY'
        # the lift is applied LAST: the radial shell above offsets each
        # point along its own position vector, so translating before it
        # would change every point's distance from the origin and
        # corrupt the extrusion
        lz = n('ShaderNodeCombineXYZ')
        lt = n('GeometryNodeTransform')
        go = n('NodeGroupOutput')

        ln = ng.links.new
        ln(gi.outputs['Full Sculpture'], bnot.inputs[0])
        ln(nam.outputs['Attribute'], band.inputs[0])
        ln(bnot.outputs['Boolean'], band.inputs[1])
        ln(gi.outputs['Lift'], cmpl.inputs[0])
        ln(cmpl.outputs['Result'], bnotl.inputs[0])
        ln(band.outputs['Boolean'], bandl.inputs[0])
        ln(bnotl.outputs['Boolean'], bandl.inputs[1])
        ln(gi.outputs['Geometry'], dg.inputs['Geometry'])
        ln(bandl.outputs['Boolean'], dg.inputs['Selection'])
        ln(dg.outputs['Geometry'], iop.inputs['Points'])
        ln(gi.outputs['Motif'], oi.inputs['Object'])
        ln(oi.outputs['Geometry'], tg.inputs['Geometry'])
        ln(gi.outputs['Plane Rotation'], tg.inputs['Rotation'])
        ln(gi.outputs['Plane Offset'], tg.inputs['Translation'])
        ln(tg.outputs['Geometry'], iop.inputs['Instance'])
        ln(na.outputs['Attribute'], iop.inputs['Rotation'])
        ln(iop.outputs['Instances'], sm.inputs['Geometry'])
        ln(gi.outputs['Copy Material'], sm.inputs['Material'])
        ln(gi.outputs['Translucent'], smw.inputs['Switch'])
        ln(iop.outputs['Instances'], smw.inputs['False'])
        ln(sm.outputs['Geometry'], smw.inputs['True'])
        ln(smw.outputs['Output'], ri.inputs['Geometry'])
        ln(ri.outputs['Geometry'], md.inputs['Geometry'])
        ln(gi.outputs['Weld'], md.inputs['Distance'])
        ln(pos.outputs['Position'], off.inputs[0])
        ln(gi.outputs['Shell'], off.inputs['Scale'])
        ln(md.outputs['Geometry'], ex.inputs['Mesh'])
        ln(off.outputs['Vector'], ex.inputs['Offset'])
        ln(gi.outputs['Shell'], cmp.inputs[0])
        ln(cmp.outputs['Result'], sw.inputs['Switch'])
        ln(md.outputs['Geometry'], sw.inputs['False'])
        ln(ex.outputs['Mesh'], sw.inputs['True'])
        ln(gi.outputs['Lift'], lz.inputs['Z'])
        ln(sw.outputs['Output'], lt.inputs['Geometry'])
        ln(lz.outputs['Vector'], lt.inputs['Translation'])
        ln(lt.outputs['Geometry'], go.inputs['Geometry'])
        for i, node in enumerate((gi, nam, bnot, band, cmpl, bnotl,
                                  bandl, dg, oi, tg, na, iop, sm, smw,
                                  ri, md, pos, off, ex, cmp, sw, lz,
                                  lt, go)):
            node.location = (200 * (i % 6), -240 * (i // 6))
        return ng

    class OBJECT_OT_symmetric_sculpture_add(bpy.types.Operator):
        """Set up a Hart-style symmetric sculpture: a flat motif in
        one plane, replicated live into the whole plane family by a
        Geometry Nodes modifier"""
        bl_idname = "object.symmetric_sculpture_add"
        bl_label = "Symmetric Sculpture"
        bl_options = {'REGISTER', 'UNDO'}

        preset: EnumProperty(
            name="Preset",
            items=[('TWISTED_RIVERS', "Twisted Rivers",
                    "After Twisted Rivers, Knotted Sea (2001): "
                    "C-shaped rivers in the 20 icosahedral planes, "
                    "three per plane"),
                   ('TUMBLEWEED', "Tumbleweed",
                    "After Tumbleweed (2006): swirling five-armed "
                    "pinwheels in the 12 dodecahedral planes"),
                   ('FRABJOUS', "Frabjous",
                    "After Frabjous (2003): 30 S-shaped parts in "
                    "the face planes of the GREAT rhombic "
                    "triacontahedron -- ends meeting in threes at "
                    "the 3-fold corners (phi^2 x the plane "
                    "distance), five-fold vortices at the 5-fold "
                    "corners (phi x)"),
                   ('WHIMSY', "Whimsy",
                    "After Whimsy (2014): 60 flat blades in the "
                    "face planes of the pentagonal "
                    "hexecontahedron (snub dodecahedron dual). "
                    "The blade is traced from the cutting "
                    "template -- a curved band with two teardrop "
                    "openings, tipped so five meet at each 5-fold "
                    "hub and three at each 3-fold corner"),
                   ('CUSTOM', "Custom",
                    "Choose the group and plane family yourself; "
                    "starts from the demo arc motif")],
            default='TWISTED_RIVERS',
            description="Sculpture setups after Hart's pieces; the "
                        "motif stays editable afterwards")
        group: EnumProperty(
            name="Symmetry Group",
            items=[('ICOSA', "Icosahedral (60)",
                    "60 rotations -- Hart's usual choice"),
                   ('OCTA', "Octahedral (24)", "24 rotations"),
                   ('TETRA', "Tetrahedral (12)", "12 rotations")],
            default='ICOSA')
        family: EnumProperty(
            name="Plane Family",
            items=_family_items, default=3,
            description="Which orbit of planes to fill. The list "
                        "names the planes the chosen Symmetry Group "
                        "actually produces, and offers only the "
                        "families that group has")
        distance: FloatProperty(
            name="Plane Distance", default=1.0, min=0.1, max=10.0,
            description="Distance of the plane family from the origin")
        shell: FloatProperty(
            name="Shell", default=0.04, min=0.0, max=1.0,
            description="Radial extrusion fraction (Hart used ~4%); "
                        "0 keeps the flat planes")
        guide_extent: FloatProperty(
            name="Guide Extent", default=3.2, min=1.0, max=12.0,
            description="Radius of the guide pattern, in units of "
                        "the plane distance. 3.2 covers every line "
                        "of the 5-, 4-, 3- and 2-fold families "
                        "(the outermost sits at 3.078, on the "
                        "icosahedral 2-fold planes) so the outer "
                        "corners a motif snaps to -- e.g. Frabjous's "
                        "tips at phi^2 = 2.618 -- have guide lines "
                        "crossing there. The general P1 families run "
                        "much farther out and need a bigger radius "
                        "to draw in full")
        guide_rings: IntProperty(
            name="Guide Rings", default=0, min=0, max=24,
            description="Thin the guide pattern to its innermost N "
                        "rings of lines (0 = draw them all). The "
                        "lines sit at a handful of distinct distances "
                        "from the plane centre, and each such ring is "
                        "one set equivalent under the plane's own "
                        "symmetry -- dropping the outer rings clears "
                        "the clutter, at the cost of the far corners "
                        "they carry")
        lift: BoolProperty(
            name="Lift Sculpture Clear of Motif", default=True,
            description="Raise the sculpture up +Z so it stops "
                        "surrounding the Motif and Guides, which stay "
                        "at the origin where they can be seen and "
                        "edited. The height is measured from the "
                        "sculpture this motif actually makes, so it "
                        "clears by the same relative margin whatever "
                        "the size; tune it afterwards with the "
                        "modifier's Lift input")
        show_polyhedron: BoolProperty(
            name="Show Defining Polyhedron", default=False,
            description="Add the semi-transparent solid whose "
                        "extended face planes are this plane family, "
                        "and mark every crossing of the guide lines "
                        "with a coloured disc -- the points a motif's "
                        "corners should sit on, since a crossing of "
                        "k lines is where k+1 planes meet and k+1 "
                        "parts converge. Colour is the orbit: two "
                        "crossings share one exactly when a rotation "
                        "of the sculpture carries one onto the other, "
                        "so they play the same role. Balls of that "
                        "colour show every point equivalent to them "
                        "around the solid, one object per orbit in a "
                        "SymSculpt Orbits collection, so a group can "
                        "be switched off on its own. Design aid only "
                        "-- excluded from renders. Guide Rings and "
                        "Guide Extent thin the crossings along with "
                        "the lines")
        translucent: BoolProperty(
            name="Translucent Copies", default=False,
            description="Draw the replicated copies in a ghost "
                        "material so the editable motif reads through "
                        "them; off = the sculpture's real material")
        motif_object: StringProperty(
            name="Motif Object", default="",
            description="Mesh object to replicate instead of the "
                        "preset motif -- draw it flat on the XY "
                        "plane. Leave empty to build the preset's "
                        "own motif")

        def execute(self, context):
            motif_builder = demo_motif
            if self.preset in PRESETS:
                g, f, motif_builder = PRESETS[self.preset]
                self.group, self.family = g, f
            kind, family = self.group, self.family
            if (kind, family) not in _AXES:
                family = 'P3'
                self.report({'WARNING'},
                            "Plane family not available for this "
                            "group -- using 3-fold planes")
            rots = group_rotations(kind)
            a, normals = plane_normals(kind, family)
            u, v = _frame(a)
            d = self.distance

            motif = None
            if self.motif_object:
                ao = bpy.data.objects.get(self.motif_object)
                if ao is not None and ao.type == 'MESH':
                    motif = ao
                else:
                    self.report({'WARNING'},
                                f"'{self.motif_object}' is not a mesh "
                                f"object -- built the preset motif "
                                f"instead")
            if motif is None:
                verts, faces = motif_builder(d)
                me = bpy.data.meshes.new("SymSculpt Motif")
                me.from_pydata(verts, [], faces)
                me.validate()
                me.update()
                motif = bpy.data.objects.new("SymSculpt Motif", me)
                context.collection.objects.link(motif)
            # the motif is authored and edited flat on the world
            # XY plane; the node group maps it onto the
            # representative plane with this rotation + offset
            plane_rot = Matrix((
                (u[0], v[0], a[0]),
                (u[1], v[1], a[1]),
                (u[2], v[2], a[2]))).to_euler()
            plane_off = (d * a[0], d * a[1], d * a[2])
            motif.matrix_world = Matrix.Identity(4)
            if not motif.data.materials:
                motif.data.materials.append(_motif_material())
            # how high the sculpture has to go to clear the motif --
            # measured from the motif that is actually being used, so
            # a big motif gets a proportionally bigger lift
            lift_z = lift_height([tuple(v.co) for v in
                                  motif.data.vertices],
                                 d, self.shell)

            # guide pattern (stellation diagram) in the same plane
            segs = stellation_lines(kind, family, d, self.guide_extent,
                                    self.guide_rings)
            gverts = []
            gedges = []
            for (p0, p1) in segs:
                gverts.append((p0[0], p0[1], 0.0))
                gverts.append((p1[0], p1[1], 0.0))
                gedges.append((len(gverts) - 2, len(gverts) - 1))
            gme = bpy.data.meshes.new("SymSculpt Guides")
            gme.from_pydata(gverts, gedges, [])
            gme.update()
            guides = bpy.data.objects.new("SymSculpt Guides", gme)
            context.collection.objects.link(guides)
            guides.matrix_world = Matrix.Identity(4)
            guides.display_type = 'WIRE'
            guides.hide_render = True

            # the sculpture: one point per rotation, euler attribute
            pts = bpy.data.meshes.new("SymSculpt")
            pts.from_pydata([(0.0, 0.0, 0.0)] * len(rots), [], [])
            attr = pts.attributes.new("sym_rot", 'FLOAT_VECTOR',
                                      'POINT')
            eulers = []
            for R in rots:
                eulers.extend(Matrix(R).to_euler())
            attr.data.foreach_set('vector', eulers)
            attr = pts.attributes.new("copy_index", 'INT', 'POINT')
            attr.data.foreach_set('value', list(range(len(rots))))
            attr = pts.attributes.new("is_motif", 'BOOLEAN', 'POINT')
            attr.data.foreach_set(
                'value',
                [all(abs(R[i][j] - (1.0 if i == j else 0.0)) < 1e-9
                     for i in range(3) for j in range(3))
                 for R in rots])
            obj = bpy.data.objects.new("SymSculpt", pts)
            context.collection.objects.link(obj)

            mod = obj.modifiers.new("Symmetric Sculpture", 'NODES')
            ng = _node_group()
            mod.node_group = ng
            lift_socket = None
            for item in ng.interface.items_tree:
                if item.in_out == 'INPUT' and item.name == 'Lift':
                    lift_socket = item.identifier
            for item in ng.interface.items_tree:
                if item.in_out != 'INPUT':
                    continue
                if item.name == 'Motif':
                    mod[item.identifier] = motif
                elif item.name == 'Shell':
                    mod[item.identifier] = self.shell
                elif item.name == 'Lift':
                    # sized from the sculpture the motif actually
                    # makes, not from d alone; still a live modifier
                    # input afterwards
                    mod[item.identifier] = lift_z if self.lift else 0.0
                elif item.name == 'Translucent':
                    mod[item.identifier] = self.translucent
                elif item.name == 'Plane Rotation':
                    mod[item.identifier] = list(plane_rot)
                elif item.name == 'Plane Offset':
                    mod[item.identifier] = list(plane_off)

            motif.parent = obj
            motif.matrix_parent_inverse = Matrix.Identity(4)
            guides.parent = obj
            guides.matrix_parent_inverse = Matrix.Identity(4)

            if self.show_polyhedron:
                # the solid whose extended face planes are this
                # family, plus a ball on every vertex and a disc
                # where that vertex lands in the guide diagram
                pv, pf = family_polyhedron(kind, family, d)
                pme = bpy.data.meshes.new("SymSculpt Polyhedron")
                pme.from_pydata(pv, [], pf)
                pme.validate()
                pme.update()
                solid = bpy.data.objects.new("SymSculpt Polyhedron",
                                             pme)
                solid.data.materials.append(_solid_material())
                context.collection.objects.link(solid)
                solid.matrix_world = Matrix.Identity(4)
                solid.hide_render = True
                solid.parent = obj
                solid.matrix_parent_inverse = Matrix.Identity(4)

                rball = 0.035 * d
                cross = crossing_points(kind, family, d,
                                        self.guide_extent,
                                        self.guide_rings)
                orbit, cgroup = crossing_orbits(kind, family, cross, d)

                pts_by_g = {}
                for p, g in orbit:
                    pts_by_g.setdefault(g, []).append(p)
                marks_by_g = {}
                for (x, y, _k), g in zip(cross, cgroup):
                    marks_by_g.setdefault(g, []).append((x, y))

                # If there are too many to draw, drop whole orbits
                # from the outside in.  Truncating mid-orbit would
                # leave a group half-drawn, which reads as a gap in
                # the symmetry rather than as something left out.
                order = sorted(pts_by_g, key=lambda g: min(
                    sum(c * c for c in p) for p in pts_by_g[g]))
                kept, total = [], 0
                for g in order:
                    if total + len(pts_by_g[g]) > _MAX_MARKS:
                        continue
                    kept.append(g)
                    total += len(pts_by_g[g])
                dropped = len(pts_by_g) - len(kept)
                if dropped:
                    self.report(
                        {'WARNING'},
                        f"{len(orbit)} crossing points is past the "
                        f"{_MAX_MARKS} the aid draws -- showing "
                        f"{len(kept)} orbits, holding back {dropped} "
                        f"of the outer ones; raise Guide Rings or "
                        f"lower Guide Extent to thin the pattern")

                # one object per orbit, so a group can be switched off
                # on its own from the outliner
                orb_coll = bpy.data.collections.new("SymSculpt Orbits")
                context.collection.children.link(orb_coll)
                made = []
                for g in sorted(kept):
                    b = _build_marker_object(
                        f"SymSculpt Orbit {g:02d} Balls",
                        [(g, _ball(p, rball)) for p in pts_by_g[g]],
                        0.45)
                    made.append((b, True))
                    if marks_by_g.get(g):
                        m = _build_marker_object(
                            f"SymSculpt Orbit {g:02d} Marks",
                            [(g, _disc((x, y, 1e-3 * d), rball))
                             for x, y in marks_by_g[g]], 1.0)
                        made.append((m, False))
                for o, rides_lift in made:
                    orb_coll.objects.link(o)
                    o.matrix_world = Matrix.Identity(4)
                    o.hide_render = True
                    o.parent = obj
                    o.matrix_parent_inverse = Matrix.Identity(4)
                    # the balls belong to the sculpture and rise with
                    # it; the discs belong to the flat guide diagram
                    # and stay down at the origin with it
                    if rides_lift and lift_socket is not None:
                        _drive_z_from_lift(o, obj, mod.name,
                                           lift_socket)
                if lift_socket is not None:
                    _drive_z_from_lift(solid, obj, mod.name,
                                       lift_socket)
                self.report(
                    {'INFO'},
                    f"{len(cross)} guide crossings in "
                    f"{len(pts_by_g)} orbits, {total} points in space")

            for o in context.selected_objects:
                o.select_set(False)
            obj.select_set(True)
            motif.select_set(True)
            context.view_layer.objects.active = obj
            fold = len(rots) // len(normals)
            self.report(
                {'INFO'},
                f"{len(normals)} planes x {fold}-fold: edit the "
                f"Motif object and every copy follows")
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            lay.prop(self, 'preset')
            if self.preset == 'CUSTOM':
                lay.prop(self, 'group')
                lay.prop(self, 'family')
            # what gets replicated, straight after which planes it is
            # replicated into
            lay.prop_search(self, 'motif_object', bpy.data, 'objects')
            for k in ('distance', 'shell', 'guide_extent',
                      'guide_rings', 'show_polyhedron', 'lift',
                      'translucent'):
                lay.prop(self, k)

    def _menu_func(self, context):
        self.layout.operator_menu_enum(
            "object.symmetric_sculpture_add", "preset",
            text="Symmetric Sculpture", icon='MOD_MIRROR')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(OBJECT_OT_symmetric_sculpture_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.remove(_menu_func)
        bpy.utils.unregister_class(
            OBJECT_OT_symmetric_sculpture_add)


def _selftest():
    # group orders and plane-family counts
    for kind, order in _ORDER.items():
        rots = group_rotations(kind)
        print(f"{kind}: {len(rots)} rotations "
              f"{'OK' if len(rots) == order else 'BAD'}")
        assert len(rots) == order
    expect = {('ICOSA', 'P5'): 12, ('ICOSA', 'P3'): 20,
              ('ICOSA', 'P2'): 30, ('ICOSA', 'P1'): 60,
              ('OCTA', 'P4'): 6, ('OCTA', 'P3'): 8,
              ('OCTA', 'P2'): 12, ('OCTA', 'P1'): 24,
              ('TETRA', 'P3'): 4, ('TETRA', 'P2'): 6,
              ('TETRA', 'P1'): 12}
    for (kind, fam), n in expect.items():
        _, normals = plane_normals(kind, fam)
        ok = len(normals) == n
        print(f"{kind}/{fam}: {len(normals)} planes "
              f"(want {n}) {'OK' if ok else 'BAD'}")
        assert ok
    # icosa 3-fold: 18 guide lines (19 others minus the parallel)
    segs = stellation_lines('ICOSA', 'P3', 1.0, 10.0)
    print(f"ICOSA/P3 guide lines: {len(segs)} "
          f"{'OK' if len(segs) == 18 else 'BAD'}")
    assert len(segs) == 18

    # the shipped Guide Extent must emit EVERY line of the k-fold
    # families -- a line whose foot lies outside the disc is dropped
    # altogether, taking with it the corner intersections that the
    # outer tips of a motif are drawn to.
    default_extent = 3.2
    for kind, fam in (('ICOSA', 'P5'), ('ICOSA', 'P3'), ('ICOSA', 'P2'),
                      ('OCTA', 'P4'), ('OCTA', 'P3'), ('OCTA', 'P2'),
                      ('TETRA', 'P3'), ('TETRA', 'P2')):
        _, normals = plane_normals(kind, fam)
        foot = max_line_foot(kind, fam, 1.0)
        segs = stellation_lines(kind, fam, 1.0, default_extent)
        want = sum(1 for b in normals
                   if abs(sum(x * y for x, y in
                              zip(_normalize(_AXES[(kind, fam)]), b)))
                   <= 1 - 1e-9)
        ok = len(segs) == want and foot < default_extent
        print(f"{kind}/{fam} guides at extent {default_extent}: "
              f"{len(segs)}/{want} lines, max foot {foot:.3f} "
              f"{'OK' if ok else 'BAD'}")
        assert ok, (kind, fam, len(segs), want, foot)

    # Frabjous draws its pointed ends to the 3-fold piercings at
    # phi^2; those must be a real crossing of two guide lines, and
    # inside the default disc
    assert max_line_foot('ICOSA', 'P2', 1.0) > PHI * PHI
    assert PHI * PHI < default_extent
    print(f"ICOSA/P2 reaches the phi^2={PHI * PHI:.4f} corner OK")

    # every (group, family) has a label, and the plane count it
    # claims must be the orbit size actually produced
    for (kind, fam), (n, _solid) in _FAMILY_SOLID.items():
        _, normals = plane_normals(kind, fam)
        lab = family_label(kind, fam)
        ok = len(normals) == n and str(n) in lab
        print(f"{kind}/{fam}: '{lab}' vs {len(normals)} planes "
              f"{'OK' if ok else 'BAD'}")
        assert ok, (kind, fam, lab, len(normals))
        # and the fold implied by the label is the orbit's stabiliser
        assert _ORDER[kind] // n == _FOLD[fam], (kind, fam)
    assert set(_FAMILY_SOLID) == set(_AXES)

    # guide rings: thinning keeps the innermost lines and is monotone
    for kind, fam in (('ICOSA', 'P3'), ('ICOSA', 'P2'),
                      ('ICOSA', 'P1')):
        radii = guide_ring_radii(kind, fam, 1.0)
        allsegs = len(stellation_lines(kind, fam, 1.0, 40.0))
        counts = [len(stellation_lines(kind, fam, 1.0, 40.0, r))
                  for r in range(1, len(radii) + 1)]
        ok = (counts == sorted(counts) and counts[-1] == allsegs
              and counts[0] < allsegs
              and len(stellation_lines(kind, fam, 1.0, 40.0, 0))
              == allsegs)
        print(f"{kind}/{fam}: {len(radii)} rings, lines {counts[0]}"
              f"..{counts[-1]} of {allsegs} {'OK' if ok else 'BAD'}")
        assert ok, (kind, fam, counts, allsegs)

    # the Whimsy blade: triangulation must cover exactly the material
    # (outer loop less the two teardrops), with no lost or doubled
    # area from the hole bridges
    def _sarea(p):
        return 0.5 * sum(p[i][0] * p[(i + 1) % len(p)][1]
                         - p[(i + 1) % len(p)][0] * p[i][1]
                         for i in range(len(p)))
    wv, wf = whimsy_motif(1.0)
    tri = sum(abs(0.5 * ((wv[b][0] - wv[a2][0]) * (wv[c][1] - wv[a2][1])
                         - (wv[b][1] - wv[a2][1])
                         * (wv[c][0] - wv[a2][0])))
              for a2, b, c in wf)
    want_a = (abs(_sarea(_WHIMSY_OUTER)) - abs(_sarea(_WHIMSY_HOLE_A))
              - abs(_sarea(_WHIMSY_HOLE_B)))
    print(f"whimsy area {tri:.6f} vs {want_a:.6f} "
          f"{'OK' if abs(tri - want_a) < 1e-9 else 'BAD'}")
    assert abs(tri - want_a) < 1e-9
    assert len(wf) == len(wv) - 2          # a full fan, no stalled ear

    # and its two tips must sit ON the 5-fold and 3-fold axes -- that
    # is what makes five blades meet at a hub and three at a corner
    aa, _ = plane_normals('ICOSA', 'P1')
    uu, vv = _frame(aa)
    rots = group_rotations('ICOSA')

    def _on_axis(pt, seed):
        p = [aa[i] + pt[0] * uu[i] + pt[1] * vv[i] for i in range(3)]
        p = _normalize(p)
        s = _normalize(seed)
        best = 9.9
        for R in rots:
            b = _apply(R, s)
            cr = (p[1] * b[2] - p[2] * b[1], p[2] * b[0] - p[0] * b[2],
                  p[0] * b[1] - p[1] * b[0])
            best = min(best, sqrt(sum(c * c for c in cr)))
        return best
    tip5 = _WHIMSY_OUTER[0]                # the loop starts at the hub
    tip3 = max(_WHIMSY_OUTER, key=lambda p: p[1])
    e5 = _on_axis(tip5, (0.0, 1.0, PHI))
    e3 = _on_axis(tip3, (1.0, 1.0, 1.0))
    print(f"whimsy tips on axes: 5-fold off {e5:.2e}, "
          f"3-fold off {e3:.2e} "
          f"{'OK' if max(e5, e3) < 1e-4 else 'BAD'}")
    assert max(e5, e3) < 1e-4

    # the defining solid of each family must come out as the real
    # thing -- these are the classical counts, and Euler catches a
    # half-built face
    for (kind, fam), (nv, nf) in (
            (('ICOSA', 'P5'), (20, 12)), (('ICOSA', 'P3'), (12, 20)),
            (('ICOSA', 'P2'), (32, 30)), (('ICOSA', 'P1'), (92, 60)),
            (('OCTA', 'P4'), (8, 6)), (('OCTA', 'P3'), (6, 8)),
            (('OCTA', 'P2'), (14, 12)), (('TETRA', 'P3'), (4, 4)),
            (('TETRA', 'P2'), (8, 6))):
        pv, pf = family_polyhedron(kind, fam, 1.0)
        edges = sum(len(f) for f in pf) // 2
        ok = (len(pv) == nv and len(pf) == nf
              and len(pv) - edges + len(pf) == 2)
        print(f"{kind}/{fam} solid: V={len(pv)}({nv}) F={len(pf)}({nf}) "
              f"euler={len(pv) - edges + len(pf)} "
              f"{'OK' if ok else 'BAD'}")
        assert ok, (kind, fam, len(pv), len(pf))

    # every marked point must be a real crossing: k lines through it
    # by construction, all distinct, all inside the guide disc
    for kind, fam in (('ICOSA', 'P5'), ('ICOSA', 'P3'),
                      ('ICOSA', 'P2'), ('OCTA', 'P3')):
        cr = crossing_points(kind, fam, 1.0, 3.2)
        segs = stellation_lines(kind, fam, 1.0, 3.2)
        worst = 0.0
        for x, y, k in cr:
            near = sorted(
                abs((b[0] - a3[0]) * (a3[1] - y)
                    - (a3[0] - x) * (b[1] - a3[1]))
                / max(sqrt((b[0] - a3[0]) ** 2 + (b[1] - a3[1]) ** 2),
                      1e-12)
                for a3, b in segs)
            worst = max(worst, near[k - 1])   # k lines must pass here
        distinct = len({(round(x, 6), round(y, 6)) for x, y, _ in cr})
        ok = (worst < 1e-6 and distinct == len(cr)
              and all(k >= 2 for _, _, k in cr)
              and all(sqrt(x * x + y * y) <= 3.2 + 1e-9
                      for x, y, _ in cr))
        print(f"{kind}/{fam}: {len(cr)} crossings, types "
              f"{sorted(set(k for _, _, k in cr))}, worst line "
              f"offset {worst:.1e} {'OK' if ok else 'BAD'}")
        assert ok, (kind, fam, worst, distinct, len(cr))

    # the crossings must include the points the designs are drawn to:
    # on the triacontahedral planes, phi^2 out along local x (where
    # three Frabjous tips meet) and phi along local y (the vortices)
    cr = crossing_points('ICOSA', 'P2', 1.0, 3.2)
    got = {(round(x, 5), round(y, 5)): k for x, y, k in cr}
    ok = ((round(PHI * PHI, 5), 0.0) in got
          and (0.0, round(PHI, 5)) in got)
    print(f"ICOSA/P2 crossings include phi^2 on x and phi on y "
          f"{'OK' if ok else 'BAD'}")
    assert ok, sorted(got)[:6]

    # orbits: every point landed exactly once, every crossing given a
    # group, and each orbit of a size the group can actually produce
    # -- N/k for a point held by a k-fold stabiliser, so 12, 20, 30
    # or 60 out of the icosahedral 60, never anything between
    for kind, fam in (('ICOSA', 'P5'), ('ICOSA', 'P3'),
                      ('ICOSA', 'P2'), ('TETRA', 'P3')):
        cps = crossing_points(kind, fam, 1.0, 3.2)
        pts, grps = crossing_orbits(kind, fam, cps, 1.0)
        keys = {tuple(round(c, 5) for c in p) for p, _ in pts}
        sizes = {}
        for _p, g in pts:
            sizes[g] = sizes.get(g, 0) + 1
        n = _ORDER[kind]
        ok = (len(pts) == len(keys) and len(grps) == len(cps)
              and set(grps) == set(sizes)
              and all(n % s == 0 for s in sizes.values()))
        print(f"{kind}/{fam} orbits: {len(sizes)} groups, sizes "
              f"{sorted(set(sizes.values()))}, {len(pts)} points "
              f"{'OK' if ok else 'BAD'}")
        assert ok, (kind, fam, sorted(set(sizes.values())))
        # every point of one orbit is the same distance out, since a
        # rotation cannot change a radius
        for g in sizes:
            rr = {round(sqrt(sum(c * c for c in p)), 6)
                  for p, gg in pts if gg == g}
            assert len(rr) == 1, (kind, fam, g, rr)

    # a motif flat on XY at plane distance d lands at sqrt(r^2+d^2)
    flat = [(0.0, 0.0, 0.0), (3.0, 4.0, 0.0)]
    r = sculpture_radius(flat, 12.0)
    print(f"sculpture_radius (3,4,0) at d=12: {r:.4f} "
          f"{'OK' if abs(r - 13.0) < 1e-9 else 'BAD'}")
    assert abs(r - 13.0) < 1e-9            # 5-12-13
    assert abs(sculpture_radius(flat, 12.0, 0.5) - 19.5) < 1e-9

    # the lift must put the sculpture's lowest point exactly `margin`
    # of a radius above the motif plane, and must grow with the motif
    for verts, d, shell in ((flat, 12.0, 0.0), (flat, 12.0, 0.04),
                            ([(0.0, 0.0, 0.0)], 1.0, 0.0)):
        rad = sculpture_radius(verts, d, shell)
        gap = lift_height(verts, d, shell, 0.3) - rad
        assert abs(gap - 0.3 * rad) < 1e-9, (verts, d, shell)
    small = lift_height([(0.5, 0.0, 0.0)], 1.0)
    big = lift_height([(PHI * PHI, 0.0, 0.0)], 1.0)
    print(f"lift scales with motif: {small:.3f} -> {big:.3f} "
          f"{'OK' if big > small else 'BAD'}")
    assert big > small
    # ... and never buries the motif: the lowest point stays clear
    assert small > sculpture_radius([(0.5, 0.0, 0.0)], 1.0)
