
# Polyhedral Tangle Generator for Blender
#
# Interwoven compounds of polyhedron frames -- "tangles" in the spirit
# of Alan Holden's orderly tangles and the sculptural renders of
# Forging Mind (e.g. "Tetra Tangle" = the compound of five tetrahedra).
# Each component polyhedron is built as hollow-face frames (each face a
# mitred ring with adjustable width and thickness; rings of adjacent
# faces overlap along the edges into ribbed struts, as in Hart's
# five-tetrahedra polylink).
#
# Compounds: 2 tetrahedra (stella octangula), 5 tetrahedra (chiral,
# icosahedral), 10 tetrahedra, 5 cubes, 5 octahedra, 3 cubes
# (octahedral). Components are rotated copies of a seed, generated by
# exact symmetry rotations.

bl_info = {
    "name": "Polyhedral Tangles",
    "author": "David Krider (Math Art project)",
    "version": (1, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Math Art > Polyhedral Tangle",
    "description": "Compounds of interwoven polyhedron frames "
                   "(five tetrahedra, five cubes, ...)",
    "category": "Add Mesh",
}

import math
from math import cos, sin, pi

PHI = (1 + 5 ** 0.5) / 2


def _unit(v):
    l = math.sqrt(sum(x * x for x in v)) or 1.0
    return tuple(x / l for x in v)


def _axis_rot(axis, ang):
    x, y, z = _unit(axis)
    c, s = cos(ang), sin(ang)
    C = 1 - c
    return ((c + x * x * C, x * y * C - z * s, x * z * C + y * s),
            (y * x * C + z * s, c + y * y * C, y * z * C - x * s),
            (z * x * C - y * s, z * y * C + x * s, c + z * z * C))


def _rot_pts(R, pts):
    return [tuple(sum(R[i][k] * p[k] for k in range(3)) for i in range(3))
            for p in pts]


def _tetra(mirror=False):
    V = [(1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1)]
    if mirror:
        V = [(-x, y, z) for (x, y, z) in V]
        F = [(0, 2, 1), (0, 3, 2), (0, 1, 3), (1, 2, 3)]
    else:
        F = [(0, 1, 2), (0, 2, 3), (0, 3, 1), (1, 3, 2)]
    return V, F


def _cube():
    V = [(x, y, z) for x in (-1, 1) for y in (-1, 1) for z in (-1, 1)]
    F = [(0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1),
         (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)]
    return V, F


def _octa():
    V = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0),
         (0, 0, 1), (0, 0, -1)]
    F = [(0, 2, 4), (2, 1, 4), (1, 3, 4), (3, 0, 4),
         (2, 0, 5), (1, 2, 5), (3, 1, 5), (0, 3, 5)]
    return V, F


_FIVE_AXIS = (0.0, 1.0, PHI)      # a 5-fold axis of the icosahedral group


def compound(kind):
    """List of (verts, faces, own_axis) per component. own_axis is a
    symmetry axis of that component, used for per-component rotation
    (the parameter that generates Lang-style polypolyhedra variants)."""
    out = []
    diag = (1, 1, 1)
    if kind == 'T2':                      # stella octangula
        V, F = _tetra(False)
        out.append((V, F, diag))
        V, F = _tetra(True)
        out.append((V, F, (-1, 1, 1)))
    elif kind in ('T5', 'T10'):
        mirrors = (False, True) if kind == 'T10' else (False,)
        for mir in mirrors:
            V0, F = _tetra(mir)
            ax0 = (-1, 1, 1) if mir else diag
            for k in range(5):
                R = _axis_rot(_FIVE_AXIS, 2 * pi * k / 5)
                out.append((_rot_pts(R, V0), F, _rot_pts(R, [ax0])[0]))
    elif kind in ('C5', 'O5'):
        V0, F = _cube() if kind == 'C5' else _octa()
        for k in range(5):
            R = _axis_rot(_FIVE_AXIS, 2 * pi * k / 5)
            out.append((_rot_pts(R, V0), F, _rot_pts(R, [diag])[0]))
    elif kind == 'C3':                    # Escher's compound
        V, F = _cube()
        out.append((V, F, (0, 0, 1)))
        for axis in ((1, 0, 0), (0, 1, 0)):
            R = _axis_rot(axis, pi / 4)
            out.append((_rot_pts(R, V), F, axis))
    else:
        raise ValueError(kind)
    return out


def _emit_face_rings(verts, faces, face_comp, ci, V, F, width,
                     thickness, scale):
    """Leonardo da Vinci style: the panel shell between the
    polyhedron scaled out and in by half the thickness, with a hole
    inset in every face. Adjacent panels share the scaled polyhedron
    vertices, so the joints along edges and at vertices are exact
    (watertight mitres), as in the models Leonardo drew for Pacioli's
    De divina proportione."""
    k_out = 1.0 + thickness / 2
    k_in = max(0.05, 1.0 - thickness / 2)
    inner = 1.0 - width
    base_o = len(verts)
    verts.extend(tuple(x * k_out * scale for x in v) for v in V)
    base_i = len(verts)
    verts.extend(tuple(x * k_in * scale for x in v) for v in V)
    for f in F:
        m = len(f)
        c = [sum(V[i][k] for i in f) / m for k in range(3)]
        hole = [[c[k] + (V[i][k] - c[k]) * inner for k in range(3)]
                for i in f]
        HO = len(verts)
        verts.extend(tuple(p[k] * k_out * scale for k in range(3))
                     for p in hole)
        HI = len(verts)
        verts.extend(tuple(p[k] * k_in * scale for k in range(3))
                     for p in hole)
        for i in range(m):
            j = (i + 1) % m
            a, b = f[i], f[j]
            faces.append([base_o + a, base_o + b, HO + j, HO + i])
            faces.append([HI + i, HI + j, base_i + b, base_i + a])
            faces.append([HO + j, HO + i, HI + i, HI + j])
            face_comp.extend([ci] * 3)


try:
    from .conway_operators import _hull_faces
except ImportError:
    try:
        from conway_operators import _hull_faces
    except ImportError:
        _hull_faces = None


def _emit_edge_struts(verts, faces, face_comp, ci, V, F, thickness,
                      scale, cap_size=1.0):
    """Square struts trimmed back from the vertices and closed with
    flat caps; each vertex gets a faceted knuckle (the convex hull of
    the surrounding strut caps) so the joints are clean."""
    h = thickness / 2
    edges = set()
    for f in F:
        m = len(f)
        for i in range(m):
            a, b = f[i], f[(i + 1) % m]
            edges.add((min(a, b), max(a, b)))
    vertex_rings = {}          # vertex index -> knuckle corner points
    for a, b in edges:
        A, B = V[a], V[b]
        t = _unit(tuple(B[k] - A[k] for k in range(3)))
        elen = math.sqrt(sum((B[k] - A[k]) ** 2 for k in range(3)))
        s = min(thickness * cap_size, 0.35 * elen)
        ref = (0, 0, 1) if abs(t[2]) < 0.9 else (1, 0, 0)
        u = _unit((t[1] * ref[2] - t[2] * ref[1],
                   t[2] * ref[0] - t[0] * ref[2],
                   t[0] * ref[1] - t[1] * ref[0]))
        w = (t[1] * u[2] - t[2] * u[1], t[2] * u[0] - t[0] * u[2],
             t[0] * u[1] - t[1] * u[0])
        A2 = tuple(A[k] + t[k] * s for k in range(3))
        B2 = tuple(B[k] - t[k] * s for k in range(3))
        base = len(verts)
        for P, vi in ((A2, a), (B2, b)):
            ring = []
            for (su, sw) in ((1, 1), (-1, 1), (-1, -1), (1, -1)):
                p = tuple((P[k] + (u[k] * su + w[k] * sw) * h) * scale
                          for k in range(3))
                verts.append(p)
                ring.append(p)
            vertex_rings.setdefault(vi, []).extend(ring)
        for i2 in range(4):
            j2 = (i2 + 1) % 4
            faces.append([base + i2, base + j2, base + 4 + j2,
                          base + 4 + i2])
        faces.append([base + 3, base + 2, base + 1, base + 0])
        faces.append([base + 4, base + 5, base + 6, base + 7])
        face_comp.extend([ci] * 6)
    if _hull_faces is None:
        return
    for vi, pts in vertex_rings.items():
        c = [sum(p[k] for p in pts) / len(pts) for k in range(3)]
        local = [tuple(p[k] - c[k] for k in range(3)) for p in pts]
        base = len(verts)
        verts.extend(tuple(p[k] + c[k] for k in range(3))
                     for p in local)
        for hf in _hull_faces(local):
            faces.append([base + i for i in hf])
            face_comp.append(ci)


def build_tangle(kind='T5', style='FACES', width=0.22, thickness=0.10,
                 size=1.0, comp_rot=0.0, spin=0.0, scale=1.0,
                 cap_size=1.0):
    """Frames for every component of the compound: hollow faces or
    edge struts. comp_rot rotates each component about its own
    symmetry axis (Lang-style variants).
    Returns (verts, faces, n_components, face_comp)."""
    comps = compound(kind)
    if abs(comp_rot) > 1e-9:
        cr = math.radians(comp_rot)
        comps = [(_rot_pts(_axis_rot(ax, cr), V), F, ax)
                 for (V, F, ax) in comps]
    if abs(spin) > 1e-9:
        R = _axis_rot(_FIVE_AXIS if kind in ('T5', 'T10', 'C5', 'O5')
                      else (0, 0, 1), math.radians(spin))
        comps = [(_rot_pts(R, V), F, ax) for (V, F, ax) in comps]
    verts = []
    faces = []
    face_comp = []
    for ci, (V, F, _ax) in enumerate(comps):
        V = [tuple(x * size for x in v) for v in V]
        if style == 'EDGES':
            _emit_edge_struts(verts, faces, face_comp, ci, V, F,
                              thickness, scale, cap_size)
        else:
            _emit_face_rings(verts, faces, face_comp, ci, V, F, width,
                             thickness, scale)
    return verts, faces, len(comps), face_comp


try:
    import bpy
    from bpy.props import (FloatProperty, EnumProperty)
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    class MESH_OT_tangle_add(bpy.types.Operator):
        """Interwoven polyhedron-frame compound (Tetra Tangle & co)"""
        bl_idname = "mesh.tangle_add"
        bl_label = "Polyhedral Tangle"
        bl_options = {'REGISTER', 'UNDO'}

        kind: EnumProperty(
            name="Compound",
            items=[('T5', "5 Tetrahedra", "the classic Tetra Tangle"),
                   ('T2', "2 Tetrahedra", "stella octangula"),
                   ('T10', "10 Tetrahedra", "both chiralities"),
                   ('C3', "3 Cubes", "Escher's compound"),
                   ('C5', "5 Cubes", "in a dodecahedron"),
                   ('O5', "5 Octahedra", "icosahedral")],
            default='T5')
        style: EnumProperty(
            name="Style",
            items=[('FACES', "Hollow Faces (da Vinci)",
                    "Leonardo da Vinci style: solid face panels with "
                    "openings, mitred exactly along the shared edges "
                    "and vertices (as in De divina proportione)"),
                   ('EDGES', "Edge Struts",
                    "Square sticks along the edges with flat caps "
                    "and faceted knuckles at the vertices (Lang "
                    "polypolyhedra style)")],
            default='FACES')
        width: FloatProperty(
            name="Frame Width", default=0.22, min=0.02, max=0.9,
            description="Hollow-face ring width (fraction of the face)")
        thickness: FloatProperty(name="Frame Thickness", default=0.10,
                                 min=0.01, max=1.0)
        cap_size: FloatProperty(
            name="Cap Size", default=1.0, min=0.3, max=3.0,
            description="How far the edge struts stop short of each "
                        "vertex (in strut thicknesses); the faceted "
                        "knuckle fills the joint")
        comp_rot: FloatProperty(
            name="Component Rotation", default=0.0, min=-180.0,
            max=180.0,
            description="Rotate every component about its own symmetry "
                        "axis (explores Lang-style polypolyhedra "
                        "variants)")
        size: FloatProperty(
            name="Component Size", default=1.0, min=0.5, max=2.0,
            description="Scale of each component about the centre")
        spin: FloatProperty(
            name="Spin", default=0.0, min=-180.0, max=180.0,
            description="Extra rotation of the whole compound about "
                        "its main symmetry axis")
        coloring: EnumProperty(
            name="Coloring",
            items=[('COMP', "Per Component", "one material per "
                    "polyhedron (view with Material Preview)"),
                   ('NONE', "None", "no materials")],
            default='COMP')
        scale: FloatProperty(name="Scale", default=1.0, min=0.01,
                             max=100.0)

        _PALETTE = [(0.83, 0.68, 0.21), (0.27, 0.52, 0.79),
                    (0.90, 0.36, 0.23), (0.30, 0.69, 0.42),
                    (0.62, 0.40, 0.75), (0.25, 0.72, 0.72),
                    (0.91, 0.56, 0.71), (0.55, 0.60, 0.29),
                    (0.45, 0.45, 0.85), (0.80, 0.50, 0.30)]

        @classmethod
        def _material_for(cls, i):
            name = f"Tangle {i + 1}"
            mat = bpy.data.materials.get(name)
            if mat is None:
                mat = bpy.data.materials.new(name)
                rgb = cls._PALETTE[i % len(cls._PALETTE)]
                mat.diffuse_color = (*rgb, 1.0)
                mat.use_nodes = True
                bsdf = mat.node_tree.nodes.get("Principled BSDF")
                if bsdf is not None:
                    bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
                    bsdf.inputs["Roughness"].default_value = 0.35
                    try:
                        bsdf.inputs["Metallic"].default_value = 0.7
                    except KeyError:
                        pass
            return mat

        def execute(self, context):
            verts, faces, nc, face_comp = build_tangle(
                self.kind, self.style, self.width, self.thickness,
                self.size, self.comp_rot, self.spin, self.scale,
                self.cap_size)
            me = bpy.data.meshes.new("Tangle")
            me.from_pydata(verts, [], faces)
            me.validate(clean_customdata=True)
            # fit (roughly) within a 2 x scale cube at the origin
            lo = [min(v.co[k] for v in me.vertices)
                  for k in range(3)]
            hi = [max(v.co[k] for v in me.vertices)
                  for k in range(3)]
            half = max((hi[k] - lo[k]) / 2.0
                       for k in range(3)) or 1.0
            f = self.scale / half
            for v in me.vertices:
                v.co = [(v.co[k] - (lo[k] + hi[k]) / 2.0) * f
                        for k in range(3)]
            if len(me.polygons) == len(faces):
                attr = me.attributes.new("component_index", 'INT', 'FACE')
                attr.data.foreach_set('value', face_comp)
                if self.coloring == 'COMP':
                    for i in range(nc):
                        me.materials.append(self._material_for(i))
                    me.polygons.foreach_set('material_index', face_comp)
            me.update()
            obj = bpy.data.objects.new("Tangle", me)
            context.collection.objects.link(obj)
            obj.location = context.scene.cursor.location
            for o in context.selected_objects:
                o.select_set(False)
            obj.select_set(True)
            context.view_layer.objects.active = obj
            self.report({'INFO'}, f"{nc} components")
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            for k in ('kind', 'style', 'width', 'thickness',
                      'cap_size', 'size', 'comp_rot', 'spin',
                      'coloring', 'scale'):
                if k == 'width' and self.style == 'EDGES':
                    continue
                if k == 'cap_size' and self.style != 'EDGES':
                    continue
                lay.prop(self, k)

    def _menu_func(self, context):
        self.layout.operator("mesh.tangle_add", icon='MOD_BOOLEAN')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(MESH_OT_tangle_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.remove(_menu_func)
        bpy.utils.unregister_class(MESH_OT_tangle_add)


if __name__ == "__main__":
    if _IN_BLENDER:
        register()
    else:
        def _check(v, f):
            """closed 2-manifold with outward normals?"""
            from collections import Counter
            cnt = Counter()
            for fc_ in f:
                for i in range(len(fc_)):
                    a, b = fc_[i], fc_[(i + 1) % len(fc_)]
                    cnt[(min(a, b), max(a, b))] += 1
            manifold = all(c == 2 for c in cnt.values())
            vol = 0.0
            for fc_ in f:
                for i in range(1, len(fc_) - 1):
                    p, q, r = v[fc_[0]], v[fc_[i]], v[fc_[i + 1]]
                    vol += (p[0] * (q[1] * r[2] - q[2] * r[1])
                            - p[1] * (q[0] * r[2] - q[2] * r[0])
                            + p[2] * (q[0] * r[1] - q[1] * r[0])) / 6
            return manifold, vol
        for kind, n in (('T2', 2), ('T5', 5), ('T10', 10), ('C5', 5),
                        ('O5', 5), ('C3', 3)):
            for style in ('FACES', 'EDGES'):
                v, f, nc, fc = build_tangle(kind, style)
                man, vol = _check(v, f)
                ok = nc == n and man and vol > 0
                print(f"{kind:4s}/{style}: comps={nc}({n}) "
                      f"manifold={man} vol={vol:+.3f} "
                      f"{'OK' if ok else 'BAD'}")
