
# Polyhedral Tangle Generator for Blender
#
# Interwoven compounds of polyhedron frames -- "tangles" in the spirit
# of Alan Holden's orderly tangles and the sculptural renders of
# Forging Mind (e.g. "Tetra Tangle" = the compound of five tetrahedra).
# Each component polyhedron is built as hollow-face frames (each face a
# mitred ring with adjustable width and thickness; rings of adjacent
# faces overlap along the edges into ribbed struts, as in Hart's
# five-tetrahedra polylink).
#
# Compounds: 2 tetrahedra (stella octangula), 5 tetrahedra (chiral,
# icosahedral), 10 tetrahedra, 5 cubes, 5 octahedra, 3 cubes
# (octahedral). Components are rotated copies of a seed, generated by
# exact symmetry rotations.
#
# References:
# - Alan Holden, "Orderly Tangles: Cloverleafs, Gordian Knots, and
#   Regular Polylinks", Columbia University Press, 1983.
# - George W. Hart, "Orderly Tangles Revisited" (regular polylinks,
#   e.g. the five-tetrahedra polylink), Bridges 2005.
# - The five-tetrahedra compound / stella octangula are classical
#   polyhedral compounds (see e.g. H. S. M. Coxeter).

bl_info = {
    "name": "Polyhedral Tangles",
    "author": "Math Art project",
    "version": (1, 0, 0),
    "blender": (4, 2, 0),
    "location": "View3D > Add > Math Art > Polyhedral Tangle",
    "description": "Compounds of interwoven polyhedron frames "
                   "(five tetrahedra, five cubes, ...)",
    "category": "Add Mesh",
}






















try:
    from .conway_operators import _hull_faces
except ImportError:
    try:
        from conway_operators import _hull_faces
    except ImportError:
        _hull_faces = None
# The mathematics lives in the sibling `weaving` engine package;
# this module is the Blender layer over it.
try:
    from .weaving.tangles import (build_tangle)
except ImportError:  # flat import outside the package
    from weaving.tangles import (build_tangle)










try:
    import bpy
    from bpy.props import (FloatProperty, EnumProperty)
    _IN_BLENDER = True
except ImportError:
    _IN_BLENDER = False


if _IN_BLENDER:

    class MESH_OT_tangle_add(bpy.types.Operator):
        """Interwoven polyhedron-frame compound (Tetra Tangle & co)"""
        bl_idname = "mesh.tangle_add"
        bl_label = "Polyhedral Tangle"
        bl_options = {'REGISTER', 'UNDO'}

        kind: EnumProperty(
            name="Compound",
            description="Which polyhedral compound to weave",
            items=[('T5', "5 Tetrahedra", "the classic Tetra Tangle"),
                   ('T2', "2 Tetrahedra", "stella octangula"),
                   ('T10', "10 Tetrahedra", "both chiralities"),
                   ('C3', "3 Cubes", "Escher's compound"),
                   ('C5', "5 Cubes", "in a dodecahedron"),
                   ('O5', "5 Octahedra", "icosahedral")],
            default='T5')
        style: EnumProperty(
            name="Style",
            description="How each component's frame is built",
            items=[('FACES', "Hollow Faces (da Vinci)",
                    "Leonardo da Vinci style: solid face panels with "
                    "openings, mitred exactly along the shared edges "
                    "and vertices (as in De divina proportione)"),
                   ('EDGES', "Edge Struts",
                    "Square sticks along the edges with flat caps "
                    "and faceted knuckles at the vertices (Lang "
                    "polypolyhedra style)"),
                   ('BALLSTICK', "Ball and Stick",
                    "Round cylindrical struts along the edges and "
                    "small spheres at the vertices (ball-and-stick "
                    "model)")],
            default='FACES')
        width: FloatProperty(
            name="Frame Width", default=0.22, min=0.02, max=0.9,
            description="Hollow-face ring width (fraction of the face)")
        thickness: FloatProperty(name="Frame Thickness", default=0.10,
                                 min=0.01, max=1.0,
                                 description="Thickness of the "
                                             "hollow-face frames")
        cap_size: FloatProperty(
            name="Cap Size", default=1.0, min=0.3, max=3.0,
            description="How far the edge struts stop short of each "
                        "vertex (in strut thicknesses); the faceted "
                        "knuckle fills the joint")
        strut_radius: FloatProperty(
            name="Strut Radius", default=0.02, min=0.001, max=0.5,
            description="Ball-and-stick edge cylinder radius")
        node_radius: FloatProperty(
            name="Node Radius", default=0.035, min=0.0, max=0.5,
            description="Ball-and-stick vertex sphere radius "
                        "(0 = no nodes)")
        comp_rot: FloatProperty(
            name="Component Rotation", default=0.0, min=-180.0,
            max=180.0,
            description="Rotate every component about its own symmetry "
                        "axis (explores Lang-style polypolyhedra "
                        "variants)")
        size: FloatProperty(
            name="Component Size", default=1.0, min=0.5, max=2.0,
            description="Scale of each component about the centre")
        spin: FloatProperty(
            name="Spin", default=0.0, min=-180.0, max=180.0,
            description="Extra rotation of the whole compound about "
                        "its main symmetry axis")
        coloring: EnumProperty(
            name="Coloring",
            description="How components are assigned materials",
            items=[('COMP', "Per Component", "one material per "
                    "polyhedron (view with Material Preview)"),
                   ('NONE', "None", "no materials")],
            default='COMP')
        scale: FloatProperty(name="Scale", default=1.0, min=0.01,
                             max=100.0,
                             description="Overall size of the compound")

        _PALETTE = [(0.83, 0.68, 0.21), (0.27, 0.52, 0.79),
                    (0.90, 0.36, 0.23), (0.30, 0.69, 0.42),
                    (0.62, 0.40, 0.75), (0.25, 0.72, 0.72),
                    (0.91, 0.56, 0.71), (0.55, 0.60, 0.29),
                    (0.45, 0.45, 0.85), (0.80, 0.50, 0.30)]

        @classmethod
        def _material_for(cls, i):
            name = f"Tangle {i + 1}"
            mat = bpy.data.materials.get(name)
            if mat is None:
                mat = bpy.data.materials.new(name)
                rgb = cls._PALETTE[i % len(cls._PALETTE)]
                mat.diffuse_color = (*rgb, 1.0)
                mat.use_nodes = True
                bsdf = mat.node_tree.nodes.get("Principled BSDF")
                if bsdf is not None:
                    bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
                    bsdf.inputs["Roughness"].default_value = 0.35
                    try:
                        bsdf.inputs["Metallic"].default_value = 0.7
                    except KeyError:
                        pass
            return mat

        def execute(self, context):
            verts, faces, nc, face_comp = build_tangle(
                self.kind, self.style, self.width, self.thickness,
                self.size, self.comp_rot, self.spin, self.scale,
                self.cap_size, self.strut_radius, self.node_radius)
            me = bpy.data.meshes.new("Tangle")
            me.from_pydata(verts, [], faces)
            me.validate(clean_customdata=True)
            # fit (roughly) within a 2 x scale cube at the origin
            lo = [min(v.co[k] for v in me.vertices)
                  for k in range(3)]
            hi = [max(v.co[k] for v in me.vertices)
                  for k in range(3)]
            half = max((hi[k] - lo[k]) / 2.0
                       for k in range(3)) or 1.0
            f = self.scale / half
            for v in me.vertices:
                v.co = [(v.co[k] - (lo[k] + hi[k]) / 2.0) * f
                        for k in range(3)]
            if len(me.polygons) == len(faces):
                attr = me.attributes.new("component_index", 'INT', 'FACE')
                attr.data.foreach_set('value', face_comp)
                if self.coloring == 'COMP':
                    for i in range(nc):
                        me.materials.append(self._material_for(i))
                    me.polygons.foreach_set('material_index', face_comp)
            me.update()
            obj = bpy.data.objects.new("Tangle", me)
            context.collection.objects.link(obj)
            obj.location = context.scene.cursor.location
            for o in context.selected_objects:
                o.select_set(False)
            obj.select_set(True)
            context.view_layer.objects.active = obj
            self.report({'INFO'}, f"{nc} components")
            return {'FINISHED'}

        def draw(self, context):
            lay = self.layout
            lay.use_property_split = True
            bs = self.style == 'BALLSTICK'
            for k in ('kind', 'style', 'width', 'thickness',
                      'strut_radius', 'node_radius', 'cap_size',
                      'size', 'comp_rot', 'spin', 'coloring', 'scale'):
                if k == 'width' and self.style != 'FACES':
                    continue
                if k == 'thickness' and bs:
                    continue
                if k in ('strut_radius', 'node_radius') and not bs:
                    continue
                if k == 'cap_size' and self.style != 'EDGES':
                    continue
                lay.prop(self, k)

    def _menu_func(self, context):
        self.layout.operator("mesh.tangle_add", icon='MOD_BOOLEAN')

    ADD_MENU = True

    def register():
        bpy.utils.register_class(MESH_OT_tangle_add)
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.append(_menu_func)

    def unregister():
        if ADD_MENU:
            bpy.types.VIEW3D_MT_mesh_add.remove(_menu_func)
        bpy.utils.unregister_class(MESH_OT_tangle_add)


def _selftest():
    def _check(v, f):
        """closed 2-manifold with outward normals?"""
        from collections import Counter
        cnt = Counter()
        for fc_ in f:
            for i in range(len(fc_)):
                a, b = fc_[i], fc_[(i + 1) % len(fc_)]
                cnt[(min(a, b), max(a, b))] += 1
        manifold = all(c == 2 for c in cnt.values())
        vol = 0.0
        for fc_ in f:
            for i in range(1, len(fc_) - 1):
                p, q, r = v[fc_[0]], v[fc_[i]], v[fc_[i + 1]]
                vol += (p[0] * (q[1] * r[2] - q[2] * r[1])
                        - p[1] * (q[0] * r[2] - q[2] * r[0])
                        + p[2] * (q[0] * r[1] - q[1] * r[0])) / 6
        return manifold, vol
    for kind, n in (('T2', 2), ('T5', 5), ('T10', 10), ('C5', 5),
                    ('O5', 5), ('C3', 3)):
        for style in ('FACES', 'EDGES'):
            v, f, nc, fc = build_tangle(kind, style)
            man, vol = _check(v, f)
            ok = nc == n and man and vol > 0
            print(f"{kind:4s}/{style}: comps={nc}({n}) "
                  f"manifold={man} vol={vol:+.3f} "
                  f"{'OK' if ok else 'BAD'}")
            assert ok
