# Apollonian gaskets and sphere packings, by inversive geometry.
#
# Part of the Math Art IFS engine (`math_art/ifs/`).  Python + numpy
# only -- no `bpy` -- so the engine imports and self-tests headlessly;
# the registered operators stay in their flat generator modules.
#
# Three mutually tangent circles determine exactly two more tangent to
# all three (Apollonius); iterating fills the gaps with a gasket whose
# curvatures are all integers when the seed's are, by the Descartes
# circle theorem
#
#     (k1 + k2 + k3 + k4)^2 = 2 (k1^2 + k2^2 + k3^2 + k4^2).
#
# Reading that as a quadratic in k4 gives two roots summing to
# 2(k1 + k2 + k3), so the second solution is k4' = 2(k1+k2+k3) - k4 --
# a reflection, which is why the whole packing is the orbit of a group
# generated by four inversions.  Curvature is signed: negative for the
# enclosing circle.  The same argument holds for spheres, via the
# Soddy-Gosset theorem 3 (sum k^2) = (sum k)^2 in three dimensions.
#
# References:
# - R. Descartes, letter to Princess Elisabeth, 1643; rediscovered by
#   F. Soddy, "The Kiss Precise", Nature 137, 1936, p. 1021.
# - T. Gosset, "The Kiss Precise", Nature 139, 1937, p. 62 -- the
#   n-dimensional form.
# - R. L. Graham, J. C. Lagarias, C. L. Mallows, A. R. Wilks and C. H.
#   Yan, "Apollonian Circle Packings: Number Theory", Journal of Number
#   Theory 100, 2003, pp. 1-45.

import cmath
import math

import numpy as np


class Ball:
    """A circle or sphere: signed curvature k (negative if enclosing),
    centre c (a 2- or 3-vector), and generation depth d (0 for the seed
    elements, increasing with each inscribed level -- used for coloring)."""
    __slots__ = ('k', 'c', 'd')

    def __init__(self, k, c, d=0):
        self.k = float(k)
        self.c = np.asarray(c, dtype=float)
        self.d = int(d)


def reflect(group, c0):
    """The element tangent to every ball in `group` other than c0.

    Descartes / Soddy reflection.  The two spheres tangent to a group of
    d+1 mutually tangent spheres in R^d have curvatures (and curvature-
    centre coordinates) summing to 2/(d-1) times the group's sum -- the
    factor is 2 for circles in the plane, 1 for spheres in space.  Using
    the 2D factor in 3D (an earlier bug) made every gap-filler tangent to
    only the inner spheres, so the packing never reached the enclosing
    sphere; the dimension-aware factor fixes that."""
    f = 2.0 / (len(c0.c) - 1)                    # 2 in 2D, 1 in 3D
    ksum = sum(b.k for b in group)
    csum = sum(b.k * b.c for b in group)
    k = f * ksum - c0.k
    c = (f * csum - c0.k * c0.c) / k
    return Ball(k, c)


def _overlaps(n, out, tol=1e-4):
    """True if positive ball n interpenetrates any positive ball in
    out. In 3D, naive Descartes reflection over every quadruple of the
    seed over-fills; rejecting overlaps keeps the packing valid."""
    rn = 1.0 / n.k
    for b in out:
        if b.k <= 0.0:
            continue
        if np.linalg.norm(n.c - b.c) < rn + 1.0 / b.k - tol:
            return True
    return False


def _base_2d():
    """Outer circle (-1) with two inner circles (2), plus the two
    Descartes circles (3) inscribed in the top and bottom gaps."""
    A = Ball(-1.0, [0.0, 0.0])
    B = Ball(2.0, [0.5, 0.0])
    C = Ball(2.0, [-0.5, 0.0])
    kA, kB, kC = A.k, B.k, C.k
    zA, zB, zC = 0.0 + 0j, 0.5 + 0j, -0.5 + 0j
    S = kA + kB + kC
    k4 = S + 2.0 * math.sqrt(max(kA * kB + kB * kC + kC * kA, 0.0))
    zsum = kA * zA + kB * zB + kC * zC
    zroot = cmath.sqrt(kA * kB * zA * zB + kB * kC * zB * zC
                       + kC * kA * zC * zA)
    tops = []
    for zr in (zsum + 2 * zroot, zsum - 2 * zroot):
        z = zr / k4
        tops.append(Ball(k4, [z.real, z.imag]))
    return A, B, C, tops


def _rec2(a, b, c, c0, out, depth, min_r, cap, gen=2):
    if len(out) >= cap:
        return
    n = reflect([a, b, c], c0)
    if n.k <= 0.0 or 1.0 / n.k < min_r or depth < 0:
        return
    n.d = gen
    out.append(n)
    _rec2(a, b, n, c, out, depth - 1, min_r, cap, gen + 1)
    _rec2(a, c, n, b, out, depth - 1, min_r, cap, gen + 1)
    _rec2(b, c, n, a, out, depth - 1, min_r, cap, gen + 1)


def gasket_2d(depth, min_r, cap):
    A, B, C, tops = _base_2d()
    for t in tops:
        t.d = 1
    out = [A, B, C] + tops
    for t in tops:
        _rec2(A, B, t, C, out, depth, min_r, cap)
        _rec2(A, C, t, B, out, depth, min_r, cap)
        _rec2(B, C, t, A, out, depth, min_r, cap)
    return out


_TETRA = np.array([(1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1)],
                  dtype=float)

# the four vertices scaled to unit circumradius: the seed spheres sit
# at the corners of a regular tetrahedron on the unit sphere
_TETRA /= math.sqrt(3.0)


def _base_3d():
    """Outer sphere (-1) with four equal inner spheres at tetrahedron
    vertices, all mutually tangent and tangent to the outer sphere."""
    # solve 1.2247 r = 1 - r  (tetra circumradius = 1 - r)
    circ = math.sqrt(3.0 / 8.0) * 2.0            # per unit tangent dist
    # centres at distance (1-r); edge = 2r; circumradius = circ * r
    r = 1.0 / (1.0 + circ)
    k = 1.0 / r
    outer = Ball(-1.0, [0.0, 0.0, 0.0])
    inner = [Ball(k, d * (1.0 - r)) for d in _TETRA]
    return [outer] + inner


def _rec3(a, b, c, d, c0, out, depth, min_r, cap, gen=1):
    if len(out) >= cap:
        return
    n = reflect([a, b, c, d], c0)
    if n.k <= 0.0 or 1.0 / n.k < min_r or depth < 0:
        return
    if _overlaps(n, out):
        return
    n.d = gen
    out.append(n)
    _rec3(a, b, c, n, d, out, depth - 1, min_r, cap, gen + 1)
    _rec3(a, b, d, n, c, out, depth - 1, min_r, cap, gen + 1)
    _rec3(a, c, d, n, b, out, depth - 1, min_r, cap, gen + 1)
    _rec3(b, c, d, n, a, out, depth - 1, min_r, cap, gen + 1)


def packing_3d(depth, min_r, cap):
    """Bounded Apollonian sphere packing, filled uniformly.

    Every curvilinear gap is a quadruple of mutually tangent spheres; its
    inscribed sphere is found by reflection and each spawns four sub-gaps
    (each triple of the quadruple plus the new sphere).  The gaps are
    processed LARGEST-INSCRIBED-FIRST from a global priority queue, with a
    dedup set on the spheres.  A depth-first recursion with a count cap
    (the earlier approach) filled some directions densely and left others
    empty; largest-first breadth filling covers the ball uniformly, and
    the global dedup replaces the old overlap rejection (the corrected
    reflection no longer over-fills)."""
    import heapq
    base = _base_3d()                            # [outer(-1), i1..i4]
    out = list(base[1:])                         # keep the 4 inner spheres
    seen = set()
    heap = []
    tie = [0]

    def key(b):
        return (round(b.k, 3), round(b.c[0], 3),
                round(b.c[1], 3), round(b.c[2], 3))

    for b in out:
        b.d = 0
        seen.add(key(b))

    def push(four, c0, gen):
        if gen > depth:
            return
        n = reflect(four, c0)
        if n.k <= 0.0 or 1.0 / n.k < min_r:
            return
        tie[0] += 1
        heapq.heappush(heap, (n.k, tie[0], n, four, gen))  # smallest k first

    for i in range(5):                           # the 5 base gaps
        push([base[j] for j in range(5) if j != i], base[i], 1)
    while heap and len(out) < cap:
        _k, _t, n, four, gen = heapq.heappop(heap)
        kk = key(n)
        if kk in seen:
            continue
        seen.add(kk)
        n.d = gen
        out.append(n)
        for t in range(4):                       # four sub-gaps against n
            triple = [four[j] for j in range(4) if j != t]
            push(triple + [n], four[t], gen + 1)
    return out


try:
    from ..surfaces.primitives import icosphere as _icosphere_shared
except ImportError:  # flat import outside the package
    from surfaces.primitives import icosphere as _icosphere_shared


def _icosphere(level=3):
    """Unit icosphere: icosahedron subdivided `level` times (level 1 =
    42 verts, 2 = 162, 3 = 642, 4 = 2562).  Higher levels round the
    spheres so mutually-tangent spheres actually appear to touch.
    The shared builder is in `surfaces.primitives`.  This caller wants
    the 'once' projection and clamps level 0 up to 1: tangent spheres
    look wrong faceted, and that clamp is this module's policy.
    """
    return _icosphere_shared(max(1, int(level)), 'once')


def _ring(centre, R, tube, nu, nv):
    verts, faces = [], []
    for i in range(nu):
        u = 2 * math.pi * i / nu
        cu, su = math.cos(u), math.sin(u)
        for j in range(nv):
            vv = 2 * math.pi * j / nv
            rr = R + tube * math.cos(vv)
            verts.append((centre[0] + rr * cu, centre[1] + rr * su,
                          tube * math.sin(vv)))
    for i in range(nu):
        for j in range(nv):
            a = i * nv + j
            b = ((i + 1) % nu) * nv + j
            c = ((i + 1) % nu) * nv + (j + 1) % nv
            d = i * nv + (j + 1) % nv
            faces.append((a, b, c, d))
    return verts, faces


def _disc(centre, R, seg, z=0.0):
    """A flat filled disc as a single seg-gon face at height z."""
    verts = [(centre[0] + R * math.cos(2 * math.pi * i / seg),
              centre[1] + R * math.sin(2 * math.pi * i / seg), z)
             for i in range(seg)]
    return verts, [tuple(range(seg))]


# Face/sphere colour palette (RGBA); kept local so the module stays a
# self-contained single-file add-on.
_PALETTE = [
    (0.86, 0.24, 0.24, 1.0), (0.95, 0.58, 0.20, 1.0),
    (0.96, 0.86, 0.30, 1.0), (0.42, 0.78, 0.36, 1.0),
    (0.24, 0.70, 0.70, 1.0), (0.28, 0.48, 0.85, 1.0),
    (0.55, 0.40, 0.82, 1.0), (0.86, 0.42, 0.70, 1.0),
]


def _mat_index(b, color_by, log_rmax, log_rmin, npal):
    """Palette slot for a circle/sphere under the chosen colouring:
    UNIFORM (one colour), DEPTH (by generation), or SIZE (log radius)."""
    if color_by == 'UNIFORM':
        return 0
    if color_by == 'DEPTH':
        return b.d % npal
    r = 1.0 / abs(b.k)                            # SIZE
    span = log_rmax - log_rmin
    if span <= 1e-9:
        return 0
    t = (math.log(r) - log_rmin) / span
    return max(0, min(npal - 1, int(t * (npal - 1) + 0.5)))


def build_apollonian(mode='PACKING', depth=5, min_r=0.0, cap=4000,
                     tube_ratio=0.06, inflate=1.0, ring_seg=20,
                     tube_seg=8, scale=1.0, gasket_style='FILLED',
                     color_by='SIZE', sphere_res=3):
    """Build the gasket (2D) or sphere packing (3D). Returns
    (verts, faces, mats, levels, n) centred and fit to a 2 m cube, where
    `mats` is a per-face palette index and `levels` the per-face
    generation depth (for splitting the output into per-level objects).
    2D circles are filled disc faces by default (`gasket_style='FILLED'`)
    or drawn as thin tube rings (`'TUBE'`); the enclosing circle is a
    background disc."""
    verts, faces, mats, levels = [], [], [], []
    npal = len(_PALETTE)
    if mode == 'GASKET':
        mr = min_r if min_r > 0 else 0.01
        balls = gasket_2d(depth, mr, cap)
    else:
        mr = min_r if min_r > 0 else 0.005
        balls = packing_3d(depth, mr, cap)
    radii = [1.0 / abs(b.k) for b in balls]
    log_rmax = math.log(max(radii))
    log_rmin = math.log(min(radii))

    if mode == 'GASKET':
        for b in balls:
            R = 1.0 / abs(b.k)
            mi = _mat_index(b, color_by, log_rmax, log_rmin, npal)
            if gasket_style == 'TUBE':
                v, f = _ring((b.c[0], b.c[1]), R, tube_ratio * R,
                             ring_seg, tube_seg)
            else:                                # FILLED discs
                z = -0.002 if b.k < 0.0 else 0.0  # enclosing circle behind
                v, f = _disc((b.c[0], b.c[1]), R, ring_seg, z)
            base = len(verts)
            verts.extend(v)
            faces.extend([tuple(base + i for i in fc) for fc in f])
            mats.extend([mi] * len(f))
            levels.extend([b.d] * len(f))
    else:
        SV, SF = _icosphere(sphere_res)
        for b in balls:
            r = inflate / b.k
            mi = _mat_index(b, color_by, log_rmax, log_rmin, npal)
            base = len(verts)
            verts.extend((b.c + r * p).tolist() for p in SV)
            faces.extend([tuple(base + i for i in fc) for fc in SF])
            mats.extend([mi] * len(SF))
            levels.extend([b.d] * len(SF))
    n = len(balls)
    V = np.asarray(verts)
    lo, hi = V.min(axis=0), V.max(axis=0)
    ext = float((hi - lo).max())
    V = (V - 0.5 * (lo + hi)) * (2.0 / ext if ext > 1e-9 else 1.0)
    return V * scale, faces, mats, levels, n
