# Citations, harvested from the module headers that already carry them.
#
# The contributor notes require every generator module in math_art/ to
# credit the
# mathematics it implements in a `References:` block -- the mathematician,
# the paper or book, the year.  Those blocks are vetted, they are kept
# current by whoever writes the generator, and `docs/scaffold_pages.py`
# already lifts them verbatim onto the documentation pages.
#
# So the surface database should not retype them from memory.  Retyping
# is how a citation becomes subtly wrong, and a wrong citation is worse
# than none: it looks authoritative.  This module reads the blocks
# instead, which means a record's provenance stays in step with the code
# for free.
#
# TWO REFINEMENTS over the docs extractor.
#
# 1. MULTIPLE BLOCKS PER MODULE.  math_art/minsurf/weierstrass.py carries
#    15 `References:` blocks, zoo.py 8 -- one per family section, each
#    citing the papers for the surfaces defined below it.  Taking only
#    the header would attribute Karcher's saddle towers to the whole zoo.
#    So every block is collected with its line number, and a row is given
#    the NEAREST PRECEDING block, which is the one written about it.
#
# 2. NAME MATCHING.  A row labelled "Wei Doubly Periodic (genus 2)" wants
#    the reference that mentions Wei first.  Surnames in the label are
#    matched against the block's entries and matching ones are promoted,
#    so the most specific citation leads.
#
# Where neither applies the record says so explicitly rather than
# carrying a placeholder -- see `METHOD_ONLY` below.

import os
import re

# The Weierstrass-Enneper representation itself, for rows whose
# individual attribution is not recorded anywhere in the tree.  This is a
# REAL citation of the construction, paired with an explicit statement
# that the individual member is unattributed -- which is information,
# where "not curated yet" is not.
METHOD_ONLY = [
    'K. Weierstrass, "Untersuchungen ueber die Flaechen, deren mittlere '
    'Kruemmung ueberall gleich null ist", Monatsber. Berliner Akad. (1866); '
    'A. Enneper, Zeitschrift fuer Mathematik und Physik 9 (1864) -- the '
    'representation formula this surface is built from.',
    "No individual attribution for this family member is recorded in the "
    "source tree; it is a member of a family generated by the method above "
    "rather than a separately published surface.",
]


def blocks(path):
    """Every `References:` block in `path`, as (line_number, [entries]).

    Entries follow the repo convention: each begins with a `-` marker (or,
    in the older header style, is simply indented) and continuation lines
    are rejoined into it.
    """
    if not path or not os.path.exists(path):
        return []
    out = []
    cur = None
    with open(path, encoding="utf-8", errors="replace") as fh:
        for n, line in enumerate(fh, 1):
            # `References:` and also the sectioned form several modules
            # use -- "References for 5:", "References for 8:" -- which
            # carries real citations and would otherwise be invisible.
            if re.match(r"^#\s*References(\s+for\s+[^:]*)?:", line):
                cur = (n, [])
                out.append(cur)
                continue
            if cur is None:
                continue
            if not line.startswith("#"):
                cur = None
                continue
            body = line[1:].rstrip()
            if not body.strip():
                cur = None
                continue
            text = body.strip()
            starts = text.startswith(("-", "*"))
            text = re.sub(r"^[-*]\s*", "", text)
            entries = cur[1]
            # A line that starts a new entry: an explicit marker, or -- for
            # the older unmarked style -- a line that looks like the start
            # of a citation (an initial-and-surname, or a quoted title).
            looks_new = bool(re.match(r"^[A-Z]\.\s*[A-Z]", text)) or \
                bool(re.match(r"^[A-Z][a-z]+,\s", text))
            if starts or not entries or (looks_new and len(entries[-1]) > 60):
                entries.append(text)
            else:
                entries[-1] += " " + text
    return [(n, [e for e in es if e]) for n, es in out if es]


def header(path):
    """The first block: the module-level references."""
    bs = blocks(path)
    return list(bs[0][1]) if bs else []


def nearest(path, line_no):
    """The block written about the code at `line_no`.

    The nearest block ABOVE the line, falling back to the header. This is
    what makes per-family citation work in a 11,000-line module that
    carries fifteen of them.
    """
    bs = blocks(path)
    if not bs:
        return []
    best = None
    for n, entries in bs:
        if n <= line_no and (best is None or n > best[0]):
            best = (n, entries)
    if best is None:
        best = bs[0]
    return list(best[1])


_SURNAME = re.compile(r"[A-Z][a-z]{2,}")

# Words that look like surnames in a label but are not.
_NOT_NAMES = {
    "Surface", "Tower", "Ends", "Genus", "Periodic", "Doubly", "Singly",
    "Higher", "Enneper", "Ended", "Handle", "Handles", "Annular", "Catenoid",
    "Catenoids", "Sphere", "Torus", "Twisted", "Tilted", "Screw", "Motion",
    "Fence", "Half", "Alternating", "Symmetrized", "Translation", "Invariant",
    "Experimental", "Family", "Full", "Level", "Bjorling", "Ribbon", "Spiral",
    "Band", "Mobius", "Helix", "Trefoil", "Archimedean", "Logarithmic",
    "Minimal", "Klein", "Bottle", "Projective", "Plane", "Planar", "Noid",
    "Prismatic", "Pyramidal", "Bipyramidal", "Antiprismatic", "Double",
    "Finite", "Wings", "Unequal", "Saddle", "Cylinder", "Nodoid", "Unduloid",
    "Second", "Exact", "One", "Sided", "Wound", "Single", "Sheet",
    # Number words: "Six-Ended Scherk Tower" must yield {Scherk}, not
    # {Six, Scherk} -- an entry mentioning "six" would otherwise outrank
    # the one that actually names Scherk.
    "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
    "Twelve", "With", "And", "The", "For", "From", "Its", "Все",
    "Rolling", "Conic", "Colliding", "Bubbles", "Lobes", "Covers", "Cover",
    "Chain", "Drop", "Water", "Hanging", "Dome", "Elasticity", "Fresnel",
    "Paper", "Bag", "Egg", "Box", "Sine", "Seashell", "Corkscrew",
    "Helico", "Conical", "Skew", "Ruled", "Cubic", "Milk", "Carton",
    "Constant", "Slope", "Compound", "Helical", "Cone", "Tangent",
    "Developable", "Steiner", "Veronese", "Shadow", "Sudanese", "Solid",
    "Figure", "Hopf", "Seifert", "Willmore", "Bubble", "Cluster", "Relaxed",
    "Capillary", "Plateau", "Soap", "Film", "Span", "Atomic", "Orbital",
    "Spherical", "Harmonic", "Supershape", "Width", "Form", "Astroidal",
    "Ellipsoid", "Bohemian", "Trihyperboloid", "Neiloid", "Bouguer",
    "Sphericon", "Pearce", "Saddle", "Polyhedron", "Elastic", "Bubbleton",
    "Crochet", "Hyperbolic", "Surfaces",
}


def surnames(label):
    """Plausible surnames in a row label, for promoting the right citation."""
    parts = set()
    for tok in re.split(r"[^A-Za-z]+", label or ""):
        if _SURNAME.fullmatch(tok) and tok not in _NOT_NAMES:
            parts.add(tok)
    return parts


def rank(entries, label):
    """Reorder `entries` so those naming the label's surnames come first."""
    names = surnames(label)
    if not names or not entries:
        return list(entries)
    hit, miss = [], []
    for e in entries:
        (hit if any(n in e for n in names) else miss).append(e)
    return hit + miss


def for_row(path, line_no, label, max_entries=6):
    """Citations for one registry row. Empty when the module carries none."""
    got = rank(nearest(path, line_no), label)
    return got[:max_entries]


def _selftest():
    """Parser self-test on a synthetic module; raises on failure."""
    import tempfile
    src = '''# A module.
#
# References:
# - H. F. Scherk, "Bemerkungen", J. reine angew. Math. 13 (1835).
# - K. Weierstrass (1866); A. Enneper (1864).

import math

# References:
# - H. Karcher, "Embedded minimal surfaces derived from Scherk's
#   examples", Manuscripta Math. 62 (1988).
# - M. Wohlgemuth, "Minimal surfaces of higher genus", 1997.

def later():
    pass
'''
    fd, path = tempfile.mkstemp(suffix=".py")
    os.write(fd, src.encode())
    os.close(fd)
    try:
        bs = blocks(path)
        assert len(bs) == 2, bs
        assert len(bs[0][1]) == 2 and len(bs[1][1]) == 2, bs

        # a continuation line must be rejoined, not made its own entry
        assert "Manuscripta Math. 62 (1988)." in bs[1][1][0], bs[1][1]

        h = header(path)
        assert h[0].startswith("H. F. Scherk"), h

        # the NEAREST block wins -- this is what stops Karcher's towers
        # being attributed to the whole module
        near = nearest(path, 200)
        assert near[0].startswith("H. Karcher"), near
        near = nearest(path, 3)
        assert near[0].startswith("H. F. Scherk"), near

        # surname matching promotes the specific citation
        got = for_row(path, 200, "Wohlgemuth Second Surface (genus 3)")
        assert "Wohlgemuth" in got[0], got

        # label noise must not be read as a surname
        assert surnames("Six-Ended Scherk Tower (genus 1)") == {"Scherk"}
        assert surnames("Torus with Catenoid + 2 Annular Ends") == set()
    finally:
        os.unlink(path)

    # against the real tree, if present
    real = os.path.join(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))), "math_art",
        "minsurf", "weierstrass.py")
    if os.path.exists(real):
        bs = blocks(real)
        assert len(bs) >= 10, \
            "weierstrass.py should carry many per-family blocks, got %d" % len(bs)

    print("RESULT: OK  (surfdb.references)")
