"""Defining data for the minimal surfaces.

GENERATED by tools/extract_definitions.py -- do not hand-edit.

Read OUT OF the shipped builders rather than transcribed into them:
the nodal expression is the source of the function that is
evaluated, and the Weierstrass data comes from calling each spec's
`terms(a, tau)` at its own moduli.  A surface whose data could not be
obtained that way is absent here rather than approximated.
"""

import json

NODAL_POLYNOMIAL = json.loads(r'''{
 "CD": "cos(3 * x + y) * cos(z) - sin(3 * x - y) * sin(z) + cos(x + 3 * y) * cos(z) + sin(x - 3 * y) * sin(z) + cos(x - y) * cos(3 * z) - sin(x + y) * sin(3 * z)",
 "CG": "3 * (sin(x) * cos(y) + sin(y) * cos(z) + cos(x) * sin(z)) + 2 * (sin(3 * x) * cos(y) + sin(3 * y) * cos(z) + cos(x) * sin(3 * z)) - 2 * (sin(x) * cos(3 * y) + sin(y) * cos(3 * z) + cos(3 * x) * sin(z))",
 "CI2Y": "2 * (sin(2 * x) * cos(y) * sin(z) + sin(x) * sin(2 * y) * cos(z) + cos(x) * sin(y) * sin(2 * z)) + cos(2 * x) * cos(2 * y) + cos(2 * y) * cos(2 * z) + cos(2 * x) * cos(2 * z)",
 "D": "sin(x) * sin(y) * sin(z) + sin(x) * cos(y) * cos(z) + cos(x) * sin(y) * cos(z) + cos(x) * cos(y) * sin(z)",
 "DPRIME": "0.5 * (cos(x) * cos(y) * cos(z) + cos(x) * sin(y) * sin(z) + sin(x) * cos(y) * sin(z) + sin(x) * sin(y) * cos(z)) - 0.5 * (sin(2 * x) * sin(2 * y) + sin(2 * y) * sin(2 * z) + sin(2 * z) * sin(2 * x)) - 0.2",
 "FK_CPMY": "-2 * cos(x) * cos(y) * cos(z) + sin(2 * x) * sin(y) + sin(2 * y) * sin(z) + sin(x) * sin(2 * z)",
 "FK_CS": "cos(2 * x) + cos(2 * y) + cos(2 * z) + 2 * (sin(3 * x) * sin(2 * y) * cos(z) + cos(x) * sin(3 * y) * sin(2 * z) + sin(2 * x) * cos(y) * sin(3 * z)) + 2 * (sin(2 * x) * cos(3 * y) * sin(z) + sin(x) * sin(2 * y) * cos(3 * z) + cos(3 * x) * sin(y) * sin(2 * z))",
 "FK_CY": "-sin(x) * sin(y) * sin(z) + sin(2 * x) * sin(y) + sin(2 * y) * sin(z) + sin(x) * sin(2 * z) - cos(x) * cos(y) * cos(z) + sin(2 * x) * cos(z) + cos(x) * sin(2 * y) + cos(y) * sin(2 * z)",
 "FK_PMY": "2 * cos(x) * cos(y) * cos(z) + sin(2 * x) * sin(y) + sin(2 * y) * sin(z) + sin(x) * sin(2 * z)",
 "FK_S": "cos(2 * x) * sin(y) * cos(z) + cos(x) * cos(2 * y) * sin(z) + sin(x) * cos(y) * cos(2 * z)",
 "FK_Y": "cos(x) * cos(y) * cos(z) + sin(x) * sin(y) * sin(z) + sin(2 * x) * sin(y) + sin(2 * y) * sin(z) + sin(x) * sin(2 * z) + cos(x) * sin(2 * y) + cos(y) * sin(2 * z) + sin(2 * x) * cos(z)",
 "FRD": "4 * cos(x) * cos(y) * cos(z) - (cos(2 * x) * cos(2 * y) + cos(2 * y) * cos(2 * z) + cos(2 * z) * cos(2 * x))",
 "FRD2": "8 * cos(x) * cos(y) * cos(z) + c2x * c2y * c2z - (c2x * c2y + c2y * c2z + c2z * c2x)",
 "G": "sin(x) * cos(y) + sin(y) * cos(z) + sin(z) * cos(x)",
 "GPRIME": "sin(2 * x) * cos(y) * sin(z) + sin(x) * sin(2 * y) * cos(z) + cos(x) * sin(y) * sin(2 * z) + 0.32",
 "IWP": "2 * (cos(x) * cos(y) + cos(y) * cos(z) + cos(z) * cos(x)) - (cos(2 * x) + cos(2 * y) + cos(2 * z))",
 "KSURF": "0.3 * (cx + cy + cz) + 0.3 * (cx * cy + cy * cz + cz * cx) - 0.4 * (cos(2 * x) + cos(2 * y) + cos(2 * z)) + 0.2",
 "LIDINOID": "0.5 * (sin(2 * x) * cos(y) * sin(z) + sin(2 * y) * cos(z) * sin(x) + sin(2 * z) * cos(x) * sin(y) - cos(2 * x) * cos(2 * y) - cos(2 * y) * cos(2 * z) - cos(2 * z) * cos(2 * x)) + 0.15",
 "NEOVIUS": "3 * (cos(x) + cos(y) + cos(z)) + 4 * cos(x) * cos(y) * cos(z)",
 "OCTO": "0.6 * (cx * cy + cy * cz + cz * cx) - 0.4 * (cx + cy + cz) + 0.25",
 "P": "cos(x) + cos(y) + cos(z)",
 "SCHERKT": "sin(z) - sinh(x) * sinh(y)",
 "SPLITP": "1.1 * (sin(2 * x) * sin(z) * cos(y) + sin(2 * y) * sin(x) * cos(z) + sin(2 * z) * sin(y) * cos(x)) - 0.2 * (cos(2 * x) * cos(2 * y) + cos(2 * y) * cos(2 * z) + cos(2 * z) * cos(2 * x)) - 0.4 * (cos(2 * x) + cos(2 * y) + cos(2 * z))"
}''')

WEIERSTRASS = json.loads(r'''{
 "BOX_1001": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.1,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.1,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.2,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.2,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.46802126852411385,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.46802126852411385,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.06802126852411389,
     0.21143741747538367
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.06802126852411389,
     0.21143741747538367
    ]
   }
  ],
  "constant": [
   -0.0,
   -1.7844914442781112
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.21143741747538367
   ]
  },
  "moduli_a": 0.1,
  "modulus_tau": [
   0.0,
   0.42287483495076733
  ]
 },
 "BOX_1010": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.13,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.13,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.2540625168102844,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.2540625168102844,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.40751143412603386,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.40751143412603386,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.28344891731574945,
     0.4
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.28344891731574945,
     0.4
    ]
   }
  ],
  "constant": [
   -0.0,
   2.461277363102036
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.4
   ]
  },
  "moduli_a": 0.13,
  "modulus_tau": [
   0.0,
   0.8
  ]
 },
 "BOX_1011": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.06,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.06,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.25007414956744817,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.25007414956744817,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.43994933834214295,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.43994933834214295,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.2501248112253052,
     0.4
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.2501248112253052,
     0.4
    ]
   }
  ],
  "constant": [
   -0.0,
   0.7850060573689439
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.4
   ]
  },
  "moduli_a": 0.06,
  "modulus_tau": [
   0.0,
   0.8
  ]
 },
 "CH": {
  "branch_points": [
   {
    "exponent": 0.6666666666666666,
    "point": [
     0.18043719743865927,
     0.0
    ]
   },
   {
    "exponent": 0.6666666666666666,
    "point": [
     0.31956280256134073,
     0.0
    ]
   },
   {
    "exponent": -0.6666666666666666,
    "point": [
     -0.18043719743865927,
     0.0
    ]
   },
   {
    "exponent": -0.6666666666666666,
    "point": [
     -0.31956280256134073,
     0.0
    ]
   },
   {
    "exponent": -0.6666666666666666,
    "point": [
     0.25,
     0.45
    ]
   },
   {
    "exponent": 0.6666666666666666,
    "point": [
     -0.25,
     0.45
    ]
   }
  ],
  "constant": [
   0.0,
   0.5235987755982988
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.45
   ]
  },
  "moduli_a": 0.06956280256134074,
  "modulus_tau": [
   0.0,
   0.9
  ]
 },
 "CLP": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.15,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.15,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.15,
     -1.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.15,
     -1.0
    ]
   }
  ],
  "constant": [
   0.0,
   0.7853981633974483
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.5
   ]
  },
  "moduli_a": 0.15,
  "modulus_tau": [
   0.0,
   2.0
  ]
 },
 "CLP_HANDLE": {
  "branch_points": [
   {
    "exponent": 0.5,
    "point": [
     0.2423350072589261,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.0,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.2423350072589261,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.5,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.0,
     0.75
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.5,
     0.75
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.75
   ]
  },
  "moduli_a": 0.2423350072589261,
  "modulus_tau": [
   0.0,
   1.5
  ]
 },
 "FRDR": {
  "branch_points": [
   {
    "exponent": 0.5,
    "point": [
     0.07,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.18,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.07,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.18,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.43,
     -0.1973931464287999
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.32,
     -0.1973931464287999
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.43,
     -0.1973931464287999
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.32,
     -0.1973931464287999
    ]
   }
  ],
  "constant": [
   0.0,
   0.7853981633974483
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.1973931464287999
   ]
  },
  "moduli_a": 0.07,
  "modulus_tau": [
   0.0,
   0.3947862928575998
  ]
 },
 "FRD_EXACT": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.0930966253175575,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.0930966253175575,
     0.0
    ]
   },
   {
    "exponent": -0.75,
    "point": [
     0.2712689164549617,
     0.0
    ]
   },
   {
    "exponent": 0.75,
    "point": [
     -0.2712689164549617,
     0.0
    ]
   },
   {
    "exponent": 0.75,
    "point": [
     0.2287310835450383,
     0.19874855082560777
    ]
   },
   {
    "exponent": -0.75,
    "point": [
     -0.2287310835450383,
     0.19874855082560777
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.40690337468244253,
     0.19874855082560777
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.40690337468244253,
     0.19874855082560777
    ]
   }
  ],
  "constant": [
   0.0,
   0.7853981633974483
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.19874855082560777
   ]
  },
  "moduli_a": 0.0930966253175575,
  "modulus_tau": [
   0.0,
   0.39749710165121555
  ]
 },
 "H2R": {
  "branch_points": [
   {
    "exponent": 0.6666666666666666,
    "point": [
     0.125,
     0.0
    ]
   },
   {
    "exponent": -0.6666666666666666,
    "point": [
     -0.125,
     0.0
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.2
   ]
  },
  "moduli_a": 0.125,
  "modulus_tau": [
   0.0,
   0.4
  ],
  "triangle_group": [
   3,
   2,
   6
  ]
 },
 "HT": {
  "branch_points": [
   {
    "exponent": 0.5,
    "point": [
     0.16666666666666666,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.16666666666666666,
     0.0
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.2
   ]
  },
  "moduli_a": 0.16666666666666666,
  "modulus_tau": [
   0.0,
   0.4
  ],
  "triangle_group": [
   2,
   3,
   6
  ]
 },
 "I6": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.0,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.0,
     0.44116403887207395
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.0,
     0.465
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.0,
     -0.44116403887207395
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.5,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.5,
     0.44116403887207395
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.5,
     0.465
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.5,
     -0.44116403887207395
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.465
   ]
  },
  "moduli_a": 0.44116403887207395,
  "modulus_tau": [
   0.0,
   0.93
  ]
 },
 "LIDINOID": {
  "branch_points": [
   {
    "exponent": 0.6666666666666666,
    "point": [
     0.0,
     0.0
    ]
   },
   {
    "exponent": -0.6666666666666666,
    "point": [
     0.5,
     0.0
    ]
   }
  ],
  "constant": [
   0.0,
   1.0471975511965976
  ],
  "domain": {
   "x": [
    0.0,
    1.0
   ],
   "y": [
    0.0,
    0.4832078917182825
   ]
  },
  "moduli_a": 0.25,
  "modulus_tau": [
   0.0,
   0.4832078917182825
  ]
 },
 "RII": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.0,
     0.0
    ]
   },
   {
    "exponent": -0.75,
    "point": [
     0.0,
     0.5459942955818213
    ]
   },
   {
    "exponent": -0.75,
    "point": [
     0.0,
     -0.5459942955818213
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.5,
     0.0
    ]
   },
   {
    "exponent": 0.75,
    "point": [
     -0.5,
     0.5459942955818213
    ]
   },
   {
    "exponent": 0.75,
    "point": [
     -0.5,
     -0.5459942955818213
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.9
   ]
  },
  "moduli_a": 0.5459942955818213,
  "modulus_tau": [
   0.0,
   1.8
  ]
 },
 "RPD": {
  "branch_points": [
   {
    "exponent": -0.6666666666666666,
    "point": [
     0.0,
     0.0
    ]
   },
   {
    "exponent": 0.3333333333333333,
    "point": [
     0.5,
     0.7817009621031912
    ]
   },
   {
    "exponent": 0.3333333333333333,
    "point": [
     0.5,
     -0.7817009621031912
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    -0.5,
    1.5
   ],
   "y": [
    0.0,
    0.7817009621031912
   ]
  },
  "moduli_a": 0.5,
  "modulus_tau": [
   0.0,
   1.5634019242063824
  ]
 },
 "SIMOES_BATISTA": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.04631108617540206,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.04631108617540206,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.25,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     -0.25,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.4536889138245979,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.4536889138245979,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.25,
     -0.485
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.25,
     -0.485
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.19605836826545586,
     -0.485
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.19605836826545586,
     -0.485
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.30394163173454414,
     -0.485
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.30394163173454414,
     -0.485
    ]
   }
  ],
  "constant": [
   0.0,
   0.7853981633974483
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.485
   ]
  },
  "moduli_a": 0.04631108617540206,
  "modulus_tau": [
   0.0,
   0.97
  ]
 },
 "SS": {
  "branch_points": [
   {
    "exponent": 0.75,
    "point": [
     0.16666666666666666,
     0.0
    ]
   },
   {
    "exponent": -0.75,
    "point": [
     -0.16666666666666666,
     0.0
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.3
   ]
  },
  "moduli_a": 0.16666666666666666,
  "modulus_tau": [
   0.0,
   0.6
  ],
  "triangle_group": [
   4,
   2,
   4
  ]
 },
 "STESSMANN": {
  "branch_points": [
   {
    "exponent": 0.75,
    "point": [
     0.16666666666666666,
     0.0
    ]
   },
   {
    "exponent": -0.75,
    "point": [
     -0.16666666666666666,
     0.0
    ]
   },
   {
    "exponent": 0.75,
    "point": [
     -0.3333333333333333,
     -0.2886751345948129
    ]
   },
   {
    "exponent": -0.75,
    "point": [
     0.3333333333333333,
     -0.2886751345948129
    ]
   }
  ],
  "constant": [
   0.0,
   0.7853981633974483
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.2886751345948129
   ]
  },
  "moduli_a": 0.16666666666666666,
  "modulus_tau": [
   0.0,
   0.5773502691896258
  ]
 },
 "TR": {
  "branch_points": [
   {
    "exponent": 0.8333333333333334,
    "point": [
     0.3,
     0.0
    ]
   },
   {
    "exponent": -0.8333333333333334,
    "point": [
     -0.3,
     0.0
    ]
   }
  ],
  "constant": [
   0.0,
   0.0
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.5
   ]
  },
  "moduli_a": 0.3,
  "modulus_tau": [
   0.0,
   1.0
  ],
  "triangle_group": [
   6,
   3,
   2
  ]
 },
 "TRIPLY_COSTA": {
  "branch_points": [
   {
    "exponent": -0.5,
    "point": [
     0.0,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.2723060550713618,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     -0.2723060550713618,
     0.0
    ]
   },
   {
    "exponent": 0.5,
    "point": [
     0.5,
     0.0
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.0,
     0.4
    ]
   },
   {
    "exponent": -0.5,
    "point": [
     0.5,
     -0.4
    ]
   }
  ],
  "constant": [
   0.6780915483770072,
   0.7853981633974483
  ],
  "domain": {
   "x": [
    0.0,
    0.5
   ],
   "y": [
    0.0,
    0.4
   ]
  },
  "moduli_a": 0.2723060550713618,
  "modulus_tau": [
   0.0,
   0.8
  ]
 }
}''')
