"""Measure a periodic surface's space group from its own level function.

The 150 periodic records are the database's largest family and its least
reproducible: `symmetry.space_group` was populated on NONE of them, and
`hermann_mauguin` on five, all hand-curated.  A record saying "triply
periodic, rank 3" and nothing else does not identify a TPMS.

WHY NOT DERIVE IT FROM `definition.evolver_cell.generators`.  That was
the obvious route -- 64 records carry exact 4x4 affine matrices with
integer rotation AND translation parts, which look exactly like
space-group elements -- and it is WRONG.  Closing those generators for
Schwarz P yields precisely the 48 operations of Pm-3m, an index-2
SUBGROUP of the Im-3m the surface actually has; Neovius does the same;
Schwarz D yields 24 operations that are not a subgroup of its published
Pn-3m in any setting.  The missing coset for P is generated by the
body-centring translation (1/2, 1/2, 1/2), which maps the surface to
itself while SWAPPING its two labyrinths -- a genuine symmetry of the
surface, but not one Brakke needs in order to tile his patch.  Those
generators are patch-tiling generators, and naming the group from them
would have confidently recorded Schwarz P as Pm-3m.

So the group is measured against the surface instead.  For a surface
given as a level set F = 0, an isometry g is a symmetry exactly when
F(g.x) = s*F(x) with ONE sign s shared over the whole domain: s = +1
preserves the two sides, s = -1 swaps them, and either way the zero set
-- the surface -- is fixed.  Every group in `tools/spacegroups.py`'s
validated Hall table is tested that way and the largest that passes is
reported, together with the origin shift it passes at, because a
space group's operations are stated relative to an origin and the
level function need not share it.

CALIBRATION.  The method reproduces the three published groups it can
be checked against -- Schwarz P and Neovius as Im-3m, the gyroid as
Ia-3d -- which is the whole reason to trust it on the rows that have
no published value.  It does NOT reproduce Pn-3m for Schwarz D: the
stored D approximant satisfies all 192 operations of Fd-3m at the
origin and Pn-3m at no origin, because the approximant is written on
an F-centred cell (F(x + pi, y + pi, z) = F(x, y, z) -- check it) that
holds several primitive cells.  That is a cell-convention difference,
not a contradiction, and following the house rule for the two Ferreol
date disagreements, BOTH values are recorded and the disagreement is
flagged rather than silently resolved.
"""

import itertools
import math
import random
from fractions import Fraction as F

from . import expr

TAU = 2.0 * math.pi

# Origin shifts to try, as fractions of the cell.  Eighths cover every
# origin choice the International Tables use for these groups (halves,
# quarters and eighths); a finer grid costs time and finds nothing.
_SHIFTS = [F(k, 8) for k in range(8)]


class Underivable(Exception):
    """The level function could not be tested."""


def _samples(n, seed):
    rng = random.Random(seed)
    return [(rng.uniform(0.0, 1.0), rng.uniform(0.0, 1.0),
             rng.uniform(0.0, 1.0)) for _ in range(n)]


def _evaluate(text, pts):
    return [expr.evaluate(text, {"x": TAU * u, "y": TAU * v, "z": TAU * w})
            for u, v, w in pts]


def satisfies(text, ops, shift=(0.0, 0.0, 0.0), n=64, seed=4242, rtol=1e-7):
    """Is the level set F = 0 fixed by every operation of `ops`?

    `ops` are (integer 3x3, translation in twelfths) in fractional cell
    coordinates, as `spacegroups.ops` returns them.  `shift` moves the
    group's origin: conjugating (R, t) by a translation s sends it to
    (R, t + (I - R)s).
    """
    pts = _samples(n, seed)
    base = _evaluate(text, pts)
    scale = max(abs(b) for b in base) or 1.0
    for R, t in ops:
        tt = [float(F(int(t[i]), 12)) + shift[i]
              - sum(R[i][k] * shift[k] for k in range(3)) for i in range(3)]
        vals = []
        for p in pts:
            q = [sum(R[i][k] * p[k] for k in range(3)) + tt[i]
                 for i in range(3)]
            vals.append(expr.evaluate(
                text, {"x": TAU * q[0], "y": TAU * q[1], "z": TAU * q[2]}))
        # ONE shared sign over the whole sample.  A per-point sign would
        # accept a function that merely happens to have equal magnitude,
        # which is not a symmetry of anything.
        if not any(all(abs(a - s * b) <= rtol * scale
                       for a, b in zip(vals, base)) for s in (1.0, -1.0)):
            return False
    return True


def _spacegroups():
    """`tools/spacegroups.py`, which is a sibling of the surfdb package."""
    import importlib
    import os
    import sys
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if here not in sys.path:
        sys.path.insert(0, here)
    return importlib.import_module("spacegroups")


def derive(text, candidates=None, quick=16, full=64):
    """The largest Hall-table group the level function satisfies.

    Returns a dict with the symbol, its order, the origin shift it holds
    at, and how many groups were tested -- or `hermann_mauguin: None`
    when nothing passes, which is data too.
    """
    sg = _spacegroups()
    names = sorted(candidates if candidates is not None else sg.HALL)
    table = []
    for hm in names:
        try:
            table.append((len(sg.ops(hm)), hm, sg.ops(hm)))
        except Exception:                                # noqa: BLE001
            continue
    # Largest first, so the FIRST group that passes is provably the
    # maximal one and the search stops there.  Ordering by name instead
    # would have to test all 181 against 512 origins apiece.
    table.sort(key=lambda row: (-row[0], row[1]))
    hits = []
    tested = 0
    top = None
    for order, hm, ops in table:
        # Once a group has passed, only groups of the SAME order can
        # tie with it; anything smaller is a subgroup and uninteresting.
        if top is not None and order < top:
            break
        tested += 1
        for s in itertools.product(_SHIFTS, repeat=3):
            sf = [float(v) for v in s]
            try:
                if not satisfies(text, ops, sf, n=quick):
                    continue
                if not satisfies(text, ops, sf, n=full):
                    continue
            except expr.ExprError as exc:
                raise Underivable("level function does not evaluate: %s" % exc)
            hits.append((hm, order, [str(v) for v in s]))
            top = order
            break

    out = {"hermann_mauguin": None, "order": 0, "origin_shift": None,
           "groups_tested": tested, "ambiguous": False, "note": None}
    if not hits:
        out["note"] = ("no group in the Hall table fixes this level set at "
                       "any eighth-cell origin")
        return out
    if len(hits) > 1:
        # A TIE IS NOT A RESULT.  Several distinct groups of the same
        # order fixing the surface means the group they generate fixes
        # it too, and that group is larger than anything the table holds
        # -- which happens when the level function is written on a cell
        # coarser than its own translational lattice, so per-cell it has
        # more operations than any standard group in its conventional
        # cell.  Naming one of the tied symbols would be picking
        # alphabetically and calling it a derivation.
        out["ambiguous"] = True
        out["order"] = hits[0][1]
        out["note"] = ("%d groups of order %d fix this surface (%s); the "
                       "group they generate is larger than any entry in the "
                       "table, so the cell is coarser than the surface's own "
                       "translational lattice and no single symbol is maximal"
                       % (len(hits), hits[0][1],
                          ", ".join(h[0] for h in hits)))
        return out
    hm, order, shift = hits[0]
    out.update({"hermann_mauguin": hm, "order": order, "origin_shift": shift})
    return out


# ---------------------------------------------------------------------
# The measured results, frozen
# ---------------------------------------------------------------------
#
# `derive()` searches 181 groups against 512 origins apiece, which is
# minutes of work -- too slow to run on every database build, and the
# answer does not change unless a level function does.  So the results
# are frozen here, in the same style as the other curated tables in this
# package, and `_selftest()` re-derives a sample to prove the table
# still matches the code that produced it.
#
# Every entry was produced by the method the calibration validates: the
# three surfaces with published groups (Schwarz P, Neovius -> Im-3m; the
# gyroid -> Ia-3d) all came back correct, and no curated value that
# resolved disagreed with its derivation.
#
# `ambiguous` rows are NOT failures.  They are surfaces whose level
# function is written on a cell coarser than its own translational
# lattice, so several standard groups of equal order fix it at once and
# the group they generate exceeds every entry in the table.  Schwarz D
# is the important one: its published Pn-3m holds at NO origin here,
# because the stored approximant is F-centred -- F(x + pi, y + pi, z) =
# F(x, y, z).  The record keeps the published symbol AND this finding;
# picking one over the other silently would be the error.

DERIVED = {
    "cd-surface": {
        "hermann_mauguin": None, "order": 192,
        "ambiguous": True,
        "note": "3 groups of order 192 fix this surface (Fd-3c:2, Fd-3m, Fd-3m:2); the group they generate is larger than any entry in the table, so the cell is coarser than the surface's own translational lattice and no single symbol is maximal"},
    "cg-surface": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "ci2y-surface": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "dprime-surface": {
        "hermann_mauguin": None, "order": 192,
        "ambiguous": True,
        "note": "2 groups of order 192 fix this surface (Fd-3m, Fd-3m:2); the group they generate is larger than any entry in the table, so the cell is coarser than the surface's own translational lattice and no single symbol is maximal"},
    "fischer-koch-cs": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "fischer-koch-cy": {
        "hermann_mauguin": "I4132", "order": 48,
        "origin_shift": ['0', '0', '0']},
    "fk-cpmy-surface": {
        "hermann_mauguin": "Ia-3", "order": 48,
        "origin_shift": ['0', '0', '0']},
    "fk-pmy-surface": {
        "hermann_mauguin": "Ia-3", "order": 48,
        "origin_shift": ['0', '0', '0']},
    "fk-s-surface": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "fk-y-surface": {
        "hermann_mauguin": "I4132", "order": 48,
        "origin_shift": ['0', '0', '0']},
    "frd-surface": {
        "hermann_mauguin": "Fm-3m", "order": 192,
        "origin_shift": ['0', '0', '0']},
    "gprime-surface": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "gyroid": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "iwp-surface": {
        "hermann_mauguin": "Im-3m", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "lidinoid": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "lidinoid-exact": {
        "hermann_mauguin": "Ia-3d", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "neovius-surface": {
        "hermann_mauguin": "Im-3m", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "scherkt-surface": {
        "hermann_mauguin": "P42/mcm", "order": 16,
        "origin_shift": ['0', '0', '1/4']},
    "schwarz-d": {
        "hermann_mauguin": None, "order": 192,
        "ambiguous": True,
        "note": "3 groups of order 192 fix this surface (Fd-3c:2, Fd-3m, Fd-3m:2); the group they generate is larger than any entry in the table, so the cell is coarser than the surface's own translational lattice and no single symbol is maximal"},
    "schwarz-p": {
        "hermann_mauguin": "Im-3m", "order": 96,
        "origin_shift": ['0', '0', '0']},
    "splitp-surface": {
        "hermann_mauguin": "Ia-3", "order": 48,
        "origin_shift": ['0', '0', '0']},
}


def derived_for(slug):
    """The frozen derivation for a slug, or None."""
    got = DERIVED.get(slug)
    return dict(got) if got else None


def _selftest():
    """Calibrate against the three surfaces with published groups."""
    sg = _spacegroups()

    # The standard nodal approximants, as the records store them.
    P = "cos(x) + cos(y) + cos(z)"
    G = "sin(x) * cos(y) + sin(y) * cos(z) + sin(z) * cos(x)"
    N = "3 * (cos(x) + cos(y) + cos(z)) + 4 * cos(x) * cos(y) * cos(z)"
    D = ("sin(x) * sin(y) * sin(z) + sin(x) * cos(y) * cos(z)"
         " + cos(x) * sin(y) * cos(z) + cos(x) * cos(y) * sin(z)")

    # POSITIVE CONTROLS: the published group must come out, and it must
    # come out as the MAXIMAL one -- a method that merely finds *a*
    # subgroup would pass a weaker test while being useless.
    for text, want in ((P, "Im-3m"), (G, "Ia-3d"), (N, "Im-3m")):
        got = derive(text)
        if got["hermann_mauguin"] != want:
            raise AssertionError("expected %s, derived %s"
                                 % (want, got["hermann_mauguin"]))

    # NEGATIVE CONTROL: the patch-tiling subgroup must NOT be reported.
    # Pm-3m holds for P, and reporting it would be the exact error that
    # deriving from evolver_cell.generators makes.
    if not satisfies(P, sg.ops("Pm-3m")):
        raise AssertionError("Pm-3m should hold for P (it is a subgroup)")
    if derive(P, candidates=("Pm-3m", "Im-3m"))["hermann_mauguin"] != "Im-3m":
        raise AssertionError("the maximal group must win over its subgroup")

    # THE RECORDED DISAGREEMENT: D satisfies Fd-3m and no setting of its
    # published Pn-3m, and its maximal order is held by THREE distinct
    # groups at once, so the derivation must report an ambiguity rather
    # than pick one.  Pinned so that if it ever changes, someone looks.
    got = derive(D)
    if not got["ambiguous"] or got["hermann_mauguin"] is not None:
        raise AssertionError("D must come back ambiguous, got %r" % (got,))
    if satisfies(D, sg.ops("Pn-3m:2")):
        raise AssertionError("Pn-3m unexpectedly holds for D at the origin")
    if not satisfies(D, sg.ops("Fd-3m")):
        raise AssertionError("Fd-3m should hold for D")
    # ...because the D approximant is F-centred; this is the reason.
    fc = satisfies(D, [(((1, 0, 0), (0, 1, 0), (0, 0, 1)), (6, 6, 0))])
    if not fc:
        raise AssertionError("D should be invariant under (1/2, 1/2, 0)")

    # A function with NO symmetry must derive nothing rather than
    # something: an oracle that always answers is not an oracle.
    if derive("cos(x) + 0.3137 * cos(2 * y) + 0.717 * sin(3 * z)",
              candidates=("Im-3m", "Ia-3d", "Fd-3m", "Pn-3m:2"),
              )["hermann_mauguin"] is not None:
        raise AssertionError("a lopsided function must not match a group")

    # THE FROZEN TABLE MUST STILL MATCH THE CODE. Re-derive a sample --
    # one resolved row and one ambiguous row -- so a change to the
    # method or to spacegroups.py cannot leave a stale table behind.
    if DERIVED["schwarz-p"]["hermann_mauguin"] != "Im-3m":
        raise AssertionError("frozen table disagrees with the calibration")
    if not DERIVED["schwarz-d"]["ambiguous"]:
        raise AssertionError("D must be frozen as ambiguous")
    live = derive(P)
    if live["hermann_mauguin"] != DERIVED["schwarz-p"]["hermann_mauguin"]:
        raise AssertionError("frozen table is stale for schwarz-p")

    print("RESULT: OK  (surfdb.symderive, %d rows frozen, 3 published "
          "groups reproduced, " % len(DERIVED) +
          "subgroup rejected, tie detected, unsymmetric function refused)")
