"""Scaffold generator doc pages, and keep their Options tables honest.

A page's Overview, "How it works" and References are human writing and
this script does not invent them.  What it does do is the mechanical
half that would otherwise be transcribed by hand for 128 generators and
then quietly rot:

  * the page skeleton, titled from the operator's own `bl_label`;
  * the **Options** table, built from the operator's RNA -- every
    property's label, default, range and description, which are all
    declared once already, in the operator;
  * the **References** section, lifted from the generator module's
    `References:` header block (the project requires one), so the
    mathematical credit on the page is the credit in the code;
  * `docs/options_snapshot.json`, which is what lets the pure-Python
    docs test notice that an operator gained or lost an option since
    its page was written, without needing Blender.

Run:

    blender --background --factory-startup --python docs/scaffold_pages.py

    ... -- --list                 what is missing, write nothing
    ... -- --only mesh.gem_add    one operator
    ... -- --refresh              rebuild Options tables in pages that
                                  carry the generated-block markers
    ... -- --adopt                convert a hand-written Options table
                                  into a generated block (Options only;
                                  prose sections are never touched)
    ... -- --snapshot-only        just rewrite options_snapshot.json

New pages land with TODO markers in the prose sections.  They are
deliberately loud: an unwritten page should look unwritten.
"""
import json
import os
import re
import sys

import bpy

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJ)
sys.path.insert(0, os.path.join(PROJ, "tools"))

import math_art                                            # noqa: E402
math_art.register()

from math_art import menu_defs                             # noqa: E402
import subjects                                            # noqa: E402

GEN = os.path.join(PROJ, "docs", "generators")
IMG = os.path.join(PROJ, "docs", "images")
SNAPSHOT = os.path.join(PROJ, "docs", "options_snapshot.json")

BEGIN = "<!-- options: generated by docs/scaffold_pages.py -->"
END = "<!-- /options -->"

# Blender's standard Add-Object properties.  They are on nearly every
# operator, mean the same thing everywhere, and say nothing about the
# mathematics, so the tables leave them out -- as the hand-written
# pages always did.
BORING = {"align", "location", "rotation", "rna_type"}


# ------------------------------------------------------------ helpers
# Shared with tests/test_docs.py, which uses it to spot figures older
# than the code that draws them.
module_for = subjects.module_for


def references_from(path):
    """The module header's `References:` block, as markdown bullets.

    The convention is a comment block of `#   Author, "Title", year.`
    with continuation lines indented further.  Entries are rejoined so
    one reference becomes one bullet.
    """
    if path is None:
        return []
    out, collecting = [], False
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if re.match(r"^#\s*References:", line):
                collecting = True
                continue
            if not collecting:
                continue
            if not line.startswith("#"):
                break
            body = line[1:].rstrip()
            if not body.strip():
                break
            text = body.strip()
            # The convention (enforced across every module header): each
            # reference begins with a `-` marker and its continuation
            # lines are indented with NO marker.  So a new entry is
            # exactly a line that starts with the marker; everything else
            # is a continuation and is rejoined into the current entry.
            # (The marker is stripped so the page owns the list format and
            # never shows "- - Author".)
            starts_entry = text.startswith(("-", "*"))
            text = re.sub(r"^[-*]\s*", "", text)
            if starts_entry or not out:
                out.append(text)
            else:
                out[-1] += " " + text
    return out


def _fmt_default(prop):
    t = prop.type
    if t == 'ENUM':
        if prop.is_enum_flag:
            return ", ".join(sorted(prop.default_flag)) or "none"
        for item in prop.enum_items:
            if item.identifier == prop.default:
                return item.name
        return str(prop.default)
    if t == 'BOOLEAN':
        if getattr(prop, "array_length", 0):
            return ", ".join(str(bool(v)) for v in prop.default_array)
        return "On" if prop.default else "Off"
    if t == 'FLOAT':
        if getattr(prop, "array_length", 0):
            return ", ".join(f"{v:g}" for v in prop.default_array)
        return f"{prop.default:g}"
    if t == 'INT':
        if getattr(prop, "array_length", 0):
            return ", ".join(str(v) for v in prop.default_array)
        return str(prop.default)
    if t == 'STRING':
        return f"`{prop.default}`" if prop.default else "empty"
    return ""


def _fmt_range(prop):
    if prop.type not in ('INT', 'FLOAT'):
        return ""
    lo, hi = prop.soft_min, prop.soft_max
    big = 1e9 if prop.type == 'FLOAT' else 2 ** 30
    if lo <= -big or hi >= big:
        return ""
    fmt = (lambda v: f"{v:g}") if prop.type == 'FLOAT' else str
    return f" Range {fmt(lo)}-{fmt(hi)}."


def option_rows(op):
    """[(label, default, description)] for `op`, in operator order."""
    mod, _, fn = op.partition('.')
    rna = getattr(getattr(bpy.ops, mod), fn).get_rna_type()
    rows = []
    for prop in rna.properties:
        if prop.identifier in BORING or prop.is_hidden:
            continue
        desc = (prop.description or "").strip()
        if prop.type == 'ENUM' and not prop.is_enum_flag:
            names = [i.name for i in prop.enum_items]
            if names:
                joined = ", ".join(names[:8])
                if len(names) > 8:
                    joined += f", and {len(names) - 8} more"
                desc = (desc + ". " if desc else "") + joined + "."
        desc = (desc + _fmt_range(prop)).strip()
        rows.append((prop.name or prop.identifier,
                     _fmt_default(prop), desc or "--"))
    return rows


def options_table(op):
    rows = option_rows(op)
    if not rows:
        return "_This generator takes no options._"
    out = ["| Option | Default | Description |", "| --- | --- | --- |"]
    for name, default, desc in rows:
        desc = desc.replace("|", "\\|").replace("\n", " ")
        out.append(f"| {name} | {default} | {desc} |")
    return "\n".join(out)


def block(op):
    return f"{BEGIN}\n\n{options_table(op)}\n\n{END}"


# -------------------------------------------------------------- pages
def label_for(op):
    for entry in menu_defs.iter_entries():
        if entry.op == op and entry.text:
            return entry.text
    mod, _, fn = op.partition('.')
    try:
        return getattr(getattr(bpy.ops, mod), fn).get_rna_type().name
    except Exception:
        return op


def skeleton(op, slug):
    title = label_for(op)
    mod, _, fn = op.partition('.')
    try:
        desc = getattr(getattr(bpy.ops, mod),
                       fn).get_rna_type().description or ""
    except Exception:
        desc = ""
    parts = [f"# {title}", ""]
    if os.path.exists(os.path.join(IMG, slug + ".png")):
        parts += [f"![{title}](../images/{slug}.png)", ""]
    parts += ["## Overview", ""]
    if desc:
        parts += [desc.strip().rstrip('.') + ".", ""]
    parts += [
        "<!-- TODO: what the shape is, who devised it, why it is "
        "interesting. Two or three sentences. -->", "",
        "## Options", "", block(op), "",
        "## How it works", "",
        "<!-- TODO: the construction, with the equations that matter. "
        "Pull the mathematics from the module header and the project's "
        "docs/ notes rather than reconstructing it. -->", "",
        "## References", "",
    ]
    refs = references_from(module_for(op))
    if refs:
        parts += [f"- {r}" for r in refs]
    else:
        parts += ["<!-- TODO: the module header carries no References: "
                  "block. Add one there first, then re-run this "
                  "scaffolder. -->"]
    parts.append("")
    return "\n".join(parts)


def refresh(path, op):
    """Rebuild the generated Options block in an existing page.

    Only pages carrying the markers are touched.  The 60 pages written
    by hand keep their curated tables until someone adopts them
    deliberately -- silently replacing prose descriptions with raw RNA
    tooltips would be a downgrade, and not this script's call to make.
    """
    text = open(path, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        return False
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END),
                 lambda _m: block(op), text, flags=re.DOTALL)
    if new == text:
        return False
    open(path, "w", encoding="utf-8").write(new)
    return True


def adopt(path, op):
    """Convert a hand-written Options table into a generated block.

    The older pages predate the generated block, and their tables have
    fallen behind the operators -- one is missing 51 options.  This
    replaces the *table* with the RNA-built one and wraps it in the
    markers, so it stays current from now on.

    Only the Options section is touched.  Overview, How it works and
    References are hand-written mathematics and are left exactly as
    they are: regenerating those would replace real prose with TODO
    markers, which is not "up to date", it is worse.

    A section carrying explanatory prose as well as a table is skipped
    and reported rather than flattened -- that prose is someone's
    writing, and losing it silently is the failure mode this whole
    exercise exists to prevent.
    """
    text = open(path, encoding="utf-8").read()
    if BEGIN in text:
        return "already"
    m = re.search(r"(## Options\s*\n)(.*?)(?=\n## |\Z)", text, re.DOTALL)
    if not m:
        return "no-options-section"
    body = m.group(2)
    prose = [ln for ln in body.splitlines()
             if ln.strip() and not ln.lstrip().startswith(("|", "<!--"))
             and not ln.startswith("_This generator takes no options._")]
    if prose:
        return "has-prose"
    new = m.group(1) + "\n" + block(op) + "\n"
    open(path, "w", encoding="utf-8").write(
        text[:m.start()] + new + text[m.end():])
    return "adopted"


def write_snapshot():
    """Per-operator label and option names, for the no-Blender docs test.

    The label is here so the test can notice a page whose title no
    longer matches the operator's own -- the Celtic Weave operator was
    renamed and its page kept saying "Celtic Knot", which nothing was
    watching for.
    """
    snap = {}
    for op in menu_defs.unique_ops():
        try:
            snap[op] = {"label": label_for(op),
                        "options": [r[0] for r in option_rows(op)]}
        except Exception as e:
            print("  snapshot FAILED", op, repr(e))
    with open(SNAPSHOT, "w", encoding="utf-8") as fh:
        json.dump(snap, fh, indent=1, sort_keys=True)
    print(f"wrote {SNAPSHOT} ({len(snap)} operators)")


def main(argv):
    only = None
    if "--only" in argv:
        only = argv[argv.index("--only") + 1]
    os.makedirs(GEN, exist_ok=True)

    if "--snapshot-only" in argv:
        write_snapshot()
        return 0

    made = refreshed = adopted = 0
    missing = []
    skipped = []
    for op in menu_defs.unique_ops():
        if only and op != only:
            continue
        if op in subjects.SKIP:
            continue
        slug = subjects.slug_for(op)
        path = os.path.join(GEN, slug + ".md")
        if not os.path.exists(path):
            missing.append((op, slug))
            continue
        if "--adopt" in argv:
            r = adopt(path, op)
            if r == "adopted":
                print("  adopted", slug)
                adopted += 1
            elif r in ("has-prose", "no-options-section"):
                skipped.append((slug, r))
        if "--refresh" in argv and refresh(path, op):
            print("  refreshed", slug)
            refreshed += 1

    if "--list" in argv:
        print(f"{len(missing)} operators with no page:")
        for op, slug in missing:
            refs = len(references_from(module_for(op)))
            print(f"    {slug:<26} {op:<38} "
                  f"{refs} refs in module header")
        return 0

    for op, slug in missing:
        path = os.path.join(GEN, slug + ".md")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(skeleton(op, slug))
        print("  created", slug)
        made += 1

    write_snapshot()
    if skipped:
        print(f"\n{len(skipped)} page(s) left alone:")
        for slug, why in skipped:
            print(f"    {slug}: {why}")
    print(f"DONE created={made} refreshed={refreshed} adopted={adopted}")
    return 0


sys.exit(main(sys.argv[sys.argv.index("--") + 1:]
              if "--" in sys.argv else []))
