"""hyperbolic -- the hyperbolic plane and hyperbolic 3-space.

The Blender-free engine behind the hyperbolic generators.  Python and
numpy only, so the package imports and self-tests headlessly; the
registered operators stay in their flat generator modules.

    tilings     {p,q} tilings of the hyperbolic plane in the Poincare
                disc, generated by inversion in the mirror circles.
    honeycombs  the regular honeycombs {p,q,r} of H^3, in the ball model.
    crochet     Taimina's crocheted surfaces of constant negative
                curvature.

WHY THIS IS A PACKAGE.  Its three members sit under three different
taxonomy headings -- Symmetry & Tilings, Polyhedra & Polytopes, and
Surfaces -- and appear in three different Add menus, purely because
hyperbolic space cuts across all of them.  That is an argument for
giving it a home, not against it.  They share no code, and the docstring
says so rather than implying an engine that is not there.
"""

from .crochet import (PRESETS, mean_curvature)
from .honeycombs import (add_sphere, add_strut, build_honeycomb, classify_symbol, gram_matrix, honeycomb_edges, sample_geodesic, simplex_data)
from .tilings import (FORM_ITEMS, FORM_RINGS, build_surface_cells, build_uniform, compute_seed, enumerate_group, fundamental_domain, snub_faces, tiling_faces, uniform_faces)

__all__ = [
    "mean_curvature",
    "PRESETS",
    "gram_matrix",
    "classify_symbol",
    "simplex_data",
    "honeycomb_edges",
    "sample_geodesic",
    "add_strut",
    "add_sphere",
    "build_honeycomb",
    "fundamental_domain",
    "enumerate_group",
    "compute_seed",
    "uniform_faces",
    "snub_faces",
    "tiling_faces",
    "build_uniform",
    "build_surface_cells",
    "FORM_RINGS",
    "FORM_ITEMS",
]

__version__ = "1.0.0"


def _selftest():
    """The facade's contract: every name in __all__ resolves, and the
    engine stays headless."""
    import sys
    missing = [n for n in __all__ if not hasattr(sys.modules[__name__], n)]
    ok = not missing
    print(f"hyperbolic: all {len(__all__)} names in __all__ resolve "
          f"{'OK' if ok else 'FAIL missing ' + ', '.join(missing)}")
    leaked = 'bpy' in sys.modules
    ok &= not leaked
    print(f"hyperbolic: importing the facade left bpy out of sys.modules "
          f"{'OK' if not leaked else 'FAIL'}")
    print("RESULT:", "OK" if ok else "FAIL")
    if not ok:
        raise AssertionError("hyperbolic facade self-test failed")
